exec(open('/tmp/audit-system-design/network05-helper.py').read())
edit('nsec-firewalls',"Attackers stole network credentials from Target's heating and ventilation contractor. From the vendor-access foothold they reached the point-of-sale systems and stole data on around 40 million payment cards. The supplier portal and the tills should never have been reachable from one another.","A March 2014 Senate staff analysis described an apparent path from compromised HVAC-vendor credentials into sensitive network areas. It cited Target's confirmation that around 40 million payment-card accounts were exposed. The report explicitly relied on then-available reports and expert analysis, not a completed public forensic reconstruction. Its segmentation lesson is to restrict supplier access to necessary resources rather than grant broad internal reachability.",'Preserve historical evidence with its stated uncertainty; do not invent direct supplier-portal-to-till topology.',['https://www.commerce.senate.gov/services/files/24d3c229-4f2f-405d-b8db-a3a67f183883'])
edit('nsec-wireless','PTW needs around 40,000 frames for a 50% chance of success, which takes a minute or two on a busy network; attackers can generate the traffic by replaying captured ARP requests.',"The 2007 PTW paper reports recovery of a 104-bit WEP key with fewer than 40,000 frames in half its cases, using an active attack. Its sub-minute collection result involved reinjection on an 802.11g network; this is an experiment-specific result, not a guarantee for any busy network.",'Scope numerical cryptanalysis result to the original active-attack experiment.',['https://eprint.iacr.org/2007/120'])
edit('nsec-wireless','the start of the published IEEE 802.11i test vector','the beginning of the derived 256-bit key for those inputs','The computed result can be reproduced; exact standard test-vector attribution was not retrieved.')
edit('nsec-vpns','Stolen VPN credentials have been the entry point for many ransomware incidents. The VPN gateways themselves sit on the internet and run complex code; Citrix, Fortinet, Ivanti and Palo Alto appliances have all had critical, actively exploited vulnerabilities in recent years.','Stolen VPN credentials or vulnerabilities in exposed gateways can provide an entry point. Internet-facing gateways therefore require restricted administration, monitoring and timely fixes.\n\n> [!note] Content gap\n> A vendor-by-vendor list of recently exploited VPN vulnerabilities and an incident-frequency claim are omitted here because the individual advisories and a comparable incident dataset were not verified.','Replace unverified changing vendor incident list with explicit gap; retain supported threat model.')
edit('nsec-vpns','Patch VPN appliances as an emergency, not on the monthly cycle.','Prioritize fixes for known exploitation and high-risk exposed vulnerabilities; follow the applicable vendor advisory and incident response process.','Not every VPN update has the same emergency risk.')
for num in [5]:
 a=json.loads((base/'nsec-threats.questions.json').read_text())[num-1]
 for i,o in enumerate(a['options']):
  for f in ['text','explanation']:
   if 'wire' in o[f]:qedit('nsec-threats',num,f'options.{i}.{f}',o[f].replace('On the wire:','At the IP-packet level:').replace('wire','IP-packet'),'Byte model excludes Ethernet overhead.')
 qreplace('nsec-threats',num,'workedExample','wire BAF','IP BAF','Align byte-level label with calculation.')
qedit('nsec-threats',12,'options.3.explanation','Predictable initial sequence numbers permit better-than-uniform guesses; unpredictable generation makes blind handshake spoofing harder.','Remove unverified incident/date attribution; retain mechanism.')
qreplace('nsec-threats',12,'workedExample','RFC 6528 requires unpredictable ones','RFC 6528 recommends an unpredictable sequence-number generation method','RFC6528 uses SHOULD; do not upgrade recommendation to universal MUST.',rfc(6528))
edit('nsec-tls','raw = socket.create_connection((host, 443))\ntls = ctx.wrap_socket(raw,\n                      server_hostname=host)\nprint(tls.version())\nprint(tls.cipher()[0])\ncert = tls.getpeercert()\nprint(dict(x[0] for x in cert["subject"]))\ntls.close()','with socket.create_connection(\n        (host, 443), timeout=10) as raw:\n    with ctx.wrap_socket(\n            raw, server_hostname=host) as tls:\n        print(tls.version())\n        print(tls.cipher()[0])\n        cert = tls.getpeercert()\n        subject = dict(\n            x[0] for x in cert["subject"])\n        print(subject)','Bound network wait and close sockets on handshake/output errors.')
print(len(rows))
