exec(open('/tmp/cs-study-audit-full/helper.py').read())
mod=Path('content/os/02-threads-scheduling');b=str(mod)+'/'
s=['https://man7.org/linux/man-pages/man7/pthreads.7.html'];ml=['https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-mlfq.pdf']
qe(b+'sched-thread-apis.questions.json','sched-thread-apis-q11','workedExample','The local result object ends its lifetime when the function returns, regardless of stack caching or physical reclamation. Dereferencing its returned address is undefined behavior. Return heap storage with a clear owner, or write into a caller-owned result field. Integer-to-pointer conversions are not a universally portable result transport.','Object lifetime and pointer portability.',s)
qe(b+'sched-priority-mlfq.questions.json','sched-priority-mlfq-q4','explanation','Aging lowers the numeric priority under this model. The question asks when it reaches 40; actual service also depends on the runnable queue and tie-breaking.','Equal priority doesnotguaranteeruntime.',ml,option=2)
qe(b+'sched-priority-mlfq.questions.json','sched-priority-mlfq-q6','prompt','MLFQ has cumulative CPU accounting and a 10 ms top-queue allotment. A job runs 2 ms then blocks repeatedly, with no intervening priority boost. After how many bursts is it demoted?','Excludebooststhatresetaccounting.',ml)
qe(b+'sched-priority-mlfq.questions.json','sched-priority-mlfq-q10','workedExample','Options 1, 2 and 3 describe inheritance, transitive inheritance and immediate priority ceilings. Option 4 is false: inheritance removes medium-priority interference in the simple example but H still waits for the holder; general bounds depend on nesting and other interference. Option 5 reverses the constants: INHERIT requests inheritance and PROTECT requests a priority ceiling.','General bound requires assumptions.',['https://docs.kernel.org/locking/rt-mutex.html'])
edit(b+'sched-thread-apis.md','and it fails on free-threaded builds','and it is not a safe shared-counter protocol on free-threaded builds','Failurepossible notuniversaloutcome.',['https://docs.python.org/3/howto/free-threading-python.html'])
qe(b+'sched-linux.questions.json','sched-linux-q4','explanation','Correct: 1024/1844 ≈ 55.5% and 820/1844 ≈ 44.5%, a gap of about 11.1 percentage points. Each share changes about 5.5 points from 50%.','Clarify percentagepointarithmetic.',['https://docs.kernel.org/scheduler/sched-design-CFS.html'],option=1)
paths=[*mod.glob('*.md'),*mod.glob('*.questions.json')];save(paths)
fs=[x for x in r['findings'] if x['file'].startswith(b)];m=json.loads((mod/'module.json').read_text())
gaps=['All six lessons and all fields of 66 questions received semantic review. Primary-source checks cover selected API contracts, scheduler algorithms, version-sensitive details and disputed claims; this is not independent source proof of every sentence.','30 host assertions passed: compiled pthread sum, Python pool and race-demo execution (no race output guarantee), observed barrier-enforced pool deadlock with subprocess termination, independent FCFS/SJF/SRTF/RR schedules and quota/weight arithmetic. Ten Linux 6.12.76 aarch64 assertions checked affinity replacement/inheritance, priority bounds and SCHED_IDLE selection.','No full kernel scheduling benchmark, privileged realtime workload, NUMA multiprocessor experiment, Kubernetes deployment or Go/JVM execution was performed. Example toy timing is qualified; unsupported universal thread/switch/NUMA measurements are explicitly absent.','Intentionally undefined C examples were analyzed as undefined behavior rather than treated as valid output tests. Partial snippets and Linux-specific privileged commands are illustrative, not complete production implementations.','Source and runtime defaults depend on versions/configuration. Whole-project links and mobile/diagram rendering are integrated by parent.']
v={'module':m['id'],'author':{'agent':'historical author unknown','date':'2026-10-05','note':'Audit bookkeeping date only.'},'verifier':{'agent':'audit_systems','date':'2026-10-05','independent':True,'sources':sorted({u for x in fs for u in x['sources']}|{'https://raw.githubusercontent.com/torvalds/linux/v6.12/kernel/sched/core.c','https://raw.githubusercontent.com/torvalds/linux/v6.12/kernel/sched/deadline.c'})},'summary':{'claimsChecked':66,'errorsCorrected':len(fs),'hedgedOrRemoved':sum(any(w in x['reason'].lower() for w in ['assum','qualif','universal','unsupported','remove']) for x in fs)},'countingMethod':'claimsChecked counts question-answer propositions, correction records include repeated fields, qualifications and formatting rather than distinct false facts.','reviewScope':'Full six lesson/66 question semantic review, selected primary checks, 40 runtime/model assertions.','corrections':fs,'lowConfidence':[{'lesson':i,'claim':'Version-dependent implementation details and completeness of illustrative examples','confidence':'medium','reason':'Core reviewed with primary sources; runtime-specific exceptions and deployment behavior remain qualified.'} for i in m['lessons']],'gaps':gaps,'lessons':{i:{'confidence':'medium'} for i in m['lessons']}}
(mod/'verification.json').write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
r.setdefault('completedModules',[]).append({'module':str(mod),'lessons':6,'questions':66,'correctionRecords':len(fs),'confidence':'medium','runtimeChecks':[{'command':'python3 /tmp/cs-study-audit-full/check_os02.py','assertionsPassed':30},{'command':'docker run --rm --network none -i --entrypoint python3 law-blog-security-audit:latest - < /tmp/cs-study-audit-full/check_os02_linux.py','assertionsPassed':10,'environment':'Linux 6.12.76-linuxkit aarch64'}],'gaps':gaps})
r['currentModule']={'module':str(mod),'status':'review complete; record written; stamp/build follow'};P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(len(fs),'correction records')
