exec(open('/tmp/cs-study-audit-full/helper.py').read())
mod=Path('content/os/03-synchronisation');b=str(mod)+'/'
qe(b+'sync-lock-free.questions.json','sync-lock-free-q8','workedExample','A reader first gets a reference to the current dictionary and releases the brief publication lock. The writer then changes host in that same dictionary, the reader reads host and port before the second assignment, and the writer finally changes port. The reader can therefore combine versions. Instead, build a replacement dictionary under the publication lock and leave every previously returned dictionary unchanged. The same rule extends to nested mutable values.','Match corrected getter lock and demonstrate stillvalidmixedsnapshotrace.',['https://docs.python.org/3/howto/free-threading-python.html'])
edit(b+'sync-locks.md','Ticket and queued locks add fairness; adaptive mutexes spin briefly before sleeping.','Ticket locks order admission subject to progress and wraparound assumptions; queued-lock fairness is implementation-specific. Adaptive mutexes may spin before sleeping.','Keep summary aligned with qualified fairness.',['https://docs.kernel.org/locking/locktypes.html'])
edit(b+'sync-lock-free.md','Read-write locks only help when read sections are long; short reads still contend on the reader count.','Read-write-lock benefits depend on workload; short reads may contend on shared reader metadata.','Remove only/long universal threshold.',['https://docs.kernel.org/RCU/whatisRCU.html'])
paths=[*mod.glob('*.md'),*mod.glob('*.questions.json')];save(paths)
fs=[x for x in r['findings'] if x['file'].startswith(b)];m=json.loads((mod/'module.json').read_text())
gaps=['Full semantic reading of all six lessons and all fields of 68 questions. Selected primary-source checks target language/locking contracts, races, progress and kernel-specific mechanisms; not every sentence is externally proven.','29 host/model assertions passed, including eight compiled C programs, atomic/lock counters, release/acquire publication, CV completion, exhaustive toy SC increment outcomes for N=1..4, SC store-buffering outcomes, Python semaphore/condition/snapshot contracts, barber progress and bounded subprocess deadlock observation.','No real weak-memory litmus stress test on x86 hardware, kernel seqlock/RCU execution, complete reclamation proof or C++26 library conformance test. C/RCU/futex fragments are explicitly illustrative where prerequisites or error handling are omitted.','Unsupported exact lock/syscall/cache-transfer/RCU timings and race-output measurements are omitted with visible content-gap notes. Local runs are not a universal performance guarantee or concurrency proof.','Whole-project links, shared diagram reconciliation and mobile rendering are integrated by parent.']
v={'module':m['id'],'author':{'agent':'historical author unknown','date':'2026-10-05','note':'Audit bookkeeping date only.'},'verifier':{'agent':'audit_systems','date':'2026-10-05','independent':True,'sources':sorted({u for x in fs for u in x['sources']})},'summary':{'claimsChecked':68,'errorsCorrected':len(fs),'hedgedOrRemoved':sum(any(w in x['reason'].lower() for w in ['assum','qualif','universal','unsupported','remove']) for x in fs)},'countingMethod':'claimsChecked counts question-answer propositions; correction records include repeated fields and qualifications, not distinct false facts.','reviewScope':'Six lessons, 68 questions, selected fetched primary sources, 29 runtime/model assertions.','corrections':fs,'lowConfidence':[{'lesson':i,'claim':'Version-specific mechanisms and complete concurrent implementation correctness','confidence':'medium','reason':'Core checked against primary sources; fragments and runtime differences explicitly qualified, not a formal implementation proof.'} for i in m['lessons']],'gaps':gaps,'lessons':{i:{'confidence':'medium'} for i in m['lessons']}}
(mod/'verification.json').write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n');r.setdefault('completedModules',[]).append({'module':str(mod),'lessons':6,'questions':68,'correctionRecords':len(fs),'confidence':'medium','runtimeChecks':[{'command':'python3 /tmp/cs-study-audit-full/check_os03.py','assertionsPassed':29,'compiledCProgramsExecuted':8,'environment':'Darwin arm64'}],'gaps':gaps});r['currentModule']={'module':str(mod),'status':'review complete, record written, stamp/build follow'};P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(len(fs),'records')
