exec(open('/tmp/cs-study-audit-full/helper.py').read())
mod=Path('content/os/01-processes');a=mod/'proc-fork-exec-wait.md'
edit(a,'if (done < 0) { /* check errno; retry EINTR */','if (done < 0) {\n    /* Check errno; retry EINTR as needed. */','Wrap explanatory comment within code-width limit.',['https://man7.org/linux/man-pages/man2/wait.2.html'])
edit(a,' parent PT ----- frame 7  (writable)',' parent PT ----- frame 7  (exclusive)','After child COW, parent PTE can remain read-only until its own fault; exclusive ownership is the correct diagram property.',['https://man7.org/linux/man-pages/man2/fork.2.html'])
# Add the source needed for the killable D-state distinction checked directly in kernel definitions.
r.setdefault('additionalSources',[]).append({'module':'os-processes','url':'https://raw.githubusercontent.com/torvalds/linux/master/include/linux/sched.h','supports':'TASK_KILLABLE includes TASK_UNINTERRUPTIBLE and TASK_WAKEKILL, while TASK_REPORT masks the latter.'})
paths=[*mod.glob('*.md'),*mod.glob('*.questions.json')];save(paths)
m=json.loads((mod/'module.json').read_text());fs=[f for f in r['findings'] if str(mod)+'/' in f['file']]
gaps=['Full semantic reading covers all 6 lessons and every field of 67 questions. Primary checks target API contracts, disputed mechanisms and implementation details; not every sentence is independently externally proven.','30 assertions across 15 compiled C/POSIX examples passed on Darwin arm64; 31 Linux aarch64 assertions passed through Python/libc in an isolated Linux 6.12.76 container. The x86-64 syscall entry/register details were checked against Linux/glibc source, not executed on x86 hardware.','Code fragments remain illustrative where they omit headers, complete application state, error paths or synchronisation; no complete OS, allocator, kernel proof, driver or production IPC implementation was verified.','Universal timing, cache-capacity and syscall/fork/IPC performance claims were omitted or explicitly made hypothetical. No benchmark or certified medical-device safety case is supplied. seL4 assurances depend on verified configurations and documented assumptions.','Whole-project link status and mobile/diagram rendering are integrated by the parent audit. Changed syscall/COW diagram source may require shared override reconciliation.']
v={'module':m['id'],'author':{'agent':'historical author unknown','date':'2026-10-05','note':'Audit bookkeeping date, not original authorship date.'},'verifier':{'agent':'audit_systems','date':'2026-10-05','independent':True,'sources':sorted({s for f in fs for s in f['sources']}|{'https://raw.githubusercontent.com/torvalds/linux/master/include/linux/sched.h'})},'summary':{'claimsChecked':67,'errorsCorrected':len(fs),'hedgedOrRemoved':sum(any(w in f['reason'].lower() for w in ['qualif','unsupported','universal','assum']) for f in fs)},'countingMethod':'claimsChecked counts 67 question-answer propositions. Correction records include repeated fields, qualifications and formatting, not distinct false facts.','reviewScope':'Full 6 lesson/67 question semantic review, selected primary-source checks, 61 local assertions in two environments.','corrections':fs,'lowConfidence':[{'lesson':id,'claim':'Platform-specific behavior and completeness of illustrative implementation','confidence':'medium','reason':'Selected primary verification and local checks; configurations and versions differ, and snippets are not production implementations.'} for id in m['lessons']],'gaps':gaps,'lessons':{id:{'confidence':'medium'} for id in m['lessons']}}
(mod/'verification.json').write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
r['status']='in progress';r['currentModule']['verificationRecord']='Created after genuine review; stamping and build integration follow.';r['currentModule']['pending']=['Stamp and validate completed module; parent reconciles shared diagram overrides.'];r['currentModule']['correctionRecords']=len(fs)
r.setdefault('completedModules',[]).append({'module':str(mod),'lessons':6,'questions':67,'correctionRecords':len(fs),'confidence':'medium','runtimeChecks':[{'command':'python3 /tmp/cs-study-audit-full/check_os01_host.py','assertionsPassed':30,'environment':'Darwin arm64','compiledCProgramsExecuted':15},{'command':'docker run --rm --network none -i --entrypoint python3 law-blog-security-audit:latest - < /tmp/cs-study-audit-full/check_os01_linux.py','assertionsPassed':31,'environment':'Linux 6.12.76-linuxkit aarch64','scope':'libc syscall, pipes, fork offsets, exit status, signals, SCM_RIGHTS, POSIX shared memory and mqueues'}],'gaps':gaps})
P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n')
print(len(fs))
