exec(open('/tmp/cs-study-audit-full/helper.py').read())
mod=Path('content/os/04-deadlock');b=str(mod)+'/'
# Final contract and source checks.
edit(b+'dl-prevention.md','## Breaking circular wait: lock ordering','## Breaking circular wait: lock ordering','Coverage checkpoint: following transfer assumes account objects provide a stable unique id.',['https://pages.cs.wisc.edu/~remzi/OSTEP/threads-bugs.pdf']) if False else None
s=(mod/'dl-prevention.md').read_text()
if 'key=lambda x: x.id' in s:
 edit(b+'dl-prevention.md','key=lambda x: x.id','key=lambda x: x.name','Use the unique immutable account names provided by the preceding lesson example; real code must enforce uniqueness and immutability.',['https://docs.python.org/3/library/functions.html#sorted'])
edit(b+'dl-livelock-starvation.md',"so it only works with primitives that have an **owner**: mutexes.","so conventional mutex PI needs an identifiable **owner**. Other systems can propagate priority through explicitly tracked server or resource dependencies; ownership need not literally be a POSIX mutex.",'Primary priorityprotocol report includes Ada rendezvous; avoid literalmutexonly.',['https://www.sei.cmu.edu/documents/976/1989_005_001_15758.pdf'])
# Store fetched sources for unchanged checked specifics too.
r.setdefault('sourceChecks',[]).append({'module':str(mod),'checks':[{'claim':'Priority inheritance/ceiling model assumptions and Ada/binary-semaphore applicability','source':'https://www.sei.cmu.edu/documents/976/1989_005_001_15758.pdf'},{'claim':'InnoDB 8.4 wait graph change notification and background detector','source':'https://raw.githubusercontent.com/mysql/mysql-server/8.4/storage/innobase/lock/lock0wait.cc'}]})
paths=[*mod.glob('*.md'),*mod.glob('*.questions.json')];save(paths)
fs=[x for x in r['findings'] if x['file'].startswith(b)];m=json.loads((mod/'module.json').read_text());qs=sum(len(json.loads(p.read_text())) for p in mod.glob('*.questions.json'))
gaps=['Full semantic reading of all six lessons and every field of all question sets; selected primary-source verification, not a claim that every sentence was externally proven.','37 host/model check groups passed, including 2187 exhaustive small Banker states and 512 exhaustive three-node wait graphs, matrix request answers, LevelLock contracts, eight-waiter FIFO ticket admission, jitter/scheduling arithmetic and an isolated pool-deadlock observation.','Retry wrapper tests use explicit transaction doubles, not live Psycopg/PostgreSQL integration. Database error/rollback semantics checked against official documentation; no live SQL Server/InnoDB cluster or kernel lockdep run.','No formal proof of complete production lock implementations, fairness under arbitrary scheduling, universal platform tool support or wall-clock timing. TSan lock-order checking explicitly depends on runtime support/configuration.','Unsupported precise handoff timings, empirical prevalence and fixed throughput estimates omitted/qualified, with visible content-gap notes. Local algorithm tests are not performance benchmarks.','Shared diagram reconciliation, whole-project links and final rendering remain parent integration tasks.']
sources=sorted({u for x in fs for u in x['sources']} | {x['source'] for entry in r.get('sourceChecks',[]) if entry['module']==str(mod) for x in entry['checks']})
v={'module':m['id'],'author':{'agent':'historical author unknown','date':'2026-10-05','note':'Audit bookkeeping date only.'},'verifier':{'agent':'audit_systems','date':'2026-10-05','independent':True,'sources':sources},'summary':{'claimsChecked':qs,'errorsCorrected':len(fs),'hedgedOrRemoved':sum(any(w in x['reason'].lower() for w in ['assum','qualif','universal','unsupported','remove','scope']) for x in fs)},'countingMethod':'claimsChecked counts question-answer propositions; correction records include repeated fields, qualifications and formatting, not distinct false facts.','reviewScope':f'Six lessons, {qs} questions, selected primary sources, 37 runtime/model check groups including 2699 exhaustive toy states.','corrections':fs,'lowConfidence':[{'lesson':i,'claim':'Complete concurrent/runtime correctness across versions and production contexts','confidence':'medium','reason':'Core claims checked; assumptions and version limitations stated. Finite examples are not complete production proofs.'} for i in m['lessons']],'gaps':gaps,'lessons':{i:{'confidence':'medium'} for i in m['lessons']}}
(mod/'verification.json').write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n');r.setdefault('completedModules',[]).append({'module':str(mod),'lessons':6,'questions':qs,'correctionRecords':len(fs),'confidence':'medium','runtimeChecks':[{'command':'python3 /tmp/cs-study-audit-full/check_os04.py','checkGroupsPassed':37,'exhaustiveBankerStates':2187,'exhaustiveWaitGraphs':512,'environment':'Darwin arm64 Python3.14'}],'gaps':gaps});r['currentModule']={'module':str(mod),'status':'review complete; verification record written; stamp/build follow'};P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(qs,len(fs))
