exec(open('/tmp/cs-study-audit-full/helper.py').read())
mod=Path('content/os/05-memory');b=str(mod)+'/'
r.setdefault('sourceChecks',[]).append({'module':str(mod),'checks':[{'claim':'Intel vol3A February2026: paging structures/MAXPHYADDR, NXE and CR0.WP permissions; sections5.8 and5.10.4 accessed/dirty flag cache invalidation contracts','source':'https://cdrdv2-public.intel.com/874249/253668-090-sdm-vol-3a.pdf'},{'claim':'Independent review of virtual-memory-regions override JSON source/title/labels matches revised four-level schematic; browser rendering not exercised','source':'content/diagram-overrides.json#virtual-memory-regions'}]})
paths=[*mod.glob('*.md'),*mod.glob('*.questions.json')];save(paths)
fs=[x for x in r['findings'] if x['file'].startswith(b)];meta=json.loads((mod/'module.json').read_text());qs=sum(len(json.loads(p.read_text())) for p in mod.glob('*.questions.json'))
gaps=['Full semantic reading of seven lessons and all fields of 84 questions; selected primary-source checking is not external proof of every sentence.','31 host/model check groups passed, including 12288 exhaustive six-reference LRU/OPT cases, replacement traces, translation/bit split, memory arithmetic, two compiled C demonstrations, tracemalloc and shared override semantic/source consistency.','Six malloc usable-size checks executed in isolated Linux Docker with glibc2.41 aarch64. This corroborates arithmetic for that runtime, not execution of the explicitly source-verified glibc2.39 x86-64 model.','No live kernel page-table, cgroup/OOM, Kubernetes, Redis, Java or alternate allocator stress test; semantics checked against primary documentation/source. Tests intentionally do not exhaust host memory or change host policy.','No hardware TLB/perf benchmark, arbitrary-CPU capacity, workload fault-latency or allocator/profiler overhead ranking is claimed; unsupported measurement specifics are removed or clearly labelled illustrative and visible content-gap notes explain omissions.','Intel reference edition is253668-090US February2026. Kernel/runtime interfaces remain platform/version dependent; assumptions and implementation scope are stated.','Diagram override JSON was independently checked against source; final browser appearance remains parent integration validation.']
sources=sorted({u for x in fs for u in x['sources']}|{'https://cdrdv2-public.intel.com/874249/253668-090-sdm-vol-3a.pdf'})
v={'module':meta['id'],'author':{'agent':'historical author unknown','date':'2026-10-05','note':'Audit bookkeeping date only.'},'verifier':{'agent':'audit_systems','date':'2026-10-05','independent':True,'sources':sources},'summary':{'claimsChecked':qs,'errorsCorrected':len(fs),'hedgedOrRemoved':sum(any(w in x['reason'].lower() for w in ['assum','qualif','universal','unsupported','remove','scope']) for x in fs)},'countingMethod':'claimsChecked counts question-answer propositions; correction records include repeated fields, scope qualifiers and formatting, not distinct false facts.','reviewScope':'Seven lessons and84 questions fully read, selected primary verification,31 host/model groups and6 Linux allocator size observations.','corrections':fs,'lowConfidence':[{'lesson':i,'claim':'All hardware/runtime/configuration and production workload behaviors','confidence':'medium','reason':'Core models, selected source claims and finite execution checked; deployment-dependent guarantees explicitly limited.'} for i in meta['lessons']],'gaps':gaps,'lessons':{i:{'confidence':'medium'} for i in meta['lessons']}}
(mod/'verification.json').write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
linux={'environment':'Linux aarch64 glibc2.41 isolated Docker law-blog-security-audit:latest, networknone','mallocUsableSizes':{'1':24,'24':24,'25':40,'30':40,'64':72,'100':104},'checkGroupsPassed':6}
Path('/tmp/cs-study-audit-full/os05/linux-results.json').write_text(json.dumps(linux,indent=2)+'\n')
r.setdefault('completedModules',[]).append({'module':str(mod),'lessons':7,'questions':qs,'correctionRecords':len(fs),'confidence':'medium','runtimeChecks':[{'command':'python3 /tmp/cs-study-audit-full/check_os05.py','checkGroupsPassed':31,'exhaustiveCases':12288},linux],'gaps':gaps});r['currentModule']={'module':str(mod),'status':'Review and execution complete; verification written; stamp/build next'};P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(qs,len(fs))
