exec(open('/tmp/cs-study-audit-full/helper.py').read())
b='content/os/02-threads-scheduling/';s=['https://man7.org/linux/man-pages/man7/pthreads.7.html'];f=['https://raw.githubusercontent.com/torvalds/linux/v6.12/kernel/sched/fair.c']
edit(b+'sched-linux.md','# Needs CAP_SYS_NICE or sufficient RLIMIT_RTPRIO','# Needs CAP_SYS_NICE or\n# sufficient RLIMIT_RTPRIO','Code width.',s)
edit(b+'sched-thread-apis.md','All four threads get a pointer to the *same* `i`, which the loop keeps changing. A thread may start after `i` has moved on, so you see duplicates or even `4`.','All four threads get a pointer to the *same* `i`. Concurrent unsynchronized reads and writes constitute a C data race (undefined behavior), and use after the loop can also exceed its lifetime. Duplicates or `4` are possible symptoms, not guaranteed outcomes.','Consistent with corrected quiz language semantics.',s)
edit(b+'sched-thread-apis.md','hands back a pointer into its own stack, which is freed when it exits.','hands back a pointer to an object whose lifetime has ended, regardless of whether its stack storage is physically reclaimed yet.','Object lifetime notphysicalfree determinesinvalidity.',s)
edit(b+'sched-thread-apis.md','**CPU-bound** tasks (compression, image processing): about one thread per core. More threads cannot run at once and just add switching.','**CPU-bound** tasks (compression, image processing): start near the effective logical CPU capacity or quota, then measure. SMT, memory bandwidth, blocking, the GIL and task granularity can change the best size.','Physicalcore notuniversal runtimeparallelism.',s)
edit(b+'sched-threads.md','millions of cheap threads mounted on a small pool of carrier OS threads.','lightweight threads mounted on carrier OS threads; achievable counts and carrier behavior depend on memory, runtime version and workload.','Removeunsupporteduniversalcapacity.', ['https://openjdk.org/jeps/444'])
edit(b+'sched-linux.md','A CFS run queue','A CFS run queue','No change placeholder.',f) if False else None
# Source-specific numeric defaults now pinned to actually checked kernel.
edit(b+'sched-linux.md','The default base slice is about 0.7–0.75 ms depending on kernel version, scaled like CFS\'s tunables (so about 3 ms on a machine with 8 or more CPUs).','In the checked Linux 6.12 source the unscaled base slice is 0.75 ms; the default logarithmic scaling gives 3 ms at eight or more CPUs. Tunables and later kernels can differ.','Pin default to sourcecheckedversion.',f)
save([*Path(b).glob('*.md'),*Path(b).glob('*.questions.json')])
