exec(open('/tmp/cs-study-audit-full/helper.py').read())
a='content/os/02-threads-scheduling/sched-cpu-basics.md';b=a.replace('.md','.questions.json');src=['https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched.pdf','https://docs.python.org/3/library/asyncio-task.html']
for old,new in [('At any moment a machine has far more runnable threads than cores. A laptop typically has hundreds of threads, most asleep, and a few dozen that want the CPU in any given second.','A machine can have more runnable threads than available logical CPUs; at other times many or all threads are asleep.'),('Most real bursts are short: a burst-length histogram usually has a big peak under a few milliseconds and a long tail.','Burst distributions depend on workload; interactive tasks often have short bursts between waits.'),('Python\'s `asyncio` and JavaScript\'s event loop switch tasks only at `await`,','Python asyncio tasks yield when an await actually suspends, while event loops also move on when callbacks or tasks return;'),('Direct costs are on the order of a microsecond or two; the cache effects can be larger.','There is no platform-independent switch-time constant; both direct and cache costs need measurement.'),('A common guideline is to make the quantum longer than most CPU bursts (often quoted as 80%), so that typical interactive jobs finish their burst and block before being preempted. Real systems use slices of roughly 1 to 100 ms.','Choose the quantum from measured burst lengths, latency goals and overhead. No workload trace or platform-specific measurement is supplied to justify a universal percentile target or slice range here.'),('SJF minimises average waiting time but needs burst predictions','For the stated single-CPU, equal-arrival, known-burst, zero-switch-cost model, SJF minimises average waiting time; general workloads need additional assumptions or burst estimates')]:edit(a,old,new,'State scheduling model assumptions and omit unsupported empirical ranges.',src)
qe(b,'sched-cpu-basics-q3','explanation','The OS preempts the thread, not individual asyncio tasks. The event loop resumes other tasks only when control returns to it; an await that completes immediately need not suspend.','await is not an unconditional scheduling point.',src,option=0)
qe(b,'sched-cpu-basics-q3','workedExample','The CPU loop does not return control to the event loop, so other tasks in that loop stall. The OS may schedule other threads, but resuming this thread continues the same loop. Offload suitable work or yield explicitly with asyncio.sleep(0). In a GIL-enabled interpreter, to_thread can improve responsiveness but does not itself provide parallel execution of pure-Python CPU work; a process pool can.','Distinguish event-loop responsiveness from GIL parallelism.',src)
qe(b,'sched-cpu-basics-q7','prompt','Assume at least two continuously runnable jobs, one 0.5 ms switch after every full 4.5 ms round-robin quantum, and no other costs. What fraction of each steady-state cycle is switching?','A single runnable job need not switch; supply cycle assumptions.',src)
qe(b,'sched-cpu-basics-q7','workedExample','One cycle is 4.5 + 0.5 = 5 ms, of which 0.5 ms is switching: 10%. With a 9.5 ms quantum the same assumed overhead would be 5%. These are hypothetical costs, not a measured real-kernel timing.','Remove unsupported real microsecond benchmark.',src)
qe(b,'sched-cpu-basics-q10','text','Short I/O-bound jobs can wait behind the long CPU burst while the disk is idle; preemptive time slicing can reduce that convoy delay','CPU need not become idle if CPU-bound work stays runnable.',src,option=1)
qe(b,'sched-cpu-basics-q10','explanation','The convoy effect delays short bursts. Preemption gives them earlier opportunities to issue I/O; actual CPU/disk utilisation depends on all burst and I/O timings.','Avoid guaranteed idle alternation and complete fix.',src,option=1)
save([a,b])
a='content/os/02-threads-scheduling/sched-priority-mlfq.md';b=a.replace('.md','.questions.json');src=['https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-mlfq.pdf','https://docs.kernel.org/locking/rt-mutex.html','https://catless.ncl.ac.uk/Risks/19.54.html','https://jacobfilipp.com/DrDobbs/articles/DDJ/1999/9911/9911a/9911as1.htm','https://docs.oracle.com/cd/E19504-01/802-5750/6i9g464te/index.html','https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling']
for old,new in [('Each thread has a priority, and the scheduler always runs the highest-priority ready thread.','In a strict-priority model, the scheduler chooses the highest-priority ready thread. Linux nice values instead set relative fair-scheduling weights; they are not strict priorities.'),('so it runs after about 107 seconds, then drops back once it has had its turn.','so it reaches equal priority after 107 seconds. Actual first service also depends on tie-breaking and queue length; a chosen policy may reset priority after service.'),('B gets the CPU within microseconds of becoming ready.','In the idealised zero-overhead trace, B runs immediately when ready; no measured wake-up latency is implied.'),('Solaris\'s time-sharing class used a table of 60 priority levels with quanta ranging from 20 ms at the top to around 200 ms at the bottom (by default).','The cited historical Solaris documentation describes 60 time-sharing priorities and default quanta from 40 ms at priority 59 to 200 ms at priority 0; these are version/configuration-specific values.'),('H now waits at most for L\'s critical section.','In this isolated three-thread example, H waits for L\'s remaining critical section plus scheduling overhead. General bounds must include nesting, higher-priority interference and any blocking by the holder.'),('the **priority ceiling** protocol:','an **immediate priority ceiling** protocol:'),('Priority inheritance (or ceilings) bounds the delay; Pathfinder was fixed by turning it on.','Priority inheritance mitigates inversion under stated scheduling/locking assumptions; Pathfinder\'s fix enabled it for the relevant semaphore mechanism.')]:edit(a,old,new,'Correct model-specific timing, priority weighting and historical defaults.',src)
s=Path(a).read_text();start=s.index('Pathfinder landed on Mars');end=s.index('### Priority inheritance',start)
edit(a,s[start:end],'''Glenn Reeves, who led Pathfinder's software team, describes a priority inversion involving a semaphore inside VxWorks `select`/pipe handling. The low-priority ASI/MET task held the resource; intermediate work delayed it while the higher-priority `bc_dist` task waited. A deadline check by `bc_sched` triggered a reset.

Engineers reproduced the failure with tracing, enabled priority inheritance through a configuration change, tested the wider effects and deployed it using their validated spacecraft patch mechanism. Reeves explicitly says they **did not use the VxWorks shell** for the update. He also says the pre-landing occurrence was investigated and remained unresolved, rather than being dismissed as a hardware glitch.

This firsthand correction matters: retain the inversion lesson without repeating the inaccurate interpreter-fix and ignored-warning story.

''','Replace secondhand historical details contradicted by spacecraft software lead.',src)
edit(a,'- [What really happened on Mars Pathfinder — Mike Jones (Cornell mirror)](https://www.cs.cornell.edu/courses/cs614/1999sp/papers/pathfinder.html)','- [Glenn Reeves: what happened on Pathfinder — firsthand correction in RISKS](https://catless.ncl.ac.uk/Risks/19.54.html)','Use firsthand correction rather than disputed secondhand account.',src)
qe(b,'sched-priority-mlfq-q1','explanation','Lower nice means greater fair-scheduling weight when competing within the same scheduling group. Lowering nice normally needs permission, but RLIMIT_NICE can authorise an unprivileged process to do so.','Nice is relative weight and can be lowered under resource-limit authorisation.',['https://man7.org/linux/man-pages/man7/sched.7.html'],option=1)
qe(b,'sched-priority-mlfq-q4','prompt','Priorities run from 0 (highest) to 127. A waiting thread improves by one level every 2 seconds, starting at 100. How long until it reaches the same priority as work arriving at priority 40?','Reaching equal priority is computable; exact first-run time needs queue assumptions.',src)
qe(b,'sched-priority-mlfq-q4','workedExample','The gap is 100 - 40 = 60 levels; 60 × 2 = 120 seconds. That establishes equal priority, not an exact first-run time. Tie-breaking, queue length and scheduling overhead determine when it actually runs.','Separate ageing threshold from scheduling guarantee.',src)
qe(b,'sched-priority-mlfq-q7','explanation','Boosting gives low-queue jobs access to the top queue again. With fair queue ordering it combats starvation, but service within every boost period is not guaranteed when the runnable queue is large.','Boost period is not a universal bound on time to service.',src,option=0)
qe(b,'sched-priority-mlfq-q7','workedExample','A boost returns low-priority jobs to the highest queue, helping old jobs and jobs whose behaviour changed. Queue ordering and available capacity still determine service; not every job must run once per period. Boosting does not by itself solve lock-owner inversion or eliminate tuning parameters.','Remove false once-per-period bound.',src)
qe(b,'sched-priority-mlfq-q9','text','Priority inversion in a select/pipe semaphore; engineers enabled inheritance, tested the change and applied it through the spacecraft patch process','Correct historical fix mechanism.',src,option=1)
qe(b,'sched-priority-mlfq-q9','explanation','Reeves identifies the semaphore in VxWorks select/pipe handling. His firsthand account rejects the claim that the shell/C interpreter was used to patch it.','Prefer firsthand account over original secondhand narrative.',src,option=1)
qe(b,'sched-priority-mlfq-q9','workedExample','The ASI/MET task held a resource needed by bc_dist. Intermediate-priority work delayed the holder; bc_sched detected the missed deadline and initiated reset. After reproducing the failure, engineers enabled inheritance, checked system-wide effects and used the validated onboard patch mechanism. This was not an interactive C-interpreter fix.','Correct mechanism and deployment procedure.',src)
qe(b,'sched-priority-mlfq-q9','link',{'title':'Glenn Reeves: firsthand Pathfinder correction in RISKS','url':'https://catless.ncl.ac.uk/Risks/19.54.html'},'Link to direct project testimony.',src)
qe(b,'sched-priority-mlfq-q10','explanation','Inheritance removes the medium-priority interference in the simple example. General delay bounds also depend on nested locks, holder blocking and higher-priority work; inheritance does not eliminate waiting.','Priority inheritance alone is not a universal critical-section-only bound.',src,option=3)
qe(b,'sched-priority-mlfq-q11','explanation','The fifth burst ends at 92; 100 is eight milliseconds later, when the next burst becomes ready after its I/O wait.','Correct two-versus-eight-millisecond arithmetic.',src,option=2)
save([a,b])
