exec(open('/tmp/cs-study-audit-full/helper.py').read())
b='content/os/03-synchronisation/';p=b+'sync-classic-problems.md';q=b+'sync-classic-problems.questions.json';s=['https://pages.cs.wisc.edu/~remzi/OSTEP/threads-sema.pdf'];book=['https://greenteapress.com/semaphores/LittleBookOfSemaphores.pdf'];py=['https://docs.python.org/3/library/queue.html'];rw=['https://man7.org/linux/man-pages/man3/pthread_rwlockattr_setkind_np.3.html'];c=['https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf']
edit(p,'At every moment `empty + full` equals N, apart from the brief window inside a producer or consumer.','When no operation holds an outstanding permit, empty + full = N. During in-flight operations, reserved permits are not yet reflected in the opposite semaphore; that interval can be arbitrarily long if a thread is delayed. These C sketches assume successful initialization/calls; production code must handle EINTR and other semaphore errors.','Invariantnotcontinuousexceptbriefnotbounded.',s)
edit(p,'A semaphore that every thread','A semaphore that every thread','noop',s) if False else None
edit(p,'add a semaphore that every thread, reader or writer, must pass through in arrival order.','add a turnstile with an explicit fair admission policy for readers and writers. Plain POSIX/Python semaphore APIs do not by themselves promise FIFO wake order.', 'Turnstilefairnessrequiresunderlyingfairness.',book)
edit(p,'it can be set to prefer writers with a non-portable attribute','its nonrecursive writer-preference mode requires promising that read locks will not be acquired recursively; the similarly named recursive writer-preference setting is ignored by glibc','ActualNPattributecriticalrestriction.',rw)
edit(p,'by the pigeonhole principle, at least one of them can get both forks.','the full five-way waiting cycle cannot form, assuming admitted philosophers retain their permit until releasing both forks and runnable holders make progress.','Deadlockproofprogressconditions.',s) if 'by the pigeonhole principle' in Path(p).read_text() else None
edit(p,'N = 3\nfree_seats = N','N = 3\nfree_seats = N', 'noop',book) if False else None
edit(p,'barber_ready = Semaphore(0)','barber_ready = Semaphore(0)\ncustomer_seated = Semaphore(0)\nhaircut_done = Semaphore(0)\ncustomer_left = Semaphore(0)','Addhandshakes sobarber cannotcallmultipleclientsbeforefirstarrives.',book)
edit(p,'        barber_ready.release()  # call\n        cut_hair()','        barber_ready.release()  # call\n        customer_seated.acquire()\n        cut_hair()\n        haircut_done.release()\n        customer_left.acquire()','Rendezvousandcompletionrequiredforexclusivechair.',book)
edit(p,'    barber_ready.acquire()   # wait turn\n    get_haircut()','    barber_ready.acquire()   # wait turn\n    customer_seated.release()\n    haircut_done.acquire()   # wait finish\n    customer_left.release()','Customerdoesnotleavebeforehaircutdone.',book)
edit(p,'- `barber_ready` is the barber calling the next customer to the chair.','- `barber_ready` calls one customer. The seated, done and left handshakes coordinate chair arrival, haircut completion and departure before the next customer is called. These snippets assume no cancellation or failure during the handshake.','Explaincompleteprotocolandfailurelimits.',book)
qe(q,'sync-classic-problems-q2','workedExample','If these rates persist, the backlog grows by 30000 lines/s: 108 million lines in an hour. At an illustrative 200 bytes per line, payload alone is 21.6 GB before object/queue overhead. Memory pressure may cause allocation failures, termination or reduced throughput; a kill is not inevitable. A bounded queue applies back-pressure, with bounded queued item count rather than a universal byte limit.','MathcorrectbutOOMkillinevitablefalse anditemsizebound.',py)
qe(q,'sync-classic-problems-q6','text','All acquire lower-numbered forks before higher ones, so wait edges increase in fork number and cannot form a cycle','Highestforkholderalreadyhaslower, originalgetothermisleading.',s,option=2)
d=json.loads(Path(q).read_text());old=next(x for x in d if x['id']=='sync-classic-problems-q8')['prompt'];qe(q,'sync-classic-problems-q8','prompt',old+' Assume the barber does not finish the current haircut while the five arrivals check for seats.','Concurrentarrivalnotatomicagainstservicecompletion.',book)
qe(q,'sync-classic-problems-q9','text','Publish an immutable configuration by atomic pointer swap, with an explicit lifetime/reclamation protocol for readers','Pointer swapalonecanuseafterfree.',c,option=2)
qe(q,'sync-classic-problems-q9','explanation','This can avoid waiting for readers before publishing a new version. The old object must remain alive while readers use it; reclamation or bounded-memory requirements can still require waiting.','RCUwriterdoesnotalwaysneverbock.',c,option=2)
qe(q,'sync-classic-problems-q9','workedExample','At a sustained rate of 5000 reads/s and mean duration 0.002 s, Little\'s law gives mean concurrency 10. That mean alone does not determine how often the count reaches zero. A fair or writer-preference policy limits reader bypass; immutable publication can remove that acquisition bottleneck if old versions are reclaimed safely. Adding threads alone supplies no starvation fix.','Mean10doesnotprovegapdistributionnoradditionalthreadsraisefixedarrivals.',s)
for id in ['sync-classic-problems-q10','sync-classic-problems-q11']:
 d=json.loads(Path(q).read_text());old=next(x for x in d if x['id']==id)['prompt'];qe(q,id,'prompt','Treat the trace as an illustrative interleaving; a literal plain-C implementation has a data race and undefined behavior. '+old,'DistinguishtoytracefromlanguageUB.',c)
qe(q,'sync-classic-problems-q11','workedExample','An illustrative failure has both producers read in=0, both overwrite buf[0], both set in=1 and both post full. The count advertises two items but only one slot was filled. Plain C racing accesses are undefined behavior, not limited to this trace. This implementation needs serialized index/slot updates; other carefully designed multi-producer algorithms can use atomics instead of a mutex.','Mutexnotuniversallyessentialalternativelockfree.',c)
save([p,q])
# Record fetched POSIX mirror rather than failed official origin.
for x in r['findings']:
 x['sources']=['https://man7.org/linux/man-pages/man3/pthread_cond_wait.3p.html' if u=='https://pubs.opengroup.org/onlinepubs/9799919799/functions/pthread_cond_wait.html' else u for u in x['sources']]
P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n')
