exec(open('/tmp/cs-study-audit-full/helper.py').read())
b='content/os/03-synchronisation/';p=b+'sync-race-conditions.md';q=b+'sync-race-conditions.questions.json';s=['https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf'];t=['https://clang.llvm.org/docs/ThreadSanitizer.html'];py=['https://docs.python.org/3/howto/free-threading-python.html']
edit(p,'Compile it with `gcc -O0 -pthread` and run it a few times on a multicore machine. You will typically see different numbers below 2,000,000 on each run, such as 1,143,027 or 1,388,412. (With optimisation on, the compiler may transform the loop and hide or change the symptom, which is its own lesson: the code is broken either way.)','This deliberately broken C program has a data race and undefined behavior, so no output is guaranteed at any optimization level. A lost-update trace below illustrates a simplified machine model, not all behavior permitted for this C program.\n\n> [!note] Content gap\n> No reproducible record supports the original exact sample counts, so they are omitted. A run that prints 2,000,000 does not establish correctness.','Unrecorded empirical output removed and UB madeexplicit.',s)
edit(p,'On the free-threaded build (3.13+, no GIL) or with a slightly different loop body, it loses updates readily.','Free-threaded builds and changes that introduce additional switching points can expose lost updates; neither failure nor a particular count is guaranteed.','Outcome conditionalnotuniversal.',py)
edit(p,'It satisfies all three requirements, on paper. On a modern multicore CPU it is **broken as written**, because both the compiler and the processor may reorder the store to `flag[me]` with the later load of `flag[other]`.','Under sequentially consistent atomic reads/writes and suitable progress assumptions, the algorithm satisfies these requirements. The plain C version is **broken as written** because it has data races and undefined behavior; hardware store buffering is an additional way a literal load/store implementation can fail.','LanguageUBnotfixedbyfencealone.',s)
edit(p,'Pure load/store algorithms like Peterson\'s fail on modern hardware without memory barriers.','Peterson\'s teaching algorithm needs a valid atomic memory model, such as sequentially consistent C atomics; fences alone do not legalize racing plain C accesses.','Keepkeytakeawayconsistent.',s)
for id in ['sync-race-conditions-q1','sync-race-conditions-q7','sync-race-conditions-q8']:
 d=json.loads(Path(q).read_text());old=next(x for x in d if x['id']==id)['prompt'];qe(q,id,'prompt','Use a sequentially consistent toy model with indivisible loads/stores and preserved per-thread order, not the semantics of data-racing C. '+old,'State explicitmodel fordeterminateanswer.',s)
qe(q,'sync-race-conditions-q1','explanation','The stipulated toy trace has a determined result. A plain C implementation with unsynchronized conflicting accesses instead has undefined behavior, so this trace is not a language-level output guarantee.','OriginaldismissedcorrectUBqualification.',s,option=3)
qe(q,'sync-race-conditions-q7','explanation','The question explicitly stipulates a sequentially consistent trace model. Its outcomes are 1 or 2; a data-racing plain C program has no corresponding output guarantee.','Toymodelnotuniversalhardware.',s,option=3)
qe(q,'sync-race-conditions-q8','explanation','Correct. The trace arranges for the final store overall to write 2. The two threads need not both finish by storing 2.','Originalsaideachthreadfinaldepends1contradictstraceA3.',s,option=1)
d=json.loads(Path(q).read_text());old=next(x for x in d if x['id']=='sync-race-conditions-q3')['prompt'];qe(q,'sync-race-conditions-q3','prompt','Treat the code as pseudocode with sequentially consistent atomic access to turn. '+old,'PlainCspinotherwiseUB underminesanswer.',s)
d=json.loads(Path(q).read_text());old=next(x for x in d if x['id']=='sync-race-conditions-q4')['prompt'];qe(q,'sync-race-conditions-q4','prompt','Assume withdraw subtracts unconditionally and performs no balance validation. '+old,'APIbehaviorotherwiseundefinedcouldrejectoverdraft.',s)
qe(q,'sync-race-conditions-q6','explanation','Both accesses are atomic, so this operation has no data race. Whether the overall application is correct still depends on its protocol and numeric requirements.','Atomicdoesnotprovewholeprogramcorrect.',s,option=3)
qe(q,'sync-race-conditions-q10','workedExample','The plain C implementation already has undefined behavior. In a separate literal machine-code model, stores can remain buffered while each core reads the other flag as zero; both may then enter. Sequentially consistent C atomics provide a valid teaching implementation. A hardware fence by itself does not repair non-atomic C data races.','DistinguishhardwareillustrationfromvalidClanguage.',s)
qe(q,'sync-race-conditions-q11','explanation','This is a data race and may be reported when the conflicting path is executed and instrumented. A detector run does not guarantee every possible race is found.','Dynamicdetectornotguaranteedreport.',t,option=3)
r['currentModule']={'module':'content/os/03-synchronisation','status':'first lesson/question pair reviewed; remaining five pending'}
save([p,q])
