from helper import *
b='content/os/06-file-systems/fs-crash-consistency';m=b+'.md';q=b+'.questions.json'
ext=['https://docs.kernel.org/admin-guide/ext4.html'];fs=['https://man7.org/linux/man-pages/man2/fsync.2.html'];pg=['https://www.postgresql.org/docs/release/11.2/','https://www.postgresql.org/docs/current/runtime-config-error-handling.html'];er=['https://docs.kernel.org/core-api/errseq.html'];bt=['https://btrfs.readthedocs.io/en/latest/ch-file-attributes.html','https://btrfs.readthedocs.io/en/latest/Checksumming.html'];zf=['https://openzfs.github.io/openzfs-docs/man/master/7/zpoolconcepts.7.html'];th=['https://pages.cs.wisc.edu/~remzi/OSTEP/file-journaling.pdf']
def e(a,c,r,s=th):edit(m,a,c,r,s)
def f(n,k,c,r,s=th,o=None):qe(q,'fs-crash-consistency-q'+str(n),k,c,r,s,o)
e('The disk can only write one block at a time, and power can fail between any two of them.','Storage can execute multiple writes concurrently; it does not ordinarily make an arbitrary multi-block filesystem update atomic. Power can fail with only part persisted.','Deviceconcurrency false.')
e('Appending one 4 KiB block to a file needs three on-disk structures updated:','In a teaching model, appending one newly allocated 4 KiB block updates three structures (real filesystems may update more):','Allocationextra metadata.')
e('`fsck` (file system check) scans the whole disk:','A classic full filesystem checker scans relevant metadata across the filesystem:','Notallrawdatadisk.')
e('Time scales with the size of the file system, not the size of the damage.','Work depends heavily on metadata volume, layout and checking algorithms rather than only the damaged portion.','Notlinearcapacityguarantee.')
e('Recovery time now depends on the size of the journal (tens of MiB up to around 1 GiB on ext4, scaled to the file system), not the size of the disk. That\'s seconds instead of hours.','Ordinary journal replay works over recoverable log transactions rather than performing a full metadata scan. Journal size, pending transactions, device speed and other recovery work determine its duration.\n\n> [!note] Recovery measurement gap\n> No reproducible timing record accompanies this lesson. Fixed seconds-versus-hours guarantees and an unversioned ext4 journal-size range are omitted.','Unsupportedjournalmax/timingremoved.',ext)
e('Modern ext4 can instead add a **checksum** to the commit block, which lets recovery spot an incomplete transaction without that extra wait.','Ext4\'s journal_async_commit mode uses journal checksums to permit a different submission ordering and reject incomplete transactions. Merely enabling checksums is not the same as enabling asynchronous commit, and acknowledged durability still requires the needed writes to persist.','journal_checksum !=async_commit.',ext)
e('Journaling data means **every block is written twice**, once to the journal and once in place. That halves write bandwidth for large writes.','In the simple full-data-journaling model, payload is written to the journal and later home locations. This increases write traffic; achieved throughput is not necessarily halved because batching, layout and device behavior matter.','2xtraffic !=halfbandwidth.',ext)
e('So metadata never points at unwritten blocks: after a crash, a file contains either the new data or the old state, never someone else\'s stale blocks.','This ordering prevents exposing stale contents of newly allocated blocks through a committed metadata update, assuming a correctly functioning storage stack. It does not make arbitrary multi-block application writes atomic or guarantee only a complete old/new application state.','Orderednotapplicationatomic.',ext)
e('So after a power cut you can lose up to about 5 seconds of metadata changes (more for data still in the page cache), but the structure stays consistent.','This controls transaction scheduling, not an application-level maximum loss window; delayed allocation, I/O delays and configuration matter. Use explicit synchronization for acknowledged durability.','Commitperiodnotstrictdurabilitybound.',ext)
e('The **final step** is a single atomic write that switches the root pointer from R to R\'. ZFS calls this root the **uberblock**.','Conceptually, a durable commit selects the new root after its dependencies are stable. Real implementations use checksummed and redundant commit records rather than assuming every root-sector write is magically atomic. ZFS uses uberblocks to identify committed tree state.','Realrootprotocolnotonesectorguarantee.',zf)
e('There\'s no journal and no fsck. The old root makes **snapshots** nearly free: just keep R and don\'t reclaim its blocks.','Copy-on-write reduces reliance on in-place metadata repair, but these systems still have recovery machinery: ZFS uses an intent log for synchronous operations, and Btrfs has a tree log and btrfs check. Snapshots can initially share blocks cheaply; retained old versions consume space as data changes.','ContradictZIL/noBtrfscheckfalse.',zf+['https://btrfs.readthedocs.io/en/latest/btrfs-check.html'])
e('ZFS also stores a **checksum of every block in the pointer that references it**, which makes the tree a Merkle tree. Btrfs checksums every data and metadata block too. A read that doesn\'t match its checksum is detected, and with redundancy (mirrors, RAID-Z) it\'s repaired automatically. That catches silent corruption (bit rot, misdirected writes) that ext4\'s journal can\'t see.','ZFS block-pointer checksums and Btrfs checksums can detect silent corruption within their configured protection scope. Btrfs metadata carries checksums, while data checksumming can be disabled, including for NOCOW data. Recoverable redundancy can let a read find and repair a valid copy; repair is not possible if every copy is bad. This protection is separate from ext4\'s metadata journal, which does not generally checksum ordinary file payload.','Not everyblock/alwaysrepair.',zf+bt)
e('Btrfs lets you disable CoW per file (`chattr +C`).','Btrfs allows NOCOW for newly created/empty files, or inheritance from a directory via chattr +C; existing populated files are not retroactively converted. Shared snapshot extents still require COW on modification.','NOCOWscope.',bt)
e('`write()` copies bytes into the page cache and returns.','Ordinary buffered regular-file write copies data into cache; direct and synchronous I/O have different paths and completion semantics.','Not allwrite buffered.',fs)
e('Returns when they are durable.','Successful completion promises durability under the filesystem/device contract; errors must be checked and faulty hardware can violate it.','Returnfailure not durable.',fs)
e('Faster.','It may avoid work; speed depends on workload and filesystem.','Notalwaysfaster.',fs)
a=Path(m).read_text();start=a.index('import os\n\ndef atomic_write');end=a.index('\n```',start)
old=a[start:end]
new='''import os
import tempfile

def atomic_write(path, data):
    d = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=d)
    try:
        try:
            view = memoryview(data)
            while view:
                n = os.write(fd, view)
                if n <= 0:
                    raise OSError("no progress")
                view = view[n:]
            os.fsync(fd)
        finally:
            os.close(fd)
        os.replace(tmp, path)
        dfd = os.open(d, os.O_RDONLY)
        try:
            os.fsync(dfd)
        finally:
            os.close(dfd)
    finally:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass'''
e(old,new,'Handle partial writes; private unique temp avoids collision/symlink clobber; clean own temp.',fs+['https://docs.python.org/3/library/tempfile.html'])
e('`rename` within one file system is atomic:','This example assumes a trusted stable directory, no concurrent replacement, a previously durable old file, and filesystem/device support for the synchronization contract. It creates a mode-0600 replacement; preserving ownership, ACLs and other metadata needs explicit handling before fsync. If an error occurs after rename, the visible result may already be new even though durability is uncertain.\n\n`rename` within one file system is atomic for namespace visibility:','Stateoldpersist/errorpostrename/permissions.',fs)
e('PostgreSQL, like most software, treated the failure as transient','The affected PostgreSQL behavior treated the failure as transient','Removeunsourcedmostsoftware.',pg)
e('The data was gone, with no error anywhere.','Recovery data could then be lost despite an earlier error having been reported.','ContradictionreportedEIO noerror.',pg)
e('Linux 4.13 and later improved tracking (Jeff Layton\'s `errseq_t` work), so each open file sees a write-back error once. But the error is still reported only once, and the dirty data is still not kept for a retry.','Linux 4.13 introduced improved writeback-error tracking using errseq_t. Relevant open file descriptions can observe newly recorded errors, but this is not an unbounded queue of every failure; sampling/coalescing and filesystem attribution matter. Improved reporting does not guarantee preservation of failed dirty data for a retry.','Not exactone everyfd everyerror.',er+fs)
e('PostgreSQL\'s fix (version 12, back-patched in early 2019 to all supported versions) was to **PANIC on fsync failure**: crash, restart and replay the WAL, which still has the changes. MySQL\'s InnoDB, MongoDB\'s WiredTiger and others made similar changes.','PostgreSQL changed the default to **PANIC on data-file synchronization failure**, documented in release 11.2 (14 February 2019), with data_sync_retry controlling the behavior. Restart and WAL recovery avoid blindly trusting a retry, subject to surviving WAL and storage. Unverified claims about other databases making the same change are omitted.','Versionclarify/unsupportedcrossDBhistory.',pg)
e('Treat a failed `fsync` as "you have lost data in this file since the last successful fsync, and you can\'t get it back from the page cache". Recover from your own log, or fail loudly. Never retry and carry on.','A writeback-related fsync failure makes durability uncertain: data may have been lost, but the error does not prove every byte was lost. A successful retry alone is not recovery. Diagnose the error and use an application recovery/rewrite protocol or fail the operation. Errors such as EINTR have different semantics; do not replace error-specific handling with a claim that every failed fsync proves data loss.','EIOuncertain !=allfail dataloss;EINTR.',fs+pg)
e('Drives that ignore flushes, and RAID controllers with write cache but no battery, can still lose acknowledged writes in a power cut. Enterprise SSDs include **power-loss protection** capacitors for this reason.','A device/controller that dishonors the durability contract can lose writes acknowledged as durable. Volatile caches without batteries can still be safe when correct flush/FUA handling persists data; power-loss protection is another mechanism, and its presence/scope must be checked per product.','No battery !=unsafeflush/allenterprisePLP.',fs)
e('- Copy-on-write file systems (ZFS, Btrfs) never overwrite live blocks and switch roots atomically, which also gives cheap snapshots and end-to-end checksums.','- CoW designs commit new trees while retaining old state; real systems add logs, redundant commit records and configurable data/checksum policies.','Summaryscope.',zf+bt)
e('Treat a failed `fsync` as data loss, never as something to retry (fsyncgate).','Treat writeback-error durability as uncertain; a successful retry alone does not recover possibly lost data.','SummaryEIOvsallfail.',fs+pg)
f(1,'prompt',json.loads(Path(q).read_text())[0]['prompt']+' Assume the lesson\'s ordinary non-checksummed three-block teaching model, with no concurrent changes.','Scopefilechecksums/metadata.',th)
f(2,'workedExample','A classic full checker must inspect broadly enough to reconcile inode/block ownership, directories and allocation metadata. Its cost depends on metadata volume, layout, algorithms and hardware, not just the damaged bytes. Journal replay usually bounds normal crash-recovery work to relevant log transactions, but neither a fixed runtime nor freedom from all later full checks follows. The stated three-hour result is hypothetical.','No seconds howeverbig/strictlinear.',th)
f(3,'prompt',json.loads(Path(q).read_text())[2]['prompt']+' Focus on journaled metadata under the teaching protocol, not rollback of unjournaled file data.','Ordereddata mayalreadywritten.',ext)
f(3,'workedExample',json.loads(Path(q).read_text())[2]['workedExample'].replace('the in-place structures were never touched.','the metadata from this transaction must not have been checkpointed. Unjournaled file data can already have reached its home location.').replace('The changes from that transaction are lost','Its journaled metadata changes are not replayed'),'Noallstructuresuntouched/data rollback.',ext)
f(4,'prompt',json.loads(Path(q).read_text())[3]['prompt']+' Use a simplified completed-journal-plus-checkpoint payload-traffic model, ignoring device amplification and repeated overwrites.','2xmodelnotactualalltraffic.',ext)
f(4,'workedExample',json.loads(Path(q).read_text())[3]['workedExample'].replace('The metadata for 1 GB of extents is a handful of blocks.','Extent metadata can be compact for long runs; fragmentation and allocation metadata add work.').replace('That 2× cost for large writes is why metadata-only journaling is the default.','The model illustrates additional traffic, not an exact throughput ratio or measured hardware write amplification.'),'Not handful universally.',ext)
f(5,'prompt',json.loads(Path(q).read_text())[4]['prompt']+' Assume a newly allocated data block, functioning storage honoring flushes, and no corruption outside the modeled crash.','No absolute impossiblehardware.',ext)
f(5,'explanation','Possible. Normal journal recovery can avoid a full checker; its runtime is not fixed.','Remove seconds.',ext,o=3)
f(5,'workedExample',json.loads(Path(q).read_text())[4]['workedExample'].replace('Only `fsync` does.','Successful appropriate synchronization, such as fsync plus required directory synchronization, provides durability under the storage contract. Other synchronous I/O mechanisms can also provide it.').replace('So the possible states are:','For the simplified new-block transaction, relevant states include:'),'Onlyfsyncfalse/recordatomicbeyondmodel.',fs+ext)
f(6,'explanation','Correct as a general Linux filesystem portability concern: file fsync does not by itself guarantee persistence of the parent directory entry. Directory synchronization support and semantics must be checked.','POSIXdoesnotuniversallyrequiredirectoryfsync.',fs,o=2)
f(6,'workedExample',json.loads(Path(q).read_text())[5]['workedExample'].replace('Portable fix:','On Linux filesystems supporting directory fsync, explicitly synchronize the directory and check errors:'),'Notallplatformdirsfsync.',fs)
f(7,'prompt',json.loads(Path(q).read_text())[6]['prompt']+' Assume the old file and its directory entry are already durable, a trusted stable directory, full successful writes, checked errors, and a filesystem/device with the required rename/fsync crash guarantees.','Otherwiseuniversalanymoment false.',fs)
f(8,'prompt',json.loads(Path(q).read_text())[7]['prompt']+' Consider the simplified tree-commit model before any replay of a separate intent log.','ZILmayreplaynew.',zf)
f(8,'workedExample','The old committed root references an intact old tree. New blocks not reachable from a valid committed root are not part of that state. Real ZFS commit selection uses redundant validated uberblocks rather than assuming one universally atomic physical write. After selecting a root, intent-log replay can recover separately acknowledged synchronous operations; the question explicitly isolates the tree-commit stage.','Nooneatomic/spaceownershipguarantee.',zf)
f(9,'explanation','This is the risk: some writeback failures can leave no dirty data for the retry to flush. The second success alone does not establish that earlier data persisted.','Maynotalwaysmarkedclean.',pg,o=0)
f(9,'explanation','Correct. Writeback-error handling does not guarantee failed data remains available for retry. Use error-aware recovery; PostgreSQL normally PANICs for data-file sync failure and relies on surviving WAL.','Not exactonceallversions.',pg+er,o=1)
f(9,'explanation','Improved errseq_t tracking is about reporting, not guaranteeing dirty-data retention. Descriptor sampling and error coalescing also matter.','Notreliableeveryerroronce.',er,o=2)
f(9,'explanation','Data may be lost, but neither loss nor another EIO is guaranteed. No new recorded error may remain for that description after the first report.','Notonceeveryerrorproof.',er,o=3)
f(9,'workedExample',json.loads(Path(q).read_text())[8]['workedExample'].replace('Correct handling: treat everything written since the last good fsync as lost.','Correct handling: regard affected durability as uncertain; not every byte is necessarily lost.').replace('fsync #1    returns EIO (reported once)','fsync #1    reports recorded EIO').replace('Follow the page through:','One possible writeback-failure path:'),'PossiblepathnotallLinux.',pg+er)
f(10,'explanation','The episode involved buffered writes and error handling; O_DIRECT was not the required cause. This lesson does not establish that other named engines made identical fixes.','Unsupportedcrossenginehistory.',pg,o=3)
f(10,'workedExample','The historical issue combined lossy writeback-error reporting with failure paths that could discard unwritten data. Linux4.13 improved error tracking using errseq_t, but that does not promise retention of every failed page or a permanent queue of every error. PostgreSQL11.2 documents default PANIC instead of retry, allowing recovery from surviving WAL. The general lesson is possible data loss and uncertain durability after a writeback failure, not that all kernels always discard all data or every fsync error is unrecoverable.','Allversions/no retention universalfalse.',pg+er)
f(11,'prompt',json.loads(Path(q).read_text())[10]['prompt'].replace('What is the most likely cause, and a common mitigation?','Which layout-related explanation should be checked, and what mitigation has relevant tradeoffs?'),'Cannotdiagnoseonlyage.',bt)
f(11,'explanation','CoW updates can fragment layout. NOCOW must be configured on empty/new files or inherited by newly created files; it disables data checksums and compression for that data. Snapshot-shared extents still require COW when modified. Measure layout and I/O before changing policy.','Snapshotstillcow/directorynotretroactive.',bt,o=1)
f(11,'workedExample','Random CoW updates can replace adjacent logical blocks with scattered extents, but measure fragmentation and storage behavior before attributing slowdown. A directory NOCOW attribute affects newly created files; it does not convert existing populated files. NOCOW disables data checksums/compression and still needs COW for shared extents. Defragmentation may unshare extents and increase space use. Filesystem migration and database-record-size tuning require workload-specific validation; database WAL does not replace all filesystem integrity features. No measured seek latency or universal tuning value is supplied.','Remove10ms/mythallNOCOW/same ZFSsize universal.',bt+zf)
f(12,'prompt',json.loads(Path(q).read_text())[11]['prompt']+' Assume the naive protocol has neither an ordering guarantee nor transaction-integrity verification.','Else checksummedfine.',th)
f(12,'explanation','Correct. A commit marker alone is insufficient if it can persist before its dependencies. An asynchronous checksummed journal can reject incomplete transactions, but it still needs a complete durable commit before acknowledging success. journal_async_commit and journal_checksum are distinct settings.','Correctasyncnotjustchecksum.',ext,o=1)
f(12,'workedExample','In the naive protocol, the commit marker can persist while some logged blocks do not, allowing invalid replay. One remedy orders and flushes log contents before the durable commit record. An asynchronous protocol can use transaction checksums to reject incomplete records, but must still ensure all required writes are stable before promising durability. Checksums detect incomplete/corrupt records; they do not themselves persist data or universally make commits faster.','Checksumnotdurability/guaranteedspeed.',ext)
save([m,q]);r['currentModule']={'module':'content/os/06-file-systems','status':'First three pairs fully read/corrected (34questions); page-cache/storage-devices/modern-distributed and execution/stamp pending'};P.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n')
