exec(open('/tmp/cs-study-audit-full/helper.py').read())
p=Path('content/os/07-io/io-network-stack.md')
s=['https://docs.kernel.org/bpf/verifier.html']
edit(p,'A **verifier** checks each program before it runs: bounded loops, every memory access bounds-checked, no arbitrary kernel pointers.','A **verifier** checks permitted control flow, pointer types and memory access before execution. Packet accesses must have provable bounds; this does not mean every access needs its own runtime check.', 'Distinguish static proof from a mandatory runtime check at every access.',s)
edit(p,'Every `> end` check is there for the verifier: without it, the program is rejected at load time, because reading past the packet would be an out-of-bounds kernel read.','The bounds checks establish that the packet fields being read are available. The verifier must be able to prove those accesses safe; an earlier sufficient check may cover several reads. This fragment has been exercised as native C with synthetic packets, but has not been compiled and loaded through a real BPF verifier in this audit.', 'Avoid claiming every individual bounds check is independently mandatory or actual BPF-load validation occurred.',s)
edit(p,'> Cloudflare drops DDoS traffic with XDP before it reaches the stack. Meta\'s **Katran** layer-4 load balancer is built on XDP. **Cilium** implements Kubernetes networking, load balancing and network policy with eBPF, replacing large iptables rule sets whose linear rule evaluation slows down as services grow.', '> Published examples include Cloudflare\'s XDP packet-filtering work and Meta\'s XDP-based **Katran** layer-4 load balancer. **Cilium** supports eBPF Kubernetes networking and a kube-proxy replacement. Its exact use of iptables depends on configuration and kernel capabilities; these examples do not guarantee a particular deployment\'s throughput.', 'Source published examples without asserting current internal deployments or universal iptables replacement/performance.', ['https://blog.cloudflare.com/how-to-drop-10-million-packets/','https://engineering.fb.com/2018/05/22/open-source/open-sourcing-katran-a-scalable-network-load-balancer/','https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/','https://docs.cilium.io/en/latest/network/ebpf/iptables/'])
edit(p,'- RSS hashes flows to per-CPU queues in hardware; RPS, RFS and XPS do steering in software, with locality and distribution depending on configuration.','- RSS hashes flows to hardware RX queues; IRQ affinity and software steering determine CPU placement. RPS, RFS and XPS help tune locality and distribution.', 'Keep summary consistent with queue-versus-CPU qualification.', ['https://docs.kernel.org/networking/scaling.html'])
edit(p,'- [NAPI — Linux kernel documentation]', '- [Ethernet throughput calculation — Infineon](https://community.infineon.com/t5/Knowledge-Base-Articles/AURIX-Ethernet-throughput-vs-bandwidth/ta-p/1123904)\n- [NAPI — Linux kernel documentation]', 'Add primary manufacturer source for 64+8+12-byte-time arithmetic.', ['https://community.infineon.com/t5/Knowledge-Base-Articles/AURIX-Ethernet-throughput-vs-bandwidth/ta-p/1123904'])
save([*p.parent.glob('*.md'),*p.parent.glob('*.questions.json')])
