from helper import *
m=Path('content/security/01-fundamentals');p=m/'secf-authentication.md';q=m/'secf-authentication.questions.json';o='https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'
qe(q,'secf-authentication-q4','explanation','Correct under the assumed rate: about 6.1 × 10^5 seconds, or seven days. Each unsalted candidate digest can be checked against all hashes using that scheme; this search only covers the stipulated password space.','Residual unsalted coverage qualification.',[o],1)
edit(p,'1. **Fast hashes, or no salt.**','1. **Fast hashes, or no salt.**','No-op placeholder',[]) if False else None
p=m/'secf-access-control.md'
edit(p,'The Bell–LaPadula model (1973) prevents secrets leaking downwards:','The Bell–LaPadula model constrains confidentiality-related information flows. In this simplified level-only explanation, assume subjects operate at the named level and have no trusted declassification exception:','Make model assumptions consistent with corrected quiz.',['https://people.eecs.ku.edu/~hossein/710/Lectures/Readings/13-Bell-Lapadu-lookback.pdf'])
edit(p,'## Further reading','> [!note] Scope and execution\n> The directional models omit compartments, trusted exceptions and formal proofs. Python access checks are illustrative and assume trustworthy context; the web handlers omit a full application. No live AWS, Windows MIC, database RLS or ReBAC service was deployed for this lesson review.\n\n## Further reading','State limits visibly.',['https://csrc.nist.gov/projects/role-based-access-control/faqs'])
p=m/'secf-principles.md'
edit(p,'## Further reading','> [!note] Example limits\n> Python permission and failure branches were exercised with test objects. The privileged C race example is a source-reviewed fragment, not an executed setuid program. Cloud policy and cache examples require deployment-specific configuration; they were not tested against live services.\n\n## Further reading','Make deployment gaps explicit.',['https://man7.org/linux/man-pages/man2/access.2.html'])
r.setdefault('additionalSources',[]).extend([x for x in ['https://scispace.com/pdf/integrity-considerations-for-secure-computer-systems-1euz8w4arz.pdf','https://people.eecs.ku.edu/~hossein/710/Lectures/Readings/13-Bell-Lapadu-lookback.pdf','https://versprite.com/cybersecurity-listings/offensive-security-services/application-threat-modeling/','https://linddun.org/linddun-go-categories/','https://openfga.dev/','https://authzed.com/docs/spicedb/concepts/zanzibar/'] if x not in r.get('additionalSources',[])])
save([*m.glob('*.md'),*m.glob('*.questions.json')])
