exec(open('/tmp/cs-study-audit-full/helper.py').read())
b=Path('content/security/02-crypto-basics');p=b/'crypto-macs.md'
edit(p,"HMAC has a security proof: it is a secure MAC as long as the hash's compression function behaves like a pseudorandom function. This is why HMAC-MD5 and HMAC-SHA1 were not immediately broken when MD5 and SHA-1 collisions appeared. Still, use **HMAC-SHA256** for new work.","A collision attack on the unkeyed hash does not automatically forge HMAC. RFC 2104 discusses why HMAC's requirements differ from ordinary collision resistance. Use **HMAC-SHA256** for new work.\n\n> [!note] Content gap: formal HMAC proof\n> The full proof paper could not be retrieved reliably during this review (official/archive retrieval failed). Its exact reduction assumptions and bounds are omitted rather than compressed into an unverified one-line theorem.",'Exactformalproofunretrieved; retainRFCsupportedclaim',['https://www.rfc-editor.org/rfc/rfc2104'])
p=b/'crypto-symmetric.md'
edit(p,'With some guessable text in either message, an attacker can recover both. This is the "two-time pad", and it has broken real systems, including WEP Wi-Fi.','Known or correctly guessed plaintext reveals corresponding bytes of the other message. The XOR alone does not determine both complete messages. This repeated-keystream failure is called the "two-time pad".','XORrelationshipnotcompleteplaintextrecovery',['https://csrc.nist.gov/pubs/sp/800/38/d/final'])
q=b/'crypto-macs.questions.json'
qe(q,'crypto-macs-q1','explanation','A captured message and tag can be replayed while the key and message interpretation remain accepted, unless the protocol enforces freshness.','Consistentreplayqualification',['https://www.rfc-editor.org/rfc/rfc2104'],2)
qe(q,'crypto-macs-q1','workedExample','Under the stated assumptions, a matching tag supports integrity of the covered bytes and authenticity to some key holder. It is a computational assurance, not logical proof or freshness. Encryption adds confidentiality; enforced sequence/timestamp/nonce policy can address replay. Signatures separate signing and verification authority but attribution requires trustworthy key binding and custody.','Avoidabsoluteproofandlegalguarantee',['https://www.rfc-editor.org/rfc/rfc2104'])
save([*b.glob('*.md'),*b.glob('*.questions.json')])
