exec(open('/tmp/lang-helpers.py').read());n='para-imperative-declarative';tf='https://developer.hashicorp.com/terraform/cli/commands/plan';re='https://react.dev/learn/render-and-commit';st='https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html';pg='https://www.postgresql.org/docs/current/using-explain.html'
for a,b,src in [
('SELECT SUM(n * n)','SELECT COALESCE(SUM(n * n), 0)',pg),
('the same query gets faster without being rewritten.','the planner may use it to accelerate suitable queries without rewriting them; an index does not guarantee a faster plan.',pg),
('list.parallelStream().map(f).sum()','list.parallelStream().mapToInt(f).sum()',st),
('A spreadsheet only recalculates cells whose inputs changed.','A spreadsheet can use dependencies to avoid unnecessary recalculation; volatile formulas and full recalculation modes are exceptions.',re),
('works out the minimum DOM changes. Your code never mutates the DOM directly.','computes DOM updates needed by its reconciliation model. Components normally describe output rather than mutate React-managed DOM directly, although refs provide imperative escape hatches.',re),
('**Kubernetes** and **Terraform** take the same approach to infrastructure. You declare "3 replicas of this container", and a **control loop** (reconciliation) repeatedly compares desired state to actual state and acts to close the gap. If a node dies and a replica disappears, the controller notices and starts another. An imperative script ("start 3 containers") would run once and never notice.','**Kubernetes** continuously reconciles declared desired state, such as three Pod replicas, against observed state. When replicas disappear its controllers attempt to restore them, subject to capacity and scheduling constraints. **Terraform** also declares desired infrastructure, but normally refreshes and reconciles during explicit plan/apply runs; it is not a continuously running self-healing controller. Imperative scripts can also run repeatedly and inspect state if programmed to do so.',tf),
('A big benefit of desired-state systems is **idempotence**:','A useful goal of desired-state operations is **idempotence** under stable inputs and provider behavior:',tf),
("React's `useMemo` and `key` props, Kubernetes ordering annotations","React's `useMemo`, or explicit Terraform dependency declarations",tf),
('Many declarative languages add imperative features (stored procedures, recursive CTEs) as a result.','SQL implementations offer procedural extensions; recursive CTEs also express iteration declaratively and can handle some convergence problems.',pg),
('Eager loading (one join) fixes it.','Eager loading with an appropriate join or batch query can avoid those per-object queries.',pg),
('Desired-state systems reconcile continuously and are idempotent; imperative scripts run once.','Kubernetes controllers reconcile continuously; Terraform usually reconciles on explicit runs. Idempotence depends on operation semantics, not on the paradigm label alone.',tf)]:lesson(n,a,b,'Correct tool semantics or qualify execution assumptions.',src)
edit(n,4,'Unindexed equality does not prove only one possible plan.',pg,lambda q:fields(q,workedExample=q['workedExample'].replace('no index on `customer_id`, so the only plan is a sequential scan of all rows','assume the measured plan was a sequential scan, confirmed with EXPLAIN')))
edit(n,5,'Five total runs vs five re-runs; Pods not containers; Terraform not self-healing.',tf,lambda q:fields(q,prompt='A script creates three new web containers on every run. A Kubernetes Deployment declares three Pods, each containing one web container. Starting empty, the script is run five times total and the unchanged manifest is applied five times. After successful reconciliation with no rollout, failures or external controllers, how many web containers are running in each case?',workedExample='The script creates 5 × 3 = 15 containers. The unchanged Deployment keeps a desired count of three Pods, each with one web container here. Once reconciliation settles, three run. Kubernetes controllers keep reconciling; Terraform normally acts on explicit plan/apply runs. An imperative script could also be idempotent if it checked existing state.'))
edit(n,6,'Numeric equivalence excludes coercion effects and exotic arrays.','https://tc39.es/ecma262/',lambda q:fields(q,prompt=q['prompt']+' Assume xs is an ordinary dense array of finite Number values, with standard array methods and no concurrent mutation.'))
edit(n,7,'Remove unmeasured timing claim.','https://docs.djangoproject.com/en/5.2/ref/models/querysets/#select-related',lambda q:opt(q,1,explanation='The query log identifies repeated database access. Measure both Python and database cost rather than assuming an unconditional microsecond loop time.'))
edit(n,8,'Generic Kubernetes ordering annotations do not order arbitrary resources.',tf,lambda q:(opt(q,3,text='Escape hatches such as SQL hints, React memoisation or explicit Terraform dependencies require understanding engine behavior'),fields(q,workedExample=q['workedExample'].replace('Kubernetes ordering annotations','explicit Terraform dependency declarations'))))
edit(n,10,'Purity alone does not make every strictness-changing rewrite sound.','https://www.haskell.org/onlinereport/haskell2010/haskellch3.html',lambda q:(opt(q,1,explanation='Correct. Purity simplifies reasoning, while mutation requires alias/effect analysis. Even pure-language fusion rules must preserve evaluation and termination semantics; arbitrary rewrites are not always safe.'),fields(q,workedExample=q['workedExample'].replace('With pure functions, order is unobservable.','For this supported fusion rule, the compiler preserves Haskell evaluation semantics.'))))
done(n)
