exec(open('/tmp/lang-helpers.py').read());n='para-multi-paradigm';j='https://openjdk.org/jeps/441';r='https://doc.rust-lang.org/book/ch13-04-performance.html';p='https://docs.python.org/3/reference/executionmodel.html';box='https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.7'
for a,b,s in [
('touch nothing else.','without editing existing shape operations, assuming construction/registration is handled separately.',r),
('Languages with **sealed** types (Java 17, Kotlin, Scala, Rust enums) add a bonus: the compiler knows the full list of cases, so it warns you when a `match` or `switch` misses one. Python\'s `match` has no such check; a missing case silently falls through and returns `None`.','Closed variant sets support exhaustiveness checks where the language requires them, such as Rust match and Java 21 pattern-switch (Java sealed types themselves arrived in 17). Requirements vary by construct/language. Python’s interpreter does not check match exhaustiveness: no matching case continues after the statement, returning None only if the function then falls off its end.',j),
('The shell is so simple that a few integration tests cover it.','The shell still needs integration tests for failures, retries, transactions and other relevant boundary behavior.',p),
('which is O(n²) in the total length.','which is quadratic for n single-element lists; more generally cost depends on both the number and lengths of the lists.',p),
('A `frozen=True` dataclass stops you reassigning fields','A `frozen=True` dataclass blocks ordinary field assignment',p),
('if you need real immutability.','and ensure their nested contents are immutable too.',p),
('each stage is an object, and boxed types like `Stream<Integer>` allocate.','pipeline objects and boxing can add overhead, though JIT optimization can remove some allocations and boxed values may be cached or already exist.',box),
('iOS means Swift.','Swift is a common native iOS choice, though Objective-C and cross-platform approaches also exist.',r),
('Data science means Python,','Python is widely used in data science,',r),
('Rust iterator chains are zero-cost; Java streams have overhead.','Rust iterator chains can optimize to loop-like code; Java stream overhead depends on boxing, workload and JIT optimization.',r)]:
 if a in (root/(n+'.md')).read_text():lesson(n,a,b,'Qualify language/version, performance and control-flow guarantees.',s)
edit(n,1,'Expression-problem example excludes registration/integration costs.',r,lambda q:fields(q,prompt=q['prompt']+' Assume provider construction, configuration and registration are handled separately; consider only existing implementations and interface-based callers.'))
edit(n,4,'Java17 sealed alone not standard pattern switch.',j,lambda q:fields(q,workedExample=q['workedExample'].replace('Java 17 sealed interfaces','Java 21 pattern-switch over sealed interfaces').replace('This is why compilers are so often written in OCaml, Haskell, Rust or Scala.','This makes languages with algebraic data types and matching useful for compiler passes.')))
edit(n,7,'Records shallowly immutable not deep.','https://openjdk.org/jeps/395',lambda q:opt(q,1,explanation='Correct. Records became final in Java 16 and have final component fields, but referenced objects can still be mutable. They are shallowly immutable data carriers.'))
edit(n,8,'Avoid unsupported labor-market claim.',r,lambda q:fields(q,workedExample=q['workedExample'].replace('; hiring is also easier for Python','; assess hiring against the actual market rather than assuming a universal advantage')))
edit(n,9,'Tuple may retain mutable contents.',p,lambda q:fields(q,workedExample=q['workedExample'].replace('store a `tuple` or `frozenset`','use immutable containers with appropriately immutable nested values')))
edit(n,10,'Expression problem has advanced solutions; basic visitor tradeoff not impossibility theorem.',j,lambda q:opt(q,0,explanation='The ordinary visitor structure shown favors new operations. Other extensibility designs exist, but this pattern does not automatically make adding both axes cheap.'))
edit(n,11,'Boxing may reuse cached/preexisting objects; runtime matchfallthroughnotautomaticreturn.',box,lambda q:(opt(q,3,text='IntStream avoids boxed Integer representation and can reduce overhead for primitive pipelines',explanation='Correct. Stream<Integer> holds references to Integer objects, which may already exist or be cached; boxing does not necessarily allocate per element, and performance must be measured.'),opt(q,4,explanation='The interpreter does not check exhaustiveness. With no matching case execution continues after match; a function returns None only if it reaches its end without returning.'),fields(q,workedExample=q['workedExample'].replace('Java boxing: `Stream<Integer>` allocates objects; `IntStream` avoids it.','Java boxing: IntStream avoids the boxed representation; cached objects and JIT optimizations can avoid allocation in some boxed pipelines.'))))
done(n)
