exec(open('/tmp/lang-helpers.py').read());n='para-functional-basics';h='https://www.haskell.org/onlinereport/haskell2010/haskellch3.html';p='https://docs.python.org/3/library/functools.html';j='https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html'
for a,b,src in [
('Today FP\'s core ideas are in every mainstream language:','FP ideas also appear in many mainstream languages:',p),
('Pure functions have **referential transparency**:','In a value-oriented model with immutable inputs/results and no observable identity or timing effects, pure calls support **referential transparency**:',h),
('results can be **memoised** safely (Python\'s `functools.cache`).','results can be **memoised** when keys represent all inputs and cached values are safe to share; Python `functools.cache` requires hashable arguments and returns the same cached result object.',p),
('| Haskell | Everything | None: default |','| Haskell | Ordinary pure values | Mutable references/arrays exist inside controlled IO/ST effects |',h),
('Java streams are similar: reusing a consumed stream throws `IllegalStateException`.','Java streams also must not be reused; implementations may throw `IllegalStateException` when reuse is detected.',j),
('For associative operations like `+` they agree.','For a finite list, an associative operation with a two-sided identity seed gives the same mathematical result. Integer addition with zero is an example; floating-point addition is not associative.',h),
('Pure functional languages have no mutable loop counters,','Pure functional code avoids mutable loop counters,',h),
('Functional language compilers perform **tail-call optimisation (TCO)**:','Many functional-language implementations support **tail-call optimisation (TCO)**:',h),
('so the recursion runs in constant stack space like a loop.','so the tail-call stack can stay bounded. This does not guarantee constant total memory: lazy accumulators, retained data or allocation can still grow.',h),
('they express the intent and avoid the stack question entirely.','they express intent, but their space behavior still depends on language, implementation and strictness.',h)]:lesson(n,a,b,'Qualify functional semantic guarantees and runtime behavior.',src)
edit(n,1,'Purity examples require ordinary value semantics and supported argument domain.',p,lambda q:fields(q,prompt=q['prompt']+' Assume ordinary built-in numeric values, nonempty lists, plain dictionaries, stable inputs, and no overloaded operations; judge value results and external mutations, ignoring allocation identity.'))
edit(n,2,'Semantic substitution does not guarantee a measured speed improvement.',h,lambda q:opt(q,2,explanation='Referential transparency establishes semantic equivalence, not a universal performance ordering; compiler and runtime details determine measured speed.'))
edit(n,3,'Java stream reuse detection is not universal.',j,lambda q:fields(q,workedExample=q['workedExample'].replace('a second terminal operation throws `IllegalStateException`','detected reuse may throw `IllegalStateException`')))
edit(n,4,'Right fold with same callback is not reverse iteration.',h,lambda q:opt(q,1,explanation='204 comes from processing the digits in reverse order with the left-fold accumulator. A right fold with the same binary function changes argument positions/grouping and is not simply reverse iteration.'))
edit(n,7,'Memoization and concurrent purity require stable immutable domain.',p,lambda q:(fields(q,prompt=q['prompt']+' Assume immutable inputs and outputs, value semantics, and a suitable cache key.'),opt(q,0,explanation='Correct under these assumptions. A Python cache still needs hashable keys, and mutable returned objects would require care because cache hits share them.'),opt(q,1,text='Tests can supply explicit input values without mocking hidden databases or clocks',explanation='Correct. Test data still needs construction; purity removes hidden effectful dependencies rather than all setup.')))
edit(n,10,'Bounded domain avoids Python sum 3.12 rounding differences.',p,lambda q:fields(q,prompt=q['prompt']+' Assume ordinary integer elements and CPython with its default recursion limit.'))
edit(n,11,'Datetime plus integer days invalid; date consistency required.','https://docs.python.org/3/library/datetime.html',lambda q:fields(q,workedExample='Make the date arithmetic explicit: `now > invoice.issued + timedelta(days=terms.days)`, importing timedelta from datetime. Use compatible date/datetime values and an agreed timezone and boundary policy. The shell fetches terms and reads the clock; the core receives those values. Test a fully specified issued date, term length and current date, including the exact due-date boundary.'))
edit(n,12,'Caching impure functions can have explicit freshness contract; unbounded capacity not inevitable infinitegrowth.',p,lambda q:(opt(q,0,explanation='Returning a value is insufficient. Caching changing external data needs an explicit freshness/invalidation contract; this cache has none.'),opt(q,2,explanation='A cache lookup can avoid database work, but its timing depends on the environment. Correctness is the issue here.'),opt(q,3,explanation='Correct. The key omits the changing rate, so a result can remain stale until the cache is cleared or discarded. An unbounded cache can also grow with the number of distinct keys.')))
done(n)
