exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-system-design-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/system-design/08-architecture/'
src=['https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables_HowItWorks.html','https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html','https://docs.aws.amazon.com/wellarchitected/latest/reducing-scope-of-impact-with-cell-based-architecture/what-is-a-cell-based-architecture.html','https://aws.amazon.com/builders-library/workload-isolation-using-shuffle-sharding/']
patch(b+'arch-multi-region.md',[
('A single cloud region is already highly available: it has several availability zones (separate data centres with independent power and networking), and a well-built multi-AZ system survives a data centre failure.', 'A cloud region may offer several availability zones, each with separate infrastructure and possibly multiple data centres. A correctly configured multi-AZ workload can tolerate specified zone failures, but a region label alone does not guarantee application availability.'),
('light in fibre covers about 200 km per millisecond. London to Sydney is about 17,000 km, so roughly 85 ms one way at best and 250–300 ms round-trip in practice.', 'long paths impose propagation delay. A hypothetical 17,000 km fibre path at 200 km/ms takes 85 ms one way before routing and equipment overhead; actual routes and measured RTTs differ.'),
('Every extra region multiplies infrastructure cost', 'Extra regions add infrastructure and operating costs'),
('Within a region, synchronous replication across AZs costs about 1–2 ms. Across regions it costs tens to hundreds of milliseconds per write.', 'Synchronous acknowledgment latency depends on required replicas, distance, storage and protocol. Benchmark the chosen deployment.\n\n> [!note] Evidence gap\n> Generic cross-AZ/region latency and recovery-time estimates are omitted because no measured deployment establishes them. Numeric quiz examples state hypothetical inputs.'),
('no data loss on regional failure (RPO = 0), but every write pays the inter-region round trip,', 'can protect acknowledged commits from loss of one region when they are durably retained in a surviving region and failover selects the correct replica; this can meet a zero-loss objective for that failure model. Each required remote acknowledgment adds latency,'),
('a regional failure can lose the last few seconds of writes (RPO > 0), and replicas lag.', 'a failure can lose acknowledged writes not yet durably replicated. Observed lag does not by itself guarantee a worst-case recovery point.'),
('| Strategy | Standby | RTO |\n|---|---|---|\n| Backup & restore | backups only | hours |\n| Pilot light | data + minimal infra | 10s of mins |\n| Warm standby | scaled-down copy | minutes |\n| Hot standby | full copy, idle | near zero |', '| Strategy | Standby | Recovery work |\n|---|---|---|\n| Backup & restore | Backups | Restore data and provision services |\n| Pilot light | Data and core infrastructure | Start missing services and scale |\n| Warm standby | Reduced working deployment | Redirect traffic and add capacity |\n| Hot standby | Provisioned working deployment | Promote/fence writers and redirect traffic |'),
('Pros: simple data model (one writer at a time, no conflicts).', 'Pros: simpler write ownership, if failover fences the old primary so only one writer remains authoritative.'),
('If you haven\'t failed over in the last few months, assume it doesn\'t work. Run regular game days: actually shift production traffic to the standby region and back.', 'Exercise failover and restore procedures on a schedule appropriate to the system, including controlled production traffic shifts where justified. Verify fencing, recovery point, routing, capacity and rollback.'),
('A bad migration, a buggy job deleting rows or ransomware is replicated to the standby within seconds. You still need point-in-time backups, ideally in a separate account, and their RPO is the time since the last good backup.', 'Logical deletions and corrupting writes can propagate to replicas. Keep tested backups and retained logs, with appropriately isolated access. The latest recoverable good state depends on available backups, logs and the incident; an RPO is a target, not simply the age of one backup.'),
('low latency everywhere, no idle capacity, and "failover" is just routing traffic away from a region that\'s already running production load, so it\'s well exercised.', 'local serving can reduce latency and each region exercises a production path. Failure routing, data promotion and spare-capacity behavior still need separate tests; active-active does not exercise every failover scenario.'),
('each must run at most about 50% utilisation in normal operation, or a failover will overload the survivor.', 'the simple equal-capacity, equally loaded linear model requires each to use at most 50% of available capacity before loss of one. Real designs need margin and must account for state, retries, caches and resource-specific bottlenecks.'),
('Each record has exactly one writer at a time, so there are no conflicts, only replication lag.', 'One authoritative writer avoids concurrent cross-region ownership if enforced through failover fencing. Local transactions still need concurrency control, and multi-record operations can require coordination.'),
('A basket can be active-active with a CRDT set: adds in both regions merge, and the worst case is an item reappearing.', 'A basket can use a CRDT with chosen add/remove semantics, but quantities, checkout, deletion and inventory constraints still need explicit product rules. Convergence alone does not bound every bad outcome.'),
('Regulations (the EU GDPR\'s rules on international transfers, sector rules for health and finance, and national data-localisation laws) constrain where personal data may be stored and processed.\n\nFor an example tenant whose contract requires EU-only storage and processing, architectural consequences include the following. GDPR itself is not a blanket ban on international transfers: transfers may be permitted under applicable adequacy decisions or safeguards.', 'Consider a hypothetical tenant whose contract explicitly requires EU-only storage and processing. The following is an architecture exercise for that stated requirement.\n\n> [!note] Content gap\n> Jurisdiction-specific legal requirements are not assessed here: no applicable contract, sector or legal analysis was supplied. This lesson does not assert that every EU customer has an EU-only obligation.'),
('In a single shared system those take everyone down.', 'Shared dependencies can let such failures affect many customers.'),
('a failure in one cell affects only its customers. With 20 cells, one bad cell is 5% of customers.', 'a cell-local failure can be contained to that cell if shared dependencies remain healthy. With 20 equally populated cells, one cell holds 5% of customers.'),
('is the one shared component, so it must be kept minimal and robust.', 'is a shared dependency to keep minimal and robust; audit other shared services and control-plane dependencies too.'),
('(RPO of seconds, RTO of minutes).', '(define objectives and verify recovery point and duration with drills).'),
('- Active-active serves users locally and exercises failover constantly; avoid conflicts by giving each record a home region.', '- Active-active exercises normal serving in each region; failover still needs testing. Home-region ownership can avoid cross-region write conflicts if fencing is enforced.')], 'Remove unsupported latency/recovery guarantees and legal assertions; scope region durability, ownership fencing and cell isolation.',src)
def region(q):
 q[0]['options'][0]['explanation']='These are recovery objectives, not proof that the deployed system can meet them. Validate recovery point and duration in the relevant failure scenarios.'
 q[0]['workedExample']='1. A five-minute RPO is the target maximum loss window; test that backups/logs or surviving replicas can provide it. A five-minute backup schedule alone is not proof.\n2. A one-hour RTO is the target restoration time; include detection, decisions, provisioning, restore, validation and routing.\n3. Stricter objectives may require durable synchronous replication and ready capacity, but do not uniquely require active-active.'
 q[1]['prompt']+=' Treat 280 ms as the measured existing RTT and assume the proposed local path measures 20 ms and does not call London synchronously.'
 q[1]['workedExample']='1. Use the hypothetical measured path values in the question, not a generic geographic latency claim.\n2. Four serial London trips cost 4 × 280 = 1,120 ms of network wait.\n3. Four local trips cost 4 × 20 = 80 ms.\n4. The modeled saving is 1,040 ms. Remote database calls could erase it.\n5. Also consider fewer serial requests and caching.'
 q[2]['prompt']+=' Assume equal region capacity, CPU demand proportional to admitted load, no immediate extra capacity and no load shedding.'
 q[3]['workedExample']=q[3]['workedExample'].replace('Use `UpdateItem` on just the changed attribute (`SET email = :e`) instead of overwriting the whole item. This narrows the window, but concurrent updates to the *same* attribute still conflict.', 'UpdateItem does not give attribute-wise merging across MREC Regions: conflicts are resolved per item, so different attributes can still lose updates.').replace('Use a strongly consistent multi-region mode if your store offers one, accepting higher write latency.', 'Choose an appropriate strongly consistent design if needed. DynamoDB MRSC currently cannot span its separate US and EU Region sets, and cannot be enabled in place on this existing MREC table.')
 q[5]['workedExample']='1. Browsing can use replicated views if the product accepts delayed availability.\n2. Reservations need an atomic condition or transaction enforcing one successful reservation per seat; a fresh read followed by an unconditional write is insufficient.\n3. Route to a fenced authoritative owner, or use an appropriate strongly consistent store with conditional updates.\n4. Measure latency and decide the product budget; no fixed global reservation RTT is asserted.\n5. Preallocated exclusive seat ownership is another possible design, with coordinated transfer.'
 q[6]['options'][1]['explanation']='Cell isolation and staged deployment reduce potential impact, provided dependencies are isolated and monitoring catches the problem before rollout expands.'
 q[6]['workedExample']=q[6]['workedExample'].replace('1 cell = 1/30 of customers, caught by alarms, rolled back.', '1 of 30 equally populated cells contains about 1/30 of customers; detection and safe rollback are still required.').replace("so it isn't itself a shared failure point.", 'to reduce, not eliminate, shared failure risk.')
 q[7]['prompt']+=' Treat the 75 ms RTT as a hypothetical measured input, assume a durable acknowledgment in Virginia, and ignore additional remote processing costs.'
 q[7]['options'][2]['explanation']='The simplified added wait is 4 × 75 = 300 ms. Surviving durable copies protect acknowledged commits under this one-region-loss model; failover must fence the old writer. Async fallback changes the loss guarantee.'
 q[7]['options'][3]['explanation']='This contradicts the supplied 75 ms RTT. There is no universal 1–2 ms cross-AZ latency applicable to this deployment.'
 q[7]['workedExample']=q[7]['workedExample'].replace('London → Ireland, about 10 ms', 'a measured lower-latency pair').replace("That's PACELC.", 'This illustrates a partition-time consistency/availability trade-off; outside partitions, remote coordination also adds latency.')
 q[8]['prompt']+=' Use an ideal equal-load, linear-capacity model without autoscaling; treat the answer as a theoretical ceiling before operating margin.'
 q[9]['prompt']+=' Assume each replica has a stable unique identity, durable counter state and atomic local increments; application retries are deduplicated separately.'
 q[9]['options'][2]['text']='A PN-Counter can represent increments and decrements using two G-Counters, with value P − N; one-like-per-user needs separate identity semantics.'
 q[9]['options'][2]['explanation']='This is one counter design, not the only way to implement likes/unlikes. Retried user actions and duplicate likes need additional modeling.'
 q[9]['options'][3]['text']='Totals may differ without a fixed small bound during a partition, then converge once updates are eventually exchanged.'
 q[9]['options'][4]['text']='An ordinary unconstrained G-Counter alone enforces a global limit of 1,000 accepted increments.'
 q[9]['options'][4]['explanation']='Ordinary convergence does not enforce a cap. Escrow/bounded-counter designs can preallocate rights for local operations, with safe coordination to transfer rights.'
 q[9]['workedExample']=q[9]['workedExample'].replace('Invariants (caps, uniqueness) need a single writer or consensus.', 'Invariant enforcement needs a suitable protocol: atomic ownership/consensus, or bounded local rights where the invariant allows escrow.')
 q[10]['prompt']+=' Assume independent uniform assignments and enough surviving worker capacity for retries.'
 q[10]['workedExample']=q[10]['workedExample'].replace('1/25 of customers entirely (4%).', 'one group entirely, about 4% of customers if group populations are equal.')
 q[11]['prompt']+=' Assume the deletion has already reached the standby before failover is considered.'
 q[11]['options'][2]['text']='The recoverable state depends on retained good backups and logs, corruption timing and reconciliation; the RPO is the target against which recovery is assessed.'
 q[11]['options'][2]['explanation']='Neither observed replication lag nor backup cadence alone guarantees a recovery point for logical corruption.'
 q[11]['options'][4]['text']='Separate-account backups with independently restricted access can reduce the chance that one mistake or credential deletes both production data and backups.'
 q[11]['options'][4]['explanation']='Isolation helps only if permissions and recovery controls enforce it; a separate account label alone does not prevent cross-account deletion.'
 q[11]['workedExample']=q[11]['workedExample'].replace('RPO for corruption = how fine-grained your backups/log archives are.', 'Assess the actual recoverable good state and reconciliation loss against the recovery objective.')
questions(b+'arch-multi-region.questions.json',region,'Correct DynamoDB item conflict and MRSC region scope, CRDT escrow exceptions, recovery objectives and capacity assumptions.',src)
report['reviewed_files']=list(dict.fromkeys(report.get('reviewed_files',[])+[b+'arch-multi-region.md',b+'arch-multi-region.questions.json']))
report['status']='Full semantic read of all nine architecture lessons and 108 questions; root corrections complete, independent verification and selected execution pending.'
p_report.write_text(json.dumps(report,indent=2)+'\n')
