exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-se-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/software-engineering/05-code-architecture/'
src=['https://peps.python.org/pep-0387/','https://docs.python.org/3/library/warnings.html','https://semver.org/','https://github.com/github/scientist','https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions','https://martinfowler.com/bliki/MonolithFirst.html','https://martinfowler.com/bliki/BranchByAbstraction.html','https://www.hyrumslaw.com/']
patch(b+'sea-api-design.md',[
('Keyword-only arguments also let you **reorder or add** options later without breaking callers.', 'Keyword-only arguments allow reordering without changing ordinary keyword calls. Adding optional arguments can preserve existing behavior; required additions, subclasses, wrappers and introspection need compatibility checks.'),
('a common incident cause.', 'so callers should choose explicit connect/read timeouts and any required overall deadline.'),
('lets callers catch everything from your library in one clause, without catching unrelated bugs.', 'lets callers catch the expected library errors placed under that hierarchy. Programmer errors and unrelated exceptions may still propagate.'),
('(retry a timeout, show a message for a decline).', '(apply a safe idempotent retry policy for an uncertain timeout, show an appropriate message for a decline).'),
('Wrap it: `raise GatewayTimeout() from exc`.', 'Translate it into a semantically appropriate library error and preserve chaining. Do not label every OperationalError a timeout; failures such as unavailable storage or invalid connection settings differ.'),
('So much code came to rely on it that Python 3.7 made it a language guarantee.', 'Python 3.7 subsequently made insertion order a language guarantee; this fact alone does not establish a single historical cause for the decision.'),
('so nobody can depend on it.', 'to discourage reliance on one stable order; this does not logically prevent callers from depending on observed behavior.'),
('That\'s why so many popular libraries stay at 0.x for years; it lets them break things without a major bump, at the cost of giving users no compatibility signal.', 'SemVer itself does not promise public-API stability during 0.x. Projects can document stricter compatibility policies; no particular maintainer motive or prevalence is inferred here.'),
('    if "secs" in kw:\n        warnings.warn(', '    if "secs" in kw:\n        if timeout is not None:\n            raise TypeError("conflicting times")\n        warnings.warn('),
('        timeout = kw.pop("secs")\n    ...', '        timeout = kw.pop("secs")\n    if kw:\n        raise TypeError("unknown option")\n    return timeout  # boundary demo, no I/O'),
('How long to wait? CPython\'s own policy, PEP 387, requires a warning to appear in at least two minor releases before removal and prefers about five years.', 'How long to wait? CPython\'s PEP 387 normally requires a deprecation period of at least two years across minor releases and prefers five years, with specified exceptions and additional replacement-support guidance.'),
('Ship a `py.typed` marker file (PEP 561) so type checkers use your annotations.', 'For a distributed package containing inline types, ship a py.typed marker as described by PEP 561. Stub-only packages and local source checking follow different discovery rules.')], 'Qualify compatibility/typing claims, classify errors accurately and reject ambiguous deprecated-argument input.',src)
def api(q):
 q[2]['workedExample']=q[2]['workedExample'].replace('you can add or reorder keyword options later without breaking anyone.', 'reordering keyword parameters preserves ordinary calls; adding required options or changing behavior can still break clients.')
 q[3]['workedExample']=q[3]['workedExample'].replace('you can reword messages freely.', 'callers have a stable alternative to parsing messages, though existing text-dependent clients still need migration.')
 q[4]['options'][0]['explanation']='Exposing driver-specific errors couples callers to that driver. Translate expected storage failures into your public hierarchy, with distinctions that accurately describe the cause and retryability.'
 q[4]['workedExample']+='\nOperationalError covers multiple failures: this simplified wrapper must not imply that every such error is transient or safe to retry.'
 q[8]['prompt']+=' Assume parameter names exposed through introspection are not part of the documented public contract.'
 q[8]['options'][3]['explanation']='Introspection changes. Under the stated contract ordinary calls remain compatible; a library that explicitly promises signature metadata would need to consider that promise too.'
 q[9]['options'][2]['explanation']='Keyword-only options improve call clarity. Optional additions can preserve behavior, but no initial default or signature style guarantees that future changes will be compatible.'
 q[9]['options'][3]['explanation']='A stable error hierarchy can decouple callers from transport types, provided the replacement preserves promised error semantics and behavior.'
 q[10]['options'][2]['text']='Allowed by SemVer\'s initial-development rule, unless the project promises stricter compatibility; users should lock or constrain versions and inspect changes.'
 q[10]['workedExample']=q[10]['workedExample'].replace('pin to `~=0.27.0`-style ranges (or lock exact versions)', 'use an exact lock for artifact selection; ~=0.27.0 permits later 0.27 patch releases and is a range rather than an exact pin')
questions(b+'sea-api-design.questions.json',api,'Distinguish API call compatibility from introspection guarantees and ranges from exact pins.',src)
patch(b+'sea-adr-evolution.md',[
('Orders publishes OrderPlaced to the\nin-process event bus. Billing\nsubscribes. No direct imports from\norders to billing.', 'Orders commits an outbox event with\nits state. A relay sends to a durable\nqueue; a separate Billing worker\nsubscribes. No direct Orders call\nto Billing is needed.'),
('+ Orders no longer depends on billing.\n+ Teams deploy independently.\n- Invoices appear after a short delay.', '+ Checkout need not wait for Billing.\n+ Separate deploys with stable contracts.\n- Invoice delay depends on queue health.'),
('The **consequences** section is the most valuable and most often skipped.', 'The **consequences** section is especially useful for explaining accepted trade-offs.'),
('Discussion happens on the PR; merging it means accepted.', 'Discussion can happen on the PR; define whether merging marks acceptance in your team\'s workflow.'),
('makes switching cheaper later.', 'can reduce call-site changes, but migration cost also depends on data and semantic compatibility.'),
('    for f in root.rglob("*.py"):', '    files = list(root.rglob("*.py"))\n    assert files, "no domain files found"\n    for f in files:'),
('            bad = mod.startswith(banned)', '            bad = mod.split(".")[0] in banned'),
('This checks only direct imports.', 'This small example checks direct absolute import statements, requires at least one source file, and matches the top-level package exactly. It does not resolve relative or dynamic imports and can include imports guarded by TYPE_CHECKING.'),
('Big-bang rewrites have a poor track record. Joel Spolsky\'s essay *Things You Should Never Do* uses Netscape\'s ground-up rewrite, which took about three years while competitors moved ahead, as the cautionary tale.', 'A long all-at-once rewrite can delay feedback and lose undocumented behavior. Joel Spolsky\'s essay Things You Should Never Do argues against this approach using Netscape as a cautionary example.\n\n> [!note] Evidence gap\n> A universal rewrite failure rate and a precise single-cause Netscape chronology are omitted; an opinion essay is not sufficient evidence for those claims.'),
('The system works at every step.', 'The aim is to keep the system serving throughout, but each cutover still needs compatible data, operational checks and a recovery plan.'),
('Switch only when the differences are understood.', 'Switch only when relevant differences are understood. Shadow execution must isolate side effects and cap additional load; Scientist evaluates both behaviors but does not inherently run them concurrently.'),
('Fowler observed that most successful microservice systems started as monoliths that were split later, while many built as microservices from scratch got into trouble,', 'In his 2015 essay, Fowler reported that almost all successful microservice stories he had heard began with monoliths, while many from-scratch stories involved trouble. This is practitioner experience, not a representative success-rate study;'),
('If two teams share one module, its boundary will blur.', 'Shared ownership can affect boundaries, but Conway\'s observation does not deterministically predict that any shared module will blur.'),
('Each feature flag left in place doubles some code paths.', 'Independent binary flags can create up to 2^n configurations; dependencies and mutually exclusive flags can reduce reachable combinations.'),
('keep it short, in the repo and immutable once accepted.', 'keep it short and preserve accepted decision history, while updating status and adding explicit corrections or superseding records.')], 'Replace in-process-bus deployment claim, fix AST false positives/vacuous success and qualify migration/causal-history guarantees.',src)
def adr(q):
 q[2]['options'][2]['explanation']='The aim is incremental replacement while serving users. Data migration and side effects can make particular steps hard to reverse; routing alone does not prove safety.'
 q[3]['options'][3]['explanation']='Small changes avoid a single long-diverged merge, but compatibility tests, green builds and data-safe rollback still require explicit work.'
 q[4]['options'][3]['explanation']='This is an automated policy check if the team chooses it. Major-version distance is not a universal measure of support or security; supported versions and vulnerabilities may be more relevant.'
 q[5]['options'][3]['explanation']='The adapter can reduce call-site changes. Semantic, configuration and operational differences can still make switching costly; it is relatively reversible under suitable assumptions.'
 q[7]['workedExample']=q[7]['workedExample'].replace('most successful microservice stories started as monoliths; many systems built as microservices from scratch ran into trouble.', 'his 2015 essay reports a pattern in stories he had heard, not a statistically representative comparison.').replace('two per person to operate.', 'an average of two services per engineer if divided equally; actual ownership and operational load need not be even.')
 q[8]['options'][0]['explanation']='An architecture diagram alone does not establish ownership or collaboration. Existing technical-team boundaries can continue to require coordination for cross-cutting product changes.'
 q[8]['options'][1]['explanation']='The observation is not defined by a 1,000-person threshold, nor is it a deterministic law about every organization or pair of developers.'
 q[8]['options'][3]['text']='Horizontal ownership can encourage layer-oriented boundaries and cross-team handoffs; cross-functional teams may better support the desired product ownership.'
 q[9]['options'][0]['explanation']='This provides comparison evidence if shadow work has isolated side effects and bounded resource use. Running both can still add production load and differences can contain sensitive data.'
 q[9]['options'][1]['explanation']='Gradual exposure can limit impact. A flag may stop future use, but it cannot undo already-issued prices or incompatible state; test rollback semantics.'
 q[10]['prompt']=q[10]['prompt'].replace('strongest evidence-based concern', 'strongest engineering concern')
 q[10]['workedExample']=q[10]['workedExample'].replace("Spolsky's essay: Netscape spent around three years rewriting its browser, shipping no new major release in that time, while the market moved.", 'Spolsky uses Netscape as an argument about delayed delivery and lost knowledge; this is not proof of a universal rewrite outcome or a verified single-cause chronology.').replace('A rewrite has no value until it\'s complete,', 'A plan that withholds all delivery until completion delays realized value,')
questions(b+'sea-adr-evolution.questions.json',adr,'Qualify incremental rollback, shadow side effects, Conway predictions and historical anecdote strength.',src)
report['reviewed_files'] += [b+n+s for n in ['sea-api-design','sea-adr-evolution'] for s in ['.md','.questions.json']]
report['status']='All six lessons and 66 questions fully read and corrected; selected execution and independent verification pending.'
p_report.write_text(json.dumps(report,indent=2)+'\n')
