exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
report={'date':'2026-10-04','status':'In progress: first two lesson/question pairs fully read; remaining seven pairs pending. Independent verifier signoff pending.','reviewed_files':[],'findings':findings,'omissions':[]}
b='content/system-design/08-architecture/'
src=['https://martinfowler.com/articles/microservices.html','https://martinfowler.com/bliki/BoundedContext.html','https://microservices.io/patterns/data/transactional-outbox.html','https://microservices.io/patterns/data/saga.html','https://www.twilio.com/en-us/blog/developers/best-practices/goodbye-microservices']
patch(b+'arch-monolith-vs-microservices.md',[
('one codebase, one build, one deployable process (often run as many identical copies behind a load balancer). Modules call each other with ordinary function calls and share one database.', 'an application deployed as one unit (often replicated behind a load balancer). Modules commonly call each other in-process and may share a database; a particular repository layout or exactly one database is not required.'),
('A stack trace shows the whole request.', 'A stack trace can show an in-process call chain; asynchronous work and external dependencies still need tracing or correlated logs.'),
('One bad deploy takes everything down, so releases get batched and become scary.', 'A bad release can affect the whole application; staged deployment and isolation can limit the impact.'),
('| Call cost | ~ns, reliable | ~ms, can fail |', '| Call cost | No network transport; can fail | Adds transport and partial failures |'),
('| Transactions | ACID | Sagas, outbox |', '| Transactions | Local ACID can span modules | Local ACID; coordination across owners |'),
('unless you add retries, timeouts and fallbacks.', 'under that simplified model. Carefully designed fallbacks can reduce required dependencies; retries can also amplify overload, and timeouts only bound waiting rather than guarantee success.'),
('your architecture will drift towards your org chart whether you like it or not.', 'communication patterns constrain and influence architecture; this is an organizational observation, not a deterministic prediction from team count.'),
('Split along **business capabilities** (orders, billing, inventory), which Domain-Driven Design calls *bounded contexts*, not along technical layers.', 'Business capabilities (orders, billing, inventory) can guide boundaries. A DDD bounded context is the scope in which a domain model and its language are consistent; it is not simply a synonym for a capability or necessarily one service. Avoid mechanically splitting every technical layer into a service.'),
('A service per database table fails all three tests, because real features span several tables.', 'A service per table often fragments a capability and increases coordination. Evaluate the actual change and data-access boundaries rather than using table count as a rule.'),
('If two services write the same table, they are one service with a network call in the middle.', 'Two services writing the same table share a data contract and can become tightly coupled; sharing does not literally make their processes one service.'),
('1. Put a routing layer (gateway or proxy) in front of the monolith.\n2. Build the new service for one capability and route that path to it.\n3. Migrate its data, then delete the old code.', '1. Introduce a routing or interface boundary around the capability.\n2. Build the replacement and establish data ownership, migration, validation and write coordination before directing production writes to it.\n3. Shift traffic gradually with a tested rollback/data-compatibility plan; retire old code only after remaining readers and writers have migrated.')], 'Remove unsupported call-latency table and deterministic organizational claims; clarify bounded contexts, transactions and migration write safety.',src)
def mono(q):
 q[0]['options'][1]['explanation']='Modules can use in-process calls without remote transport failure modes. Local calls can still throw, partially mutate state or be interrupted by a crash.'
 q[1]['options'][0]['text']='Communication boundaries are likely to influence component boundaries; roughly one major area per team is a plausible outcome, not a guaranteed count'
 q[1]['workedExample']=q[1]['workedExample'].replace('so you get about four components.', 'so component boundaries may resemble team boundaries; the law does not calculate an exact number.').replace('will be thin and hard to change.', 'can become harder to negotiate and change.')
 q[2]['options'][1]['explanation']='Correct under independent success probabilities. 0.999^6 is about99.4015%; translating request failures into downtime hours additionally assumes the same fraction applies over time.'
 q[2]['workedExample']=q[2]['workedExample'].replace('downtime ≈ 0.6% × 8,760 h ≈ 52.6 h/year.', 'if interpreted as independent time availability over a365-day year, equivalent downtime is (1-0.999^6)×8,760≈52.4hours/year. A request failure fraction alone does not specify outage duration.')
 q[3]['options'][1]['explanation']='Correct as a warning sign: direct shared-table access couples data contracts. Backward-compatible changes may not require every team to release together.'
 q[3]['options'][2]['explanation']='Asynchronous events alone are not evidence of a distributed monolith. They decouple immediate execution, but consumers still depend on schema semantics, delivery and capacity.'
 q[3]['workedExample']=q[3]['workedExample'].replace('Async events: decoupled in time and data. Healthy.', 'Async events: can decouple execution time, but still require compatible schemas and reliable delivery.')
 q[4]['options'][2]['explanation']='Correct. Explicit boundaries can reduce future extraction work; network, data and operational changes can still make extraction expensive.'
 q[5]['workedExample']=q[5]['workedExample'].replace('migrate data (often dual-write or change data capture, then verify).', 'migrate and verify data using a consistent snapshot plus change capture or another coordinated protocol. Independent dual writes can diverge; establish one authoritative write path and reconcile catch-up.').replace('keeping rollback available.', 'with rollback tested against the data written by the new service.').replace('delete the monolith\'s billing code and tables.', 'retire old code and tables only once rollback, retention and remaining-consumer requirements permit it.')
 q[7]['options'][0]['explanation']='Separate containers do not define a modular monolith, and they do not automatically establish microservice independence. The defining distinction is enforced module boundaries within one deployment unit.'
 q[8]['options'][2]['text']='The organization has a concrete requirement to isolate card-data handling behind controlled process and network boundaries'
 q[8]['options'][2]['explanation']='Correct. A specific isolation requirement can justify extraction; merely naming a service or using a separate process does not establish compliance or remove connected systems from scope.'
 q[8]['workedExample']=q[8]['workedExample'].replace('PCI: a smaller audited boundary. Yes.', 'Required card-data isolation: extraction may help implement the approved security boundary. Yes; compliance scope requires separate assessment.')
 q[9]['prompt']+=' The page may show an out-of-date loyalty tier and does not use it to authorize payment or enforce a credit limit.'
 q[9]['options'][3]['text']='Keep a local read model updated by customer events, accepting delayed visibility and handling duplicate or out-of-order events'
 q[9]['options'][3]['explanation']='Correct with the stated stale-read tolerance. Orders can read its copy during an owner outage, but lag has no automatic seconds-level bound.'
 q[9]['workedExample']=q[9]['workedExample'].replace('no network hop, no dependency.', 'no synchronous Customers call, though it still depends on its own read store and eventually on reliable updates.').replace('staleness of seconds, plus another consumer to run and monitor.', 'replication lag that must be monitored; outages can make it arbitrarily long. Bootstrap, deletion and repair paths also matter.').replace('Use a synchronous call instead when you need the very latest value, for example a credit limit check.', 'For a credit limit, ask the authoritative owner to atomically authorize/reserve against its state. A separate synchronous read followed by a write can still race.')
 q[10]['prompt']=q[10]['prompt'].replace('what replaces that transaction?', 'without a distributed atomic-commit protocol, which pattern can coordinate the business process?')
 q[10]['options'][1]['explanation']='Correct. The local transaction commits business state and an outbox row together; a relay publishes later and may publish duplicates. Compensation is another fallible business action, not atomic rollback.'
 q[10]['workedExample']=q[10]['workedExample'].replace('two databases, so no single ACID transaction.', 'separate databases with no shared atomic-commit protocol in this scenario.').replace('the business must accept that state.', 'the business must accept that intermediate state. Make handlers idempotent, publish each transition reliably, and retry or reconcile failed compensation.')
 q[11]['options'][2]['explanation']='Correct. Incremental migration creates smaller feedback loops. Routing rollback is safe only while old and new behavior and data remain compatible.'
 q[11]['workedExample']=q[11]['workedExample'].replace('shift traffic gradually (1%, 10%, 100%) → migrate its data → delete old code.', 'coordinate/migrate its data → shift traffic gradually (1%,10%,100%) → retire old code after validation.').replace('Each step can be rolled back by changing the route.', 'A route change alone cannot undo incompatible writes; plan data compatibility, reconciliation and rollback before migration.')
questions(b+'arch-monolith-vs-microservices.questions.json',mono,'Fix outbox atomicity, migration rollback, credit-limit race and stale-read assumptions; qualify architecture generalizations.',src)
src=['https://12factor.net/processes','https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/','https://kubernetes.io/docs/concepts/workloads/controllers/deployment/','https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/','https://www.rfc-editor.org/rfc/rfc9700.html','https://www.rfc-editor.org/rfc/rfc8725.html','https://www.pgbouncer.org/features.html','https://www.postgresql.org/docs/current/runtime-config-connection.html']
patch(b+'arch-stateless-web-tier.md',[
('The cheapest scaling move in system design is **adding more identical servers behind a load balancer**. It only works if any server can handle any request.', 'A common way to scale an application tier is **adding instances behind a load balancer**. Making requests independent of any particular instance simplifies this; stateful systems can also scale through partitioning or replication.'),
('A stateless service keeps **no client-specific data in its own memory or local disk between requests**.', 'A stateless application tier does not rely on **instance-local client state surviving until a later request**. Rebuildable caches and per-request working memory are compatible with this design.'),
('Need 3× capacity? Run 3× the servers.', 'More instances can increase capacity when requests distribute well and shared dependencies have headroom; scaling is not automatically linear.'),
('Nothing is lost.', 'Durable external state remains available under its own guarantees, but in-flight requests, connections and uncommitted work can be lost.'),
('with one ~0.5 ms lookup.', 'with a lookup whose latency depends on topology, load and the store.'),
('Sessions can be revoked instantly by deleting the key.', 'Deleting the session prevents future authorizations only once all relevant checks observe the deletion; caches, replicas, failover and already-authorized requests affect cut-off.'),
('No server-side lookup at all; any server can verify the signature.', 'Verification can be local if the server already has trusted keys and policy. Signature checking must be accompanied by issuer, audience, expiry and application-specific authorization checks.'),
('| Redis store | ~0.5 ms | instant | store outage |', '| Redis store | Store lookup | Depends on observation/consistency | Store outage or lost state |'),
('target around 50–70% so there\'s headroom for spikes.', 'choose a target from load testing and required headroom;50–70% is an illustrative starting range, not a universal optimum.'),
('A new VM may take 1–3 minutes to boot and warm up; a container on an existing node takes seconds.', 'VM provisioning, image pulls and application warm-up all take time; measure readiness time for the actual workload rather than assuming a VM/container timing range.'),
('Many Postgres instances fall over well before that.', 'Whether that exceeds limits or sustainable load depends on database configuration, memory and active query demand.'),
('an image that runs the same everywhere.', 'an image for a supported platform; host kernel, architecture, configuration and external services still affect behavior.'),
('so once its image is on the node it can start in under a second, with little overhead. (Pulling a large image onto a fresh node can still take tens of seconds, which is one reason to keep images small.)', 'which can reduce some virtualization overhead. Time to serving readiness still depends on the runtime, image availability, initialization and dependencies.'),
('a stable virtual IP and DNS name (`orders.default.svc`) that load-balances across the matching pods, whose IPs keep changing.', 'a normal ClusterIP Service provides a stable virtual IP and DNS name for matching endpoints. Headless and ExternalName Services behave differently.'),
('a *readiness* probe decides whether a pod receives traffic; a *liveness* probe decides whether it gets restarted.', 'readiness contributes to endpoint eligibility for normal Service traffic; a liveness failure reaching its threshold can restart the failing container under its restart policy.'),
('waits for a 5-minute stabilisation window before scaling *down*', 'uses the highest recent recommendation within a default 5-minute scale-down stabilisation window'),
('adds nodes, which takes minutes rather than seconds. Pods stay *Pending* until the new node is ready.', 'can provision nodes when suitable capacity is available and policy permits. Timing is workload/provider-dependent; quotas, capacity shortages and scheduling constraints can leave pods Pending.'),
('Because the pods are stateless, users never notice which version served them, as long as both versions are compatible with the current database schema.', 'This aims to maintain availability, but statelessness and schema compatibility alone do not guarantee invisible updates: APIs, sessions, capacity and draining must also remain compatible.'),
('for a second or two *after* `SIGTERM`.', 'during the propagation delay, including after SIGTERM; there is no universal one- or two-second bound.'),
('- Stateless app servers keep no per-client data locally, so any instance can serve any request and instances become disposable.', '- Stateless app tiers do not depend on durable instance-local client state; replaceable caches are allowed, while backing stores retain the state that must survive.')], 'Correct statelessness definition, false linear-scaling/lossless-failure guarantees, unmeasured timings and Kubernetes lifecycle semantics.',src)
def stateless(q):
 q[0]['options'][1]['text']='It does not depend on instance-local client state being retained between requests, so a replacement instance can reconstruct what it needs'
 q[3]['options'][1]['explanation']='A key rotation only invalidates old tokens once every verifier stops accepting the old key. It is broad rather than per-user revocation, and cached keys or overlap can delay cut-off.'
 q[3]['options'][2]['explanation']='Correct as a design approach. Revoking refresh credentials prevents future refresh once observed, but existing access tokens continue until expiry or a separate enforced revocation check.'
 q[3]['workedExample']=q[3]['workedExample'].replace('Worst case exposure is now about 15 minutes.', 'After refresh is disabled, existing15-minute access tokens can remain usable until expiry (plus configured clock tolerance); merely changing the policy does not shorten already-issued24-hour tokens.').replace('For instant cut-off, keep a small denylist', 'For prompt cut-off, require every authorization to consult a consistently enforced denylist')
 q[3]['link']={'title':'OAuth2.0Security Best Current Practice','url':'https://www.rfc-editor.org/rfc/rfc9700.html'}
 q[4]['options'][1]['explanation']='A rebuildable cache can fit a stateless tier if its freshness and consistency satisfy the request contract. Stale authorization or configuration can still cause correctness problems.'
 q[5]['options'][1]['explanation']='These changes address provisioning delay and connection pressure; validate readiness time and query capacity rather than assuming containers and a pooler guarantee recovery.'
 q[5]['workedExample']=q[5]['workedExample'].replace('Containers on pre-provisioned nodes start in seconds, not minutes.', 'Pre-provisioned nodes can reduce some startup delay; measure application readiness, image loading and dependencies.').replace('put orders into a queue', 'admit orders into a bounded queue with explicit acceptance, deduplication and inventory semantics')
 q[6]['options'][0]['explanation']='Correct as a likely cause. Endpoint updates and local termination proceed concurrently; preStop runs before the stop signal and shares the grace-period budget. Draining reduces this failure mode but must be validated.'
 q[6]['options'][3]['explanation']='A single replica is fragile, but a rolling update with surge capacity can overlap old and new pods; one replica does not by itself imply every deployment has downtime.'
 q[6]['workedExample']='1. Termination starts concurrent endpoint updates and kubelet shutdown. Normal terminating endpoints become not ready; propagation is not instantaneous.\n2. The kubelet runs any preStop hook before sending the configured stop signal (normally SIGTERM). Both hook and draining consume the grace period.\n3. An app exiting immediately can drop routed or in-flight work.\n4. Measure propagation, continue serving during an appropriate preStop delay, then stop accepting new work and drain with a bounded deadline. Reconnect long-lived clients.\n5. Load-test rollouts and failure paths. This reduces avoidable resets but does not guarantee zero errors under every failure.'
 q[6]['link']={'title':'Kubernetes Pod lifecycle','url':'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/'}
 q[7]['prompt']='For an ordinary Deployment using normal Service endpoint routing, what is the difference when a readiness or liveness probe reaches its configured failure threshold?'
 q[7]['options'][3]['text']='Readiness failure removes normal endpoint eligibility without itself restarting the container; liveness failure can cause its restart under the configured policy'
 q[7]['workedExample']=q[7]['workedExample'].replace('Rolling deploys wait for readiness before removing old pods.', 'Rolling update behavior uses availability and maxUnavailable/maxSurge settings; it need not wait for every new pod before removing any old pod.')
 q[8]['prompt']=q[8]['prompt'].replace('Each pod keeps a database pool of 25 connections', 'Each pod attempts to open its full25-connection database pool simultaneously')
 q[8]['workedExample']=q[8]['workedExample'].replace('250 connections. Fine.', '250connections, below the configured ceiling but not necessarily below sustainable query load.').replace('Each Postgres connection is a process using several MB, so 1,500 would hurt even if allowed.', 'Each server connection consumes resources; actual memory and query cost depend on configuration and activity.').replace('per-pod pools of 5–10.', 'per-pod limits chosen from measured concurrency. Transaction pooling requires application compatibility with session-state restrictions.')
 q[8]['link']={'title':'PostgreSQL connection settings','url':'https://www.postgresql.org/docs/current/runtime-config-connection.html'}
 q[9]['prompt']='A healthy Deployment has10replicas, maxSurge:2 and maxUnavailable:0. What limits does the rolling-update controller aim to maintain, excluding independent failures and allowing terminating pods to finish?'
 q[9]['options'][0]['text']='Up to12non-terminating pods and at least10available pods under normal rollout control; total existing pods can be higher while termination finishes'
 q[9]['options'][0]['explanation']='Correct. Surge and unavailability constrain rollout decisions; terminating pods can temporarily consume extra resources, and node/app failures can still reduce actual availability.'
 q[9]['options'][3]['explanation']='The controller does not intentionally remove all available capacity with maxUnavailable:0. It does not provide an unconditional minimum under failures or an absolute total-pod cap.'
 q[9]['workedExample']='1. Desired count:10.\n2. Surge allowance:2additional non-terminating pods during normal rollout.\n3. maxUnavailable:0 directs the controller to retain desired available capacity as it replaces pods.\n4. Availability can differ from readiness when minReadySeconds applies.\n5. Terminating old pods can remain present and consume resources beyond the nominal12until their grace periods end.\n6. These are controller policies, not a promise against node outages, probe failures, insufficient capacity or incompatible versions.'
 q[10]['prompt']+=' Assume asymmetrically signed access tokens and a validated issuer/audience/expiry policy.'
 q[10]['options'][0]['explanation']='Correct. A server-side refresh-session record (often storing a token hash rather than raw token) supports revocation checks at refresh. Refresh frequency depends on client activity and policy.'
 q[10]['options'][2]['explanation']='Correct. Reuse detection is evidence of replay, though legitimate concurrent clients can also reuse a token. Family invalidation must be atomic and does not automatically revoke issued access tokens.'
 q[10]['options'][3]['explanation']='Correct with trusted key distribution and the stated validation policy. Signature validity alone is insufficient; enforce issuer, audience, expiry and required claims.'
 q[10]['workedExample']=q[10]['workedExample'].replace('Worst case after a theft report: up to 15 minutes of access.', 'After refresh revocation is enforced, already-issued access tokens can remain usable for their remaining lifetime plus allowed clock tolerance; stronger cut-off needs additional checks.').replace('Cost: one store lookup per user per 15 minutes, versus one per request for server-side sessions.', 'Refresh lookup frequency depends on active clients and their refresh schedules; it is not exactly one lookup per user per15minutes.')
 q[10]['link']={'title':'OAuth2.0Security Best Current Practice','url':'https://www.rfc-editor.org/rfc/rfc9700.html'}
 q[11]['workedExample']=q[11]['workedExample'].replace('A 2-minute dip never causes a scale-down.', 'A2-minute dip following an in-window high recommendation preserves that recommendation; an older high recommendation that has already expired does not provide this protection.')
questions(b+'arch-stateless-web-tier.questions.json',stateless,'Correct replica availability bounds, preStop order, JWT revocation, local caches and connection-pool assumptions.',src)
for name in ['arch-monolith-vs-microservices','arch-stateless-web-tier']:
 for ext in ['.md','.questions.json']:report['reviewed_files'].append(b+name+ext)
report['omissions']=[{'lesson':'arch-monolith-vs-microservices','claim':'Generic nanosecond vs millisecond call-cost table','reason':'No reproducible benchmark/environment supports universal call latency.'},{'lesson':'arch-stateless-web-tier','claim':'Fixed session lookup and container/VM startup timings','reason':'No measured deployment exists to substantiate these product-wide timings.'}]
Path('docs/audit-system-design-architecture.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
