exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-system-design-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/system-design/08-architecture/'
src=['https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/','https://istio.io/latest/docs/ambient/architecture/','https://istio.io/latest/docs/ambient/usage/waypoint/','https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html','https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/','https://grpc.io/docs/guides/deadlines/','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/net/InetAddress.html']
patch(b+'arch-service-communication.md',[
("In a static world you'd hard-code `payments.internal:8080`.", 'Hard-coding an instance IP is fragile when instances change. A stable DNS name such as payments.internal:8080 can still be appropriate when discovery or routing updates its backing endpoints.'),
('Only pods passing their readiness probe are in the Service\'s endpoint list. AWS ALBs with target groups work the same way.', 'EndpointSlices can include unready endpoints with condition flags; normal routing chooses eligible endpoints, with exceptions such as publishNotReadyAddresses. A pod need not have an explicit readiness probe. ALB target groups also use health checks, but their failure policies differ: ALB can fail open when all targets are unhealthy.'),
('A **service mesh** (Istio, Linkerd) puts a proxy sidecar next to every service and manages them all from a central control plane.', 'A **service mesh** manages service-to-service traffic through a data plane and a control plane. In a sidecar deployment (for example Istio or Linkerd), proxies run alongside enrolled workloads; sidecarless designs use a different topology.'),
('**Metrics and tracing** for every call', '**Metrics and trace spans** for intercepted supported traffic; sampling and protocol support vary, and end-to-end traces need application context propagation'),
('typically sub-millisecond, but it adds up on deep call chains', 'latency depends on configuration, load and protocol and can accumulate on deep call chains'),
('an optional per-namespace proxy only where you need HTTP-level features.', 'optional waypoint proxies for Layer7 policies, enrolled at namespace, service or workload scope as supported by configuration.'),
('slow dependencies tie up the caller\'s threads.', 'slow dependencies retain caller resources. Blocking clients hold threads; asynchronous clients can still retain requests, connections and memory.'),
('the emails go out when it recovers.', 'delivery can resume when it recovers, provided durable retention, retries and deduplication cover the outage and the provider accepts the messages.'),
('make sure an outer timeout is longer than the inner ones it wraps.', 'allocate nested calls and retries within the remaining end-to-end deadline, leaving time for local work and response handling.'),
('with a retry budget so retries can\'t multiply load during an outage.', 'with a retry budget to bound additional load during an outage.'),
('separate connection pools per dependency, so one slow service can\'t exhaust all the threads.', 'bound in-flight work and queues per dependency, with separate resources where needed. Separate connection pools alone do not guarantee isolation of a shared thread pool.')], 'Correct endpoint membership vs readiness, ALB fail-open, mesh topology and tracing, and deadline/bulkhead guarantees.',src)
def comm(q):
 q[0]['prompt']+=' Assume payments is a normal ClusterIP Service in the same namespace, with ordinary readiness routing and kube-proxy forwarding.'
 q[1]['workedExample']=q[1]['workedExample'].replace('Orders writes the order and publishes `OrderPlaced` (ideally via a transactional outbox so they can\'t diverge), then returns.', 'Orders commits the order and an outbox record atomically, then returns. A relay publishes later; monitor retries and retention, and make consumers tolerate duplicate delivery.')
 q[2]['options'][0]['explanation']='Correct for intercepted eligible traffic with configured mesh trust. With transparent interception, the app normally calls the destination service address, not localhost.'
 q[2]['workedExample']=q[2]['workedExample'].replace('every call in and out of the pod.', 'configured intercepted traffic; exclusions, unsupported protocols and bypass paths matter.')
 q[3]['workedExample']=q[3]['workedExample'].replace("4. Netflix's own move from Ribbon towards proxy-based approaches reflects exactly this pressure.", '4. This is an architectural trade-off; no single historical cause for a specific company migration is asserted here.')
 q[4]['prompt']='The gateway gives a request2seconds overall. A waits up to5seconds for its call to B; B takes8seconds and ignores cancellation. Calls start near t=0 and no deadline is propagated. What happens?'
 q[4]['options'][1]['text']='The gateway times out near2seconds; A can wait until5seconds and B can run until8seconds unless cancellation is propagated and honored'
 q[4]['workedExample']=q[4]['workedExample'].replace('about 3 s of A\'s capacity and 8 s of B\'s.', 'about3seconds of A waiting after the gateway gives up; B runs8seconds total, including6seconds after the user deadline.').replace('propagate deadlines (gRPC does this natively) so downstream work stops when the caller has given up.', 'propagate deadlines using the relevant gRPC implementation settings, and make handlers stop spawned work when cancellation is observed. Cancellation is cooperative; it cannot undo completed effects.')
 q[6]['workedExample']=q[6]['workedExample'].replace('B sees16,000','B sees16,000').replace('B sees 16,000 req/s just as it\'s struggling, which makes recovery very unlikely.', 'up to16,000 bottom-level attempts/s are implied if every retry fits the budget and the sustained system has sufficient concurrency; deadlines, backoff and capacity can reduce the realized rate.')
 q[7]['options'][1]['explanation']='Correct. Events describe facts without prescribing one recipient; consumers still depend on event schema and meaning. Commands request an action from an intended handler.'
 q[8]['options'][0]['explanation']='Other clients recovering makes a process-local cache a plausible explanation, but different resolvers and cache paths mean it does not logically rule out every DNS-side issue.'
 q[8]['workedExample']='1. Check the addresses resolved and retained inside the affected process and client library.\n2. In Java25 InetAddress, successful lookup caching defaults to an implementation-specific period; networkaddress.cache.ttl=-1 means cache forever. Older security-manager defaults should not be assumed for modern JDKs.\n3. Also inspect negative/stale caches and address lists retained by connection pools. Reconnection need not force a new DNS lookup.\n4. Configure and test discovery refresh and failure behavior; a stable load-balancer name can reduce instance churn but its own addresses can also change.'
 q[8]['link']={'title':'Java25 InetAddress caching policy','url':'https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/net/InetAddress.html'}
 q[9]['options'][1]['explanation']='Correct for an intercepted sidecar-to-sidecar call. Benchmark added latency; there is no universal sub-millisecond cost.'
 q[9]['options'][2]['explanation']='HTTP remains usable. With transparent interception, the app calls the service address normally and the proxy handles intercepted transport.'
 q[10]['options'][1]['explanation']='Kafka producer transactions do not enlist an arbitrary external database in shared atomic commit. The described setup needs an outbox or another explicitly supported coordination protocol.'
 q[10]['workedExample']=q[10]['workedExample'].replace('Nothing lost.', 'The durable pending event remains available to the relay; delivery still depends on recovery, retention and retry policy.')
 q[11]['options'][0]['explanation']='Individual p99 values cannot determine the p99 of the sum: dependence and latency distributions matter. The extra nonnegative call adds work and another dependency, so measure the end-to-end path.'
 q[11]['workedExample']='1. The individual p99 values sum to750ms before Loyalty and900ms after it, but these sums are not the request p99.\n2. Measure the joint end-to-end distribution and enforce the800ms deadline; this data alone does not prove an SLO pass or failure.\n3. The user need not wait for points, so remove Loyalty from the required checkout path.\n4. Publish through a reliable outbox/event path, compute points asynchronously, and show a pending state until they are available.'
questions(b+'arch-service-communication.questions.json',comm,'Fix additive p99 inference, inconsistent timeout timeline, Java caching defaults and mesh localhost misconception.',src)
src=['https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html','https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html','https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/data-modeling-foundations.html','https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs','https://redis.io/docs/latest/commands/zrevrank/','https://redis.io/docs/latest/develop/reference/client-side-caching/']
patch(b+'arch-scaling-reads.md',[
('Most consumer systems read far more than they write. A social feed might see 100 reads per write; a product catalogue, 1,000 or more.', 'Many read-heavy applications, such as feeds and catalogues, benefit from serving copies of data; measure the actual read/write mix instead of assuming a universal ratio.'),
('(a missing index can turn a 2 ms query into a 2 s table scan)', '(compare execution plans and measured latency with representative data)'),
('These can buy an order of magnitude for very little cost.', 'Measure their benefit before adding infrastructure; gains depend on the original bottleneck.'),
('# 51 round trips of ~1 ms = ~51 ms', '# Assume 1 ms per serial round trip:\n# 51 round trips = 51 ms (network only)'),
('Scales read throughput roughly linearly with replica count (Amazon Aurora, and RDS for MySQL and PostgreSQL, allow up to 15 read replicas per source).', 'Adds read-serving capacity subject to replication overhead, workload balance and shared bottlenecks. Replica limits depend on the engine and service configuration; check current provider documentation.'),
('Replication is usually asynchronous, so replicas are behind by milliseconds normally, and by seconds or minutes under heavy load.', 'With asynchronous replication, visibility can lag without a fixed upper bound; monitor replay progress and failure recovery.'),
('                   [Redis]  hit: ~0.5 ms', '                   [Redis]  hit'),
('                   [ DB ]   ~5-50 ms', '                   [ DB ]'),
('| Layer | Holds | Typical hit time |\n|---|---|---|\n| Browser/CDN | static, public pages | ~10–50 ms (RTT) |\n| In-process | hot keys | ~µs |\n| Distributed | shared results | ~0.5 ms |\n| DB from memory | hot pages | ~1 ms |', '| Layer | Holds | Main considerations |\n|---|---|---|\n| Browser/CDN | Cacheable responses/assets | Cache policy and network distance |\n| In-process | Hot keys | Per-instance freshness and memory |\n| Distributed | Shared results | Network, load and consistency |\n| Database buffer cache | Hot pages | Query work, locks and I/O |\n\n> [!note] Evidence gap\n> Fixed cache and database latency ranges are omitted because no measured environment supports them. The calculation below uses explicit hypothetical inputs.'),
('give everything a TTL, and know which data can tolerate staleness.', 'choose freshness, invalidation and eviction policies for each kind of data. A TTL is useful in many designs but does not alone bound source-data age; immutable content-addressed data can use different policies.'),
('a `like_count` column maintained on write is instant.', 'a correctly maintained like_count avoids recounting rows, though lookup and write contention still have costs.'),
('you design tables around queries ("one table per access pattern"), because they don\'t support joins.', 'you model access patterns rather than rely on server-side relational joins. Cassandra often uses query-specific tables; DynamoDB supports both single-table and multiple-table designs, so one table per access pattern is not a universal rule.'),
('needs a unique index on the view and takes longer.', 'requires an already populated view and a qualifying unique index covering all rows with plain column keys. It is not invariably slower; relative cost depends on how many rows change.'),
('where writes go to a normalised model and reads go to one or more denormalised views.', 'which separates command and query responsibilities. CQRS can use one database and does not require a normalized write model or denormalized read model.'),
('The price is staleness, storage and complexity in keeping copies in sync.', 'The costs can include storage, maintenance work and either staleness or stronger coordination to keep copies current.')], 'Remove unmeasured latency/linear-scaling claims; correct TTL freshness, DynamoDB modeling, CQRS and concurrent materialized-view refresh.',src)
def reads(q):
 q[0]['prompt']+=' The primary confirms the committed update immediately; an uncached read from the replica still shows the older value.'
 q[0]['workedExample']=q[0]['workedExample'].replace('for about 10 s after a user writes, route that user\'s reads to the primary, or wait until the replica\'s replay position passes the write\'s log position.', 'route the required fresh read to the primary, or wait until the replica has replayed at least the write\'s commit position. A fixed10-second primary window is a heuristic, not a bound on lag.')
 q[1]['prompt']='In a single-writer database architecture, which change does not partition ownership of writes or directly add another primary accepting a separate share of them?'
 q[1]['options'][0]['explanation']='Correct among these options. Replicas can indirectly free primary resources by offloading reads, but full replicas still replay the complete write stream rather than partition it.'
 q[1]['prompt']='Which change primarily offloads reads while retaining the same single-writer primary and a complete write stream on each full replica?'
 q[1]['workedExample']=q[1]['workedExample'].replace('each node still does 100% of the write work.', 'every full replica replays the write stream, though execution/replay costs differ.').replace('Writes scale with sharding, batching or bigger hardware, not replication.', 'Offloading reads can free primary headroom. Sharding, batching and larger hardware can address other write bottlenecks, but none guarantees a fixed scaling factor.')
 q[3]['prompt']+=' The product accepts briefly delayed counts but not day-old counts.'
 q[3]['options'][1]['explanation']='Correct. Maintaining the aggregate avoids an O(number of likes) recount. The point-lookup cost depends on the store/index; update atomically with like changes or reconcile an idempotent projection.'
 q[3]['workedExample']=q[3]['workedExample'].replace('Read: one row lookup, about 1 ms.', 'Read: one indexed row/key lookup; measure latency. Couple the count update atomically to the like record, or use reliable deduplicated projection and reconciliation.')
 q[4]['prompt']=q[4]['prompt'].replace('Which approaches are appropriate?', 'Which approaches can reduce repeated aggregation if their refresh duration, source lag and cache age are budgeted to stay within that hour?')
 q[4]['options'][0]['text']='A precomputed view or rollup refreshed often enough that source age plus refresh interval/duration stays below one hour'
 q[4]['options'][0]['explanation']='Correct. Refreshing every hour alone can exceed a one-hour data-age budget because refresh work and source lag add time.'
 q[4]['options'][3]['text']='Cache the shared result with a freshness policy that accounts for its source snapshot age and refresh duration, not just time since insertion'
 q[4]['options'][3]['explanation']='Correct. A one-hour TTL by itself does not prove one-hour source freshness; misses still pay the aggregation cost and need controlled refresh.'
 q[4]['workedExample']=q[4]['workedExample'].replace('rollup table refreshed hourly (or maintained incrementally) plus a short cache in front.', 'a rollup maintained incrementally or refreshed within a measured age budget, plus a cache that preserves that budget.')
 q[5]['workedExample']=q[5]['workedExample'].replace('about 200 followers means about 200 list inserts per post.', 'if a particular normal account has200followers, it requires about200list inserts. The stated200followees per user does not establish that every normal account has200followers.').replace('Write cost is bounded.', 'Use an explicit fan-out threshold and queue admission budget to bound per-post work; total work still depends on posting rates and recipients.')
 q[6]['options'][2]['explanation']='Some lag is expected, but acceptable age is a product requirement. An hour can arise from backlog, unavailable dependencies or event-handling errors; investigate rather than infer a unique cause.'
 q[6]['workedExample']=q[6]['workedExample'].replace('Partition events by order ID so one order\'s events arrive in order (e.g. Kafka key = orderId).', 'Partition related events consistently and define causal/version rules. Matching keys in separate topics or from independent producers do not create a cross-service total order.').replace('Store a version or sequence number per row and ignore older updates.', 'Use ordered per-entity versions for complete snapshots. Partial events/deltas need gap handling or separate source versions; dropping every older delta can lose required updates.')
 q[7]['options'][1]['text']='About51ms of serial network round trips; batching authors takes two queries (~2ms network), while an appropriate join can use one'
 q[8]['options'][3]['explanation']='Correct as a simple mitigation while the chosen replica only advances. Failover/reassignment can regress; carry a minimum observed version and wait or route to an eligible replica for a guarantee.'
 q[8]['workedExample']=q[8]['workedExample'].replace('that\'s usually acceptable.', 'that is a policy choice, not a monotonic-read guarantee. Preserve an observed-version token across reassignment if the product requires monotonic reads.')
 q[9]['options'][1]['text']='CONCURRENTLY allows SELECTs during refresh, requiring a populated view and a unique plain-column index covering all rows'
 q[9]['options'][3]['text']='Visible source data can be older than one refresh interval because refresh duration, upstream lag and failures also contribute'
 q[9]['options'][3]['explanation']='Correct. An hourly start schedule plus a4-minute successful refresh can expose a prior snapshot for about64minutes; missed refreshes can be older still.'
 q[9]['workedExample']=q[9]['workedExample'].replace('needs a unique index; slower, but readers aren\'t blocked.', 'needs a qualifying unique index and a populated view; permits concurrent SELECTs and is not universally slower.')
 q[9]['link']={'title':'PostgreSQL REFRESH MATERIALIZED VIEW','url':'https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html'}
 q[10]['options'][1]['explanation']='These reduce local residency or trigger eviction, but neither alone guarantees source freshness: Redis may refill stale data, invalidation can be lost, and a concurrent load can repopulate an old value.'
 q[10]['workedExample']=q[10]['workedExample'].replace('worst-case staleness ≤30s.', 'worst-case staleness ≤30s.').replace('Local TTL 10–30 s: worst-case staleness ≤ 30 s.', 'Local TTL10–30s bounds local entry age, not database-data age if upstream Redis is stale.').replace('each server evicts the key on message.', 'each connected server evicts on receipt; add recovery for missed messages and guard concurrent stale repopulation.').replace('always read the authoritative price.', 'authorize and persist the charge using an authoritative price/version under the intended transaction; an earlier read can race a price change.')
 q[11]['prompt']+=' The product needs live ranking, with deterministic tie-breaking and no personalized filtering.'
 q[11]['workedExample']=q[11]['workedExample'].replace('Your rank: count of players with higher scores.', 'Redis ZREVRANK returns a zero-based position including a member-order tie-break; add1 for ordinal display. Equal-score competition/dense ranks require a different policy.').replace('Memory: 20M members × roughly 100 bytes ≈ 2 GB, which fits on one Redis node.', 'Memory and node fit are not established here. Measure representative member lengths, encodings, allocator overhead, persistence/fork headroom and replica requirements; no universal bytes-per-member estimate is included.')
 q[11]['link']={'title':'Redis ZREVRANK','url':'https://redis.io/docs/latest/commands/zrevrank/'}
questions(b+'arch-scaling-reads.questions.json',reads,'Fix stale-read freshness budgets, followee/follower confusion, cross-stream ordering and zero-based tied ranks.',src)
for name in ['arch-service-communication','arch-scaling-reads']:
 for ext in ['.md','.questions.json']:report['reviewed_files'].append(b+name+ext)
report['status']='In progress: four lesson/question pairs fully read; remaining five pairs pending. Independent verifier signoff pending.'
report['omissions'] += [{'lesson':'arch-service-communication','claim':'Universal sub-millisecond mesh proxy overhead and a company-specific migration motive','reason':'No benchmark or firsthand migration evidence supports the generic latency/motive assertions.'},{'lesson':'arch-scaling-reads','claim':'Cache/DB latency table and Redis bytes-per-member fit estimate','reason':'No measured environment or representative data supports these capacity estimates.'}]
p_report.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
