exec(open('/tmp/lang-helpers.py').read());n='para-oop';p='https://docs.python.org/3/howto/descriptor.html';j='https://docs.oracle.com/javase/specs/jls/se21/html/jls-15.html#jls-15.12';tree='https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/TreeSet.html'
for a,b,src in [
('OOP is still imperative underneath: objects have mutable state and methods run statements in order.','OOP is often combined with imperative code, but objects may be immutable and their methods may be pure.',p),
('    def deposit(self, amount):\n        if amount <= 0:','    def deposit(self, amount):\n        if type(amount) is not int:\n            raise TypeError("integer pence")\n        if amount <= 0:',p),
('    def withdraw(self, amount):\n        if amount > self._balance:','    def withdraw(self, amount):\n        if type(amount) is not int:\n            raise TypeError("integer pence")\n        if amount <= 0:\n            raise ValueError("must be > 0")\n        if amount > self._balance:',p),
('Callers can only change the balance through `deposit` and `withdraw`, so the invariant is enforced in one place. If you later store the balance in pence, or log every change, callers do not need to change.','This educational account uses integer pence and rejects nonpositive amounts. Callers respecting the public API use these methods, so validation is centralized. Python’s underscore convention does not prevent direct mutation of `_balance`; this is not a concurrent or production banking implementation.',p),
('a set that counts how many elements were ever added.','a set that counts attempted insertions, including duplicates.',j),
('You can also swap in a `TreeSet` without changing anything.','You may substitute another Set implementation only if its contract suits callers: TreeSet requires an ordering and has different null and equality/ordering considerations.',tree),
('Java, C# and C++ (for `virtual` methods) implement this with a **virtual method table** (vtable): each class has an array of method pointers, and each object holds a pointer to its class\'s table.','A common implementation technique is a **virtual method table** (vtable). The diagram is a simplified model: actual Java, C# and C++ runtimes/ABIs differ in object layout, interface dispatch and optimization; language semantics do not mandate one table layout.',j),
('A call `a.speak()` compiles to "load vptr, load slot 0, call it". That is one or two extra memory loads,','In this simplified model, `a.speak()` loads the table and target before an indirect call; exact instruction and load counts vary,',j),
('`obj.speak` searches the instance\'s dictionary, then each class in the **method resolution order** (MRO).','With ordinary `object.__getattribute__`, lookup gives data descriptors found through the class MRO precedence over the instance dictionary, then considers non-data descriptors and other class attributes. Functions implement non-data descriptors, which bind ordinary methods. Custom attribute hooks can change lookup behavior.',p),
('Java resolves overriding at runtime via vtables but overloading at compile time from static types.','Java selects overriding implementations at runtime and resolves overloads at compile time from static types; vtables are an implementation technique.',j)]:lesson(n,a,b,'Correct object contracts, validation and implementation-versus-language distinction.',src)
edit(n,1,'Encapsulation does not prove correctness under all concurrency and construction paths.',p,lambda q:fields(q,workedExample=q['workedExample'].replace('Checking two methods proves the invariant for the whole program.','Validate construction and every permitted mutation path, including synchronization if objects are shared concurrently.')))
edit(n,3,'Multiple inheritance availability language-dependent.',j,lambda q:opt(q,3,explanation='Correct. Services use a logger rather than being loggers; in single-class-inheritance languages such as Java this also consumes the sole superclass choice.'))
edit(n,8,'Lesson Account uses single underscore, not hypothetical mangled name.',p,lambda q:fields(q,workedExample=q['workedExample'].replace("Check: `Account().__dict__` shows `{'_Account__balance': 0}`.","If Account initializes `self.__balance = 0`, its dictionary contains `_Account__balance`; the lesson's single-underscore example instead uses `_balance`.")))
edit(n,10,'Making a published extensible class final breaks clients.',j,lambda q:(opt(q,1,text='For new APIs, make classes final unless designed for extension; migrate existing subclassing clients before closing an API'),fields(q,workedExample=q['workedExample'].replace('Final by default: no subclasses, no dependence.','For new APIs, final by default prevents new subclass dependencies. Retrofitting final on a published superclass is a breaking change.'))))
edit(n,11,'Megamorphic inlining outcome not absolute; dependent on JIT/version/profile.',j,lambda q:(opt(q,3,text='A monomorphic site may allow guarded inlining of Circle.area; a diverse receiver profile can make useful inlining harder and retain indirect dispatch',explanation='Correct. This is an optimization opportunity, not a guaranteed performance outcome. HotSpot decisions depend on profile, method size, compiler and version.'),fields(q,workedExample='HotSpot profiles receiver types. A monomorphic site may inline the observed implementation with a guard or another valid type assumption. A diverse receiver profile can reduce profitable inlining opportunities, leaving indirect dispatch and fewer downstream optimizations. Some polymorphic sites can still inline targets; six classes does not impose a universal ban. Measure the actual compiled workload.')))
done(n)
