exec(open('/tmp/lang-helpers.py').read());n='para-logic-dataflow';d='https://souffle-lang.github.io/tutorial';p='https://www.swi-prolog.org/pldoc/man?predicate=%5C%2B/1';e='https://learn.microsoft.com/en-us/office/client-developer/excel/excel-recalculation'
for a,b,s in [
('anything it cannot prove is false.','a goal that finitely fails is treated as false for negation as failure. A search that loops has not established failure.',p),
('it means "no such fact is in the database".','it means the goal finitely failed against the available facts and rules.',p),
('As a result every program **terminates**, and it is evaluated **bottom-up** (repeatedly deriving new facts until nothing changes), so clause order doesn\'t matter.','For basic positive, function-free Datalog over a finite domain, bottom-up fixed-point evaluation terminates because only finitely many facts can be derived. Bottom-up evaluation is common, not the only strategy. Extensions such as arithmetic that generates new values can lose the finite-domain termination guarantee.',d),
('The spreadsheet is the most widely used dataflow (and arguably most widely used programming) system in the world.','Spreadsheets are a familiar example of dataflow-style dependencies.',e),
('Change A1 and the spreadsheet recalculates only the cells downstream of it, in **topological order**','In an automatic, nonvolatile acyclic calculation, changing A1 causes dependent cells to be recalculated in dependency order',e),
('which is why Excel reports a **circular reference**.','which Excel normally reports as a **circular reference**; optional iterative calculation can handle intentionally circular models subject to its convergence settings.',e),
('each stage runs concurrently as data arrives.','processes can run concurrently, but sort generally needs the complete input before producing globally sorted output.',e),
('| Datalog | Terminates | Less expressive |','| Basic finite-domain Datalog | Fixed-point termination | Extensions may lose guarantee |',d),
('Datalog restricts Prolog so that programs always terminate and evaluate bottom-up; it powers CodeQL, Soufflé and Datomic.','Basic finite-domain Datalog supports terminating fixed-point evaluation; CodeQL, Soufflé and Datomic use related or extended languages whose restrictions must be checked separately.',d),
('correct implementations update in topological order to avoid glitches.','glitch-free implementations maintain dependency consistency, for example through ordering or lazy recomputation.',d)]:lesson(n,a,b,'Correct termination, search, recalculation or buffering assumptions.',s)
edit(n,2,'Worked example misidentified failing option.',p,lambda q:fields(q,workedExample=q['workedExample'].replace('the second case fail','the fourth case fail')))
edit(n,3,'Automatic recalculation excludes manual/volatile modes.',e,lambda q:fields(q,prompt=q['prompt']+' Assume automatic recalculation and only these nonvolatile formulas.',workedExample=q['workedExample'].replace('Only cells downstream of A1 are recomputed.','In this simple model only dependent cells need recomputation; volatile formulas and full recalculation can add work in actual spreadsheets.')))
edit(n,5,'Right recursion also loops on cyclic relations; tabling changesbehavior.',d,lambda q:fields(q,prompt=q['prompt']+' Assume ordinary untabled Prolog and the acyclic family facts in the lesson.',workedExample=q['workedExample'].replace('so every recursive call moves one step down a finite chain','which terminates for these acyclic facts; cyclic parent relations can still loop without tabling or cycle handling')))
edit(n,7,'Finite positive basic language needed for termination.',d,lambda q:fields(q,prompt='For basic positive function-free Datalog over a finite set of constants, evaluated to its least fixed point, which statements are true? Select all that apply.',workedExample=q['workedExample']+' These guarantees do not automatically extend to arithmetic/value-generating or other unrestricted dialect features.'))
edit(n,8,'Sort buffers despite concurrent processexecution.',e,lambda q:opt(q,1,explanation='Correct. It is a dataflow pipeline whose processes may run concurrently, but sort normally consumes all input before emitting the globally sorted result.'))
edit(n,10,'Left recursion not sole loopcause.',p,lambda q:opt(q,1,explanation='These specified facts form a finite acyclic chain, so the parent-first recursion terminates. Other programs can loop from cycles or other recursion patterns, not only left recursion.'))
edit(n,11,'Round count needs synchronous snapshot semantics.',d,lambda q:fields(q,prompt=q['prompt'].replace('all facts known so far','only facts present at the start of that round')))
done(n)
n='para-scope-closures';p='https://docs.python.org/3/reference/executionmodel.html';r='https://doc.rust-lang.org/reference/types/closure.html';h='https://www.haskell.org/onlinereport/haskell2010/haskellch3.html'
for a,b,s in [
('a C `static` local has function scope','a C `static` local has block scope',p),
('If a function assigns to a name *anywhere*, that name is local *everywhere* in the function:','Unless a `global` or `nonlocal` declaration applies, binding a name anywhere in a function makes it local throughout that function:',p),
('### Closures capture variables, not values','### Python closures capture bindings',p),
('This is the most important fact about closures,','In Python and ordinary JavaScript closures, references to lexical bindings persist; other languages offer capture by value or reference. This distinction is',p),
('Rust\'s borrow checker rejects such code, and `move` closures take ownership instead.','Safe Rust rejects escaping borrows that outlive their referents. A `move` closure captures by value, moving or copying its captures; moving a borrowed reference does not extend the referent’s lifetime.',r),
('until the listener is removed, a common source of memory leaks.','while the listener and captured object remain reachable. Removing the listener helps only if no other live reference retains the closure or object.',p),
('arguments are evaluated fully before the call.','argument expressions are evaluated to values before the call; this does not recursively force lazy objects or traverse referenced data.',h),
('**Call by value** (C, Java primitives):','**Call by value** (C and Java, including Java reference values):',h),
('**Call by sharing** (Python, Java objects, JavaScript, Ruby):','**Call by sharing** (a useful description of Python, JavaScript, Ruby and Java object-reference behavior):',p),
('Closures capture variables, not values. Captured variables live on the heap (cells, upvalues) so they outlive the creating frame.','Capture rules depend on language: Python shares cells, while C++ and Rust also capture by value. Escaping environments often use heap storage, but storage and lifetime depend on implementation and ownership.',r),
('Python, Java and JavaScript pass by sharing: mutation is visible to the caller, rebinding is not.','Python and JavaScript share object references; Java is pass-by-value, including copied reference values. Mutating a shared object can be visible, but rebinding a parameter does not rebind the caller’s variable.',p)]:lesson(n,a,b,'Clarify capture, scope, lifetime and argument semantics.',s)
edit(n,6,'Question asks actual printed result.',p,lambda q:fields(q,prompt=q['prompt'].replace('What do the two calls return?','What is printed?')))
edit(n,11,'Move capture does not rescue borrowed referent lifetime.',r,lambda q:(opt(q,4,text='Safe Rust rejects closures outliving borrowed data; move captures by value but does not extend a borrowed referent’s lifetime',explanation='Correct. Values may be moved or copied into the closure. A captured reference still has its original lifetime constraint.'),fields(q,workedExample=q['workedExample'].replace('`move` transfers ownership.','`move` captures values; moving a reference does not make its referent live longer.'))))
edit(n,12,'Haskell if is syntactic, though equivalent lazy function possible.',h,lambda q:fields(q,workedExample=q['workedExample'].replace('Haskell can define `if` or `&&` as ordinary functions','Haskell can define a function with if-like behavior and defines `&&` as a function (the built-in `if ... then ... else` form itself is syntax)')))
done(n)
