exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-theory-discrete.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/theory/02-discrete-structures/'
src=['https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_session19.pdf','https://research.ibm.com/publications/register-allocation-via-coloring']
patch(b+'disc-graphs.md',[
('which problems are easy and which are hopeless.', 'which problems have efficient general algorithms and which have no known polynomial-time solution.'),
('A **path** is a sequence of vertices joined by edges; a **cycle** is a path that returns to its start without repeating edges or other vertices.', 'A walk is a sequence of vertices joined by edges. A simple path repeats no vertex; a cycle closes a path by returning to its start, with no other repeated vertices. An Euler trail may revisit vertices but never edges.'),
('Most real graphs are sparse (m much smaller than n²), so adjacency lists are the default.', 'For sparse graphs (m much smaller than n²), adjacency lists save space. The table assumes unsorted neighbor lists; hash-set or sorted representations change membership costs.'),
('For a graph with n vertices, these are all equivalent:', 'For a nonempty finite simple undirected graph with n vertices, these are equivalent:'),
('There is exactly one path between every pair of vertices.', 'There is exactly one simple path between every pair of distinct vertices.'),
('Adding any edge to a tree creates exactly one cycle;', 'Adding an edge between previously nonadjacent vertices of a tree creates exactly one cycle;'),
('The number of labelled trees on n vertices is nⁿ⁻²', 'For n ≥ 2, the number of labelled trees on a fixed n-vertex set is nⁿ⁻²'),
('For directed graphs, the condition is that every vertex has in-degree equal to out-degree (for a circuit).', 'For a directed Euler circuit with at least one edge, each vertex must have equal in-degree and out-degree, and all non-isolated vertices must belong to one connected component when directions are ignored. Balance alone is insufficient.'),
('and in generating de Bruijn sequences that test every possible keypad code with the fewest key presses.', 'and in generating de Bruijn sequences. Those give minimal universal strings for a sliding-window code tester; a keypad that requires Enter, resets after failure or locks out attempts needs a different model.'),
('as is the travelling salesman problem (the cheapest Hamiltonian cycle in a weighted graph).', 'as is the decision version of travelling salesman (is there a tour of cost at most B?). Finding a cheapest tour is an NP-hard optimization problem.'),
("Chaitin's allocator (1982) introduced this approach, and its descendants are still used in production compilers.", 'Chaitin and colleagues described an implemented graph-colouring allocator in their 1981 paper Register allocation via coloring.'),
('Since every face of a simple planar graph (with at least 3 vertices) is bounded by at least 3 edges and every edge borders at most 2 faces, 3F ≤ 2E.', 'For a connected simple plane graph with at least 3 vertices, each face boundary walk has length at least 3. Counting edge sides with multiplicity (a bridge is traversed twice on the same face) gives total boundary length 2E, hence 3F ≤ 2E.'),
('Euler circuits exist exactly when every degree is even (Euler paths: 0 or 2 odd vertices), and are found in linear time; Hamiltonian cycles are NP-complete.', 'When all edge-bearing vertices are connected, an undirected Euler circuit exists exactly when all degrees are even; an Euler trail needs 0 or 2 odd vertices. Construction is linear; deciding Hamiltonian-cycle existence is NP-complete.'),
('Planar graphs satisfy V − E + F = 2 and E ≤ 3V − 6, which proves K₅ and K₃,₃ non-planar.', 'A connected plane drawing satisfies V − E + F = 2. Simple planar graphs with V ≥ 3 satisfy E ≤ 3V − 6; the triangle-free bound E ≤ 2V − 4 is what rules out K₃,₃.')], 'Fix TSP decision/optimization classification, path terminology, Euler connectivity and planar proof assumptions, and register-allocation date.',src)
def graphs(q):
 q[0]['prompt']+=' Treat links as undirected point-to-point edges.'
 q[2]['workedExample']=q[2]['workedExample'].replace("The quadratic growth is why full meshes don't scale: 100 nodes need 4,950 links, and why systems use gossip protocols or hub topologies instead.", 'The edge count grows quadratically: 100 nodes require 4,950 pairwise links. Whether that is practical depends on physical versus logical connections and traffic; sparse overlays or hubs can reduce the connection count.')
 q[8]['workedExample']=q[8]['workedExample'].replace('In a simple planar graph with V ≥ 3, each face is bounded by at least 3 edges and each edge borders at most 2 faces, so 3F ≤ 2E.', 'For a connected simple plane graph with V ≥ 3, face boundary walks have length at least 3. Count edge sides with multiplicity, including bridges twice, to obtain 3F ≤ 2E.')
 q[9]['options'][0]['explanation']='Check that all edge-bearing vertices are connected and every degree is even, in O(n + m). Isolated vertices need not be visited by the edge-covering circuit.'
 q[10]['prompt']='In the simplified register-colouring model, four mutually interfering live values form K₄ and only 3 interchangeable registers are available. What must change?'
 q[10]['options'][0]['explanation']='K₄ needs four colours. Four vertices bound the chromatic number above by four, but do not make three sufficient.'
 q[10]['options'][2]['explanation']='With the fixed interference graph, three registers cannot hold all four values. Spill a value or transform the program/live ranges, for example by rematerializing a value when needed.'
 q[10]['workedExample']=q[10]['workedExample'].replace('The **register pressure** at a program point is the size of that clique.', 'In this simplified model the number of simultaneously live register-requiring values gives register pressure. Real targets add register classes, widths, fixed-register constraints and opportunities for rematerialization.')
 q[11]['workedExample']+='\nThe remaining edges can form a spanning tree only if the original graph connects these components; otherwise Kruskal ends with a spanning forest.'
questions(b+'disc-graphs.questions.json',graphs,'Clarify router and allocator models, planar edge-side counting, Euler isolated vertices and spanning-tree connectivity.',src)
srcn=['https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_session12.pdf','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_session13.pdf','https://cacr.uwaterloo.ca/hac/about/chap4.pdf','https://cacr.uwaterloo.ca/hac/about/chap8.pdf','https://www.rfc-editor.org/rfc/rfc8017.html','https://www.rfc-editor.org/rfc/rfc8446.html','https://docs.openssl.org/3.5/man3/BN_generate_prime/','https://docs.python.org/3/library/math.html','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/lang/Math.html#floorMod(int,int)','https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-number-divide']
patch(b+'disc-number-theory.md',[
('Number theory used to be the textbook example of pure maths with no applications. Then public-key cryptography arrived, and now every HTTPS connection relies on it.', 'Number theory underpins public-key systems such as RSA and finite-field or elliptic-curve key exchange. HTTPS can use different TLS authentication and key-exchange modes; RSA is not required for every connection.'),
('C, C++, Java, JavaScript and Go truncate towards zero, giving `-7 % 3 == -1`. Code like `buckets[hash % n]` can then index out of range for a negative hash. In those languages use `((a % n) + n) % n`.', 'Modern C/C++, Java and Go integer division truncates towards zero. JavaScript Number division is floating-point, but its remainder also gives -7 % 3 == -1 (BigInt division truncates). A negative remainder may be an invalid index. For a positive modulus use Java Math.floorMod, or compute r = a % n and add n only when r < 0. Unconditionally adding n in ((a % n) + n) % n can overflow a fixed-width signed integer.'),
('unsigned 64-bit integers *are* arithmetic mod 2⁶⁴, which is why they wrap around.', 'unsigned 64-bit arithmetic in C/C++ wraps modulo 2⁶⁴. Other languages may use checked arithmetic or wider integers; signed C/C++ overflow is not defined as modular wraparound.'),
('gcd(a, b) is the largest integer dividing both.', 'For integers a and b not both zero, gcd(a, b) is their greatest positive common divisor. We use the programming convention gcd(0, 0) = 0.'),
('def gcd(a, b):\n    while b:', 'def gcd(a, b):\n    a, b = abs(a), abs(b)\n    while b:'),
('It is fast: every two steps the larger number at least halves, so it takes O(log min(a, b)) iterations.', 'For positive inputs, Euclid uses O(1 + log min(a, b)) remainder steps; one operand zero is an immediate case. This counts arithmetic operations, not their growing bit cost.'),
('The **extended Euclidean algorithm** finds them by running Euclid and tracking how each remainder is built from a and b:', 'The extended Euclidean algorithm finds them by tracking how each remainder is built from a and b. This recursive teaching version accepts non-negative integers; large worst-case inputs can exceed Python\'s recursion limit, so use an iterative implementation for those cases:'),
('That makes the integers mod p a **field**: you can add, subtract, multiply and divide.', 'That makes the residues mod p a field: addition, subtraction and multiplication are defined, and division by nonzero residues is possible.'),
('Elliptic-curve cryptography and Shamir\'s secret sharing typically compute in such prime fields. Reed–Solomon error correction (used in QR codes and RAID 6) uses a close cousin, the finite field GF(2⁸), whose elements fit in a byte.', 'Elliptic curves and Shamir secret sharing can use prime fields; binary extension fields are another option. Reed–Solomon codes work over finite fields, with GF(2⁸) a common byte-oriented choice. GF(2⁸) is not ordinary integer arithmetic modulo 256.'),
('```python\ndef primes_upto(n):\n    is_p', '```python\nfrom math import isqrt\n\ndef primes_upto(n):\n    if n < 2:\n        return []\n    is_p'),
('int(n**0.5)', 'isqrt(n)'),
('Each round with a random base wrongly passes a composite with probability at most 1/4, so 40 rounds gives error below 2⁻⁸⁰. OpenSSL and most crypto libraries use it.', 'For a fixed odd composite, each independently uniform random base has a false-pass probability at most 1/4, so 40 independent rounds give at most 2⁻⁸⁰. This is a conditional false-pass bound, not the posterior probability that any accepted candidate is composite. OpenSSL documents trial division followed by Miller–Rabin rounds; its round policy is version-dependent.'),
('RSA is built on exactly that gap.', 'Factoring an RSA modulus breaks its private-key protection, but hardness of factoring alone is not a proof that every RSA-based scheme is secure.'),
('def modpow(a, e, n):\n    result = 1', 'def modpow(a, e, n):\n    if e < 0 or n <= 0:\n        raise ValueError("e>=0, n>0 required")\n    result = 1 % n'),
('Python\'s built-in `pow(a, e, n)` does this (and more efficiently).', 'Python\'s built-in pow(a, e, n) performs efficient modular exponentiation and also supports invertible negative exponents. The teaching routine above is for integer e ≥ 0 and n > 0 and is not constant-time cryptographic code.'),
('Miller–Rabin adds an extra check that catches these.', 'Miller–Rabin adds stronger checks; base 2 rejects 561, but a single round is not guaranteed to reject every Carmichael number.'),
('Pick two large random primes p and q (each around 1024 bits or more).', 'For this mathematical two-prime construction, pick distinct odd primes p and q. Production key sizes and generation requirements must follow the chosen library and current deployment policy.'),
('**Encrypt** c = mᵉ mod n. **Decrypt** m = c^d mod n.', 'For an integer message representative 0 ≤ m < n, encrypt c = mᵉ mod n and decrypt m = c^d mod n.'),
('**Why it\'s secure (as far as we know)**: computing d needs φ(n), which needs p and q, which needs factoring n. The best known classical algorithm (the general number field sieve) is sub-exponential but still infeasible for 2048-bit n. A large quantum computer running Shor\'s algorithm would break it, which is why post-quantum schemes are being deployed.', '**Security connection:** knowing p and q lets an attacker compute a private exponent. However, inverting the RSA function has not been proved equivalent to factoring, and attacks can target weak encoding, key generation, side channels or protocols without factoring n. Secure RSA schemes require their own assumptions and implementation protections. Shor\'s algorithm would factor n on a sufficiently capable fault-tolerant quantum computer.\n\n> [!note] Evidence gap\n> No universal RSA latency or hardware attack-time estimate is supplied: this lesson has no reproducible benchmark or deployment threat model for one.'),
('which is several times faster.', 'which reduces operand sizes and can accelerate decryption; the speedup depends on arithmetic, hardware and implementation.'),
('fixed-width integers are arithmetic mod 2ᵏ.', 'unsigned C/C++ k-bit arithmetic wraps modulo 2ᵏ; other language/type rules differ.'),
('it is secure because factoring is hard, but only with proper padding.', 'factoring n breaks the key, but secure use also depends on the scheme assumptions, encoding, randomness and implementation.')], 'Fix negative-modulo overflow advice, sieve edge case and modpow infinite loop, scope Miller–Rabin probability, and remove false RSA factoring equivalence/unsourced timing.',srcn)
def number(q):
 q[0]['options'][0]['explanation']='Modern C and Java integer division gives quotient -2 and remainder -1. JavaScript Number division instead gives a noninteger quotient; Python // floors to -3.'
 q[0]['workedExample']=q[0]['workedExample'].replace('`h % n` is always a valid index in Python.', '`h % n` is a valid index into an n-element sequence when h is an integer and n > 0.')
 q[3]['options'][1]['text']='The ordinary rational number 1/7, without choosing a residue'
 q[3]['options'][1]['explanation']='Here an inverse is a residue class, conventionally represented by an integer 0 through 39. Modular notation 1/7 can denote that inverse when defined, but the ordinary rational 1/7 is not the requested representative.'
 q[6]['workedExample']=q[6]['workedExample'].replace('Each multiplication is on 2048-bit numbers, which is why RSA private-key operations take on the order of a millisecond, and why implementations use CRT to work with half-size numbers.', 'Operand size is determined by the modulus; if that is also 2048 bits, residues have at most 2048 bits and products can be wider before reduction. CRT uses smaller moduli. No latency follows without measuring a specified implementation and machine.')
 q[9]['options'][2]['explanation']='Correct. 561 = 3·11·17 is composite and passes Fermat for every coprime base. Miller–Rabin base 2 rejects 561; other bases can pass, so use a suitable tested primality routine.'
 q[9]['workedExample']=q[9]['workedExample'].replace('Each round errs with probability at most 1/4, even on Carmichael numbers.', 'For each fixed odd composite, an independently uniform random base has false-pass probability at most 1/4, including Carmichael numbers.')
 q[10]['options'][1]['explanation']='The raw RSA primitive is multiplicative modulo n. OAEP encoding and validation prevent treating arbitrary products of ciphertexts as valid encryptions of corresponding application-message products; they do not change the primitive\'s algebra.'
 q[10]['options'][4]['explanation']='65537 is a conventional public exponent and is not inherently insecure. Security also needs valid key generation, a suitable scheme and correct implementation; padding is not the only possible failure point.'
 q[11]['prompt']+=' Assume a nonempty shard array.'
 q[11]['options'][1]['explanation']='For positive n, Math.floorMod(h, n) gives 0 ≤ r < n. The handwritten expression ((h % n) + n) % n can overflow when n is large, so it is not a safe general replacement.'
 q[11]['workedExample']=q[11]['workedExample'].replace('Python never has this problem since its `%` already floors.', 'For a positive modulus, Python integer % already gives a non-negative remainder. In Java, unconditional remainder-plus-n normalization can itself overflow; Math.floorMod avoids that trap.')
questions(b+'disc-number-theory.questions.json',number,'Correct JS division, RSA runtime inference, modular-fraction wording, Miller–Rabin detection and Java normalization overflow.',srcn)
report['reviewed_files'] += [b+n+s for n in ['disc-graphs','disc-number-theory'] for s in ['.md','.questions.json']]
report['status']='All six lessons and 72 questions fully read/corrected; selected execution and independent verification pending.'
report['limitations']=['No production cryptographic implementation or performance measurement attempted; toy arithmetic examples only.','Independent verifier still required before stamping.']
report['omissions']=[{'lesson':'disc-number-theory','claim':'Universal RSA millisecond latency and hardware attack-time estimate','reason':'No reproducible benchmark or deployment threat model available; explicit evidence-gap note in lesson.'}]
p_report.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
