exec(open('/tmp/network04-helper.py').read());d=json.loads(report.read_text())
ntp_sources=['https://www.rfc-editor.org/rfc/rfc5905.html','https://www.rfc-editor.org/rfc/rfc8915.html','https://chrony-project.org/doc/4.7/chrony.conf.html','https://developers.google.com/time/smear','https://www.bipm.org/en/cgpm-2022/resolution-4','https://www.ntp.org/documentation/4.2.8-series/clock/','https://www.ntp.org/support/securitynotice/ntpbug1532/','https://www.nist.gov/publications/calibration-timing-accuracy-nist-cyber-physical-systems-testbed-0','https://www.rfc-editor.org/rfc/rfc4253.html','https://www.rfc-editor.org/rfc/rfc4252.html','https://www.rfc-editor.org/rfc/rfc4254.html','https://www.openssh.com/txt/release-9.0','https://www.openssh.com/txt/release-9.6','https://www.openssh.com/txt/release-10.0','https://terrapin-attack.com/','https://man.openbsd.org/sftp.1','https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02','https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md','https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md','https://grpc.io/docs/guides/deadlines/','https://grpc.io/docs/guides/status-codes/','https://grpc.io/docs/guides/retry/','https://grpc.io/docs/guides/keepalive/','https://grpc.io/blog/grpc-load-balancing/','https://protobuf.dev/programming-guides/encoding/','https://docs.python.org/3/library/time.html']
p2p_sources=['https://www.bittorrent.org/beps/bep_0003.html','https://www.bittorrent.org/beps/bep_0005.html','https://www.bittorrent.org/beps/bep_0009.html','https://www.bittorrent.org/beps/bep_0029.html','https://www.bittorrent.org/beps/bep_0042.html','https://www.bittorrent.org/beps/bep_0052.html','https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf']+['https://www.rfc-editor.org/rfc/rfc'+str(n)+'.html' for n in (8445,8489,8656,8827,8831,3550,7587,7983,9605,6184,4585,8829,5764)]
for scope,urls in [('NTP/SSH/SFTP/gRPC lesson and all11 quizzes; selected normative claims and dated implementation documentation',ntp_sources),('BitTorrent/Kademlia/WebRTC/RTP lesson and all11 quizzes; Kademlia PDF pages2 and6 visually inspected after corrupt text extraction',p2p_sources)]:
 for u in urls:d['sources'].append({'url':u,'scope':scope,'checked':'2026-10-05'})
d['tests'] += [{'command':'python3 /tmp/check-network04-ntp.py','result':'PASS40,010 assertions; both actual lesson Python fences, random NTP asymmetry models and uint64 varint boundary/invalid tests; no clock daemon, SSH server or gRPC runtime.'},{'command':'python3 /tmp/check-network04-p2p.py','result':'PASS34,107 assertions; both actual Python fences,10,000 bencoding and RTP fixtures, exhaustive4-bit XOR triangle inequality, RTCP wrap arithmetic. No live torrent, ICE NAT simulation, TURN service, SFU or browser media call.'}]
d['omissions'] += [{'lesson':'app-email','content':'Provider/API deployment prevalence and guaranteed rollout duration','reason':'No reliable universal empirical measurement; text explicitly omits prevalence and rejects time-based completeness guarantee.'},{'lesson':'app-ntp-ssh-grpc','content':'Universal current monlist amplification/deployment ratio and cross-language gRPC receive-limit defaults','reason':'No representative deployment data or complete implementation version matrix established; explicit absence notes.'},{'lesson':'app-p2p-webrtc','content':'Current DHT population/typical rounds, universal TURN10–20% rate, universal interactive150ms cutoff','reason':'No reliable representative current measurement supporting those universal specifics; text states absence.'}]
d['limitations']=['All six lessons and66 entire question records read; coverage is semantic review, not a clause-by-clause certification of every sentence. Confidence remains medium.','Primary RFCs/BEPs, original research, upstream code/docs and provider policies support core claims; product/browser defaults and deployments remain time-sensitive and explicitly qualified.','All ten Python lesson fences executed through the six listed harnesses; conceptual SMTP/IMAP/SSH/SDP/HTTP wire fragments are annotated abbreviated fixtures, not complete interoperability implementations.','Email transport mocked to avoid sending mail; actual stdlib serialization tested. No live DNS resolver/DNSSEC validator, browser cookie matrix, QUIC migration lab, packet captures or performance measurements.','Kademlia original PDF text was corrupt; downloaded and visually read relevant pages2 and6. No claim of reading every page of every source.','Whole-project link sweep, shared manual diagram inspection,390px rendering and integration tests remain parent integration tasks. Some optional further-reading links were not individually fetched in this pass.','claimsChecked counts66 whole quiz records plus grouped correction records. It is not a count of unique atomic factual claims; errorsCorrected includes clarifications, boundary guards and formatting corrections.']
d['status']='Independent semantic review complete: six lessons and66 complete quiz records; corrections and executable checks complete. Module record/stamp and scoped build being finalised.';d.pop('resume',None)
d['per_file_coverage']=[{'file':str(p),'full_read':True,'question_records':len(json.loads(p.read_text())) if p.name.endswith('.questions.json') else None,'confidence':'medium'} for p in sorted(r.iterdir()) if p.suffix=='.md' or p.name.endswith('.questions.json')]
d['summary']={'lessons':6,'questions':66,'grouped_corrections':len(d['findings']),'confidence':'medium'}
report.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
ids=[p.stem for p in sorted(r.glob('*.md'))]
sources=list(dict.fromkeys(s if isinstance(s,str) else s['url'] for s in d['sources']))
v={'module':'net-application','author':{'agent':'Original historical content author; provenance not independently established','date':'2026-10-05'},'verifier':{'agent':'audit_synth, independent review of pre-existing author content; corrections made in verifier role','date':'2026-10-05','independent':True,'sources':sources},'summary':{'claimsChecked':66+len(d['findings']),'errorsCorrected':len(d['findings']),'hedgedOrRemoved':len(d['omissions'])},'corrections':[f["file"]+': '+(f.get('question','')+' ')+f['reason'] for f in d['findings']],'lowConfidence':[{'lesson':i,'claim':'Deployment and implementation specifics beyond the explicitly stated protocol/model conditions','confidence':'medium','reason':'Primary-supported core and deterministic examples reviewed; no complete runtime interoperability matrix or every-sentence primary-clause mapping.'} for i in ids],'gaps':d['limitations']+[o['content']+': '+o['reason'] for o in d['omissions'] if isinstance(o,dict)],'lessons':{i:{'confidence':'medium'} for i in ids}}
(r/'verification.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
print(d['summary']);print('primary source entries',len(sources))
