exec(open('/tmp/network06-helper.py').read());n='wm-debugging'
q(n,1,['options',0,'explanation'],'Immediate refusal reports explicit rejection of the attempt, not proof of route failure. A local stack or intermediate device may reject it, so no response from the intended host is established.','Local rejection need not imply a remote reply.')
q(n,4,['options',3,'explanation'],'These are different probe and return-path samples. Hop 4’s reply RTT alone does not establish an equivalent transit delay or a bottleneck for application traffic.','Later low RTT does not prove all earlier transit traffic avoided delay.')
q(n,5,['options',0,'text'],'The capture proves that the database has no listener on port 5432','Original option was a consistent hypothesis too, making single-answer question ambiguous.')
q(n,6,['options',0,'explanation'],'A DNS query tests name resolution, not the specified packet-size behaviour. A successful login does not prove every DNS answer or address-family path is correct.','Prompt does not establish login by name and DNS correctness is not universal.')
q(n,6,['options',3,'explanation'],'Restarting is not a direct measurement of size-dependent path behaviour and may destroy useful diagnostic state. First test the path hypothesis.','Avoid treating restart outcome as proven while cause remains a hypothesis.')
q(n,10,['options',0,'explanation'],'The supplied trace directly establishes advertised receive-window closure. It does not establish packet loss as its cause; lack of observed retransmissions alone cannot exclude every loss elsewhere.','Loss need not be visible in one finite capture.')
q(n,10,['options',3,'explanation'],'The advertised zero window directly constrains new data. A separate PMTU issue may coexist, but it is not what the specified window advertisements establish.','Do not make a universal signature claim or exclude coexistence.')
q(n,11,['options',0,'explanation'],'Correct as a candidate. New tracked flows require capacity. Linux conntrack may emit a rate-limited table-full message; a remote NAT gateway has its own telemetry, and logging is not guaranteed for every failure.','Not every host/provider table failure prints the Linux message.')
q(n,11,['options',1,'explanation'],'Correct as a candidate. Automatic source-port allocation and reusable tuples are finite; TIME_WAIT and active connections can consume them. Pooling or reuse may reduce pressure, while actual remedies depend on the measured allocation policy and limit.','Explicit binding/source addresses/configuration qualify universal ephemeral-only limit and unique fix.')
md(n,'the kernel logs "table full".','Linux conntrack may log a rate-limited "table full" message; remote NAT services expose different telemetry.', 'Table exhaustion does not guarantee a local kernel log.')
md(n,'The ideal Reno congestion-avoidance Mathis approximation (adequate data/window, light/moderate loss and no RTO-dominated behaviour) is:','The simplified Reno congestion-avoidance Mathis model below assumes one ACK per segment, adequate data/window, light/moderate loss and no RTO-dominated behaviour:', 'The1.22 coefficient assumes ACK ratio1; delayed ACKs change model coefficient.')
coverage(n)
d=json.loads(report.read_text())
for u in ['https://everything.curl.dev/usingcurl/verbose/writeout.html','https://curl.se/docs/manpage.html','https://man7.org/linux/man-pages/man8/ss.8.html','https://man7.org/linux/man-pages/man8/ping.8.html','https://www.rfc-editor.org/rfc/rfc2923','https://datatracker.ietf.org/doc/html/rfc3819']:
 d['sources'].append({'url':u,'scope':'Debugging primary/manual checks: milestone interpretation, TCP windows/queues, ICMP/PMTU and simplified Reno throughput.'})
d['status']='Independent full semantic review complete first five pairs: 5 lessons,60 questions. Internet-structure pending.'
d['resume']='Internet-structure lesson and quiz full read, GPON/ITU/ICPC/satellite primary checks; execute harness; stamp and scoped build.'
report.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
