exec(open('/tmp/network06-helper.py').read());n='wm-sdn'
md(n,'Outer UDP source port is derived from a hash of the inner headers, so the fabric\'s ECMP still spreads tenant flows across paths.','RFC 7348 recommends deriving the outer UDP source port from inner headers to provide entropy for outer-header ECMP. Actual path use depends on the hash, mapping and traffic.', 'A recommendation is not a universal implementation requirement or balanced-path guarantee.')
q(n,8,['options',1,'text'],'New-flow forwarding depends on the overloaded controller path, so first packets can queue or be dropped and may need retransmission','Prompt does not restrict traffic to TCP SYNs or guarantee every new flow waits exactly one RTT.')
q(n,8,['options',0,'explanation'],'Existing-rule forwarding continues while telemetry identifies packet-in queuing and flow-installation delay. This points to the reactive control path; it does not certify all forwarding hardware capacity.','Do not infer complete capacity validation from some covered traffic continuing.')
q(n,12,['options',0,'explanation'],'A can send packets to C before its entry exists. Under the supplied drop-on-miss policy those packets are dropped, creating a temporary black hole.','Remove controller fallback explicitly excluded by prompt.')
qr(n,12,['workedExample'],'Install C → D and confirm processing using the appropriate barrier/acknowledgment mechanism.','Install C → D and confirm successful installation, checking errors and the appropriate barrier/acknowledgment mechanism.','OpenFlow barrier completion alone is not successful flow installation: preceding errors must be checked.')
coverage(n)
d=json.loads(report.read_text())
for u in ['https://opennetworking.org/wp-content/uploads/2014/10/openflow-switch-v1.3.5.pdf','https://docs.aws.amazon.com/vpc/latest/userguide/subnet-sizing.html','https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html','https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html','https://www.rfc-editor.org/rfc/rfc7348','https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-basics.html','https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html','https://research.google/pubs/b4-experience-with-a-globally-deployed-software-defined-wan/','https://people.eecs.berkeley.edu/~sylvia/papers/el-fares.pdf']:
 d['sources'].append({'url':u,'scope':'SDN/OpenFlow1.3.5/AWS/VXLAN primary checks; last paper independently closes data-centre fat-tree count.'})
d['status']='Independent full semantic review complete for first four pairs: 4 lessons, 48 questions. Debugging/internet structure pending.'
d['resume']='Read debugging and internet-structure pairs, primary-source close, rerun harness, write independent verification and scoped check.'
report.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
