exec(open('/tmp/network04-helper.py').read());n='app-p2p-webrtc'
def u(i,p,v):q(n,i,p,v,'Make assessment conditions explicit and remove unsupported guarantees.')
def o(i,j,k,v):u(i,['options',j,k],v)
def rep(i,p,a,b):qr(n,i,p,a,b,'Make assessment conditions explicit and remove unsupported guarantees.')
rep(3,['workedExample'],'So packets carry timestamps 0, 960, 1920... while sequence numbers go 0, 1, 2...','With illustrative zero initial values, timestamps would be 0, 960, 1920... and sequences 0, 1, 2...; actual initial values are randomised and wrap modulo their field widths.')
u(3,['link'],{'title':'RFC 7587: RTP Payload Format for Opus','url':'https://www.rfc-editor.org/rfc/rfc7587'})
rep(4,['prompt'],'A BitTorrent client','A BitTorrent v1 client with trusted metainfo')
o(4,1,'explanation','Given the trusted metainfo in the prompt, a tracker is not a replacement source of piece hashes. A mismatch means these bytes cannot be accepted as the expected piece.')
rep(4,['workedExample'],'If one peer supplied all bad blocks, ban it.','Apply a cautious peer-reputation policy. A mixed-source piece mismatch alone cannot identify the bad contributor; even a sole supplier does not prove deliberate malice.')
o(5,2,'explanation','The tracker role supplies peer lists, rather than the initial data piece. A machine could separately run a seeding service.')
o(5,3,'text','Optimistic unchoking gives a peer an upload opportunity without requiring a prior contribution')
o(5,3,'explanation','In the classic BEP 3 policy an optimistic slot rotates on a 30-second cadence, with bias towards new connections. This creates an opportunity, not a guarantee of rapid completion.')
u(5,['workedExample'],'BEP 3 describes changing choking decisions every ten seconds and rotating an optimistic unchoke every thirty. If that optimistic peer is interested, it counts within the four allowed interested downloaders. New connections are favoured in selection. This lets a newcomer obtain something to trade; seeders and modern client policies may behave differently.')
u(6,['prompt'],'Two WebRTC peers are on different private networks with endpoint-dependent NAT mappings. ICE direct host and server-reflexive checks have failed, but a valid TURN relay path succeeds. Which candidate pair can be selected?')
o(6,0,'explanation','The stated successful relay path supplies connectivity after these direct checks failed. TURN is not guaranteed to work on every network.')
o(6,1,'explanation','Priority cannot make a failed path usable; this prompt explicitly says the direct host checks failed.')
o(6,2,'explanation','The prompt says those checks failed. Endpoint-dependent mappings can make a STUN-observed address unsuitable for another destination, but NAT labels alone do not prove universal failure.')
u(6,['workedExample'],'ICE evaluates actual reachability. In this scenario, direct checks fail and a relay-involving pair succeeds, so the controlling agent can nominate that valid pair. Depending on the selected pair, one or both peers use a TURN allocation. Relay transport must itself be allowed by the network; media traffic consumes relay bandwidth.')
rep(7,['prompt'],'how much does each participant upload?','ignoring protocol overhead and retransmissions, how much does each participant upload?')
u(7,['workedExample'],'Mesh: (6−1) × 1.2 = 6.0 Mbit/s per client. With one nonsimulcast upstream to an SFU: 1.2 Mbit/s. If all five other streams are forwarded at full rate, download is 6.0 Mbit/s in either topology. Selective forwarding or different encodings change the download; overhead and retransmissions add traffic.')
o(8,4,'text','Ordinary per-hop DTLS-SRTP alone prevents an SFU that terminates those sessions from reading the media content')
o(8,4,'explanation','False. That SFU has the per-hop media keys. Additional end-to-end content encryption such as SFrame can keep payload content hidden from it.')
rep(8,['workedExample'],'certificate is self-signed.','the certificate may be self-signed.')
rep(8,['workedExample'],'So trust reduces to the signalling channel: tamper with SDP → MITM.','Without independent identity verification, substituted signalling fingerprints can enable an active intermediary; a passive TURN relay does not automatically obtain the media keys.')
rep(9,['options',3,'explanation'],'(one second at the 90 kHz video clock).','(90,000 ticks, corresponding to a one-second interval if the negotiated clock is 90 kHz).')
u(9,['workedExample'],'Byte 0x80 gives V=2, P=0, X=0, CC=0. Byte 0xe0 gives M=1 and PT=96. Big-endian sequence 0x0005 is 5; timestamp 0x00015f90 is 90,000; SSRC is 0x12345678.\n\nPT 96 is dynamically mapped; the header alone does not identify the codec or clock rate. A difference of 90,000 ticks means one second at 90 kHz, but this absolute timestamp does not show elapsed stream time without a reference. Marker semantics depend on the negotiated payload format.')
o(10,1,'text','Exponentially sized distance buckets support logarithmic lookup scaling when routing and ID-distribution assumptions hold')
o(10,1,'explanation','The model supports progress through ID prefixes. This is not a promise that every response halves numeric XOR distance or that failed nodes and adversaries cannot disrupt a lookup.')
o(10,2,'text','Parallel queries reduce dependence on one slow or dead contact')
o(10,2,'explanation','Concurrency, such as the paper\'s example α=3, can overlap delays. It does not eliminate all timeouts or guarantee a result.')
u(10,['workedExample'],'XOR symmetry allows incoming messages to teach useful contacts. Maintained distance buckets support prefix progress under the model\'s assumptions. Parallel queries overlap delays, while responsive old contacts are retained rather than automatically replaced by newcomers. If a round finds no closer node, original Kademlia still queries remaining closest candidates before terminating. Actual latency, success and churn behaviour depend on the network; no current typical round count is assumed.')
rep(11,['prompt'],'A sender\'s RTCP sender report left at NTP time T.','Using seconds for this arithmetic example rather than the compact wire representation, a sender\'s RTCP sender report left at time T.')
rep(11,['workedExample'],'It\'s the same idea as NTP\'s delay calculation.','This assumes stable rates and no intervening clock step. On the wire LSR/A use compact NTP fields, DLSR uses 1/65536-second units, and subtraction must handle wraparound.')
coverage(n)
