exec(open('/tmp/network06-helper.py').read());n='wm-datacentre'
md(n,'Why data centres replaced tree networks with Clos fabrics','Why many data centres use Clos fabrics','Avoid implying all facilities replaced one topology.')
md(n,'a tree that funnels everything up to a big core router','a hierarchy that funnels traffic between aggregation branches through a core','Same-branch traffic need not traverse core.')
md(n,'Choosing per *packet* would reorder TCP segments','Choosing per *packet* can reorder TCP segments','Path variation can reorder, not inevitably.')
md(n,'Hashing balances well when there are thousands of small flows.','With well-distributed keys and enough similarly sized flows, hashing can spread load approximately evenly.','Flow count alone does not guarantee byte balance.')
md(n,'If every tier uses the same hash function and fields, the flows that went "left" at one tier all hash the same way at the next tier too, and some links get nothing. Switches seed their hash differently to avoid this.','Correlated hash choices across tiers can underuse some paths, especially with matching path counts and mappings. Different hash seeds or inputs can reduce this polarisation.','Topology and mappings determine polarisation; distinct seeds are a mitigation, not universal guarantee.')
md(n,'**DCTCP** uses ECN marks from switches to reduce the sending rate in proportion to congestion, keeping queues short','**DCTCP** estimates the fraction of marked bytes and adjusts its congestion window proportionally, aiming to keep queues short','RFC8257 alpha estimates marking fraction; low queues not guaranteed.')
q(n,2,['options',0,'explanation'],'Implementation costs vary; the transport-ordering concern explains this policy without assuming one mechanism is always cheaper.','No supplied ASIC evidence for universal cost equivalence.')
q(n,2,['options',1,'text'],"Per-packet choice can deliver a TCP connection's segments out of order across paths of different delay, potentially triggering spurious loss recovery",'Align conditional reordering claim with explanation.')
q(n,6,['options',0,'explanation'],'The stipulated uniform independent hash does not account for current link load. Two flows can choose the same path.','Restrict load-blindness to specified selector, not all ECMP implementations.')
q(n,7,['workedExample'],'A hierarchy can concentrate inter-branch traffic on core links, and STP can block redundant forwarding paths for an instance. A fully connected two-tier routed fabric provides a path through each spine between distinct leaves. ECMP can use multiple eligible paths; port limits, routing configuration, hashing and finite capacity still constrain traffic.','Avoid every cross-rack path reaching core and guaranteed use of all paths.')
q(n,8,['options',0,'explanation'],'An appropriately configured resilient-hashing implementation can preserve healthy assignments on removal. Simple modulo hashing does not; resilient implementations also have bucket and rebalancing policies.','Not every resilient implementation guarantees exactly only failed flows move.')
q(n,11,['options',2,'explanation'],'Spraying packets across members that lack compatible connection state can disrupt handling, rather than preserve flow affinity. The outcome depends on which members receive packets and what state is available.','Remove every-connection universal claim.')
q(n,11,['options',3,'explanation'],'With two equal members, one failure removes half the nominal capacity and forces its flows elsewhere. The remaining member still lacks the failed member’s state; reducing member count does not solve that issue.','For mod2→mod1, healthy-member flows do not remap; original generalized rehash implication misleading.')
coverage(n)
d=json.loads(report.read_text())
for u in ['https://datatracker.ietf.org/doc/html/rfc7938','https://www.rfc-editor.org/rfc/rfc2992','https://www.rfc-editor.org/rfc/rfc8257','https://engineering.fb.com/2014/11/14/production-engineering/introducing-data-center-fabric-the-next-generation-facebook-data-center-network/','https://research.google/pubs/jupiter-rising-a-decade-of-clos-topologies-and-centralized-control-in-googles-datacenter-network/','https://research.google/pubs/maglev-a-fast-and-reliable-software-network-load-balancer/','https://docs.kernel.org/networking/ip-sysctl.html']:
 d['sources'].append({'url':u,'scope':'Data-centre primary topology/hash/congestion and documented historical deployment checks; arithmetic verified separately.'})
d['status']='Independent full semantic review complete for Wi-Fi, cellular and data-centre: 3 lessons, 36 questions. SDN lesson read; its quiz and remaining pairs pending.'
d['resume']='Finish primary closure fat-tree source; read SDN quiz and check OpenFlow/AWS; then debugging and internet-structure.'
report.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
