exec(open('/tmp/network06-helper.py').read());n='wm-internet-structure'
md(n,'It is tens of thousands of independently run networks that have agreed to exchange traffic','It comprises independently administered networks exchanging traffic under their routing policies','Remove undated count inconsistent with evidence-limits paragraph.')
md(n,'One port reaches hundreds of peers, instead of one cable per peer.','A shared-fabric port can reach many willing peers, subject to membership and policy, instead of needing a separate physical link for each.', 'IXP size and peering agreements vary.')
md(n,'Repair ships must sail out, grapple the cable up and splice it','A marine repair may require a ship to recover the cable and splice it', 'Recovery method varies; not every repair uses grappling or identical sequence.')
md(n,'VDSL2 from a street cabinet (FTTC) is fast only over short copper runs, which is why speeds vary street by street.','VDSL2 rates depend on copper length, line quality, profile and interference; shorter runs can support higher rates.', 'Fast has no defined cutoff; remove absolute distance threshold.')
q(n,1,['options',1,'explanation'],'In this scenario the broad onward-reachability service is transit; the limited neighbour exchange is peering. Actual reachability remains subject to policy and failures.','Avoid universal every-address transit guarantee.')
q(n,1,['options',2,'explanation'],'Correct. The paid broad-reachability service is transit. The agreed exchange of the neighbours’ own/customer traffic has no traffic settlement payment, so it is settlement-free peering.','Do not generalize unpaid prevalence from a supplied example.')
q(n,7,['options',1,'explanation'],'The downstream optical channel is shared: the OLT sends a common downstream stream carrying traffic for multiple ONTs. Subscriber allocations and filtering determine their delivered data; each home does not receive a dedicated 10 Gbit/s channel.','Downstream is broadcast from OLT, not homes contending or taking upstream-style turns.')
q(n,8,['options',1,'explanation'],'QUIC can reduce setup exchanges in suitable cases, but it does not shorten the specified physical path. Each remaining exchange still incurs that path’s propagation delay.','Unsupported200ms specific estimate absent from prompt removed.')
q(n,9,['options',0,'explanation'],'An up step after a peering link violates the stated valley-free model. A route learned by P2 from a provider would not be exported to peer P1; moreover the assumed Tier 1 P2 has no transit provider.','Original explanation reversed where P2 learns destination route.')
q(n,10,['options',1,'explanation'],'The prompt gives the /22 a shorter AS path at this router. AS-path comparison between these distinct prefixes does not override longest-prefix forwarding once both are installed.','Remove stale reference to historical real-site/many-network scenario.')
coverage(n)
d=json.loads(report.read_text())
for u in ['https://www.iscpc.org/publications/icpc-viewpoints/charting-submarine-cables-is-critical-for-maritime-safety-and-infrastructure-protection/','https://cloud.google.com/blog/products/infrastructure/googles-dunant-subsea-cable-is-now-ready-for-service','https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits','https://www.itu.int/rec/T-REC-G.984.2','https://www.itu.int/rec/T-REC-G.9807.1','https://docs.de-cix.net/article/n3i1zu0abx-how-to-implement-peering-services','https://openconnect.netflix.com/en/','https://www.rfc-editor.org/rfc/rfc7454','https://www.ripe.net/about-us/news/youtube-hijacking-a-ripe-ncc-ris-case-study/','https://blog.cloudflare.com/how-verizon-and-a-bgp-optimizer-knocked-large-parts-of-the-internet-offline-today/']:
 d['sources'].append({'url':u,'scope':'Internet structure primary checks; Dunant and RIPE available search extracts with full-page timeout; ITU detailed rate-table closure tracked separately.'})
d['status']='All6lessons and72completequestionrecords independently full-read and corrected; final source closure and stamp pending.'
d['resume']='Finish ITU detailed line rates, P4 capability source and Reno coefficient; record test/stamp/check. Root harness independent rerun PASS25966 all5Pythonfences including real offline TLS.'
d['tests'].append({'scope':'All five actual lesson Python fences','command':'docker run --rm --network none -v /Users/alfiegormley/Github/cs-study-app:/work:ro -v /tmp/cs-study-audit-2026-10-04:/audit:ro --entrypoint python3 law-blog-security-audit:latest /audit/check-network06.py /work','result':'Independent rerun PASS25966assertions including exact outputs, random interval-union/ECMP/subnet/propagation models and real offline trusted TLS handshake plus hostname rejection. No radio/WAN/cloud hardware tests.'})
report.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
