exec(open('/tmp/network06-helper.py').read())
n='wm-cellular'
md(n,"why the radio's power states dominate latency and battery", "how the radio's power states affect latency and battery use",'Do not assert a universal dominant contribution without a measured workload.')
md(n,'## The radio: scheduled, not contended','## Scheduled radio access','Random access still involves contention, as the lesson explains.')
md(n,"## The radio's power states: the thing apps feel most","## Radio power states and application traffic",'Remove unsupported ranking of application effects.')
md(n,'Keeping the radio active is one of the biggest power costs on a phone. So the radio has states, controlled by **RRC** (Radio Resource Control):','Radio activity can contribute substantially to energy use, depending on the device and workload. **RRC** (Radio Resource Control) manages connection states:', 'Qualify energy claim; RRC connection states are not literal power levels.')
md(n,'The first packet after a quiet period must wait for the phone to move from idle to connected: random access, RRC setup and security signalling.','When ordinary user-plane transfer requires an idle UE to establish an RRC connection, random access, RRC setup and associated signalling add delay. A quiet period alone does not establish that this transition is required.', 'Remove universal promotion requirement contradicted by retained contexts and inactive-state features.')
md(n,'base stations buffer generously to avoid loss over the radio, so latency under load can climb to hundreds of ms (bufferbloat).','large persistent queues on a mobile path can add substantial latency under load (bufferbloat); measure the location and size rather than assuming a particular base station buffer.', 'Avoid unsupported universal deployment behaviour and numerical range.')
q(n,1,['options',3,'explanation'],'Requesting uplink resources does not itself require allocating a new IP address; IP-session establishment is a separate procedure.','RRC-connected status alone does not prove an IP address was allocated during attach.')
q(n,2,['options',0,'explanation'],'A handover changes the serving radio resources and can occur between cells of the same base station. Session anchoring and path updates, rather than an assumed base-station address assignment, explain the retained address.','Intra-base-station handover invalidates every-handover node-change claim.')
q(n,2,['options',3,'explanation'],'SIM credentials support subscriber identification and authentication. A fixed address stored on the SIM is not the session anchoring and path-update mechanism described here.','Avoid an unnecessary universal prohibition on all SIM data.')
q(n,3,['options',3,'explanation'],'Link adaptation can depend on channel estimates and scheduler policy. The supplied trace specifically establishes RRC setup; it does not establish a special first-packet modulation rule.','Channel state/history can influence initial link adaptation.')
q(n,7,['options',2,'explanation'],'Correct. Expiration can disrupt an idle connection. Later traffic may be dropped, rejected or create another mapping, depending on the NAT and packet; continued TCP connectivity is not assured.','No universal later-packet discard after expiration.')
q(n,9,['options',3,'explanation'],'NAT64 is not restricted to port 443. Reachability still depends on supported protocols, mappings and policy; here the raw socket lacks a usable translated path.','Avoid claiming every port is necessarily translated.')
q(n,10,['options',3,'explanation'],'Keepalives can help detect some failures, but cannot migrate ordinary TCP across an endpoint-address change. Frequent probes add traffic and may increase energy use.','Energy cost is workload dependent and keepalive detection is conditional.')
q(n,11,['options',0,'explanation'],'The observation does not establish a handover. A few additional kilometres of propagation alone cannot explain hundreds of milliseconds; scheduling, retransmissions, queues and other path effects need investigation.','Do not categorically exclude load-related mobility decisions.')
coverage(n)
d=json.loads(report.read_text())
for u in ['https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-M.2410-2017-PDF-E.pdf','https://www.etsi.org/deliver/etsi_ts/138200_138299/138211/17.06.00_60/ts_138211v170600p.pdf','https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/17.09.00_60/ts_123501v170900p.pdf','https://developer.apple.com/support/ipv6/','https://developer.android.com/develop/connectivity/network-ops/network-access-optimization','https://www.rfc-editor.org/rfc/rfc6877']:
 d['sources'].append({'url':u,'scope':'Cellular primary verification: IMT evaluation conditions, NR resource blocks and slot numerology, 5GC address allocation and inactive state, platform radio and IPv6 translation behaviour. Not a complete clause audit.'})
d['status']='Independent full semantic review complete for Wi-Fi and cellular: 2 lessons, 24 questions. Four pairs remain unread.'
d['resume']='Next wm-datacentre full pair, then SDN/debugging/internet structure; execute root model harness before final stamp.'
report.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
