from pathlib import Path
import json
B=Path('content/theory/05-computability');p=B/'compu-reductions-rice.md';s=p.read_text()
def r(a,b):
 global s
 assert a in s,a
 s=s.replace(a,b)
r('It explains why static analysers, type checkers and malware scanners must all approximate.', 'It limits exact, terminating analysis of non-trivial extensional properties for arbitrary programs. This does not mean every analysis task or formal type-checking judgement is undecidable.')
r('which tells you nothing about B.', 'which alone does not prove B undecidable.')
r('It does not have to solve anything: it just rewrites the question.', 'It need not decide A or B: it translates instances. It may perform arbitrary terminating computation, not only textual rewriting.')
r('Useful properties, all following from the definition:', 'The machine examples below describe well-formed encodings. To make each map total on all strings, detect malformed encodings and send them to a fixed no-instance of the target, taking malformed strings as non-members of the source. Complement arguments use complements in that same universe.\n\nUseful properties, all following from the definition:')
r('  otherwise: reject (or loop)', '  if M rejects w: reject\n  # If M loops, the simulation loops.')
r('Undecidable (semantic, non-trivial), for arbitrary programs:\n\n- Does it ever print "hello"? Does it ever divide by zero, or dereference null?\n- Does it return 0 on every input? Does it accept a regular language?\n- Is it equivalent to this reference implementation, or this specification?\n- Is it malware (does it ever do anything in a given malicious set)?', 'For the language version stated here, examples include:\n\n- Does M accept the fixed string `hello`?\n- Is L(M) regular, finite or empty?\n- Is L(M) equal to a fixed recognisable reference language?\n\nEach property depends only on L(M), and some TMs have it while others do not. A corresponding partial-function version of Rice covers non-trivial properties of the computed function, such as returning 0 on every input.\n\nPrinting, division by zero and null dereferences are **not automatically properties of the recognised language**: two machines can accept the same language but differ in these events. Event reachability is also undecidable in general when the model can simulate an arbitrary TM and trigger the event only after it halts. That is a separate reduction, or can be phrased using an instrumented recogniser. A vague label such as "malware" needs a precise non-trivial property before any theorem applies.')
r('Rice says no analyser can be all three of:', 'For these non-trivial extensional properties of arbitrary programs, Rice says no analyser can be all three of:')
r('A type checker is the everyday example. Java rejects `int x = flag ? 1 : "a";` even if `flag` is always true at runtime. That conservative rejection of some safe programs is the price of a decidable, sound check. **Abstract interpretation** (Cousot and Cousot, 1977) is the general theory of computing such sound approximations.', 'Java rejects `int x = flag ? 1 : "a";` even if `flag` is always true: the reference conditional expression must satisfy the target assignment type for both branches, and the string branch is not compatible with `int`. This is a particular language rule, not a restriction uniquely forced by Rice. A different sound language could accept some statically known constant-branch cases.\n\nA terminating type checker can decide a formal typing judgement exactly. The harder question is whether arbitrary programs in a model that permits runtime type faults can ever reach such a fault. In a sufficiently expressive model this is undecidable by a reachability reduction, so an always-terminating sound safety analyser must be conservative. Languages that exclude an error by construction need separate treatment. **Abstract interpretation** (Cousot and Cousot, 1977) provides a framework for sound approximation.')
r('is there a sequence whose top and bottom concatenations match?', 'is there a non-empty finite sequence of dominoes, allowing repetitions, whose top and bottom concatenations match?')
r('**Type inference for System F** (polymorphic λ-calculus) is undecidable (Wells, 1994), which is why Haskell and OCaml use restricted forms of polymorphism or require annotations.', '**Typability and type checking for Curry-style System F**, where pure λ-terms lack explicit type annotations, are undecidable (Wells, 1994). This must not be confused with decidable checking of fully annotated Church-style System F. Practical languages use restricted inference and/or annotations, with details depending on their type systems.')
r('**f must be computable and total, but need not run M.** The reduction builds M′; it never simulates M (which might loop).', '**f must be computable and total.** These reductions construct M′ without running an unbounded simulation of M. Other reductions may use bounded simulation or other terminating computations; "never run a machine" is not a general rule.')
r('- Reductions build new machines from old ones; they never run them. A_TM ≤m HALT_TM, and E_TM and EQ_TM are undecidable; EQ_TM is neither recognisable nor co-recognisable.', '- The constructions here emit new machines without waiting for M to halt. A_TM ≤m HALT_TM; E_TM is undecidable, and EQ_TM is neither recognisable nor co-recognisable.')
r('- Real analysers trade soundness, completeness or automation: that is why type checkers reject some safe programs and linters miss some bugs.', '- Exact total analysis of an undecidable property is impossible on all inputs. Particular instances, restricted languages and formal type judgements may still be decidable.')
s+='\n- [Wells, LICS 1994: Curry-style System F](https://lics.siglog.org/archive/1994/Wells-Typabilityandtypech.html)\n- [Java Language Specification: conditional operator](https://docs.oracle.com/javase/specs/jls/se25/html/jls-15.html#jls-15.25)\n'
p.write_text(s)
p=B/'compu-reductions-rice.questions.json';qs=json.loads(p.read_text());q={str(i+1):v for i,v in enumerate(qs)}
q['2']['prompt']='Which question about an arbitrary TM is undecidable by the language version of Rice\'s theorem?'
q['2']['options'][0]['text']='Does its recognised language contain the fixed string "hello"?'
q['2']['options'][0]['explanation']='Correct. This depends only on L(M), and some machines accept hello while others do not.'
q['2']['options'][1]['text']='Does its encoding contain more than 100 symbols?'
q['2']['options'][1]['explanation']='A finite string-length check decides this structural property.'
q['2']['options'][3]['text']='Does its transition table contain more than five states?'
q['2']['options'][3]['explanation']='Count the states in the finite description. This is structural, not a property of L(M).'
q['2']['workedExample']='Rice requires a property that is invariant under equality of recognised languages and non-trivial among TMs. Accepting hello meets both tests. Description size and number of states do not depend only on L(M). A fixed simulation bound is decidable. Printing hello is a different event-reachability question and needs an explicit reduction or an instrumented model.'
q['8']['prompt']='Why can Java reject `int x = flag ? 1 : "a";` even if flag is always true at runtime?'
q['8']['options'][0]['text']='Its conditional-expression and assignment rules require the string branch to be compatible with the int target; formal type checking need not decide exact runtime reachability'
q['8']['options'][0]['explanation']='Correct. This particular rule rejects the expression. A checker can decide its formal typing rules exactly while conservatively approximating runtime safety.'
q['8']['options'][1]['explanation']='The rejection follows the Java language rules. Undecidability does not force every language to use this exact rule.'
q['8']['options'][2]['explanation']='This rejection follows static typing rules, not a failed attempt to execute the program. Some language implementations do evaluate expressions at compile time, so "type checkers never run code" is too broad.'
q['8']['options'][3]['explanation']='The rejection also occurs for a constant true condition: the string alternative is incompatible with an int target under these rules.'
q['8']['workedExample']='1. The conditional combines int and String alternatives.\n2. In this assignment context, Java checks branch compatibility with the int target; String is not compatible.\n3. A formal type checker can decide those language rules exactly.\n4. Deciding whether arbitrary programs in a sufficiently expressive unsafe model can reach a runtime fault is a different, generally undecidable question.\n5. A sound total safety analysis must then be conservative, but Rice does not dictate Java\'s particular conditional-expression rule.'
q['8']['link']={'title':'Java Language Specification: conditional operator','url':'https://docs.oracle.com/javase/specs/jls/se25/html/jls-15.html#jls-15.25'}
q['9']['options'][3]['explanation']='This proposed reduction does not supply the required lower bound. In fact it cannot exist: E_TM is co-recognisable, so it would make EQ_TM co-recognisable, contrary to the second proof.'
q['10']['workedExample']=q['10']['workedExample'].replace('Rule of thumb: whatever is *impossible* for the left side is impossible for the right side.', 'Here recognisability transfers backwards along a computable mapping reduction. This is not a blanket statement about efficiency: no running-time bound on f was required.')
q['12']['options'][0]['explanation']='Correct. After conversion to suitable Chomsky normal form, CYK decides membership; its cubic bound in input length assumes a fixed grammar, with grammar-size and conversion costs otherwise included.'
q['12']['workedExample']=q['12']['workedExample'].replace("the complement of 'is a valid TM computation history' is context-free", 'a CFG can recognise invalid encodings of accepting computation histories for a fixed machine and input').replace("The pattern: questions about one string are usually decidable; questions about whole languages of powerful models usually aren't.", 'The model and question both matter: CFG membership is decidable, but whether an arbitrary TM accepts even a fixed word is undecidable. Do not infer decidability merely from asking about one string.')
p.write_text(json.dumps(qs,ensure_ascii=False,indent=2)+'\n')
print('Rice corrections applied')
