exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-theory-automata.json');report={'date':'2026-10-05','status':'In progress; first three pairs corrected; five lesson bodies and four quiz files read.','reviewed_files':[],'findings':[],'limitations':['Execution and independent verification pending.']};findings=report['findings'];b='content/theory/04-automata/'
src=['https://swtch.com/~rsc/regexp/regexp1.html','https://swtch.com/~rsc/regexp/regexp2.html','https://westes.github.io/flex/manual/Performance.html','https://github.com/google/re2','https://github.com/google/re2/wiki/Syntax','https://docs.rs/regex/latest/regex/','https://pkg.go.dev/regexp','https://www.pcre.org/current/doc/html/pcre2matching.html']
patch(b+'auto-dfa.md',[
('A vending machine does not remember your whole history of coins. It remembers one thing: how much credit you have right now. A traffic light does not know what happened yesterday, only which phase it is in.', 'A simplified vending-machine controller can track bounded credit, and a simplified traffic light can track its current phase. Real controllers may also track timers, sensors and historical data.'),
('        q = delta.get((q, c))\n        if q is None:\n            return False   # no move: reject', '        if (q, c) not in delta:\n            return False   # no move: reject\n        q = delta[(q, c)]'),
('with O(1) work per symbol and **constant memory** regardless of input length.', 'for a fixed machine with constant-time transition lookup, using constant auxiliary state storage beyond the stored machine and input.'),
('"Even number of 1s **and** divisible by 3" has 2 × 3 = 6 states. The shortest non-empty strings it accepts are `11` (3), `110` (6), `1001` (9) and `1100` (12).', 'The product for even parity and divisibility by 3 has 2 × 3 = 6 states before minimisation. It accepts 0 and other all-zero strings; positive-value examples without leading zeroes include 11 (3), 110 (6), 1001 (9) and 1100 (12).'),
('Tools such as lex and flex compile token regexes into one DFA, which is why lexing is linear time.', 'Tools such as lex and flex compile token patterns to automata. One DFA membership scan is linear; longest-match tokenization, backup, rescanning and actions need separate complexity analysis.'),
('**Regex engines** such as RE2, Rust\'s `regex` and GNU grep build DFAs (often lazily, a state at a time) to scan text in linear time.', '**Regex engines** such as RE2 and Rust\'s regex can combine DFA and NFA strategies; supported searches have input-linear bounds for a fixed pattern. GNU grep also uses other strategies depending on pattern and mode.'),
('Every sequential circuit with a finite number of flip-flops is a finite-state machine.', 'A synchronous digital circuit with bounded discrete internal state can be modelled as a finite-state machine; this abstraction omits analog timing effects.'),
('membership is always O(n) time and O(1) space', 'a fixed-machine membership scan takes O(n) transitions and O(1) auxiliary space'),
('remainder mod k needs k.', 'the remainder construction uses k states but can sometimes be minimised further.')], 'Fix zero-string examples, general-state simulator, lexer complexity and remainder minimality claims.',src)
def dfa(q):
 q[0]['options'][3]['explanation']='This DFA tracks parity directly. DFAs can count up to a fixed bound or modulo a constant; they cannot maintain an unbounded exact counter.'
 q[2]['options'][1]['explanation']='One transition per symbol, with a stored transition table and only one current state; auxiliary memory is independent of input length for this fixed machine.'
 q[3]['options'][0]['explanation']='Two states cannot separate all four prefix classes. For example, suffixes completing a multiple of four distinguish ε, a, aa and aaa pairwise.'
 q[7]['prompt']=q[7]['prompt'].replace('c.isdigit()', 'c in "0123456789"')
 q[9]['options'][2]['explanation']='There are three distinguishable situations: accepting remainder0, remainder2, and odd remainder. ε separates0 from the others; suffix0 separates2 from an odd remainder.'
 q[11]['prompt']='A bracket validator accepts exactly balanced strings of ( and ) with nesting depth at most 3, such as (()(())), and rejects strings that exceed that depth. How many states does a minimal complete DFA need?'
questions(b+'auto-dfa.questions.json',dfa,'Correct ASCII digit classification, two-state distractor reasoning and misleading HTML sanitizer framing.',src)
patch(b+'auto-nfa.md',[
('The second view gives the simulation: keep the **set of states** the machine could currently be in.', 'For efficient simulation, merge all copies at the same state and input position: keep the set of possible states, rather than one clone per path.'),
('giving O(n · (m + e)) time', 'giving O((n + 1) · (m + e)) time including the initial closure'),
('Ken Thompson\'s 1968 regex search algorithm, used in the QED editor, worked this way, and RE2 and Go\'s `regexp` still do.', 'Thompson\'s algorithm tracks reachable states; modern RE2 and Go regexp use related automaton techniques alongside other optimizations.'),
('In practice most NFAs from real regexes determinise to a modest number of states, but engines', 'Full determinisation can be manageable for a given workload, but engines'),
('O(n · (m + e)) time, or O(n · m) for bounded out-degree.', 'O((n + 1)·(m + e)) time including initialization, or O((n + 1)·m) for bounded out-degree.')], 'Count initial closure, distinguish merged-state simulation from path cloning and remove unsupported typical-size prevalence.',src)
def nfa(q):
 q[6]['prompt']=q[6]['prompt'].replace('what does this print?', 'with delta containing exactly the pictured transitions and acc = {"p0", "r0"}, what does this print?')
 q[7]['workedExample']=q[7]['workedExample'].replace('≈ 2 × 10⁸ basic operations in the worst case.', 'has scale m·n = 2 × 10⁸ state visits, with implementation-dependent constant factors; this is not an exact operation count or timing measurement.')
 q[10]['options'][1]['text']='A transition already in the cache can be followed by a table lookup'
 q[10]['options'][1]['explanation']='True for the assumed table-based cache. The cache hit rate depends on the pattern, input and memory budget; no universal typical-hit-rate measurement is implied.'
 q[10]['prompt']+=' Assume expected constant-time cache lookup, O(m) work per uncached transition and bounded bookkeeping per step; only this single search is being analysed.'
 q[10]['workedExample']=q[10]['workedExample'].replace('and the common case is close to O(n).', 'under the stated implementation assumptions. If most transitions are cached, most input steps use a lookup.')
questions(b+'auto-nfa.questions.json',nfa,'Supply epsilon-NFA fixture assumptions and qualify exact operation counts/cache cost model.',src)
patch(b+'auto-thompson.md',[
('You type `(a|b)*abb` into grep and it scans a gigabyte in a second.', 'A tool such as grep -E can compile (a|b)*abb and scan input using the resulting matcher. Throughput depends on the tool, data, hardware and I/O.'),
('`.` is the union of every symbol in the alphabet.', 'In a formal wildcard notation, . can denote the union of the alphabet. Real regex engines commonly exclude newline unless a dot-all option is enabled.'),
('Backreferences like `(a+)\\1` are **not** shorthand for anything here. They take the language outside the regular languages entirely, which is why automaton-based engines refuse them (lesson 6).', 'General backreferences can express non-regular languages, such as (a+)b\\1 matching aⁿbaⁿ for n ≥ 1. Some individual backreference patterns are still regular: (a+)\\1 matches positive even-length runs of a, equivalent to (aa)+. Engines such as RE2 reject the feature syntactically rather than proving regularity separately for each pattern.'),
('```python\nfrom collections import defaultdict', 'This compact compiler accepts validated postfix expressions of literal characters and the operators ., | and *. It omits parsing, escaping, character classes and explicit ε/∅ tokens. Its global state accumulates across calls; reset delta and n before comparing independent machine sizes.\n\n```python\nfrom collections import defaultdict'),
('    return st.pop()\n\nstart, acc', '    if len(st) != 1:\n        raise ValueError("invalid postfix")\n    return st.pop()\n\nstart, acc'),
('Checked against Python\'s `re.fullmatch` on every string over {a, b} up to length 10, the two agree.', 'The audit compares this NFA with re.fullmatch on all strings over {a, b} up to length 10; that finite check supports the example but is not the general equivalence proof.'),
('GNU grep also matches with a DFA, built lazily, though it constructs it with the position-based method mentioned below rather than via Thompson\'s NFA.', 'GNU grep may select DFA, literal-search or other matching strategies depending on options and pattern features.'),
('Naive backtracking does not, which is part of the ReDoS story in lesson 6.', 'A naive recursive backtracker without a zero-progress guard may loop; practical engines commonly detect empty repetitions, although other patterns can still cause excessive backtracking.'),
('- Formal regexes have three operators (union, concatenation, star) over ∅, ε and single symbols; the rest is shorthand.', '- Formal regexes use union, concatenation and star over ∅, ε and single symbols. Many practical features are shorthand, while general backreferences add expressive power.')], 'Remove throughput claim, correct regular backreference counterexample, scope builder grammar/global state and distinguish practical empty-loop guards.',src)
def thompson(q):
 q[1]['workedExample']=q[1]['workedExample'].replace('Running the Python', 'After resetting delta and n, running the Python')
 q[4]['prompt']+=' Here ε is formal empty-string notation, not a literal engine character.'
 q[4]['workedExample']=q[4]['workedExample'].replace('so only rows with "no" for ε and "yes" for aaa match. A brute-force check over a⁰ to a⁸ confirms it.', 'and the three equivalent expressions each describe exactly a positive run of a. These two test strings alone would not prove equivalence for an arbitrary regex; checking a⁰ through a⁸ is additional finite evidence.')
 q[8]['options'][0]['explanation']='The four two-symbol prefixes are pairwise distinguishable by ε or a one-symbol suffix; two states cannot represent all four classes.'
 q[9]['options'][2]['text']='General backreferences, including (a+)b\\1'
 q[9]['options'][2]['explanation']='No. This particular pattern describes aⁿbaⁿ for n ≥ 1, a non-regular language. By contrast (a+)\\1 alone is regular, equivalent to (aa)+; the feature is rejected by these engines regardless.'
 q[9]['workedExample']=q[9]['workedExample'].replace('Backreferences are the line between "regex" and "regular". RE2, Go and Rust refuse them for exactly this reason.', 'General backreferences exceed finite-automaton expressiveness, though some specific patterns using them remain regular. RE2, Go regexp and Rust regex reject the unsupported syntax rather than analyze such special cases.')
questions(b+'auto-thompson.questions.json',thompson,'Correct a quiz that classified the regular language (a+)backreference as non-regular, and scope finite equivalence tests.',src)
report['reviewed_files']=[b+n+s for n in ['auto-dfa','auto-nfa','auto-thompson','auto-pumping'] for s in ['.md','.questions.json']]+[b+'auto-minimisation.md']
report['omissions']=[{'lesson':'auto-thompson','claim':'One gigabyte per second grep throughput','reason':'No reproducible hardware/data benchmark supplied; replaced by a qualitative description.'}]
p_report.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
