from pathlib import Path
import json
p=Path('content/architecture/03-isa/isa-compile-link-load.md');s=p.read_text()
s=s.replace('It is really four separate programs, each producing a file the next one consumes,', 'It has preprocessing, compilation, assembly and linking stages (which need not be separate programs or materialized files),')
s=s.replace('why the first call to a library function is slower than the second,', 'why lazy binding can add work to a first library call,')
s=s.replace('A compiler sees one file at a time,', 'In ordinary separate compilation a compiler processes one translation unit at a time (link-time optimization can cross that boundary),')
s=s.replace('which take no space in the file', 'whose zero-filled payload occupies no file bytes; section metadata still exists')
s=s.replace('places in the code that must be patched', 'locations in code or data that may require fixups')
s=s.replace('The linker (`ld`, or faster drop-ins such as `gold`, `lld` and `mold`)', 'A linker such as GNU `ld`, `gold`, LLVM `lld` or `mold`')
s=s.replace('Match every undefined symbol to exactly one definition.', 'Resolve symbol references according to binding and visibility rules. Undefined weak symbols and dynamic imports are exceptions to a simple one-definition model.')
s=s.replace('Static archives (`libfoo.a`) are searched **in command-line order**', 'With traditional GNU ld archive processing, static archives (`libfoo.a`) are searched **in command-line order**')
s=s.replace('when the linker scanned `libm.a`, nothing needed it yet.', 'when that archive was first considered, the required reference had not yet appeared. Archive groups can cause repeated searches; other linkers such as LLD have different backward-reference handling.')
s=s.replace('That makes it self-contained and quick to start, but large,', 'This reduces dependencies on shared-library files for the linked code, but does not remove all runtime resources or guarantee faster startup or a larger final binary,')
s=s.replace('GNU_RELRO R      read-only after start', 'GNU_RELRO varies range to protect after relocation')
s=s.replace('Note that no segment is both writable and executable.', 'This schematic has no RWX load segment; actual linker output and permission flags vary. GNU_STACK describes stack policy, and GNU_RELRO identifies a range to protect rather than adding another independent mapping. Note that no LOAD entry shown is both writable and executable.')
s=s.replace('`DT_NEEDED` entries; see them with `ldd` or `readelf -d`', '`DT_NEEDED` entries; inspect them with `readelf -d`')
s=s.replace('One copy of libc\'s code sits in physical memory, shared by every process, and a libc update fixes every program at once.', 'Processes mapping the same unchanged library file can share its code pages. Replacing a library file normally benefits newly started processes; existing processes can retain the old mapping until restarted. ABI compatibility, containers and bundled copies also matter.')
s=s.replace('Shared libraries are compiled as', 'Shared libraries commonly use')
s=s.replace('For symbols in *other* modules, PIC goes through', 'For symbols requiring runtime address resolution, a common PIC mechanism uses')
s=s.replace('The loader fills in the GOT with real addresses at start-up.', 'The loader resolves applicable GOT entries; some function slots can instead be bound lazily.')
s=s.replace('Only the GOT page is modified per process;', 'This mechanism relocates pointer slots rather than rewriting those instruction bytes; other writable data or relocation targets can still differ per process, while')
s=s.replace('Function calls to other modules go through', 'External calls can go through')
s=s.replace('Lazy binding speeds up start-up', 'Lazy binding can reduce startup resolution work')
s=s.replace('resolves everything at start-up.', 'requests eager binding of the object’s required dynamic symbols at load time.')
s=s.replace('so a memory bug can\'t redirect library calls by overwriting a GOT entry.', 'so ordinary writes cannot overwrite the protected GOT slots. Other writable control data and permission-changing capabilities remain separate concerns.')
s=s.replace('When you run a program on Linux:', 'For a conventional dynamically linked glibc ELF program on Linux:')
s=s.replace('maps each needed library, applies relocations, fills the GOT, runs initialisers, then jumps', 'maps dependencies, performs required relocations (leaving lazy slots where applicable), and runs loader-managed initialization before transferring')
s=s.replace('which finishes C runtime set-up and calls `main(argc, argv, envp)`.', 'which handles remaining initialization, including the main executable’s initialization functions in the glibc 2.39 path reviewed here, then invokes main. The third envp parameter is a platform extension, not the ISO C two-argument main signature.')
s=s.replace('C and C++ let a program write past the end of a buffer.', 'An out-of-bounds access violates C/C++ rules and has undefined behaviour, but ordinary native code often lacks runtime bounds checks.')
s=s.replace('three cheap, broad mitigations', 'three widely used mitigations')
s=s.replace('is a bit in each page-table entry: bit 63 on x86-64. If set, an instruction fetch from that page faults.', 'uses architectural execute permissions. In x86-64 paging with NX supported and EFER.NXE enabled, bit 63 of relevant paging-structure entries can prohibit execution. If effective permissions prohibit execution, an instruction fetch faults.')
s=s.replace('The OS applies **W^X** ("write xor execute"): a page is writable or executable, never both.', 'A **W^X** policy aims to avoid simultaneously writable and executable mappings; enforcement and exceptions depend on the OS and configuration.')
s=s.replace('(that is what `GNU_STACK RW` records)', 'in typical hardened layouts (`GNU_STACK RW` specifically requests a non-executable stack, not heap/data policy)')
s=s.replace('they flip page permissions or keep two mappings, and Apple platforms require a special `MAP_JIT` mapping.', 'follow platform JIT permission, cache-maintenance and synchronization rules. Separate RW/RX aliases satisfy only a mapping-level W^X rule, not a stronger prohibition on writable access to executable backing memory.')
s=s.replace('at random addresses on every run.', 'at randomized addresses when enabled, subject to platform constraints; repeated addresses remain possible.')
s=s.replace('(2 = full, the default).', '(2 adds heap randomization to mode 1; defaults depend on kernel configuration and system policy).')
s=s.replace('(`readelf -h` shows `Type: DYN`). Mainstream distributions\' compilers default to `-pie`,', '(typically ELF Type DYN, but DYN also describes shared objects). Compiler defaults are toolchain-specific; use `-fPIE -pie` explicitly when appropriate,')
s=s.replace('On 64-bit systems there is plenty of entropy: roughly 28 bits for `mmap` regions on x86-64 Linux by default. On 32-bit systems there was so little that guessing repeatedly was practical.', 'Address width permits more randomization space but does not determine effective entropy. A fixed default-bit count and universal attack-time estimate are omitted because architecture, kernel configuration and deployment determine them.')
s=s.replace('So a single leaked pointer (an **information leak**) reveals the whole module\'s layout.', 'With a matching binary and a correctly identified symbol, a leaked address can reveal that module’s base and the locations of objects at known offsets. Arbitrary leaked pointers, symbol interposition and indirect-function implementations need additional identification.')
s=s.replace('The kernel randomises its own base as well (KASLR).', 'KASLR can also randomize the kernel base when supported and enabled.')
s=s.replace('A linear overflow that reaches the return address must trample the canary first.', 'In a protected layout, a contiguous overwrite toward the return address crosses the guard. Detection requires that it actually change the guard and that execution reach a check.')
s=s.replace('Here is real Clang output, with `-fstack-protector-strong`, for a function with a 32-byte local buffer:', 'Here is an illustrative x86-64 Linux/glibc stack-protector layout for a 32-byte local buffer. The ellipsis marks omitted application code; exact compiler output and layout vary:')
s=s.replace('On x86-64 Linux, glibc keeps the per-process canary', 'In the glibc 2.39 x86-64 layout reviewed here, the stack guard is accessed')
s=s.replace('so a C string-copy can\'t read it out or write it back intact.', 'to impede string-based disclosure and overwrite across the guard. A terminating zero can still overwrite its first byte unchanged; this is not protection against every overwrite or leak.')
s=s.replace('`-fstack-protector-strong` instruments functions with local arrays or locals whose address is taken; Ubuntu\'s GCC enables it by default, and distributions such as Fedora and Debian build their packages with it.', '`-fstack-protector-strong` covers additional functions with local arrays or references to local frame addresses; optimized-away or register-only objects do not count. Defaults depend on compiler and build configuration.')
s=s.replace('canaries detect only *contiguous* overwrites of the return address, and only when the function returns.', 'a canary detects a mismatch when its check executes. A non-contiguous write that hits the canary may also be detected; writes that bypass it or cause harm before the check can escape that protection.')
s=s.replace('Canaries | return-address smash', 'Canaries | some overwrites crossing the guard')
s=s.replace('Newer hardware closes more gaps.', 'Additional mechanisms can reduce particular attack paths when hardware, OS, compiler and application support enable them.')
s=s.replace('`-D_FORTIFY_SOURCE` adds bounds checks to calls such as `memcpy` where sizes are known.', 'With a supporting libc and compiler configuration, `_FORTIFY_SOURCE` can add checks to selected library operations using inferred object sizes; it does not bounds-check every memory access.')
s=s.replace('static archives are searched in command-line order.', 'traditional GNU ld archive extraction is order-sensitive, with grouping and linker-specific exceptions.')
s=s.replace('external calls through PLT stubs', 'some external calls through PLT stubs')
s+='''\n### Primary implementation references\n- [GNU ld options and archive/RELRO rules](https://sourceware.org/binutils/docs/ld/Options.html)\n- [Linux ASLR control](https://docs.kernel.org/admin-guide/sysctl/kernel.html#randomize-va-space)\n- [glibc 2.39 stack-guard setup](https://github.com/bminor/glibc/blob/glibc-2.39/sysdeps/unix/sysv/linux/dl-osinfo.h)\n- [glibc 2.39 startup](https://github.com/bminor/glibc/blob/glibc-2.39/csu/libc-start.c)\n'''
p.write_text(s);p=p.with_suffix('.questions.json');q=json.loads(p.read_text())
q[0]['options'][2]['explanation']='Correct as conceptual stages. The driver may combine stages within a process and pipe intermediates rather than creating each file.'
q[1]['options'][3]['text']='The linker could not resolve a required reference to parse_config under the selected inputs and linking rules'
q[1]['options'][3]['explanation']='A missing object/library, archive order, visibility or mismatched symbol naming can cause this; a definition may exist somewhere without being usable in this link.'
q[1]['workedExample']='Separate compilation allows unresolved references in a relocatable object. A required unresolved reference at the final link produces this error. Check the defining object/library, exact symbol name, visibility and linker-specific archive order. Weak references and dynamic imports have distinct rules.'
q[2]['prompt']+=' Assume the CPU supports NX and execute-disable checking is enabled.'
q[2]['workedExample']='With x86 NX supported and EFER.NXE enabled, effective paging permissions can forbid instruction fetches. Reading and writing have separate permission checks. A typical hardened stack mapping is non-executable, preventing instruction execution there, but NX does not prevent an out-of-bounds write or reuse of already executable code.'
q[3]['prompt']=q[3]['prompt'].replace('This link fails', 'Using traditional GNU ld archive processing, this link fails')
q[3]['workedExample']='When GNU ld first considers libm.a, main.o has not introduced its sqrt reference. Later it reads main.o, but does not automatically revisit that earlier archive. Placing main.o before -lm fixes this dependency order. Archive groups can request rescanning, and LLD’s handling differs. The initial undefined-symbol set need not be empty: startup objects may already contribute references.'
q[4]['options'][0]['text']='The zero rel32 field is a placeholder; the PLT32 relocation lets the linker calculate its target-relative displacement with addend −4'
q[4]['options'][2]['explanation']='The zeros are a displacement placeholder, not evidence of the callee’s address. Address zero’s mapping status is unrelated to interpreting this relocation.'
q[4]['workedExample']=q[4]['workedExample'].replace('In a dynamically linked program, `target` is `puts@plt`.', 'For the illustrated external PLT call, target is puts@plt; linkers may resolve suitable references directly instead.')
q[5]['prompt']='In the classic lazy-PLT scenario from the lesson, the first call resolves puts to libc and updates this GOT slot. With no auditing, rebinding or loader overrides, what happens on the second call through the same slot?'
q[5]['options'][0]['explanation']='In this scenario the slot was resolved and updated on the first call. Other objects have their own slots, and unusual loader settings can change binding behaviour.'
q[5]['options'][3]['explanation']='The ordinary user-space control transfer shown does not need a kernel forwarding operation. The function itself can make system calls.'
q[6]['prompt']='What does the conventional relocatable ELF object for the lesson’s main function calling puts contain? Select all that apply.'
q[6]['options'][4]['explanation']='This conventional relocatable object is linked before being executed; it does not carry the executable’s PT_INTERP mapping instructions. This is not a claim about every possible ELF or specialized object format.'
q[7]['prompt']+=' Assume the leaked address identifies a known function implementation in the exact libc binary used by the process.'
q[7]['options'][0]['text']='Known offsets within that libc binary let an attacker derive its load base and addresses of other known locations'
q[7]['options'][0]['explanation']='Correct under the stated identification assumption. A module-base leak does not automatically reveal unrelated mappings, heap allocations or arbitrary other process state.'
q[7]['workedExample']='For the identified implementation in the matching binary, subtract its known offset from the leaked address to infer the load base. Add other known offsets to locate code/data in that module. This defeats that part of address randomization, not every mitigation or every address. Avoid unnecessary raw-pointer disclosure and fix the underlying bug.'
q[8]['prompt']='In the lesson’s protected stack layout, which scenarios can cause corruption or a harmful indirect call without first producing a canary-mismatch failure? Assume every overwrite that crosses the guard changes it, and ordinary return paths execute the guard check. Select all that apply.'
q[8]['options'][3]['explanation']='Correct. A corrupted local pointer can be used before an epilogue guard check; corruption confined below the guard might not change it at all.'
q[8]['workedExample']='A changed guard is detected if its check is reached. Under the stated layout and assumptions, contiguous writes reaching saved RBX or the return address cross and change it. A direct write to the return address skips it, heap corruption is outside this frame, and an indirect call through a corrupted local pointer can cause harm before the check. Canaries do not detect all memory corruption.'
q[9]['options'][2]['explanation']='The illustrated GOT is data, not instruction text. Initial and eventual protection depend on the segment layout and relocation policy.'
q[9]['options'][3]['explanation']='Correct for the conventional lazy-PLT design: resolve slots before making their region read-only. The flags are passed through a compiler driver as -Wl,-z,relro,-z,now.'
q[9]['workedExample']='Lazy PLT binding needs future writes to unresolved function slots; partial RELRO may still protect other GOT entries. Eager binding resolves these slots at load time, and an appropriate GNU_RELRO range can then protect them too. The conventional full-RELRO combination is -z relro -z now. This concerns relocation slots for loaded objects, not a promise to pre-resolve every possible future dynamic lookup.'
q[10]['prompt']='In two hypothetical systems an address is chosen uniformly from 2^8 or 2^28 possibilities and stays fixed throughout the guessing experiment. Every guess is checked, with no repeats. Approximately how many guesses are needed on average, counting the successful guess?'
q[10]['options'][2]['explanation']='Correct approximately. With N equally likely positions searched once each, the exact expected successful-guess position is (N+1)/2: 128.5 or 134,217,728.5.'
q[10]['options'][3]['explanation']='The question explicitly gives different uniform search spaces; no real-system default or universal entropy claim is being made.'
q[10]['workedExample']='A fixed uniform target has each rank 1 through N equally likely, so E[guesses]=(N+1)/2. For N=256 this is 128.5; for N=268,435,456 it is 134,217,728.5. If an independent address is re-randomized after every failure, the experiment instead has geometric mean N. No elapsed attack time follows without a rate and restart model.'
q[11]['options'][2]['text']='A leading zero can stop NUL-terminated reads before the remaining guard bytes and obstruct one continuous string copy across it'
q[11]['options'][2]['explanation']='Correct, with limits. STRCPY reads the source terminator, not the old destination: it can copy a final zero onto the guard’s zero byte unchanged. Counted writes, targeted reads and other primitives can bypass this design.'
q[11]['workedExample']='On little-endian x86-64, clearing the low byte puts a zero first in the stored guard. A string read reaching that intact byte stops before the remaining bytes. Reproducing the zero inside a single NUL-terminated source also stops that copy there, but a terminating-zero overwrite can leave the first guard byte unchanged. The remaining seven bytes provide at most 56 random bits if uniformly generated; this is not an unconditional unguessability guarantee.'
p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Applied compile/link/load lesson and 12-question corrections')
