exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-se-architecture.json');report={'date':'2026-10-04','status':'In progress; first two lesson/question pairs fully read; execution and independent verification pending.','reviewed_files':[],'findings':[],'limitations':['No full module verification yet.']};findings=report['findings'];b='content/software-engineering/05-code-architecture/'
src=['https://martinfowler.com/bliki/PresentationDomainDataLayering.html','https://import-linter.readthedocs.io/en/stable/','https://docs.python.org/3/library/decimal.html','https://alistair.cockburn.us/hexagonal-architecture/','https://peps.python.org/pep-0544/','https://docs.python.org/3/library/abc.html']
patch(b+'sea-layered.md',[
('is the oldest and most common answer to this.', 'is a common answer to this.'),
('When those reasons stay separated, changes stay small.', 'Separating those concerns can reduce the scope of changes; new requirements or storage semantics can still cross boundaries.'),
('The same feature split into layers:', 'The following teaching fragments split the feature into layers; module imports and app wiring are omitted. Assume decimal totals are stored as text in the SQLite example. A real endpoint also needs authorization, input validation, an explicit transaction/concurrency policy and a decision about repeated discount requests.'),
('        factor = 1 - Decimal(pct) / 100\n        self.total = self.total * factor', '        pct = Decimal(str(pct))\n        if not pct.is_finite():\n            raise ValueError("finite percent")\n        if not 0 <= pct <= 100:\n            raise ValueError("percent range")\n        factor = 1 - pct / 100\n        self.total *= factor'),
('        return Order(r[0], Decimal(r[1]),', '        if r is None:\n            raise LookupError(oid)\n        return Order(r[0], Decimal(r[1]),'),
('    except OrderClosed:\n        return {"error": "closed"}, 409', '    except OrderClosed:\n        return {"error": "closed"}, 409\n    except UnknownCode:\n        return {"error": "unknown code"}, 400\n    except LookupError:\n        return {"error": "not found"}, 404'),
('Classic layering can\'t avoid this tension: either the domain depends on storage (ORM classes), or storage depends on the domain.', 'That conflicts with a literal source-import ordering of this particular diagram. Layered separation can use mappers or dependency inversion; it does not require domain objects to inherit an ORM.'),
('If your application layer is full of `if` statements about business policy, rules have leaked out of the domain.', 'In a rich domain-model design, repeated business decisions in application services suggest missing domain behavior. Conditional orchestration is not itself a violation, and transaction-script designs deliberately organize logic differently.'),
('Strict layering produces the **architecture sinkhole** anti-pattern:', 'Strict layering can produce **architecture sinkhole** paths:'),
('each layer uses only the services of the one below.', 'they illustrate layered responsibilities, although real implementations include cross-layer interactions and do not all follow this exact import rule.'),
('so everything depends on it, *including the domain*.', 'and a literal downward dependency implementation couples the domain to storage. This is not inevitable in every layered design.'),
('[importlinter:contract:layers]', '[importlinter]\nroot_package = shop\n\n[importlinter:contract:layers]'),
('- Classic layering puts the database at the bottom, so the domain ends up depending on storage. Hexagonal architecture inverts that.', '- A downward source dependency on infrastructure couples rules to storage; dependency inversion can preserve layered separation without that coupling.')], 'Qualify layering guarantees, fix missing-row/unknown-code cases, validate discount input and complete linter root configuration.',src)
def layered(q):
 q[0]['prompt']+=' Assume relaxed layering in the order listed.'
 q[1]['options'][1]['explanation']='A guarded database update can reinforce the invariant atomically under concurrency. It is not a substitute for a shared domain rule, and a separate read-then-save must also prevent races.'
 q[1]['options'][3]['explanation']='Duplication increases the risk of divergent rules; divergence is not logically inevitable.'
 q[2]['options'][3]['explanation']='Separation can localize changes, but a feature or database semantic change may still affect multiple layers.'
 q[2]['workedExample']=q[2]['workedExample'].replace('With layers, each one is confined.', 'With suitable boundaries, these changes can be more localized; this is a design aim, not a guarantee.')
 q[4]['workedExample']=q[4]['workedExample'].replace("Mark Richards' rule of thumb (from *Software Architecture Patterns*) is that around 20% of requests being simple pass-throughs is fine; if most are, reconsider.", 'There is no measured universal acceptable percentage supplied here. Judge whether the boundary provides useful isolation or merely forwards calls.')
 q[6]['options'][0]['explanation']='A single file can preserve conceptual separation, but distinct feature modules make import boundaries easier to express and check; merging files does not inherently erase the rule.'
 q[8]['options'][0]['text']='The domain is coupled to persistence machinery, which can complicate isolation and alternate storage even if some ORM methods can be tested without a live database.'
 q[8]['options'][0]['explanation']='This design names the ORM inside domain classes. Dependency inversion or extracting pure calculations can reduce that coupling; ORM inheritance alone does not imply every test opens a database.'
 q[8]['workedExample']=q[8]['workedExample'].replace('To construct an `Order` in a test, Python must import the ORM and usually configure a database. Every pricing test pays that cost.', 'Constructing Order requires the ORM classes and possibly framework setup; whether a live database is needed depends on what its methods access.')
 q[9]['options'][0]['explanation']='In the intended rich-model design the rule belongs in a shared domain operation. A service can itself be reused by multiple entry points, so its location does not make reuse impossible.'
 q[9]['options'][1]['explanation']='A domain method centralizes valid transitions, but Python public attributes can still be assigned directly unless access is otherwise controlled.'
 q[9]['workedExample']+='\nThe snippet illustrates responsibility placement, not atomic delivery: committing an order and sending email require an explicit failure/retry policy, often an outbox.'
questions(b+'sea-layered.questions.json',layered,'Correct concurrency enforcement, one-file layering, ORM testing and universal sinkhole threshold claims.',src)
patch(b+'sea-hexagonal.md',[
('Classic layering has one awkward arrow: the domain sits on top of the data layer, so business rules end up depending on storage.', 'A conventional downward dependency from domain to infrastructure couples business code to storage; layered separation can instead use dependency inversion.'),
('The core defines its ports with `typing.Protocol`, which gives structural typing: any class with the right methods counts, with no inheritance needed.', 'The core defines ports with typing.Protocol for static structural typing: matching member types can satisfy the contract without inheritance. Type hints do not enforce the behavioral contract at runtime. These snippets share their definitions; a packaged app needs the corresponding imports.\n\n```python\n# core/model.py\nclass Order:\n    def __init__(self, oid, status):\n        self.id = oid\n        self.status = status\n\n    def place(self):\n        if self.status != "draft":\n            raise ValueError("not draft")\n        self.status = "placed"\n```'),
('The use case depends only on those ports:', 'The use case depends only on those ports. This minimal example demonstrates wiring, not reliable cross-system delivery: saving and notifying need an explicit transaction/retry policy. A production flow can atomically commit state and an outbox row, then notify asynchronously.'),
('        return Order(row.id, row.status)', '        if row is None:\n            raise LookupError(oid)\n        return Order(row.id, row.status)'),
('        row.status = order.status', '        if row is None:\n            raise LookupError(order.id)\n        row.status = order.status'),
('Notice the translation:', 'The SQL fragment assumes an OrderRow mapping and a caller-owned session transaction. Here add updates an existing row; it is not a general insert implementation. Notice the translation:'),
('That test runs in microseconds, with no database, network or mock library.', 'That test requires no database, network or mock library.\n\n> [!note] Evidence gap\n> No fixed test-duration figure is asserted without a measured environment. Fake-based tests also need adapter contract/integration checks; they do not prove real transaction, missing-row or concurrency behavior.'),
('It is the only module that knows about everything.', 'It coordinates concrete wiring; this does not literally require one module to import every class in a large application.'),
('Python rarely needs a dependency-injection framework for this.', 'This example does not need a dependency-injection framework.'),
('switch an email provider or database by writing one adapter.', 'an adapter can isolate a provider change when its semantics satisfy the existing port; transactions, consistency and capabilities may still require design changes.'),
('Django\'s admin, model forms and ORM querysets assume models *are* domain objects.', 'Django admin and ModelForm are built around ORM models. Separate domain classes require mapping or integration, but do not inherently prevent retaining these framework features.')], 'Add the missing executable domain model, scope protocols and fake guarantees, and expose persistence/notification atomicity limits.',src)
def hexagonal(q):
 q[2]['options'][0]['explanation']='A fake can exercise domain behavior without external I/O. Its latency is not a fixed guarantee, and separate checks must verify real adapter semantics.'
 q[2]['workedExample']=q[2]['workedExample'].replace("The use case can't tell the difference", 'The same port-shaped interaction can be used')
 q[5]['options'][0]['explanation']='No external adapter boundary is needed for this pure collaboration. Internal abstractions can still serve other design goals; they are not universally useless.'
 q[6]['workedExample']=q[6]['workedExample'].replace('The pay side is roughly fixed per entity and port; the get side grows with the amount of business logic.', 'Both costs and benefits depend on mapping complexity, integration needs, testing and expected changes; there is no fixed per-entity cost law.')
 q[8]['options'][1]['explanation']='Protocols and abstract base classes are different mechanisms. ABC runtime checks can use inheritance, virtual registration or subclass hooks; registration alone does not establish static structural typing.'
 q[8]['workedExample']=q[8]['workedExample'].replace('there, `MemRepo` would need to subclass the ABC or be registered.', 'runtime membership can come from inheritance, registration or a subclass hook; static type-checker acceptance is a separate question.')
 q[9]['options'][3]['explanation']='Transport retry mechanics can belong in an adapter, but charging retries must preserve the payment provider\'s idempotency contract and overall budget. Retrying a timeout blindly can duplicate effects.'
 q[10]['options'][1]['explanation']='Given these requirements, framework defaults may be proportionate. Separate domain classes add work but do not inherently prohibit using Django admin or model forms on ORM models.'
 q[10]['workedExample']=q[10]['workedExample'].replace('and loss of Django admin and `ModelForm`.', 'plus integration with Django admin and ModelForm if separate domain classes are introduced.').replace('The benefit is near zero and the cost is high, so don\'t.', 'Given the stated simple requirements, the proposed structure may cost more than it helps; evaluate actual future needs.')
questions(b+'sea-hexagonal.questions.json',hexagonal,'Correct fake/ABC claims, payment retry safety and overstated framework feature loss.',src)
report['reviewed_files']=[b+n+s for n in ['sea-layered','sea-hexagonal'] for s in ['.md','.questions.json']]
p_report.write_text(json.dumps(report,indent=2)+'\n')
