exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-theory-discrete.json'); report={'date':'2026-10-05','status':'In progress; first four lesson/question pairs fully read; execution and independent verification pending.','reviewed_files':[],'findings':[],'limitations':['Remaining two lesson/question pairs not yet fully read.']}; findings=report['findings']; b='content/theory/02-discrete-structures/'
src=['https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_session6.pdf','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_session7.pdf','https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset','https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf','https://www.postgresql.org/docs/current/ddl-constraints.html']
patch(b+'disc-sets-functions.md',[
('A type is a set of values. A database table is a set of rows. A hash function is a function from keys to buckets.', 'A simple model treats a type as a set of values and a mathematical relation as a set of tuples. SQL tables can contain duplicate rows, and a hash table usually maps a key through a hash value to a bucket.'),
('which reads exactly like a Python comprehension', 'which resembles a Python comprehension (mathematical sets can also be infinite)'),
("Python's built-in `set` gives you all of these", "Python's built-in set supports union, intersection, difference and symmetric difference; complement needs an explicit universe, U - a"),
('This is why brute-force subset algorithms are O(2ⁿ): 20 items is about a million subsets, 40 items is about a trillion.', 'There are 2ⁿ subsets: about a million for 20 items and a trillion for 40. Runtime also includes work per subset. The shown construction scans n positions for each mask, taking Θ(n·2ⁿ) elementary operations under a unit-cost bit model, before accounting for formatting and printing.'),
('and an SQL `CROSS JOIN` literally computes the Cartesian product.', 'and an SQL CROSS JOIN combines every input-row occurrence with every occurrence on the other side, retaining duplicate multiplicities.'),
('SHA-256 maps arbitrary byte strings (an infinite set) to 2²⁵⁶ possible outputs.', 'Standard SHA-256 accepts messages shorter than 2⁶⁴ bits and produces one of 2²⁵⁶ outputs. Its finite input domain is still vastly larger than its output space.'),
('This explains why a lossy step anywhere in a pipeline makes the whole pipeline lossy: you cannot recover what an early step threw away.', 'If a stage merges two reachable states that arose from distinct valid inputs, later deterministic stages cannot recover that distinction without additional information. Non-injectivity only on states the pipeline never reaches need not lose information.'),
('injections A -> B      n(n-1)...(n-m+1)\nbijections A -> A      n!   (permutations)', 'injections A -> B      n!/(n-m)! if m<=n\n                      0 if m>n\nbijections A -> A      m!   (permutations)'),
('There are nᵐ functions because', 'Use the counting convention 0⁰ = 1 for the unique empty-domain function. There are nᵐ functions because'),
('A Python function that reads the clock or a global variable is not a function in this sense, because the same input can give different outputs. **Pure functions** match the maths, which is why they are easy to test, cache (memoise) and parallelise.', 'A routine whose result depends on changing hidden state may return different results for the same explicit arguments. Including the relevant state in the mathematical input gives a function again; reading an immutable constant does not itself violate determinism. Pure terminating routines fit the simple total-function model and can be easier to test, memoise and parallelise.'),
('**Base64, UTF-8, gzip**: lossless encodings are injective. JPEG and MP3 are not.', '**Base64, UTF-8, gzip**: with a fixed encoder configuration and appropriate valid input domain, lossless round trips require injectivity. Ordinary lossy JPEG and MP3 encoding merge distinct inputs; the JPEG family also includes lossless modes.'),
('**Primary keys**: the mapping from key to row must be injective, which is what a `UNIQUE` constraint enforces.', '**Primary keys**: projecting each row to its primary-key value uniquely identifies that row. A primary key combines uniqueness with non-nullness; a bare UNIQUE constraint can permit multiple nulls depending on the database and configuration.'),
('f(x) = x² is surjective onto [0, ∞) but not onto ℝ.', 'With domain ℝ, f(x) = x² is surjective onto [0, ∞) but not onto ℝ.'),
('Side effects and hidden state break the "same input, same output" rule.', 'Changing hidden state can break the same-explicit-input/same-result rule; an output side effect can violate purity even when the returned result is deterministic.'),
('union, intersection, difference and complement map directly to Python\'s `|`, `&`, `-` and `^` operators.', 'union, intersection, difference and symmetric difference map to Python\'s |, &, - and ^; complement is U - A for an explicit universe U.'),
('bitmasks enumerate subsets, which is why subset brute force is O(2ⁿ).', 'bitmasks identify 2ⁿ subsets; constructing each list explicitly costs Θ(n·2ⁿ) total elementary operations.')], 'Fix function-count variable, subset-enumeration complexity, finite SHA input domain, set operators, SQL uniqueness/bag semantics and purity scope.',src)
def sets(q):
 q[5]['options'][0]['explanation']='Truncation cannot remove the pigeonhole limit. A 32-bit output is also too small for cryptographic collision resistance: generic birthday search needs only about 2¹⁶ trials.'
 q[5]['options'][2]['text']='Use the reduction ID mod 2³²'
 q[5]['workedExample']=q[5]['workedExample'].replace('Real hash tables therefore always include collision handling (chaining or probing).', 'General-purpose hash tables need a collision policy, such as chaining or probing; a table tailored to a fixed key set can instead use perfect hashing.')
 q[7]['workedExample']=q[7]['workedExample'].replace("(With NULLs, SQL's three-valued logic adds wrinkles, which is why the question rules them out.)", 'The De Morgan rewrite also holds under SQL three-valued logic. With NULLs, UNKNOWN is not the same as FALSE, so a set-complement interpretation of filtered rows needs care.')
 q[10]['options'][0]['explanation']='On all integers, f(-3) = f(3) = 9. Squaring is injective on the non-negative integers, and also on the non-positive integers, but not on all of ℤ.'
 q[11]['prompt']='Assume a deterministic encoder and decoder satisfy decode(encode(x)) == x for every valid value x. View encode : Values → Bytes and decode : Bytes → Values as total mathematical functions on an accepted byte-string domain containing every encoded value. What follows?'
 q[11]['workedExample']=q[11]['workedExample'].replace('Bytes outside the image of encode can decode to anything (or be rejected)', 'Accepted byte strings outside the image of encode can decode to other valid values; rejected inputs lie outside this total decoder domain').replace('A property-based test (e.g. with Hypothesis) checking the round trip is therefore checking that your encoding is lossless.', 'Property-based tests supply evidence on the cases generated; they do not establish the universal premise unless the entire finite domain is exhaustively checked.')
questions(b+'disc-sets-functions.questions.json',sets,'Clarify truncated-hash security, SQL NULL behavior, squaring domain and total decoder/testing assumptions.',src)
src2=src[:2]+['https://docs.python.org/3/reference/datamodel.html#object.__hash__','https://docs.python.org/3/library/graphlib.html','https://pip.pypa.io/en/stable/cli/pip_install/#installation-order']
patch(b+'disc-relations.md',[
('This is how Kruskal\'s algorithm tracks components, and how compilers unify type variables.', 'Union-find tracks components for Kruskal\'s algorithm and can support type-variable unification. Full type unification also needs to handle type structure and checks such as the occurs check.'),
("`==` must behave as an equivalence relation, and `__hash__` must be constant on each class (equal objects must have equal hashes), otherwise dicts and sets break.", 'Well-behaved value equality is normally an equivalence relation, but Python does not enforce these laws and NaN is a standard exception. Hashable objects that compare equal must have equal hashes, and their hash must stay stable while used as keys.'),
('Dependency graphs are usually drawn as strict orders.', 'An acyclic direct-dependency graph need not itself be transitive; its positive-length reachability relation is a strict partial order.'),
('CRDTs rely on a "merge" that is a join.', 'state-based CRDTs use a join operation on a semilattice of states; operation-based CRDTs use different delivery and commutativity conditions.'),
('(a cycle would violate antisymmetry)', '(a cycle of distinct vertices conflicts with antisymmetry of reachability, and a self-loop conflicts with strict precedence)'),
('Make, Bazel, pip\'s dependency installer, spreadsheet recalculation and SQL migration tools all do this.', 'Build and dependency tools use dependency ordering when prerequisites form a DAG. Cycle policies vary: pip documents an installation fallback for dependency cycles, so not every such tool rejects them.'),
('In a distributed database, each version carries a vector clock.', 'In a store that tracks versions with vector clocks, each version carries counters for its tracked participants.'),
('a R⁺ b if there is a path from a to b.', 'a R⁺ b if there is a path of positive length from a to b.'),
('For sparse graphs, a BFS or DFS from each node is usually faster.', 'With adjacency lists, a BFS or DFS from every vertex takes O(n(n+m)); this improves the asymptotic bound on sparse graphs, without promising a fixed wall-clock speedup.'),
('in a graph, it is "in the same connected component".', 'it groups vertices into connected components after ignoring any edge directions.'),
('A NaN key in a dict can only be found again by identity.', 'For ordinary float-NaN lookups, retaining the identical key object permits retrieval even though NaN is not equal to itself; another separately created float NaN does not match it.'),
('Timestamps from different machines give a total order that may not match causality; that\'s why Lamport and vector clocks exist.', 'Wall-clock timestamps can tie and need not match causality. Lamport timestamps respect causal precedence but do not detect concurrency; a process-ID tie-breaker can make them total. Vector clocks can expose concurrency under their model.')], 'Fix equality guarantees, direct-edge versus reachability orders, cycle handling, CRDT scope and clock distinctions.',src2)
def relations(q):
 q[9]['workedExample']+='\nRestrict monetary inputs to finite values and keep the normalized value immutable while it is a key. Implement unsupported-type comparison with NotImplemented; rounding alone does not fix mutable hashes or NaN equality.'
 q[10]['workedExample']=q[10]['workedExample'].replace('stricter implementations detect the contradiction and throw.', 'some implementations may detect a contract violation and throw; detection is not guaranteed for every bad input.')
 q[11]['workedExample']=q[11]['workedExample'].replace('which is exactly what a package manager or build tool should reject.', 'which prevents a strict prerequisite-before-dependent order. A build must resolve or reject that cycle; some package installers, including pip, document a different cycle policy.')
questions(b+'disc-relations.questions.json',relations,'Qualify mutable/NaN equality fixes, comparator detection and package-cycle handling.',src2)
patch(b+'disc-counting.md',[
('Factorials grow faster than exponentials:', 'For every fixed base c > 1, n! eventually grows faster than cⁿ:'),
('The last row, **multisets**,', 'Here n ≥ 1 and k ≥ 0; no-repeat factorial formulas assume k ≤ n (otherwise the count is zero). The last row, **multisets**,'),
('gzip and zstd add a small header to incompressible data for exactly this reason.', 'format framing and block overhead are concrete reasons gzip or zstd output may grow. The counting argument proves that some growth is unavoidable for such a total shrinking compressor; it does not require a particular header design.'),
('With 365 days, certainty needs 366 people, but 23 people already give a better than 50% chance.', 'In the model of independent, uniformly distributed birthdays over 365 possible days, certainty needs 366 people, but 23 already give a better than 50% chance.'),
('a b-bit hash starts colliding after about 2^(b/2) items', 'independent uniformly distributed b-bit hash outputs have substantial collision probability around 2^(b/2) items (collisions can also occur earlier)')], 'State counting and birthday-model domains and separate incompressibility theorem from concrete format overhead.',src)
def counting(q):
 q[2]['options'][3]['explanation']='With independent uniformly distributed birth months, 5 people already have about a 61.8% chance of a shared month. This is not a guarantee; pigeonhole needs 13.'
 q[5]['options'][2]['explanation']='For these distinct inputs, 36 = 6² includes repeated positions such as (3, 3). itertools.permutations does not reuse an input position, though repeated values in its input can still appear more than once.'
 q[6]['options'][4]['explanation']='3 × C(10, 2) = 135, not 120. Picking a pair then a distinct third element would have 8 choices for that third element, and would count each triple three times.'
 q[9]['prompt']='A startup claims its lossless compressor, defined for all finite bit strings without an uncounted side channel, makes every 1 KiB (1,024-byte) file strictly smaller. Which statements are correct? Select all that apply.'
 q[9]['options'][3]['text']='For a lossless compressor defined on all finite bit strings, shrinking one input forces expansion of at least one other input'
 q[9]['workedExample']=q[9]['workedExample'].replace('1 KB', '1 KiB').replace('In practice, compressors like gzip and zstd fall back to storing incompressible input almost verbatim, so the output is slightly *larger*.', 'Concrete formats add framing or block overhead and can emit raw blocks, so incompressible input may grow. The theorem itself does not prescribe how a compressor represents those files.')
questions(b+'disc-counting.questions.json',counting,'Fix KiB assumption, total-compressor domain, itertools distinct-position semantics and incorrect distractor rationale.',src)
patch(b+'disc-inclusion-recurrences.md',[
('Each term is ⌊1000/d⌋, computed in O(1),', 'Each term is one integer division ⌊1000/d⌋ (constant time in a fixed-width arithmetic model),'),
('almost independent of n.', 'approaching that limit as n grows; small cases differ substantially, for example D(1)/1! = 0 and D(2)/2! = 1/2.'),
('and why memoising it makes it linear.', 'and why memoisation reduces it to O(n) additions. Exact Fibonacci values have Θ(n) bits, so this is not a linear bit-complexity bound.'),
('We never plug in a value for x;', 'For the formal counting manipulations here we do not need to evaluate x;'),
('```python\ndef ways(n, coins):', 'Assume n is a non-negative integer and coins contains distinct positive integer denominations.\n\n```python\ndef ways(n, coins):'),
('count balanced bracket strings, binary trees with n nodes, and ways to triangulate a polygon.', 'count balanced strings of n bracket pairs, ordered rooted binary-tree shapes with n nodes (left/right distinguished), and triangulations of a convex polygon with n + 2 vertices.'),
('If the characteristic equation has a double root r,', 'For a genuine second-order recurrence with a nonzero double root r,')], 'Qualify arithmetic complexity, derangement convergence, formal-series scope and Catalan indexing/tree model.',src)
def recurrences(q):
 q[9]['prompt']+=' Assume constant positive base costs and unit-cost arithmetic; the halving recurrences are considered on powers of two.'
 q[9]['options'][4]['explanation']='With fib(0) and fib(1) as base cases, fib(20) makes 21,891 calls, growing as Θ(φⁿ). Memoisation uses Θ(n) arithmetic operations; exact-integer bit costs grow with the values.'
 q[9]['workedExample']=q[9]['workedExample'].replace('Two recursive calls on n − 1 or n − 2 double the work each level, which is exponential.', 'The unequal Fibonacci branches terminate at different depths; their total grows as Θ(φⁿ), rather than doubling across every complete level.')
questions(b+'disc-inclusion-recurrences.questions.json',recurrences,'State recurrence/base-cost model and fix unequal Fibonacci tree doubling claim.',src)
report['reviewed_files']=[b+n+s for n in ['disc-sets-functions','disc-relations','disc-counting','disc-inclusion-recurrences'] for s in ['.md','.questions.json']]
p_report.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
