from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-cellular.md');s=p.read_text()
def r(a,b):
 global s
 assert a in s,a[:70]
 s=s.replace(a,b)
a=s.index('Wi-Fi is a free-for-all:');b=s.index('## The big picture',a)
s=s[:a]+'''Cellular systems centrally schedule much of their radio traffic, unlike basic Wi-Fi contention. This is a distinction in access mechanisms, not a guarantee of collision-free radio or predictable latency: random access, interference, coverage and load still matter. Cellular deployments can use licensed, shared or unlicensed spectrum; Wi-Fi also has scheduled multi-user modes.

For applications, mobile paths introduce changing capacity, radio-state transitions, possible address changes and provider-specific translation or filtering. Design for interruption and measure the devices and networks you support.

''' +s[b:]
r('| Session control | in MME / P-GW | SMF |','| Session control | distributed across MME and gateway control functions | SMF |')
r('| Subscriber data | HSS | UDM / AUSF |','| Subscriber data / authentication | HSS with associated authentication functions | UDM/UDR for subscriber data; AUSF for authentication |')
r('The 5G core is built as a set of **service-based** network functions talking HTTP/2 APIs to each other, designed to run as cloud software, rather than the fixed boxes of earlier generations. The idea is the same as the 4G core, split up more finely.','The 5G core defines **service-based** control-plane functions with HTTP-based service interfaces. Not every interface is HTTP/2: user-plane tunnels and control interfaces such as N4 use other protocols. Functions can be virtualised; earlier generations also support virtualisation, so “5G software versus 4G fixed boxes” is misleading.')
r('When a phone attaches, the core gives it an IP address from the packet gateway (P-GW in 4G, UPF in 5G) and sets up a **bearer** (4G) or **PDU session** (5G). Your packets travel from the base station to the gateway inside **GTP-U** tunnels (UDP port 2152).','For an IP session, session establishment selects/allocates addressing and user-plane resources. LTE uses EPS bearers with a P-GW anchor. In 5G, the SMF manages the PDU session and address allocation, potentially using a UPF or external allocation mechanism; a session-anchor UPF forwards user traffic. Not every PDU session carries IP: Ethernet and unstructured types also exist. Relevant radio-to-core user-plane interfaces use **GTP-U**, whose registered destination UDP port is 2152.')
r('When you move between cells, the core just re-points the tunnel to the new base station. Your IP address and TCP connections survive handover between cells, even at 120 km/h.','During a supported handover that preserves the session anchor/address, user-plane paths can be updated while the application retains its IP address. Connections can survive, but radio interruption, loss, session changes or timeout can still break them; no particular vehicle speed guarantees continuity.')
r('What does *not* survive is a switch between networks: moving from cellular to Wi-Fi gives you a new IP address from a different provider entirely.','Moving to an independently addressed Wi-Fi path commonly changes the effective endpoint address. Keeping the old path alive, provider-integrated access, tunnels or mobility-capable transports can change the outcome.')
r('LTE and 5G NR both use **OFDMA** in the downlink: the channel is divided into thousands of narrow subcarriers, grouped into **resource blocks** (12 subcarriers). In LTE, subcarriers are 15 kHz apart, so a resource block is 180 kHz wide, and the scheduler hands out blocks every 1 ms **transmission time interval**.','LTE and NR use OFDM-based downlink resource allocation. A resource block spans **12 subcarriers**; the number of active subcarriers depends on the channel configuration. In the conventional LTE example, 15 kHz spacing gives 180 kHz per resource block and a 1 ms subframe scheduling interval. Later features and specialised modes qualify a universal 1 ms rule. LTE uplink commonly uses DFT-spread OFDM (SC-FDMA), rather than simply the same downlink waveform.')
r('A phone cannot simply transmit. It sends a **scheduling request**, the base station grants it uplink resources, and only then does it send. This adds a few milliseconds of latency, but means no collisions, efficient use of spectrum and fair sharing that the operator controls.','For dynamically scheduled uplink data without an existing grant, a connected UE can request resources and receive an uplink grant. Existing/configured grants and random-access procedures mean a fresh request/grant is not required for every packet. Scheduling coordinates access but does not eliminate random-access collisions or inter-cell interference; fairness is a scheduler policy, not an automatic guarantee.')
r('Subcarrier spacing can be 15, 30, 60 or 120 kHz; each doubling halves the slot length:','Common examples use 15, 30, 60 or 120 kHz spacing. This is not the complete set in later releases. For normal cyclic prefix, the corresponding full-slot duration is `1 ms / 2^μ` with spacing `15 × 2^μ kHz`; mini-slot transmission need not occupy a full slot:')
r('5G spans two frequency ranges:','NR specifications define release-specific frequency ranges, with different supported bandwidths and spacings:')
r('- **FR1** (410 MHz to 7.125 GHz). Low bands (700 MHz) cross walls and cover kilometres but have little bandwidth. Mid band, around **3.4–3.8 GHz** in the UK and Europe, is the 5G workhorse: channels of up to 100 MHz with decent range.','- **FR1** includes low and mid bands. Lower frequencies often aid coverage, while wider available allocations can provide capacity; actual range depends on power, antennas and surroundings. A 3.5 GHz deployment is an illustrative mid-band case, not a universal regional allocation.')
r('- **FR2**, **millimetre wave** (24 GHz and up). Channels of hundreds of MHz and multi-gigabit rates, but range is in the low hundreds of metres, and a hand, a wall or foliage can block it. Base stations use beamforming to aim narrow beams at each phone.','- **FR2** covers higher-frequency NR bands, commonly called mmWave in the industry, and has release-specific subdivisions. Wide channels and beamforming can support high capacity, but blockage and link budget matter. A fixed “few hundred metres” coverage rule is not reliable for every deployment.')
r('Early deployments were **non-standalone** (NSA): a 5G radio carrier bolted onto an LTE anchor cell and the 4G core. The control signalling still runs over LTE. **Standalone** (SA) 5G uses the new 5G core and unlocks features such as network slicing and the RRC_INACTIVE state.','A common **NSA option 3** deployment uses LTE/EPC as the master/core with NR as secondary access. **SA option 2** connects NR to the 5G core. “NSA” has broader architectural usage, and a status icon alone does not prove which capabilities are active. Feature availability depends on release, configuration, device and operator support.')
r('The ITU targets for 5G (IMT-2020) include peaks of 20 Gbit/s downlink and user-plane latency of 4 ms for mobile broadband and 1 ms for ultra-reliable low-latency use. These are radio-segment targets in ideal conditions. A real round trip from a phone to a server on the Internet is typically tens of milliseconds, because it includes scheduling, backhaul, the core and the path beyond.','ITU IMT-2020 evaluation requirements include a 20 Gbit/s peak downlink data rate and 4 ms eMBB / 1 ms URLLC user-plane latency targets under their defined conditions. The latency measure is one-way radio user-plane latency, not an Internet ping RTT; the peak rate is not a per-user service guarantee. Scheduling, backhaul, core routing, server work and other path segments contribute to application latency.')
r('- **Idle**: the phone only wakes periodically to listen for paging. Very low power.','- **Idle**: the UE has no active RRC connection, but can perform paging monitoring, measurements, reselection and other procedures. It is not powered off.')
r('- **Connected**: the phone has radio resources and can send and receive immediately, but burns power.','- **Connected**: RRC context supports scheduled communication; grants and discontinuous reception (DRX) still affect timing and power. Connected does not mean continuously transmitting or always at maximum power.')
r('- 5G SA adds **RRC_INACTIVE**: the network keeps the phone\'s context, so it can resume much faster than from idle while still saving power.','- NR **RRC_INACTIVE** retains access-stratum context and can reduce resumption work relative to idle. Its supported use is release/deployment-specific; related LTE suspension and newer inactive-state data features make “all packets always need full promotion” too broad.')
r('In LTE this is designed to be under 100 ms, and in practice it is often tens of ms. On 3G it could take a second or two.','The delay depends on radio state, procedures, release, coverage and load; no fixed millisecond value is guaranteed.')
r('After the last packet, the radio stays connected until an inactivity timer, set by the operator and commonly several seconds to around 10 s, expires. Every short burst of traffic buys a full tail of high-power radio time.','Activity can leave the radio in a higher-energy state after payload transfer ends. Timers, DRX and other state transitions determine the cost. Bursts can overlap or share radio activity; connected time is not identical to measured energy.')
r('Model the radio as staying connected for a 10 s tail after each request:','Use a toy model: instantaneous requests each add an interval `[t, t + 10)` of activity. Count the union of those intervals. Ignore promotion time, transfers, DRX, other applications and observation-window clipping:')
r('def radio_on(times, tail=10.0):\n    """Seconds the radio stays CONNECTED."""','from math import isfinite\n\ndef radio_on(times, tail=10.0):\n    """Union length of fixed-tail intervals."""\n    times = list(times)\n    if not isfinite(tail) or tail < 0:\n        raise ValueError("invalid tail")\n    if any(not isfinite(t) for t in times):\n        raise ValueError("invalid time")')
r('An app that polls every 30 s keeps the radio in its high-power state for 1,200 s per hour: a third of the time, for a few bytes of data. Batching to once every 5 minutes cuts that to 120 s. Requests close together share a tail: `radio_on([0, 4, 8, 50])` is 28 s, not 40.','In this model, the supplied one-hour schedules produce 1,200 and 120 seconds of interval coverage. This is not a prediction of battery energy on a real phone. Nearby requests share intervals: `radio_on([0, 4, 8, 50])` returns 28 seconds, not 40.')
r('one burst of requests beats many trickles.','grouping delay-tolerant work can reduce repeated radio activity; avoid downloading unnecessary data.')
r('The OS maintains one shared connection for every app.','Platform-managed delivery can share infrastructure across apps; delivery timing and energy are not free or guaranteed.')
r('do not set aggressive timeouts on it.','choose measured end-to-end deadlines and retry behaviour rather than assuming a constant first-request cost.')
r('Mobile operators have far more devices than public IPv4 addresses, so most use **carrier-grade NAT** (CGNAT). Thousands of phones share one public IPv4 address. Consequences:','**Carrier-grade NAT** (CGNAT) lets an operator share public IPv4 addresses among many subscribers. The number sharing one address and availability of public addressing vary. Possible consequences:')
r('A phone cannot accept inbound connections. Peer-to-peer apps need relays or NAT traversal (STUN, TURN, ICE).','Unsolicited inbound IPv4 connections are commonly restricted without suitable mappings/policies. Peer-to-peer applications can use ICE with STUN and, when needed, TURN relays; STUN itself is not a relay.')
r('often shorter than on home routers.','according to protocol and operator policy.')
r('Rate-limiting or blocking by IP on your servers can hit thousands of innocent users behind one address.','Rate-limiting by public IP can group unrelated subscribers; combine appropriate account/token and abuse controls rather than treating an address as one person.')
r('Many large operators now run **IPv6-only** networks. Phones get only an IPv6 address, and IPv4-only servers are reached via NAT64/DNS64 or **464XLAT**, which translates on the phone and in the network. T-Mobile US is a well-known example. Apple has required App Store apps to work on IPv6-only networks since 2016, which in practice means: use hostnames, use the system networking APIs, and never hard-code IPv4 literals.','Operators can provide **IPv6-only** access with NAT64/DNS64 or **464XLAT** to reach IPv4 services. 464XLAT combines client-side stateless translation with network-side stateful translation. Apple’s IPv6-only compatibility guidance recommends hostnames and system APIs; some system APIs can synthesise an IPv6 destination even from an IPv4 literal. Raw IPv4-only socket code without translation/synthesis is a different case.')
r('Walking from 5G into the office Wi-Fi changes the phone\'s IP address. A TCP connection is identified by its 4-tuple, so every open connection breaks.','If an application loses its cellular path and must use an independently addressed Wi-Fi path, ordinary TCP cannot simply change its endpoint tuple. Joining Wi-Fi alone does not necessarily close every existing cellular connection.')
r('a client can migrate to a new address without a new handshake.','eligible client migration can preserve a confirmed connection when permitted and the new path works; validation and other conditions still apply.')
r('**Multipath TCP** runs subflows over Wi-Fi and cellular at once. Apple has used it for Siri since iOS 7, so a voice request survives leaving Wi-Fi mid-sentence.','**Multipath TCP** can carry one connection over multiple subflows, for example Wi-Fi and cellular, when endpoints and policies support it. It improves mobility options without guaranteeing uninterrupted service.')
r('**expensive** (cellular) or **constrained** (Low Data Mode)','**expensive** or **constrained** under the platform’s definitions; these flags are not interchangeable with a simple cellular-versus-Wi-Fi test')
r('from tens of kbit/s at the cell edge to hundreds of Mbit/s near a mid-band mast.','with coverage, scheduling, congestion, device capabilities and backhaul.')
r('Delay-based congestion control such as BBR copes better than pure loss-based algorithms.','BBR is model-based, using delivery-rate and RTT estimates; it is not simply delay-based and does not universally outperform CUBIC. CUBIC can also react to ECN rather than waiting only for loss.')
r('the radio link retransmits (HARQ and RLC) before TCP sees a loss, trading loss for latency spikes.','HARQ and, where configured, acknowledged-mode RLC can recover some radio losses before TCP sees them. Retry limits and unacknowledged modes mean not every loss is hidden.')
r('**Handovers** cause brief stalls.','**Handovers** can cause interruption or loss of varying duration.')
r('logically separate end-to-end networks with their own quality guarantees','logical networks with selected capabilities and policies; actual end-to-end guarantees require provisioned resources, isolation, admission control and an enforceable service agreement')
r('**Multi-access edge computing** (MEC) puts compute at or near the UPF, inside the operator\'s network, so traffic to an edge application does not travel to a distant cloud region. AWS Wavelength is one commercial example. Both matter mainly for specialist uses today; most apps still talk to an ordinary cloud region.','**Multi-access edge computing** (MEC) can place application compute nearer access networks, potentially reducing the path to a distant cloud region. Placement is not necessarily beside a UPF, and a nearby server alone does not guarantee low end-to-end latency.')
a=s.index('## Key takeaways');b=s.index('## Further reading',a)
s=s[:a]+'''## Key takeaways
- Cellular separates user equipment, radio access and core functions. Session anchoring can preserve addresses across supported handovers.
- Scheduled data access coexists with random access, configured grants and interference; cellular is not universally collision-free.
- NR numerology, architecture options and state behaviour are release- and configuration-dependent.
- Batching can reduce radio activity, but a fixed-tail model measures interval coverage, not battery energy.
- Plan for changing capacity, addressing, translation and interruptions. Migration-capable transports also have prerequisites.

> [!note] Evidence limits
> Fixed handover success speeds, radio-state timings, spectrum-wide range figures, operator market shares and guaranteed energy/latency improvements are omitted because no deployment evidence establishes them here. Complete release-specific band tables and advanced inactive-state data procedures are outside this lesson. No cellular modem or operator-network experiment was run.

''' +s[b:]
s+='\n- [Android: Optimise network access and radio use](https://developer.android.com/develop/connectivity/network-ops/network-access-optimization)\n- [RFC 6877: 464XLAT](https://www.rfc-editor.org/rfc/rfc6877)\n- [3GPP TS 38.211 Release 17: NR physical channels and modulation](https://www.etsi.org/deliver/etsi_ts/138200_138299/138211/17.06.00_60/ts_138211v170600p.pdf)\n'
p.write_text(s)
