exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-system-design-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/system-design/08-architecture/'
src=['https://spark.apache.org/docs/latest/sql-performance-tuning.html','https://nightlies.apache.org/flink/flink-docs-stable/docs/connectors/datastream/guarantees/','https://iceberg.apache.org/spec/','https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/','https://spark.apache.org/docs/latest/rdd-programming-guide.html']
patch(b+'arch-batch-vs-stream.md',[
('Your transactional databases answer "what is the state *now*?" for one user at a time.', 'Transactional databases commonly support many concurrent users and operational queries.'),
('| Latency | minutes–hours | ms–seconds |', '| Latency | Depends on job and scheduling | Depends on processing and trigger policy |'),
('Google\'s 2004 **MapReduce** paper showed how to process petabytes on thousands of cheap, failure-prone machines', 'Google\'s 2004 **MapReduce** paper described processing large datasets on clusters of commodity machines'),
('(HDFS replicas)', '(Google used GFS; Hadoop uses HDFS replicas)'),
('tasks are deterministic and inputs are immutable, so a failed task is simply rerun elsewhere.', 'with deterministic functions over stable input and framework-managed output commit, failed tasks can be rerun elsewhere. Arbitrary external side effects are not made exactly-once by task retries.'),
('a job never modifies its input, so reruns are safe.', 'the framework convention is to read stable input and publish new output. User code must avoid unsafe external mutations; the framework does not make every program safe to retry.'),
('each MapReduce stage writes its full output to disk (and the DFS) before the next starts.', 'map output is materialized on local disk and reducer output is written to the distributed file system; reducers can fetch completed map outputs before all maps finish. Chained jobs materialize intermediate results.'),
('instead of replicating intermediate data, Spark remembers', 'Spark can remember'),
('and recomputes lost partitions from their parents.', 'and recompute lost partitions from their parents. Persistence can also use disk or replication; deterministic transformations and stable sources matter for reproducibility.'),
('`map` and `filter` work per partition with no network traffic; `groupBy` and `join` need a **shuffle**, which is usually the most expensive part of a job.', 'map and filter do not themselves redistribute rows; reading input can still use the network. Grouping and joins often need a shuffle, but existing partitioning, broadcasting or storage-partition joins can avoid it. Inspect the physical plan.'),
('the processor\'s estimate that "no more events older than T will arrive". When the watermark passes the end of a window, the window can be emitted. Events arriving later still are *late data*: drop them, or update the result.', 'an event-time progress estimate, not a promise that older data cannot arrive. Window triggers and cleanup depend on the engine and allowed-lateness policy; late data can update results, go to a side output or be dropped.'),
('Flink combines checkpoints with replayable sources (Kafka offsets) and transactional or idempotent sinks, so each event affects the output exactly once even after failures. The *processing* may happen more than once; the *effect* doesn\'t.', 'Flink can recover internal state consistently using checkpoints and replayable sources. End-to-end effects require a compatible transactional sink or a carefully ordered, versioned idempotent design. An arbitrary external call or plain keyed upsert does not automatically give exactly-once observable behavior.'),
('A bug or approximation in the speed layer only affects the last few hours, and is corrected automatically on the next batch run.', 'A correct batch recomputation can replace inaccurate recent views once it covers their period. This depends on correct retained input, batch logic and reconciliation; it is not a universal hours-long error bound.'),
('It requires long log retention (or tiered storage in Kafka) and a processor with good state management and exactly-once semantics, which Flink and Kafka Streams now provide.', 'It requires sufficient retained history, correct state/replay handling and sinks appropriate to the application. Built-in exactly-once support can help but is not a definition of Kappa or a guarantee for arbitrary external side effects.'),
('A **data warehouse** (Snowflake, BigQuery, Redshift) stores cleaned, structured data in **columnar** format, optimised for SQL analytics. Schema is enforced on write.', 'A **data warehouse** (Snowflake, BigQuery, Redshift) provides managed analytical queries, commonly using columnar storage. It can hold raw and semi-structured as well as cleaned data; schema behavior depends on its table and data types.'),
('providing ACID transactions, schema evolution, time travel and efficient metadata,', 'providing table-level commit/snapshot mechanisms, schema evolution and metadata used by compatible engines. Exact transaction scope and retained time-travel history depend on the format, catalog, engine and configuration,'),
('Always: keep **immutable raw data** so any derived result can be recomputed after a bug fix.', 'Retain sufficient raw data or suitable snapshots for the required rebuild horizon, subject to deletion and retention requirements. Reproducible replay also needs relevant schemas, code and external inputs.'),
('Stream processing needs event-time windows, watermarks, durable state and checkpointing to give correct, exactly-once results.', 'Stateful event-time processing uses windows, progress policies and recovery mechanisms. End-to-end correctness also depends on source and sink semantics; not every stream job needs windows or state.')], 'Correct MapReduce persistence/retries, Spark shuffle exceptions, watermark guarantees and end-to-end sink semantics.',src)
def batch(q):
 q[0]['options'][1]['explanation']='This requirement favors continuous low-latency processing. Fraud detection can also occur later; the one-second deadline is this product\'s constraint.'
 q[0]['workedExample']=q[0]['workedExample'].replace('the result loses its value after a second or two (the payment is approved)', 'this product requires a result within a second')
 q[2]['workedExample']=q[2]['workedExample'].replace('When the watermark passes 08:01, e.g. watermark = max event time seen − 2 min.', 'When the configured event-time trigger fires for that window. A simplified watermark can lag observed event time; actual generators, input minima and idle-input handling matter.')
 q[3]['prompt']='A Spark shuffle aggregation groups 2 billion orders by customer_id. One hot key accounts for 25% of rows, and the physical plan shows those 500 million rows concentrated in one long-running task. Which diagnosis and mitigation fit?'
 q[3]['options'][0]['explanation']='More executors alone do not divide this one hot-key task; change the aggregation plan or distribution.'
 q[3]['options'][1]['text']='Data skew: for a mergeable aggregate such as SUM, partially aggregate by a salted key, then combine the partial sums by customer_id.'
 q[3]['options'][1]['explanation']='This divides a hot key\'s initial work while preserving the aggregate. Verify semantics: not every aggregate can be combined by summing partial results.'
 q[3]['workedExample']='1. The plan confirms skew: 25% × 2 billion = 500 million hot-key rows.\n2. The other 1.5 billion rows would average about 7.5 million over 199 partitions if evenly distributed; actual hashing can add other rows to the hot partition.\n3. For SUM, assign salt buckets, compute partial sums by (customer_id, salt), then sum partials by customer_id.\n4. NULL keys are a legitimate group in aggregation; dropping them changes the result. For an ordinary inner equijoin, NULLs do not match and Spark may already filter them.\n5. AQE skew-join splitting is not a universal automatic fix for every hot-key aggregation.'
 q[4]['workedExample']=q[4]['workedExample'].replace('Requires a reliable processor with state and exactly-once (Flink, Kafka Streams).', 'Needs a replay/state/output design meeting the application\'s correctness requirements; built-in exactly-once support alone does not cover arbitrary external systems.')
 q[5]['options'][1]['text']='Restore state and source positions consistently; use a supported checkpoint-coordinated transactional sink, or a proven idempotent versioned output protocol that rejects stale attempts.'
 q[5]['options'][1]['explanation']='A plain merchant-key upsert can expose rewound totals or let stale retries overwrite newer output. State recovery plus arbitrary upserts is not sufficient for exactly-once observable results.'
 q[5]['workedExample']='1. Restore merchant state and Kafka positions from the same completed checkpoint, then replay.\n2. Bare increments can double count output already written before failure.\n3. Bare SET total can temporarily regress and race stale retries. A versioned, fenced idempotent protocol must define and enforce output ordering.\n4. A compatible transactional sink coordinates commit/abort with checkpoints and recovery; validate its actual guarantees and timeouts.\n5. Internal state consistency and externally observable effects are separate guarantees.'
 q[6]['prompt']=q[6]['prompt'].replace('read half-written data', 'see incomplete multi-file table updates')
 q[6]['options'][1]['explanation']='Columnar files can reduce scan work, and compatible table-format readers use atomic metadata commits for consistent snapshots. Catalog and schema governance remain necessary; this does not fix every slow query.'
 q[6]['workedExample']=q[6]['workedExample'].replace('Half-written reads: no atomic commit.', 'Incomplete table updates: S3 objects are individually atomic, but an arbitrary set of files is not a table transaction.').replace('readers see old or new, never partial.', 'compatible readers see one committed snapshot; bypassing the table metadata loses that guarantee.')
 q[7]['options'][0]['explanation']='A tumbling window partitions time into disjoint blocks, so it cannot represent the trailing ten minutes at every minute boundary. Early triggers may still emit partial results more often.'
 q[7]['workedExample']=q[7]['workedExample'].replace('Tumbling: span = refresh.', 'Tumbling: non-overlapping fixed blocks; trigger frequency is separate.')
 q[8]['options'][0]['explanation']='A 24-hour delay still does not prove that nothing arrives later. It also delays watermark-driven final output and increases retained state.'
 q[8]['options'][2]['explanation']='Early and corrected results can meet freshness needs; retained side-output events must actually be reconciled to achieve eventual completeness. Use versioned window outputs or transactional updates.'
 q[9]['options'][2]['text']='After verified catch-up, switch readers through a supported atomic pointer change; retain and keep v1 current during any required rollback window before retiring it.'
 q[9]['options'][2]['explanation']='Catch-up and a coordinated cutover avoid serving partial recomputation. Dropping the old output immediately would remove the proposed rollback path.'
 q[9]['options'][4]['explanation']='Use independent consumer identity and offset management. Kafka group-managed consumers would divide partitions, while modern Flink sources can assign partitions themselves; sharing group identity is not a safe way to run independent replay jobs.'
 q[9]['workedExample']=q[9]['workedExample'].replace('90 days at 5× live speed takes about 18 days', 'with a constant live arrival rate, 90 days of backlog processed at 5× that rate catches up in 90/(5−1) = 22.5 days').replace('stop v1, drop `agg_v1`.', 'retire v1 and its output only after the required rollback window and verification.')
 q[10]['prompt']+=' Assume the large inputs do not already have compatible partitioning and no broadcast or storage-partition join is selected.'
 q[10]['options'][3]['explanation']='Under these assumptions a sort-merge join redistributes inputs by key. Compatible pre-partitioning or a different supported join plan can avoid shuffling one or both sides.'
 q[11]['prompt']+=' Assume equal per-day volume, decimal units, the date predicate is fully resolved by partition pruning, and ignore metadata/encoding overhead. Compare with an unpartitioned JSON scan.'
 q[11]['workedExample']=q[11]['workedExample'].replace('Overall ≈ 360,000× less I/O.', 'The ideal ratio is 200 × 365 × 5 = 365,000× fewer payload bytes under these assumptions; actual I/O includes metadata and layout effects.')
questions(b+'arch-batch-vs-stream.questions.json',batch,'Fix Spark NULL/skew example, plain-upsert exactly-once claim, live replay catch-up arithmetic and window/columnar assumptions.',src)
report['reviewed_files']=list(dict.fromkeys(report.get('reviewed_files',[])+[b+'arch-batch-vs-stream.md',b+'arch-batch-vs-stream.questions.json']))
p_report.write_text(json.dumps(report,indent=2)+'\n')
