from pathlib import Path
import json
p=Path('content/architecture/03-isa/isa-risc-cisc.md');s=p.read_text()
s=s.replace('came from research in the early 1980s:', 'grew from research in the 1970s and 1980s, including')
s=s.replace('only loads and stores touch memory; arithmetic works on registers.', 'ordinary ALU operations use registers/immediates, with separate memory-transfer instructions. Atomic read-modify-write instructions are an important extension.')
s=s.replace('every instruction the same size (32 bits), easy to fetch and decode.', 'often a 32-bit base encoding, simplifying boundary detection; compressed extensions are exceptions.')
s=s.replace('32 registers rather than 8, so values stay out of memory.', 'typically a relatively large register file, reducing spills; exact counts vary by ISA.')
s=s.replace('where `a` is an `int *`.', 'where `a` points to 32-bit integers, the index is in range and the increment does not overflow a signed C `int`. These are ordinary non-atomic updates.')
s=s.replace('On ARM64 memory is touched only by loads and stores, so it takes three:', 'Using ordinary AArch64 load, add and store instructions takes three:')
s=s.replace('The x86 version is 4 bytes; the ARM64 version is 12. But inside a modern x86 core, that one `add` is cracked into roughly the same steps (load, add, store) anyway.', 'The shown x86 encoding is 4 bytes; the A64 sequence is 12. The x86 instruction still requires a read, arithmetic and a write internally; the number and fusion of micro-ops depend on the core. A single memory-operand instruction is not automatically an atomic inter-thread increment.')
s=s.replace('It means each instruction is simple and regular, and memory is accessed only by loads and stores.', 'The label describes design tendencies, not a rule that every instruction does only one simple operation. AArch64 includes atomic read-modify-write and other specialized operations.')
s=s.replace('Every register field is 5 bits (32 values: x0 to x30 plus a special 31, which means the zero register or the stack pointer depending on the instruction). Because fields sit in fixed places, the decoder can pull out register numbers before it even knows the exact instruction. That makes wide decoding easy: Apple\'s M1 performance cores decode eight instructions per cycle.', 'The general-purpose register fields in this format are 5 bits: encodings 0–30 name numbered registers, while 31 has instruction-dependent special meaning. Regular field placement helps decoding, but not every A64 instruction uses this format. An exact Apple M1 decode-width claim is omitted because a primary hardware specification establishing it was not available in this review.')
s=s.replace('| `movz`/`movk` | 16 bits, placed at bit 0, 16, 32 or 48 |','| 64-bit `movz`/`movk` | 16 bits, placed at bit 0, 16, 32 or 48 |')
s=s.replace('| `and`/`orr` | repeating bit patterns ("bitmask immediates") |','| Immediate `and`/`orr` | repeated, rotated nonempty runs of ones within power-of-two-sized elements; not arbitrary repeated patterns |')
s=s.replace('| `ldr`/`str` offset | 12 bits, scaled by access size |','| Unsigned-offset scalar `ldr`/`str` | 12 bits, scaled by access size; other addressing forms differ |')
s=s.replace('An instruction is assembled from optional pieces:', 'A common legacy/REX encoding uses these pieces. This is a schematic, not the complete encoding grammar: VEX, EVEX and APX/REX2 add other forms, and not every combination below is valid.')
s=s.replace('prefixes   0-4 B    lock, rep, size...', 'prefixes   varies   legacy groups: lock, rep, size...')
s=s.replace('three-operand**: `add x0, x1, x2` leaves both sources intact.', 'three-operand**: `add x0, x1, x2` leaves both distinct source registers intact. x86 also has three-operand instruction families, including AVX and APX forms; do not generalize the legacy ADD syntax to the whole ISA.')
s=s.replace('common instructions are 1–3 bytes, so more code fits in the instruction cache.', 'short encodings can reduce instruction-cache footprint; actual code density depends on the instruction mix.')
s=s.replace('Wide x86 decoders are complex and power-hungry, which is why modern x86 cores cache already-decoded micro-ops in a **µop cache**.', 'Boundary detection adds work, although predecoding and parallel candidate decoding can help. Some x86 cores cache decoded **micro-ops**; this is not an ISA requirement or a universal core feature.')
s=s.replace('| Pre-/post-index | none |', '| General load/store pre-/post-index | no general bracket form; string/stack instructions can update pointers implicitly |')
s=s.replace('`p->next` is `[p + 8]`', '`p->next` could be `[p + 8]` for a layout with that field offset')
s=s.replace('x86-64 reaches ±2 GB from RIP; ARM64\'s `adrp` reaches ±4 GB in 4 KB pages, with the low 12 bits added by the next instruction.', 'A normal x86-64 RIP-relative disp32 ranges from −2 GiB to +2 GiB−1 relative to the next instruction. AArch64 `adrp` uses a signed 21-bit offset in 4 KiB units from the current PC rounded down to a 4 KiB boundary (−4 GiB through +4 GiB−4 KiB); a subsequent instruction can supply the low offset. These are encoding units, not a requirement that the OS use 4 KiB pages.')
s=s.replace('as a free shift-and-add:', 'as a shift-and-add that preserves flags (it still consumes execution resources):')
s=s.replace('Since the Pentium Pro (1995), x86 cores translate instructions into internal RISC-like **micro-ops** and execute those out of order. The CISC front end is a translation layer.', 'Many high-performance x86 cores decode instructions into internal **micro-ops** and execute them out of order. Neither out-of-order execution nor any particular micro-op format is mandated by x86; some x86 implementations are in-order.')
a=s.index('What still differs');b=s.index('## Pitfalls',a)
s=s[:a]+'''Encoding, available operations, memory-ordering rules and compatibility requirements remain important differences. Do not infer a whole chip’s power consumption or performance from “RISC” or “CISC” alone.

A detailed account of market-share causes and a universal quantitative decoder-power comparison are omitted: these require evidence about particular products, workloads and periods, beyond the architectural contracts reviewed here.

'''+s[b:]
s=s.replace('On ARM64, `add` takes 0–4095; bigger constants need extra instructions or a different form.', 'The A64 immediate ADD form accepts 0–4095, optionally shifted left 12. Other constants need a different sequence.')
s=s.replace('RISC: load/store, fixed-length, many registers, regular formats. CISC: memory operands, variable length, more work per instruction.', 'RISC and CISC are broad design traditions. Load/store organization and regular formats are common RISC traits, with exceptions such as compressed encodings and atomic operations.')
s=s.replace('ARM64 instructions are always 32 bits with fixed field positions;', 'A64 instructions are 32 bits with regular instruction formats;')
s=s.replace('x86-64 instructions are 1–15 bytes built from prefixes, REX, opcode, ModRM, SIB, displacement and immediate.', 'x86-64 instructions are 1–15 bytes; the legacy/REX examples use opcode, optional ModRM/SIB, displacement and immediate fields. Newer prefix families add encoding forms.')
s=s.replace('Modern x86 cores translate to RISC-like micro-ops,', 'Many modern x86 cores use internal micro-ops,')
s+='''\n### Primary references\n- [Arm: A64 ISA and compilers](https://developer.arm.com/community/arm-community-blogs/b/architectures-and-processors-blog/posts/the-a64-isa-and-compilers)\n- [Intel XED encoding documentation](https://github.com/intelxed/xed/blob/main/docsrc/xed-doc-top.txt)\n- [RISC-V compressed extension specification](https://docs.riscv.org/reference/isa/v20260120/unpriv/c-st-ext.html)\n- [IBM’s RISC history](https://www.ibm.com/history/risc)\n'''
p.write_text(s);p=p.with_suffix('.questions.json');q=json.loads(p.read_text())
q[0]['options'][1]['explanation']='AArch64 uses 64-bit general-purpose address operands, with implemented virtual and physical address widths depending on architectural features and configuration. ADRP reach is not a whole-memory limit.'
q[0]['options'][3]['text']='Ordinary ALU instructions use registers/immediates rather than memory operands; memory transfers use separate instructions'
q[0]['options'][3]['explanation']='Correct for ordinary arithmetic such as ADD. Atomic read-modify-write instructions are an important specialized exception to an overbroad “only plain loads/stores access memory” rule.'
q[0]['workedExample']='Load/store organization separates ordinary ALU arithmetic from memory transfers. It does not impose a small instruction count, a 4 GB address-space limit or one-cycle completion, and modern extensions include atomic memory operations.'
q[1]['workedExample']='Effective address = 0x2000 + 5 × 8 + 16 = 0x2038. The displacement is in bytes. This can describe a fixed header plus indexed 8-byte elements; a 16-byte field offset would not lie within an 8-byte struct element.'
q[2]['workedExample']='The ordinary A64 ADD instruction accepts register/immediate operands, not the bracketed memory operand in option 3. LDR followed by ADD performs the proposed load-and-add. This statement does not exclude specialized atomic read-modify-write instructions.'
q[4]['workedExample']=q[4]['workedExample'].split('Fixed field positions')[0]+'Regular placement of register fields helps decoding; actual hardware cost depends on the implementation.'
q[7]['prompt']=q[7]['prompt'].replace('`edi = 7`','`rdi = 7`')
q[8]['prompt']='Why does finding several instruction boundaries in a fetch block require extra work for variable-length x86 encodings compared with fixed-width A64?'
q[8]['options'][0]['explanation']='Fixed-width A64 boundaries follow at four-byte intervals from an aligned instruction start. x86 length depends on instruction fields, so parallel decoding needs boundary detection or precomputed boundary information. Particular cores may use decoded-instruction caches.'
q[8]['options'][1]['explanation']='Register count does not explain variable instruction boundaries. Baseline x86-64 has 16 general-purpose registers; APX extends it to 32.'
q[8]['options'][3]['explanation']='The central issue is variable instruction length, not data endianness. A64 instruction encoding has its own fixed byte-order rules independent of configurable data endianness.'
q[8]['workedExample']='A 32-byte block beginning on an A64 instruction boundary contains eight complete A64 instructions. An x86 block can contain varying numbers of complete instructions plus partial ones. Hardware can use length detection, predecode metadata or speculative candidate decoding; decoded-instruction caches can avoid some repeated work. This does not make a wide A64 decoder effortless.'
q[9]['prompt']+=' Count only instruction bytes and one constant, ignoring alignment padding, branch-around code and pool sharing.'
q[9]['options'][2]['explanation']='For this particular constant, the stated move-wide sequence uses four instructions. Some other 64-bit constants fit one encoded pattern, so “64-bit value” alone does not prove four are necessary.'
q[9]['workedExample']='The specified x86 encoding is 2 + 8 = 10 bytes. Four A64 instructions occupy 16 bytes. One literal LDR plus one 8-byte constant uses 12 bytes before padding or branch-around code. The load has memory-system costs; sharing a literal can amortize its data bytes. These counts do not determine which approach is faster.'
q[10]['options'][0]['text']='Many high-performance x86 cores decode instructions into internal micro-ops and execute out of order'
q[10]['options'][0]['explanation']='Correct for many implementations; it is not mandated by the ISA and does not describe every x86 core.'
q[10]['options'][3]['text']='Variable-length encodings can improve code density for suitable instruction mixes, while requiring boundary detection'
q[10]['options'][3]['explanation']='Correct as a trade-off, not a promise that every x86 program is smaller than its A64 equivalent.'
q[10]['workedExample']='The first, second and fourth statements are true with their stated qualifications. A64 is fixed at 32 bits; Thumb-2 and RISC-V compressed extensions illustrate mixed instruction lengths. Microarchitecture and workload determine performance, not the RISC/CISC label alone.'
p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Applied RISC/CISC lesson and 11-question corrections')
