import json
from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-debugging.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['options'][1]={'text':'The connection attempt was explicitly refused, commonly by a reset or rejection; check the listener and path policies','explanation':'Correct. The error alone does not prove that the intended destination host generated a RST. Captures and server checks can establish the source.'}
q(1)['workedExample']='Immediate refusal differs from waiting for a deadline, but it does not identify a unique cause. Check the intended service address/port and listening sockets, then inspect host/path rejection rules and capture evidence. A timeout can reflect loss, overload, routing or a deadline that was too short; it does not prove silent firewall dropping.'
q(2)['options'][1]['explanation']='Correct as the basic technique. Reply suppression, filtering, tunnels and different probe paths can leave missing or ambiguous hops.'
q(2)['workedExample'] += '\n\nThe discovered interfaces need not form one immutable forward path, and displayed RTT includes each probe’s return path. Routers need not respond to every probe.'
q(3)['prompt']=q(3)['prompt'].replace('What is the approximate network round-trip time to the server?','Assume one fresh direct TCP connection, no retries, proxies, address-racing delays or reuse, and negligible local overhead. What approximate RTT does the connect-minus-DNS interval suggest?')
q(3)['workedExample']='Under the supplied idealisation, 0.050 − 0.010 = 0.040 seconds approximates handshake RTT. The TLS phase is 80 ms, but timing alone does not establish TLS version. The subsequent 50 ms to first byte includes request/network/server effects; it does not measure server CPU time. Body reception lasts another 20 ms.'
q(4)['options'][0]['explanation']='Missing intermediate replies do not directly measure the loss rate of traffic forwarded to the destination. Separate probes may also take different paths.'
q(4)['options'][1]={'text':'Intermediate reply handling is a plausible explanation; these samples do not establish 38% end-to-end forwarding loss','explanation':'Correct. Rate limits, reply processing and return paths can explain the pattern. Further measurements are needed before claiming the whole forwarding path is fault-free.'}
q(4)['options'][2]['explanation']='The final samples show no observed loss for those probes, but finite sampling and differing probe/application paths limit the conclusion. Asymmetry alone does not invalidate every measurement.'
q(4)['workedExample']='Hop 4’s probes receive fewer/slower replies, while the displayed destination probes succeeded. That often points to intermediate response behaviour rather than persistent 38% transit loss. It is not proof of one cause: routing, timing and return paths can differ. Compare sustained end-to-end application tests and captures rather than declaring that only loss repeated at every later hop is real.'
q(5)['prompt']=q(5)['prompt'].replace('What is the most likely cause?','Which hypothesis is consistent with this capture and should be tested further?')
q(5)['options'][0]['explanation']='A reachable closed port often returns RST, but filtering, return-path loss or host conditions can hide it. Silence does not prove a listener exists.'
q(5)['options'][1]['explanation']='Correct as a plausible hypothesis. The capture only establishes that replies were not observed here; it does not locate the missing traffic or exclude host overload/unavailability.'
q(5)['options'][2]={'text':'The capture proves the database is responding normally and only the application accept call is slow','explanation':'False. A listener or resource overload can affect setup, but these client-side packets do not prove normal server response.'}
q(5)['workedExample']='The displayed SYN gaps are 1, 2 and 4 seconds, with no captured reply. That is a supplied trace, not every Linux version’s default schedule. Check both directions and the server: if SYNs arrive, inspect listener/resource state, policy and response transmission; if they do not, inspect upstream forwarding and capture coverage. Missing RST does not uniquely rule out a closed port.'
q(6)['prompt']=q(6)['prompt'].replace('Which test best confirms the likely cause?','Which listed test directly probes the suspected size-dependent path behaviour?')
q(6)['options'][1]['text']='On Linux, compare ping -4 -M do -s 1472 server with smaller sizes, alongside captures and ICMP-policy checks'
q(6)['options'][1]['explanation']='Correct. This gathers PMTU-related evidence. Failure alone can also reflect ICMP filtering or local PMTU state; it does not prove blocked fragmentation-needed messages.'
q(6)['options'][2]['explanation']='Default small traceroute probes may miss a size-dependent issue. Configurable packet sizes and PMTU-oriented tools can offer additional evidence.'
q(6)['workedExample']='Small-success/large-failure after adding encapsulation supports an MTU hypothesis. Under IPv4 without options, 1,472 echo payload bytes produce 1,500 IP bytes and 1,372 produce 1,400. Establish the effective MTU, direction and missing error feedback with captures. Correct ICMP/MTU handling or a justified TCP MSS setting can help; a fixed MSS value is not a universal VPN repair.'
q(7)['prompt']=q(7)['prompt'].replace('Which conclusions are justified?','Assume one new direct TCP/TLS connection, negligible local connect overhead and no proxy/retry/reuse. Which statements are justified?')
q(7)['options'][1]={'text':'The measured TLS phase is 302 ms, roughly twice the ideal 148 ms connect-RTT estimate, but this does not identify TLS version','explanation':'Correct. Several protocol, processing and network effects can affect handshake duration.'}
q(7)['options'][2]['explanation']='TTFB is cumulative and includes earlier setup. The 158 ms after TLS still contains network/request/server effects, so it does not isolate server execution time.'
q(7)['options'][3]['explanation']='Correct. The interval after first byte is 3 seconds. Check payload size, streaming/server pauses, path throughput and endpoint limits.'
q(7)['workedExample']='The intervals are DNS 2 ms, connect 148 ms, TLS 302 ms, post-TLS to first byte 158 ms and remaining transfer 3,000 ms. Under the supplied assumptions connect approximates RTT. Neither TLS version, geographic distance nor server processing time follows uniquely from these numbers. The body interval dominates this sample, but server streaming delays can contribute as well as network throughput.'
q(8)['prompt']='In the ideal Reno Mathis model, use MSS 1,460 bytes, RTT 20 ms and p = 0.001 (0.1%), with rate ≈ (MSS/RTT) × 1.22/√p and byte-to-bit conversion. What rate does the formula return?'
q(8)['options'][3]['explanation']='About 2.25 Mbit/s would result from using p = 0.1 (10%), whose square root is ten times √0.001. Using 1% loss would give a different value, about 7.12 Mbit/s.'
q(8)['workedExample']=q(8)['workedExample'].split('So a 1 Gbit/s')[0]+'This is a model result for the supplied Reno assumptions, not a universal loss-based TCP ceiling or a prediction obtained from ping alone.'
q(9)['prompt']='A single backlogged TCP flow has a measured effective flight-window limit of 4,000,000 bytes and a fixed 80 ms RTT. Assume sufficient link capacity and no tighter bottleneck. What limit does the window/RTT model give?'
q(9)['workedExample']=q(9)['workedExample'].replace('3. Fix: raise socket buffers (and the kernel\'s `tcp_rmem`/`tcp_wmem` limits), or use parallel streams. Upgrading the link would change nothing.','3. Identify which measured limit is binding before changing configuration. Socket-memory settings, advertised receive window and cwnd are distinct. The model alone does not prescribe a buffer increase or parallel streams.')
q(10)['prompt']=q(10)['prompt'].replace('Where is the bottleneck?','Which constraint is directly evidenced, and where should investigation start?')
q(10)['options'][2]={'text':'Receiver flow control is stopping new data; investigate application consumption and receive-side resource/window policy','explanation':'Correct. A zero advertised window is not a raw free-memory reading and does not prove slow disk or a blocked application is the only cause.'}
q(10)['workedExample']='A zero advertised receive window permits no further ordinary new data in that window. The sender’s probes and later bursts are consistent with flow-control stalls. Inspect receive queues, memory limits, window behaviour and application consumption. The trace does not uniquely identify the server’s disk, nor prove there are no other network problems.'
q(11)['prompt']='An API gateway fails to allocate resources for new outbound TCP connections while established traffic continues. OS diagnostics point to new-flow resource pressure rather than a path-wide outage. Which are direct resource-exhaustion candidates? Select all that apply.'
q(11)['options'][2]['explanation']='A PMTU problem is a path/packet-size issue, not direct exhaustion of the new-flow allocation resources specified here. It can affect setup or later protocol data in other circumstances.'
q(11)['options'][3]['explanation']='RTT alone is not an exhausted allocation resource, though long connection lifetimes and short application deadlines can contribute to pressure or failures.'
q(11)['workedExample']='Inspect conntrack/NAT capacity, socket/descriptor limits and usable source tuples. A simplified single-destination model with 28,232 ephemeral ports, a 60-second TIME_WAIT hold, no reuse and negligible active lifetime gives 28,232/60 ≈ 470.5 new connections per second. This is not a universal Linux limit: configuration, tuple reuse, source addresses and active connection lifetime alter it. Use errors and counters to establish the actual limit.'
q(12)['workedExample']='The supplied gaps are 1, 2, 4 and 8 seconds. Continuing that exact rule gives a 16-second next gap, so the next SYN is at 15 + 16 = 31 seconds. This is arithmetic for the specified trace, not a universal current Linux retry schedule. Set application deadlines based on requirements and measured behaviour; no fixed 1–5 second recommendation follows.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
p=Path('content/networks/06-wireless-modern/wm-debugging.md');p.write_text(p.read_text().replace('a observed reply','an observed reply'))
