import json
from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-datacentre.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['prompt']='In a healthy fully connected two-tier fabric, each rack has one leaf and every leaf has one equal-cost link to each of 8 spines. No service-chain detour is used. Between servers on different leaves, how many switches are traversed and how many shortest paths connect the leaves?'
q(1)['options'][2]['explanation']='There is one eligible shortest path per spine under the stated topology. Choosing only one route would not by itself imply STP is in use.'
q(2)['options'][1]['explanation']='Correct. Different path delays can cause reordering and potentially spurious loss recovery. The response depends on the TCP algorithm and its reordering tolerance.'
q(2)['workedExample']='Per-packet path variation can reorder arrivals. A flow-stable hash avoids reordering caused by this selection while its mapping stays unchanged. TCP does not always respond by halving cwnd: detection and congestion response vary. Failure, remapping or other network elements can still reorder packets.'
q(3)['options'][2]['explanation']='This incorrectly compares port counts alone: 40/4 = 10. The port speeds differ, so use aggregate bandwidths.'
q(3)['workedExample']=q(3)['workedExample'].replace('each gets 160 / 40 = 4 Gbit/s instead of 10. Traffic that stays inside the rack is unaffected.','the aggregate 160 Gbit/s uplink limits off-rack traffic. Equal sharing would give 4 Gbit/s each, but this is not guaranteed. Direct same-leaf traffic avoids these uplinks, though it can have other limits.')
q(4)['prompt']='A fully connected two-tier fabric has eight spines, each with 32 usable 100 Gbit/s leaf-facing ports and no breakout or reserved ports. Each leaf has eight matching uplinks and 48 ports for one singly attached server each. What is the maximum server count?'
q(5)['prompt']='In a healthy fully connected two-tier fabric, each leaf has 32 × 25 Gbit/s server ports and one 100 Gbit/s link to each of four spines. One spine fails, with no other failure. What is the new leaf oversubscription ratio and the fraction of its nominal aggregate uplink capacity lost?'
q(5)['workedExample']=q(5)['workedExample'].replace('Routing withdraws paths through the dead spine and ECMP rehashes flows onto the other three.','After failure detection and routing convergence, traffic can use the surviving paths. Transient loss and exact remapping depend on the implementation.')
q(6)['workedExample']=q(6)['workedExample'].replace('each backup gets half a link while two links sit idle.','both compete for one link, potentially sharing it unevenly, while three of the four links carry neither backup flow.')
q(7)['options'][0]={'text':'STP can leave redundant links non-forwarding for an instance, while routed ECMP can use multiple paths','explanation':'Correct. The exact capacity left unused depends on the design; it is not necessarily half.'}
q(7)['options'][1]={'text':'The simple two-tier topology gives different-leaf paths the same number of switches','explanation':'Correct. Queueing and other effects can still make latency differ; equal hop count is not a latency guarantee.'}
q(7)['options'][2]['explanation']='Correct when leaves have the necessary ports and links. Scale-out remains subject to port, routing and budget limits.'
q(8)['prompt']='Uniform hash values select next-hop labels [0,1,2,3] by hash mod 4. Link 3 fails; the surviving ordered labels [0,1,2] use hash mod 3. What fraction of flows previously on healthy links change physical uplink?'
q(8)['workedExample']=q(8)['workedExample'].replace('stateful middleboxes behind ECMP lose their connections. Resilient hashing fixes this by moving only the failed link\'s flows.','stateful middleboxes may lose connection state unless it is shared or reconstructable. Resilient hashing can minimise movement, with exact behaviour depending on bucket and rebalancing policy.')
q(9)['options'][0]['explanation']='1,024 is k². The stated host-count formula is k³/4, so another factor of k/4 = 8 is needed.'
q(9)['workedExample']=q(9)['workedExample'].replace('All with identical commodity switches and full bisection bandwidth, which is why the 2008 paper was so influential.','This is the specified even-k topology’s host count. Its provisioned bisection capacity does not mean arbitrary hash-based routing always achieves full throughput for every traffic matrix.')
q(10)['prompt']='A query fans out to 200 shards, each replying with 20,000 bytes. A capture shows a concentrated reply burst, destination egress queue drops, and recovery of some replies only after an approximately 200 ms RTO. Which mechanism explains this measured trace?'
q(10)['options'][0]['explanation']='Upstream oversubscription can matter in other cases, but the supplied trace identifies drops at the destination egress queue.'
q(10)['options'][1]={'text':'Incast overwhelms the destination egress queue, and the affected flows in this trace recover through retransmission timeout','explanation':'Correct. The trace supplies the queue-drop and RTO evidence. Not every incast episode drops packets or waits for a fixed Linux 200 ms timer.'}
q(10)['options'][2]['explanation']='The supplied evidence identifies post-query reply drops and retransmission recovery; no DNS delay is needed to explain this trace.'
q(10)['options'][3]['explanation']='ECMP reordering is possible under some conditions, but the given evidence directly establishes queue drops and timeout recovery.'
q(10)['workedExample']='The total response payload is 200 × 20,000 = 4,000,000 bytes. At 25 Gbit/s it requires 1.28 ms of serialization, ignoring overhead. Whether a particular burst overflows depends on arrival timing and available buffer; here the capture establishes that it did. RACK/TLP or fast recovery could avoid an RTO in other traces. Consider concurrency control, pacing and suitable ECN/AQM configuration; do not blindly lower retransmission timers.'
q(11)['prompt']='Eight stateful L4 load balancers advertise one VIP behind simple modulo ECMP. A member failure remaps many healthy flows to members lacking their state. Which changes can address this mechanism? Select all that apply.'
q(11)['options'][0]['explanation']='Correct as a potential mitigation: an appropriate resilient-hash policy preserves healthy assignments on member removal. Check the actual implementation and rebalancing behaviour.'
q(11)['options'][1]={'text':'Use a design with consistent backend selection plus the shared or reconstructable connection/NAT state needed to handle a flow on another member','explanation':'Correct. Consistent hashing alone is insufficient for arbitrary stateful proxies, SNAT allocations or changing backend sets. All members need compatible configuration and state handling.'}
q(11)['workedExample']='With uniform hashes, simple mod 8 → mod 7 remapping preserves about 1/8 of all physical assignments under stable member ordering; about 6/7 of healthy-member flows move. Resilient network hashing reduces unnecessary movement. A load-balancer design can also make moved traffic recoverable through consistent backend selection and the required state mechanism. Maglev combines hashing and connection tracking; it is not proof that hashing alone fixes every stateful load balancer.'
q(12)['prompt']='An uplink averages 25% utilisation over five minutes and records egress queue drops. Fine-grained telemetry shows short periods when aggregate arrivals exceed the port’s service rate. What explains the coexistence of low average use and drops?'
q(12)['options'][1]={'text':'Bursts of excess arrivals fill the available queue even though quieter periods keep the long-term average low','explanation':'Correct. Queue growth depends on arrivals minus service during the burst, not the five-minute mean. Buffer allocation and competing traffic also matter.'}
q(12)['options'][3]['explanation']='STP blocking does not explain the measured excess-arrival queue growth. Non-forwarding STP ports can still exchange control traffic, so “no traffic at all” would be inaccurate.'
q(12)['workedExample']='If arrivals exceed service by 20 Gbit/s for 1 ms, backlog grows by 20e9 × 0.001 / 8 = 2.5 MB. A smaller available queue can overflow despite low long-term utilisation. The supplied fine-grained evidence supports the burst explanation; a generic output-drop counter alone could also include other platform-specific causes. Investigate queue allocation, shaping, pacing and congestion feedback.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
