from pathlib import Path
import json
B=Path('content/architecture/01-data-representation');p=B/'rep-text-encoding.md';s=p.read_text()
def r(a,b):
 global s
 assert a in s,a
 s=s.replace(a,b)
r('A **character set** assigns each character a number.', 'A coded **character set** assigns numbers to its encoded elements; a user-perceived character can require several of those elements.')
r('three encodings of the same Unicode code points.', 'three encoding forms for Unicode scalar values (code points excluding the surrogate range). UTF-16 and UTF-32 also need a byte-order convention for byte serialisation.')
r('Windows-1252 (a near superset of Latin-1)', 'Windows-1252 (mostly shares Latin-1 assignments but replaces many C1-control positions with other characters)')
r('and hundreds more. A file did not record which it used.', 'and many others. Plain text bytes often lack encoding metadata, though a file format can include such metadata. Shift JIS is variable-width, not merely a different assignment of single high bytes.')
r('**Unicode** gives every character in every script a single code point,', '**Unicode** provides a shared repertoire of encoded characters across many writing systems,')
r('Plane 0, the **Basic Multilingual Plane** (BMP, U+0000 to U+FFFF), holds almost all characters in everyday use. Emoji, historic scripts and rarer CJK characters live in the higher planes. Unicode currently assigns over 150,000 characters, so most of the space is still free.', 'Plane 0, the **Basic Multilingual Plane** (BMP, U+0000 to U+FFFF), includes many common scripts. Supplementary planes contain further scripts, CJK characters and many emoji; some emoji are in the BMP. Not every code point is an assigned character: the code space also includes surrogates, private-use areas, noncharacters and unassigned positions.')
r('The obvious encoding stores each code point as a 32-bit integer. Every character is 4 bytes,', 'UTF-32 stores each Unicode scalar value as one 32-bit code unit. That is four octets per scalar value,')
r('| U+0800–FFFF | 3 |', '| U+0800–FFFF, excluding D800–DFFF | 3 |')
r("The leading byte says how many bytes follow (count its leading 1s),", 'For a valid multibyte sequence, the number of leading 1s gives the **total** byte count, not the number of following bytes,')
r('**ASCII compatible.** Every ASCII file is already valid UTF-8, byte for byte. Old tools that only care about `/`, `\\n` or `,` keep working.', '**ASCII compatible.** ASCII text is valid UTF-8 byte for byte. Tools that recognise only ASCII delimiters can often process UTF-8 unchanged, provided they otherwise preserve arbitrary bytes.')
r('**Self-synchronising.** You can tell from any single byte whether it starts a character (`0xxxxxxx` or `11xxxxxx`) or continues one (`10xxxxxx`). If you land in the middle of a stream, skip at most 3 bytes to resync. A corrupt byte damages one character, not the rest of the file.', '**Self-synchronising.** In a valid UTF-8 stream, continuation bytes start with 10 and other bytes start a sequence. At most three continuation bytes remain after an arbitrary position inside a character. Invalid bytes such as C0, C1 and F5–FF require rejection or specified error handling; corruption is not guaranteed to damage exactly one character.')
r('**Sorting.** Comparing UTF-8 bytes gives the same order as comparing code points.', '**Sorting.** Lexicographic comparison of unsigned bytes in valid UTF-8 agrees with scalar-value order. This is not linguistic collation, and normalisation differences still matter.')
r('Around 98% of websites now use UTF-8, and it is the default for JSON (RFC 8259 requires it for open exchange), HTML5, Linux, macOS, Rust, Go and Python source files.', 'UTF-8 is widely used for interchange. RFC 8259 requires it for JSON exchanged outside a closed ecosystem; Rust and Go source text use UTF-8, and it is Python 3 source\'s default. Operating-system files and C strings are not universally UTF-8, and decoding defaults depend on the interface and configuration.\n\n> [!note] Evidence gap\n> The previous website-adoption percentage is omitted: it lacked a dated survey and sampling definition, so it was not reliable evidence for a current universal figure.')
r('Code points in the BMP take one unit.', 'BMP scalar values (excluding D800–DFFF) take one unit.')
r('UTF-16 exists because Unicode originally promised that 65,536 characters would be enough. Java, JavaScript, Windows (the `W` APIs), .NET and Qt adopted 16-bit characters early, then had to bolt on surrogates when Unicode grew in 1996.', 'UTF-16 extends an earlier 16-bit design with surrogate pairs. Java, JavaScript, Windows W APIs, .NET and Qt use 16-bit code units in their string interfaces; their adoption histories differ, so they should not all be described as pre-1996 adopters.')
r('| Go, Rust, C `strlen` | UTF-8 bytes |', '| Go string len; Rust str.len() | bytes (Rust str is valid UTF-8; Go strings may hold arbitrary bytes) |\n| C strlen | bytes before the first NUL, regardless of encoding |')
r('produces a lone surrogate, which is invalid. In C, `strlen("é")` is 2 in a UTF-8 source file.', 'can produce a lone surrogate: allowed in a JavaScript string but not well-formed UTF-16 for interchange. In C, strlen("é") is 2 if the execution string literal encoding is UTF-8; source-file encoding alone does not guarantee that.')
r('A **grapheme cluster** is what the user perceives as one symbol,', 'An extended **grapheme cluster** approximates a user-perceived character under Unicode segmentation rules,')
r('Cursor movement, truncation ("first 50 characters") and text-field limits should count graphemes.', 'User-facing cursor movement and character limits often need grapheme segmentation. Storage/protocol limits still need byte counts; neither replaces the other.')
r('macOS file systems have historically stored names decomposed, which is why a file created on a Mac can fail to match the "same" name from Linux.', 'HFS+ historically uses a modified decomposed form; other macOS file systems have different storage and comparison rules. Do not assume that all macOS filenames are byte-for-byte standard NFD.')
r('When UTF-8 bytes are decoded as Windows-1252, every non-ASCII character becomes 2 to 4 junk characters:', 'Decoding UTF-8 bytes as Windows-1252 often produces mojibake, but some bytes are undefined in strict Windows-1252 decoders and can raise errors:')
r('If you see `Ã©` or `â€™` (a curly apostrophe), something decoded UTF-8 as Windows-1252.', 'Sequences such as `Ã©` or `â€™` often indicate UTF-8 decoded as Windows-1252 (though the displayed text alone is not conclusive).')
r('so it cannot store anything above U+FFFF, including emoji.', 'so it cannot store supplementary characters such as 😀. Some emoji are BMP characters and do fit.')
r('Validate, then check.', 'Decode strictly, apply the protocol\'s canonicalisation rules, then validate the decoded path and enforce containment in the intended directory. Unicode normalisation alone is not a path-traversal defence.')
r('functions like `toupper` work on single bytes and mangle multi-byte UTF-8 characters.', 'functions such as toupper operate on unsigned-char values (or EOF) according to the C locale, not arbitrary Unicode characters. Passing a negative signed char is undefined behaviour. Processing UTF-8 byte by byte this way is not Unicode case conversion and may leave bytes unchanged or corrupt them, depending on the locale.')
r('- Normalise (usually NFC) before comparing user text.', '- Choose normalisation and comparison rules for the application. NFC handles canonical equivalence; do not silently change text when exact original bytes or a protocol-specific form are required.')
p.write_text(s)
p=B/'rep-text-encoding.questions.json';qs=json.loads(p.read_text());q={str(i+1):v for i,v in enumerate(qs)}
q['1']['options'][2]['explanation']='Three-byte encodings cover scalar values U+0800–FFFF, excluding the surrogate range, such as € (U+20AC).'
q['1']['options'][3]['explanation']='Four-byte UTF-8 encodes supplementary scalar values above U+FFFF, including many emoji (some emoji are in the BMP).'
q['1']['workedExample']=q['1']['workedExample'].replace('the most common source of mojibake.', 'one common cause of mojibake.')
q['3']['prompt']=q['3']['prompt'].replace('a UTF-8 stream', 'a valid UTF-8 stream')
q['5']['workedExample']=q['5']['workedExample'].replace('Most CJK characters take 3 bytes in UTF-8 but 2 in UTF-16, one reason some East Asian systems preferred UTF-16.', 'This BMP ideograph takes 3 bytes in UTF-8 and 2 in UTF-16. Supplementary CJK characters take 4 bytes in either encoding; repertoire counts are not the same as text-frequency statistics.')
q['7']['options'][0]['explanation']='Typical UTF-16 encodings of this ASCII-heavy text introduce NULs when misread as UTF-8; they do not explain the specific E2 80 99 → â€™ transformation.'
q['7']['workedExample']=q['7']['workedExample'].replace("If the bad text has already been saved, it is double-encoded and must be repaired, e.g. `s.encode('cp1252').decode('utf-8')`.", "If this exact reversible mis-decoding is confirmed, s.encode('cp1252').decode('utf-8') can undo it. It is not a general repair: mixed encodings, replacement characters or lost bytes may make reversal impossible; preserve a copy first.")
q['8']['options'][1]['text']='In valid UTF-8, each byte can be classified as starting a scalar-value encoding or continuing one'
q['8']['options'][4]['explanation']='Correct. All bytes of multibyte sequences have the high bit set. A U+0000 inside text still terminates a C string, so arbitrary Unicode text needs explicit length handling.'
q['10']['prompt']=q['10']['prompt'].replace('A legacy MySQL table', 'A MySQL 8.4 table')
q['10']['options'][2]['explanation']='Those bytes are UTF-8 for 😀, not UTF-16. Connection configuration still needs checking alongside the column encoding.'
q['10']['workedExample']=q['10']['workedExample'].replace('4. Fix:', '4. Example migration syntax for MySQL 8.x (the chosen collation also changes comparison semantics; review indexes and uniqueness before applying):')
q['11']['options'][4]['explanation']='These uppercase results still differ: precomposed É versus E plus U+0301. Case mapping is not normalisation; in general Unicode case mappings can be context-sensitive or expand one code point into several.'
q['11']['workedExample']=q['11']['workedExample'].replace('Rule: normalise user-supplied text (usually NFC) at input, before storing, comparing or hashing it.', 'If canonical-equivalence matching is intended, normalise both strings consistently, often to NFC. Preserve original text or follow protocol-specific rules where exact bytes matter.')
q['12']['prompt']=q['12']['prompt'].replace('a lenient UTF-8 decoder', 'an obsolete decoder that accepts overlong UTF-8 sequences').replace('a lenient decoder', 'that decoder')
q['12']['options'][0]['text']='It produces / (U+002F), creating ../ and potentially bypassing the traversal filter'
q['12']['options'][0]['explanation']='Correct for the stipulated obsolete decoder. Whether access escapes the root also depends on subsequent path resolution and containment checks.'
q['12']['options'][2]['explanation']='A conforming UTF-8 decoder rejects the sequence or follows an error policy such as replacement; permissive decoding does not necessarily mean accepting overlongs as characters.'
q['12']['workedExample']=q['12']['workedExample'].replace('Defence: decode strictly (rejecting overlongs), normalise, *then* validate.', 'Defence: strictly decode, apply protocol-specific canonicalisation, validate the resulting path, and enforce filesystem containment. Unicode NFC by itself does not prevent traversal.')
p.write_text(json.dumps(qs,ensure_ascii=False,indent=2)+'\n')
print('Unicode corrections applied')
