import json
from pathlib import Path
p=Path('content/networks/03-tcp/tcp-congestion.questions.json'); qs=json.loads(p.read_text())
def q(n): return qs[n-1]
q(1)['prompt']='In an ideal slow-start model, cwnd starts at 10 segments, ssthresh remains far above it, every segment gets its own ACK, and each round sends a full window without loss or other limits. What is cwnd at the start of round 4?'
q(1)['options'][0]['explanation']='This adds one segment per round. The specified slow-start model doubles the window each round.'
q(1)['options'][3]['explanation']='The model doubles the window; it does not multiply by ten.'
q(1)['workedExample']=q(1)['workedExample'].replace('have been sent by then','were sent in the three completed rounds, before sending round 4')
q(2)['prompt']='A continuously backlogged, congestion-window-limited sender has cwnd = 100 segments of 1,460 payload bytes and a constant RTT of 50 ms. The receive window and link capacity impose no tighter limit. What is its approximate steady payload rate?'
q(2)['options'][2]['explanation']='The calculation is 146,000 bytes divided by 0.05 seconds, then multiplied by 8: 23.36 Mbit/s.'
q(2)['options'][3]['explanation']='Under the stated assumptions, the congestion window and RTT determine the approximate rate.'
q(3)['options'][0]['explanation']='This reverses their roles. The TCP Window field advertises rwnd; the base TCP header has no cwnd field.'
q(3)['options'][2]['explanation']='Both constrain sending throughout the connection. In a simple model, available new-data budget is max(0, min(cwnd, rwnd) minus bytes in flight).'
q(3)['options'][3]={'text':'cwnd is sender-side congestion-control state; rwnd is the receiver’s advertised sequence-space allowance','explanation':'Correct. The receiver advertises a window, while the sender maintains cwnd using its congestion-control algorithm. The advertised window is not simply a raw free-memory count.'}
q(3)['workedExample']='1. rwnd constrains the sequence space the receiver currently permits.\n2. cwnd constrains sending according to the sender’s congestion-control algorithm.\n3. Both apply; either can be the tighter limit. The base TCP header carries rwnd, not cwnd.'
q(4)['prompt']='In an ideal Reno model, cwnd and FlightSize are both 40 segments when three duplicate ACKs trigger recovery. Set ssthresh to half FlightSize, ignore temporary recovery inflation, and choose congestion avoidance when cwnd equals ssthresh. After recovery, what are ssthresh and cwnd, and cwnd after one full loss-free round with approximately one-segment additive growth?'
q(4)['options'][1]['explanation']='Correct. Half the stated FlightSize is 20. Recovery ends at cwnd = ssthresh = 20; the specified additive-growth round gives approximately 21.'
q(4)['options'][2]['explanation']='The question explicitly chooses congestion avoidance at equality. RFC 5681 permits either slow start or congestion avoidance when cwnd equals ssthresh.'
q(4)['workedExample']='1. FlightSize is 40, so this model sets ssthresh = 20.\n2. After recovery, cwnd is 20; temporary inflation is excluded.\n3. Choosing congestion avoidance at equality gives approximately 21 after the specified full round. These are idealised round-level values, not a complete ACK-by-ACK trace.'
q(5)['prompt']='Use the lesson’s round-based teaching model: a first timeout occurs with cwnd and FlightSize both 40 segments, setting ssthresh = 20 and cwnd = 1. Each subsequent loss-free full round doubles cwnd but caps it at ssthresh. How many rounds reach ssthresh?'
q(5)['workedExample']='The specified model gives 1 → 2 → 4 → 8 → 16 → 20, so the answer is five rounds. The cap is a teaching-model rule; this is not a universal timing guarantee for a real ACK-driven TCP implementation.'
q(7)['prompt']='Which statements correctly describe potential CUBIC benefits or its specified core behaviour relative to Reno? Select all that apply.'
q(7)['options']=[{'text':'Its cubic growth can rebuild a large window faster than Reno’s additive growth on high-bandwidth, long-RTT paths','explanation':'Correct. This is a design motivation, not a guarantee of a particular recovery time under every workload.'},{'text':'Its time-based cubic target reduces the dependence of window growth on ACK-round frequency','explanation':'Correct. Similar windows across different RTTs do not imply identical throughput or universal fairness.'},{'text':'Its specified multiplicative reduction factor is 0.7 rather than Reno’s approximately 0.5','explanation':'Correct. This retains a larger fraction of the window; actual utilisation still depends on path and workload.'},{'text':'It guarantees empty router queues and no queueing delay','explanation':'False. CUBIC can build queues. Congestion may be signalled by loss or ECN; overflow is not the only possible signal.'},{'text':'It identifies and ignores all random non-congestion losses','explanation':'False. CUBIC does not have a perfect classifier that exempts all such loss events.'}]
q(7)['workedExample']='The first three describe CUBIC’s cubic target and reduction factor. Actual growth is ACK-driven and also includes a Reno-friendly region; application-limited periods require special handling. Neither guaranteed queue elimination nor perfect random-loss classification follows from the algorithm.'
q(8)['prompt']='Use only the ideal CUBIC target W(t) = C(t − K)^3 + Wmax, with C = 0.4, β = 0.7 and Wmax = 200 segments. After reducing the target to βWmax, when does that cubic target return to 200? Ignore the Reno-friendly region, application limits and further congestion.'
q(8)['workedExample']='The reduced target is 0.7 × 200 = 140 segments. K = cbrt(200 × 0.3 / 0.4) = cbrt(150) ≈ 5.31 seconds. Using the unrounded K gives W(0) = 140 and W(K) = 200 exactly. This describes the ideal target, not a guaranteed recovery time for an actual flow.'
q(9)['prompt']='In an ideal Reno model, a full-flight flow sends 10 Gbit/s of payload at a fixed 100 ms RTT with 1,500 payload bytes per segment (ignore headers). Its window is about 83,333 segments. After halving that window for a loss event, assume growth of exactly one segment per RTT, no further loss and no other limits. Roughly how long to regain the original window?'
q(9)['options'][1]['explanation']='Adding roughly 41,667 segments at one per 0.1-second RTT takes about 4,167 seconds, far longer than 8 seconds.'
q(9)['workedExample']=q(9)['workedExample'].replace('4. Any other loss in that hour restarts the climb. RFC 3649 used this example to motivate high-speed algorithms; CUBIC\'s time-based growth answers it.','4. This is an ideal recovery calculation. RFC 3649 discusses the related difficulty of maintaining very large average Reno windows; its average-window loss-rate calculation is a distinct model.')
q(10)['prompt']='In a controlled test with spare path capacity and random link loss, a service observes higher sustained throughput after switching the sender from CUBIC to BBRv1 while keeping loss detection and retransmission machinery unchanged. Which mechanism can explain this observation?'
q(10)['options'][2]={'text':'BBRv1 bases its pacing model on measured delivery rate and minimum RTT rather than applying CUBIC’s multiplicative response to congestion events','explanation':'Correct. This can make BBRv1 less sensitive to some random-loss patterns. It does not mean loss has no effect on its recovery, delivery-rate estimates or throughput.'}
q(10)['workedExample']='CUBIC reduces its window on congestion events, which can include random link losses misinterpreted as congestion. BBRv1 instead uses a delivery-rate/minimum-RTT model, with additional recovery and policing behaviour. That difference can explain the measured improvement; it does not guarantee one on every path. A 1% packet-loss rate does not imply only a 1% throughput penalty, and the Reno-oriented Mathis approximation is not a general CUBIC formula.'
q(11)['prompt']='Which statements describe BBRv1 in Linux v6.12? Select all that apply.'
q(11)['options'][0]={'text':'It tracks a minimum-RTT estimate over a nominal 10-second window','explanation':'Correct. This is an estimate of low-queue RTT, not a guaranteed measurement of pure propagation delay.'}
q(11)['options'][1]={'text':'On expiry of its minimum-RTT estimate, eligible ProbeRTT operation reduces its cwnd target to four packets','explanation':'Correct. After in-flight data falls sufficiently, completion requires the 200 ms interval and a packet-timed round. Idle restart and other state conditions matter; this is not an unconditional ten-second schedule.'}
q(11)['options'][2]['explanation']='Correct. The gain cycle contains 1.25, 0.75 and six 1.0 gains, with conditions controlling phase advancement.'
q(11)['options'][4]['explanation']='The receiver does not need to run BBR as its own sending algorithm. This is sender-side TCP congestion control.'
q(11)['workedExample']='Linux v6.12 BBRv1 uses a ten-packet-round maximum delivery-rate filter and a nominal ten-second minimum-RTT window. ProbeBW has gains 1.25, 0.75, then six 1.0 phases. Eligible ProbeRTT operation targets four packets and requires its timing/round conditions. It neither halves its sending rate on every packet loss nor requires a BBR receiver. These details should not be silently generalised to later BBR versions.'
q(11)['link']={'title':'Linux v6.12 BBR implementation','url':'https://github.com/torvalds/linux/blob/v6.12/net/ipv4/tcp_bbr.c'}
q(12)['prompt']='Two hosts negotiate classic RFC 3168 ECN. A router marks one ECN-capable data packet CE and the packet arrives. Assume a new congestion event, successful feedback and no packet loss. What happens next?'
q(12)['options'][1]={'text':'The receiver echoes congestion with ECE; the sender reduces its congestion window and signals CWR, without retransmitting solely because of the mark','explanation':'Correct. Classic ECN feeds congestion information back without requiring the marked packet to be lost. No fixed latency advantage over every loss-detection method is implied.'}
q(12)['workedExample']='1. The router forwards the CE-marked packet.\n2. The receiver echoes congestion using ECE until CWR acknowledges the response.\n3. For the specified new congestion event, the sender performs its congestion response and signals CWR. Repeated ECE ACKs do not require a fresh reduction for every ACK.\n4. The delivered mark alone requires no retransmission. ECN does not prevent other packets being lost or guarantee freedom from timeouts.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
