from pathlib import Path
import json
base=Path('content/theory/03-probability')
p=base/'prob-distributions.md';s=p.read_text()
def r(a,b):
 global s
 assert a in s,a
 s=s.replace(a,b)
r('Most random quantities in computing follow one of a handful of standard shapes. If you can recognise the shape, you get a formula for every probability, the mean and the spread, for free.','Standard distributions provide useful models for some random quantities in computing. Their formulas apply when the model assumptions fit the process; resemblance alone is not enough.')
r('not the data:', 'and check that model against the data:')
r('| Successes in n fixed trials |','| Successes in n independent trials with the same success probability |')
r('| Trials until first success |','| Independent trials with constant success probability until first success |')
r('| Rare events in a time window |','| Events in a window of a homogeneous Poisson process |')
r('| Sum of many small effects |','| Standardised sum of many independent, identically distributed effects with finite nonzero variance (approximately) |')
r('All four grow out of the humble **Bernoulli trial**: one experiment with success probability p (a packet delivered, a disk surviving the year, a request succeeding).','The binomial and geometric distributions directly use **Bernoulli trials**: experiments with success probability p. Poisson and normal distributions also arise as limits of suitable Bernoulli models, but their uses extend beyond those limits.')
r('A data centre has 1,000 disks with a 2% annual failure rate. Failures per year are Bin(1000, 0.02): mean 20, standard deviation √(1000 × 0.02 × 0.98) ≈ 4.4. So plan spares for about 20, and treat 30 or so (two SDs above) as a bad but plausible year.','In a hypothetical fleet of 1,000 disks, suppose each independently has a 2% probability of failing during a year. The number of original disks that fail is Bin(1000, 0.02): mean 20, standard deviation √(1000 × 0.02 × 0.98) ≈ 4.4. This does not count failures of replacement disks. A spare-stock policy also needs a tolerated shortage probability and replenishment lead time; the mean alone is insufficient.')
r('A 5-node Raft or Paxos cluster loses availability when 3 or more nodes are down. If each node is independently down 1% of the time:','A fixed 5-node majority-quorum cluster cannot form a majority when 3 or more nodes are down. If each node is independently down with probability 1% at a sampled instant:')
r('About 10⁻⁵, or a few minutes a year, assuming independence. Correlated failures (lesson 1) are the real threat.','About 10⁻⁵, equivalent to roughly 5.2 expected minutes per 365-day year if these marginal probabilities remain constant. This estimates quorum loss due to node downtime, not total service unavailability: network partitions, leader elections and recovery also matter. Correlated failures invalidate the product model.')
r('Repeat Bernoulli(p) trials until the first success.','Repeat independent Bernoulli(p) trials with constant 0 < p ≤ 1 until the first success.')
r('Retries until a request succeeds, probes until an empty slot in open addressing, and rolls until a six all follow this shape.','Independent retries with constant success probability and independent fair-die rolls until a six fit this model. Open-addressing probes generally are not independent draws with replacement, so geometric waiting time is only a simplified probing model, not an exact law for every table.')
r('Requests arriving at a server, errors per hour, cosmic-ray bit flips per gigabyte per month: lots of independent opportunities, each very unlikely. The count in a fixed window is **Poisson** with rate λ (the average count per window):','Many independent rare opportunities can yield an approximately **Poisson** count. An exact example is the count in a fixed window of a homogeneous Poisson process, with constant intensity and independent increments. Here λ ≥ 0 denotes the expected count in that window, not a rate with unspecified units:')
r('the arrivals are bursty and a plain Poisson model will understate your peaks.','a single Poisson model does not match that dispersion. Bursts, changing intensity or heterogeneous populations are possible causes. Mean–variance equality alone does not establish a Poisson distribution.')
r('A worker pool can handle 9 per second. How often is a second overloaded?','Compare that count with a nominal capacity of 9 requests per second. How often does a one-second arrival count exceed 9?')
r('About 3.2% of seconds see 10 or more requests: roughly two overloaded seconds a minute, despite having nearly twice the average capacity. To push that below 0.1% you need capacity for 12 per second (P(X ≥ 13) ≈ 0.07%). Headroom over the mean is not optional; queueing theory builds on exactly this.','About 3.2% of one-second windows see 10 or more requests: about 1.91 such windows per minute in expectation. A threshold of 12 is exceeded with probability P(X ≥ 13) ≈ 0.202%, still above 0.1%. A threshold of 13 is exceeded with probability P(X ≥ 14) ≈ 0.0698%. These are arrival-count probabilities, not queue-overflow or latency probabilities: buffering, existing backlog and service times also matter.')
r('of a Poisson process are **exponential** with mean 1/λ,','of a homogeneous Poisson process with positive intensity r events per time unit are **exponential** with mean 1/r time units,')
r('The **central limit theorem (CLT)** says the sum (or average) of many independent random variables with finite variance is approximately normal, whatever their individual distribution.','One standard **central limit theorem (CLT)** says that the centred and scaled sum of independent, identically distributed variables with finite, nonzero variance converges in distribution to a standard normal as the sample size grows. This motivates a large-sample normal approximation; independence and finite variance alone are not sufficient for arbitrary non-identically distributed sequences, and no universal finite sample size guarantees accurate tails.')
r('Roll 100 dice.', 'Roll 100 independent fair six-sided dice.')
r('The binomial and Poisson both look normal for large n or λ, by the same theorem.', 'The binomial has a useful normal approximation when both np and n(1 − p) are sufficiently large; the Poisson approaches normal as λ grows. Check tail accuracy and use a continuity correction for discrete counts.')
a=s.index('> [!warning] Latency is not normal');b=s.index('\n## Choosing a distribution',a)
s=s[:a]+'''> [!warning] Check latency tails before choosing a model
> Latency can be right-skewed, multimodal or heavy-tailed, but none of these properties follows merely from being nonnegative. Right skew also does not imply a heavy tail. A normal approximation may misestimate high percentiles; inspect measured distributions and enough tail observations before using it for an SLO. Mean and standard deviation alone do not determine the tail.
''' + s[b:]
r('**Keep trying until it works?** Geometric (discrete) or exponential (continuous time).','**Independent constant-probability trials until success?** Geometric. Waiting for the next event in a homogeneous Poisson process? Exponential.')
r('**Count events in a window, many opportunities, each rare?** Poisson.','**Count independent rare events at a stable rate?** Consider a Poisson model and check its assumptions.')
r('**A sum or average of many independent pieces?** Normal, by the CLT.','**A standardised sum or average meeting CLT conditions?** Consider a normal approximation and check finite-sample accuracy.')
r('with `pmf`, `cdf` and `sf` (survival function, 1 − cdf) methods.', 'with `cdf` and `sf` (survival function, 1 − cdf) methods. Discrete distributions provide `pmf`; the continuous normal provides `pdf` instead. Use `sf` directly for small upper-tail probabilities to reduce cancellation error.')
r('- Binomial Bin(n, p): successes in n trials;', '- Binomial Bin(n, p): successes in n independent, equal-probability trials;')
r('- Geometric: trials to the first success;', '- Geometric: independent trials with constant p > 0 to the first success;')
r('- Poisson(λ): counts of rare events in a window; mean = variance = λ; approximates Bin(n, p) with λ = np.', '- Poisson(λ): a count model with mean = variance = λ; approximates Bin(n, p) for large n, small p and λ = np.')
r('- Normal: 68–95–99.7 rule; the CLT makes sums of many independent pieces approximately normal.', '- Normal: 68–95–99.7 rule; a normal approximation for sums needs CLT conditions and adequate sample size.')
r('- Capacity must exceed the mean: Poisson(5) still exceeds 9 about 3% of the time.', '- Poisson(5) exceeds 9 about 3% of the time; arrival-count thresholds alone do not determine queueing performance.')
r("- Real latency and traffic are skewed and heavy-tailed; don't model them as normal.",'- Measure latency and traffic distributions rather than assuming a normal model or a heavy tail.')
s+='\n- [Poisson distribution API — SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html)\n- [Normal distribution — NIST](https://www.itl.nist.gov/div898/handbook/eda/section3/eda3661.htm)\n'
p.write_text(s)
p=base/'prob-distributions.questions.json';qs=json.loads(p.read_text());q={x['id'].split('-q')[-1]:x for x in qs}
q['1']['options'][2]['explanation']='0.03 is the per-disk probability, not the mean count. A normal is continuous and only an approximation here; large n alone is insufficient when np is small.'
q['1']['options'][3]['explanation']='An exponential models a continuous waiting time under a constant-hazard assumption, not a count of failed disks.'
q['4']['prompt']='A fair coin is flipped independently 5 times. What is the probability of **exactly 3 heads**?'
q['6']['options'][3]['explanation']='For Poisson(5), P(X ≥ 5) is about 56%, whereas P(X ≥ 6) is about 38%; neither is the requested tail P(X ≥ 10).'
q['6']['workedExample']=q['6']['workedExample'].split('That is about')[0]+'That is about 1.91 windows per minute in expectation. To make the arrival count exceed the threshold with probability below 0.1%, use 13: P(X ≥ 14) ≈ 0.0698%. A threshold of 12 gives P(X ≥ 13) ≈ 0.202%. Queue overload also depends on backlog, buffering and service times.'
q['8']['prompt']='Under the explicit independence and stable-rate assumptions below, which counts admit a reasonable **Poisson approximation**? Select all that apply.'
q['8']['options'][0]['text']='Requests per second from many independent users, each with a small request probability and a stable aggregate rate'
q['8']['options'][2]['text']='Bit flips per day modelled as many independent rare events with a stable aggregate rate'
q['8']['options'][4]['text']='Typos per equal-length page, modelled as independent rare errors with constant probability per character'
q['8']['workedExample']+='\n\nThese are modelling assumptions, not established facts about all websites, memories or manuscripts. Correlation or changing rates can invalidate the approximation.'
q['9']['prompt']='At a sampled instant, each node of a fixed 5-node majority-quorum cluster is independently down with probability 1%. What is the probability that too few nodes remain up to form a majority?'
q['9']['workedExample']+=' This is only node-downtime quorum loss, not total service unavailability; it omits partitions, elections and recovery. The annual value is an expectation assuming stable marginal probabilities.'
q['10']['prompt']=q['10']['prompt'].replace('100 fair dice','100 independent fair six-sided dice')
q['10']['options'][3]['explanation']='This range has half-width about 171 rather than 34. Scaling a single-die SD by n would be wrong: independent variances add, so the sum SD is √100 × √(35/12) ≈ 17.1.'
q['11']['options'][0]={'text':'Even under an exact normal model, mean + 3σ is approximately the 99.865th percentile, not the 99.7th','explanation':'Correct. About 99.73% lies between −3σ and +3σ; half the remaining probability lies above +3σ. The one-sided percentile is about 99.865%.'}
q['11']['options'][2]['explanation']='False. Mean and SD alone do not determine percentiles. Chebyshev gives at least 8/9 of probability within three SDs for distributions with finite positive variance, not the normal 99.73%.'
q['11']['workedExample']='1. For a normal, Φ(3) ≈ 0.99865, so mean + 3σ is about p99.865. The 99.7% rule describes the two-sided interval.\n2. The proposed normal also assigns about 0.135% probability below zero. It can only be an approximation to nonnegative latency.\n3. Nonnegativity alone proves neither right skew nor a heavy tail. Measure the distribution; mean and SD alone do not determine its high percentiles.\n4. Use adequate raw observations or a histogram to estimate the tail, recording sampling and bucket uncertainty.'
p.write_text(json.dumps(qs,ensure_ascii=False,indent=2)+'\n')
print('Corrected distributions lesson and 12-question review')
