exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
report=json.loads(Path('docs/audit-root.json').read_text());findings=report['findings']
b='content/software-engineering/04-git-cicd/'
src=['https://trunkbaseddevelopment.com/branch-for-release/','https://dora.dev/capabilities/trunk-based-development/','https://nvie.com/posts/a-successful-git-branching-model/','https://www.sec.gov/Archives/edgar/data/1569391/000119312513401173/d613486dex101.htm']
patch(b+'git-workflows.md',[
('The cost of bringing them back together grows faster than linearly with the time apart:', 'Longer separation can increase integration work and delay discovery of incompatibilities; there is no universal mathematical growth law:'),
('only building and testing the combined code can.', 'review, static analysis and tests of the combined code may detect it.'),
('so anyone can branch from or release any commit.', 'providing a baseline for further work. Passing tests alone does not establish release readiness.'),
('no long-lived branches apart from trunk', 'no long-lived development branches apart from trunk; maintained release branches are a separate case'),
('Every flag doubles the paths through that code.', 'n independent Boolean flags permit up to 2^n configurations; constraints and mutually exclusive paths can reduce the reachable behavior combinations.'),
('Knight Capital\'s 2012 trading loss of roughly $440 million involved', 'The SEC\'s account of Knight Capital\'s 2012 incident reports losses exceeding $460 million and describes'),
('Fixing trunk first guarantees the bug cannot reappear in the next release.', 'Fixing trunk first avoids forgetting to forward-port that fix. Later edits can still regress the behavior, so retain a regression test.'),
('A freeze is a symptom of low confidence in trunk; the fix is better automated testing, not a longer freeze.', 'A freeze can reflect weak integration confidence or an explicit operational/business constraint. Improve feedback and release controls rather than treating a longer freeze as a substitute for them.'),
('small, frequent integrations avoid textual and semantic conflicts.', 'small, frequent integrations shorten feedback and can reduce conflict size; they do not eliminate conflicts.'),
('and always fix on trunk first.', 'and prefer trunk-first fixes when the bug exists there; release-only defects still need appropriate maintenance fixes.')], 'Remove unsupported integration growth law and impossible regression guarantee; distinguish release branches and correct SEC incident loss.',src)
def workflow(q):
 q[0]['prompt']='Which variable does this lesson emphasize when comparing the integration risks of branching workflows?'
 q[0]['workedExample']=q[0]['workedExample'].replace('grows faster still (every change on one side can interact with every change on the other)', 'can increase as more potentially interacting edits accumulate; this is not a measured universal growth law').replace('So the expected integration pain rises sharply with T.', 'Longer separation can therefore make integration harder; actual cost depends on overlap and architecture.')
 q[1]['workedExample']=q[1]['workedExample'].replace('Anything with `develop`, `release/*` and `hotfix/*` is GitFlow.', 'Those names are characteristic of GitFlow, but names alone do not establish a workflow; trunk-based teams can also maintain release branches.')
 q[2]['prompt']+=' Assume main still points at that production release and no release branch is currently open.'
 q[3]['workedExample']=q[3]['workedExample'].replace('Use types (a `Money` type) so the change breaks compilation rather than meaning.', 'Use distinct checked unit types or a Money type with an explicit unit contract; a shared name alone does not make a pounds-to-pence change a compile error.')
 q[4]['options'][3]['explanation']='Correct. Keep unfinished behavior gated, maintain compatible initialization/schema changes, and test both intended paths. A flag alone does not prove the deployment safe.'
 q[5]['workedExample']=q[5]['workedExample'].replace('The last two options are the opposite of point 3 and point 1 respectively.', 'A separate long-lived integration branch is not one of the listed practices; its presence is not logically the same as exceeding three branches.')
 q[6]['options'][0]['explanation']='Correct for a bug present on trunk. This avoids forgetting the forward-port, while a regression test guards against later changes; -x records the source commit.'
 q[6]['workedExample']=q[6]['workedExample'].replace('so 5.2 and later include it automatically.', 'so future releases based on that ancestry can include it, unless later edits undo or break it.')
 q[8]['options'][2]['explanation']='Merge preserves commit ancestry. It does not automatically discard a change made only on main: reintroducing the bug requires another change, a conflict resolution or releasing the unfixed branch directly.'
 q[8]['workedExample']=q[8]['workedExample'].replace('any conflict around the fixed lines may be resolved in favour of the release, or the old code path may simply be reused; either way, 4.1.0 ships without it.', 'a bad conflict resolution or a later semantic change can undo the fix. Merely leaving an unchanged old line on develop does not by itself make a normal merge overwrite a main-only fix. Releasing directly from the unfixed release branch is another failure path.')
 q[10]['options'][0]['text']='Independent Boolean flags can create up to 2^n configurations, making exhaustive coverage expensive as n grows'
 q[10]['options'][0]['explanation']='Ten independent flags permit1,024 combinations. Constraints can reduce reachable combinations; whether all are tested is a property of the suite.'
 q[10]['options'][1]['explanation']='Correct. The SEC described a repurposed flag invoking old Power Peg code on one server and losses exceeding $460 million in the Knight Capital incident.'
 q[10]['workedExample']=q[10]['workedExample'].replace('means the `else` branch is untested', 'may leave the else branch unexercised in production; automated tests may still cover it')
questions(b+'git-workflows.questions.json',workflow,'Clarify branch policies, unit types, feature-flag combinations and merge behavior after omitted hotfixes.',src)
src=['https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners','https://martinfowler.com/articles/ship-show-ask.html','https://google.github.io/eng-practices/review/developer/small-cls.html','https://google.github.io/eng-practices/review/reviewer/speed.html','https://docs.python.org/3/library/sqlite3.html','https://research.google/pubs/modern-code-review-a-case-study-at-google/']
patch(b+'git-code-review.md',[
('Almost every professional team reviews code before it reaches the main branch.', 'Many teams review code before it reaches the main branch; others use pairing or selective post-merge review.'),
('at least two people understand every change.', 'review can help more people understand a change; approval alone does not guarantee understanding.'),
('Humans are poor at spotting an off-by-one in line 340 of a diff; CI is excellent at it.', 'A targeted boundary test can catch an off-by-one that a reviewer misses; CI only detects what its checks actually exercise.'),
("an email like `x' OR '1'='1` returns other customers' orders.", "an email such as x' OR 1=1 -- can turn this SQLite query into an unconditional selection while commenting out the malformed trailing clause."),
('A fixed version:', 'A fixed version for Python sqlite3 (other drivers can use different placeholder syntax):'),
('a quick "looks right in general, detailed review this afternoon" unblocks the author.', 'an initial response can clarify expectations, but approval-dependent merges remain blocked until the required review is complete.'),
('**Show** (merge, then open a PR for after-the-fact discussion)', '**Show** (open a PR, wait for automated checks, then merge without waiting for human feedback)'),
('maps paths to the people or teams who must review changes there.', 'maps paths to owners who can be requested for review; requiring owner approval is a separate protection setting.'),
('Here a change to `billing/api.py` needs `@acme/payments`, and a change to `billing/main.tf` needs `@acme/infra`, because `*.tf` comes later in the file.', 'With required code-owner review enabled, billing/api.py needs an eligible payments owner approval, and billing/main.tf an infra owner approval because *.tf matches last. Listing several owners on one line permits approval by any one of them; it does not require every listed team.')], 'Correct SQLite injection illustration, CODEOWNERS approval semantics and Ship/Show/Ask ordering.',src)
def review(q):
 q[1]['workedExample']='Google gives roughly100lines as a commonly manageable change and1,000as usually too large, leaving the decision to the reviewer. File count, generated code, mechanical edits and complexity also matter. Small coherent changes can improve feedback and reversibility; line count is a guideline, not a correctness guarantee.'
 q[4]['workedExample']=q[4]['workedExample'].replace('If payments must also review Terraform under billing, add a later line `/billing/*.tf @acme/payments @acme/infra`.', 'A later line /billing/*.tf @acme/payments @acme/infra lists both as eligible owners, but approval from either team satisfies GitHub\'s code-owner requirement. Requiring both needs an additional policy or check.')
 q[5]['workedExample']=q[5]['workedExample'].replace('Both get reviewed within hours instead of days.', 'This can reduce review burden; completion time still depends on reviewer availability and complexity.')
 q[8]['options'][2]['explanation']='A valid signature binds the commit to a signing key under the verification policy; it neither proves all author metadata nor requires content review.'
 q[9]['options'][1]['explanation']='Human judgment remains important. Automated architectural rules and other tools can support review but do not establish complete fitness for product intent.'
 q[9]['options'][2]['explanation']='Correct. Scanners can compare resolved versions with known advisories; results still depend on database freshness, dependency detection and applicability.'
 q[10]['prompt']=q[10]['prompt'].replace('merge, then open a PR for feedback', 'open a PR, let automated checks pass, then merge without waiting for human feedback')
 q[10]['options'][0]['explanation']='Correct under the team\'s policy. Open the PR and pass automated checks, then merge while leaving space for colleagues\' subsequent feedback.'
questions(b+'git-code-review.questions.json',review,'Correct two-owner approval misconception, Show sequencing and overstated automation guarantees.',src)
src=['https://docs.github.com/en/actions/reference/security/securely-using-pull_request_target','https://docs.github.com/en/actions/reference/security/secure-use','https://github.com/actions/setup-python','https://testing.googleblog.com/2016/05/flaky-tests-at-google-and-how-we.html','https://reproducible-builds.org/docs/definition/','https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency','https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue']
patch(b+'git-ci-pipelines.md',[
('anyone can branch from it, release it or bisect it.', 'developers have a tested baseline for branching and diagnosis. Release readiness also depends on deployment, compatibility and operational checks.'),
('"Does this break anything?" is answered by a pipeline, not by asking around.', 'The pipeline supplies repeatable evidence about the behaviors and properties its checks cover; a green run is not proof that nothing breaks.'),
('group: ci-${{ github.ref }}', 'group: ${{ github.workflow }}-${{ github.ref }}'),
('What each part does:', 'This teaching example uses readable version tags and a moving runner label; production policy should pin reviewed action commits and control tool/dependency versions. requirements.txt must include the test and lint dependencies.\n\nWhat each part does:'),
('restores downloaded packages keyed on the requirements file, so installs are fast.', 'restores downloaded packages keyed on dependency files and environment details; pip installation still runs, and speed depends on the cache hit and remaining work.'),
('most red builds were not real failures, so engineers learn to ignore red.', 'many transitions involved tests known to be flaky. This does not establish that most red builds were false positives: intermittent failures can expose real races or other defects.'),
('CI on a pull request tests the branch.', 'What PR CI tests depends on the trigger and checkout ref.'),
('each PR must rebase and rerun CI', 'each PR must update by merge or rebase and rerun CI'),
('tagged with the commit SHA, and every later stage should deploy that exact artefact.', 'associated with the source revision and identified by an immutable digest, and every later stage should deploy that exact artifact. A SHA-shaped image tag is still mutable unless registry policy prevents replacement.'),
('the same source produces bit-for-bit identical output, so anyone can verify an artefact was built from the claimed source.', 'the same specified source, build instructions and environment reproduce bit-for-bit identical designated artifacts. Independent reproduction supports provenance checks; source alone does not specify all build inputs.'),
("GitHub's `pull_request` event gives fork PRs a read-only token and no secrets. `pull_request_target` runs with the base repository's secrets and write token. That is safe only while it runs the base branch's code; checking out and running the PR's code under `pull_request_target` hands your secrets to anyone who opens a PR.", 'Fork pull_request workflows normally receive restricted tokens and no repository secrets, but runner isolation and repository settings still matter. pull_request_target can access privileged base-repository credentials, subject to explicit permissions and event policy. Executing untrusted PR code or injecting untrusted input into its commands can expose those credentials; merely using the trusted workflow file does not make it safe.'),
('workflows pinned to a SHA were not affected.', 'pins to reviewed unaffected commits resisted that tag-repointing attack. A pin to malicious code, or an action that dynamically downloads unpinned code, is still unsafe.'),
('Build one immutable, SHA-tagged artefact and promote it;', 'Build one artifact per intended build configuration, identify it by digest, and promote it;')], 'Correct cache, flaky-test statistics, mutable image tags, reproducibility inputs and untrusted workflow trust boundaries.',src)
def ci(q):
 q[2]['workedExample']=q[2]['workedExample'].replace('Target shape, for example:', 'Illustrative target budget, not measured results:').replace('Result: about10minutes', 'Result: about10minutes')
 q[2]['workedExample']=q[2]['workedExample'].replace('Result: about 10 minutes, fewer intermittent failures, and failures that name the broken unit.', 'Those assumed durations sum to10minutes; benchmark the actual suite and fix sources of nondeterminism rather than assuming a test count guarantees runtime or reliability.')
 q[3]['prompt']+=' Assume equal total test duration per shard, runners starting together, and no queueing or shared-resource contention.'
 q[4]['prompt']=q[4]['prompt'].replace('Which mechanism prevents this at scale?', 'Assuming the combined tests detect the incompatibility, which mechanism checks the integrated candidate before merging?')
 q[4]['workedExample']=q[4]['workedExample'].replace('rebase and rerun CI', 'update by merge or rebase and rerun CI')
 q[5]['workedExample']=q[5]['workedExample'].replace('This is why Google found most pass-to-fail transitions involved flaky tests, and why quarantining matters.', 'This hypothetical independent-probability model illustrates compounding risk; it is not a causal derivation of Google\'s observed transition statistics. Flaky failures can also expose real defects.')
 q[6]['options'][2]['explanation']='Correct for reusable download caches when the installer still resolves and verifies required packages. Speedup depends on cache contents and workload.'
 q[6]['workedExample']=q[6]['workedExample'].replace('Exact hit: lockfile unchanged, restore and skip installation.', 'Exact hit on a package download cache: restore it and still run the locked install/sync step. Downloaded packages are not an installed environment.')
 q[8]['prompt']+=' Assume repository policy and checkout protections permit the checkout, and the secret is exposed to the test process.'
 q[8]['options'][1]['text']='The tests execute fork-controlled code in a context holding a private token; an attacker can attempt to exfiltrate it'
 q[8]['options'][2]['explanation']='Fork pull_request workflows normally withhold secrets, but this question explicitly gives the privileged test process a private token. Permissions and event policies must be checked.'
 q[8]['workedExample']='1. Untrusted PR code includes tests, build scripts, dependencies and configuration, not just the workflow YAML.\n2. If it executes with a private registry token, it can attempt to read or send that token.\n3. A label or approval does not sandbox code or freeze a mutable PR head. Use unprivileged isolated testing where possible.\n4. A privileged follow-up must treat artifacts and metadata from the untrusted run as untrusted input; it must not execute them or interpolate them unsafely into commands.\n5. If a privileged run is unavoidable, review the exact revision, bind approval to that revision and grant only the required scoped credentials. Current event and checkout safeguards can block the illustrated configuration; never disable them as a routine fix.'
 q[9]['options'][0]['text']='Pinning the action to a reviewed, unaffected full-length commit SHA instead of a mutable tag'
 q[9]['workedExample']=q[9]['workedExample'].replace('Every workflow using those tags ran the new code on its next run.', 'Workflows resolving an affected tag during the compromise could run the malicious code.').replace('Keep SHA pins current', 'A pin does not freeze unpinned dependencies downloaded by the action. Keep SHA pins current')
 q[10]['prompt']+=' Use a simplified model: independent PRs start from the same old base, every merge invalidates other results, each retest takes30minutes, no batching and no failures.'
 q[10]['options'][3]['text']='In this model throughput is at most about16merges per working day; a speculative merge queue can improve it if enough runners are available'
 q[10]['workedExample']=q[10]['workedExample'].replace('about 80 per day, if failures are rare.', 'an illustrative upper bound of80per day if runners are available, queue overhead is negligible and failures are rare; this is not a product throughput guarantee.')
 q[11]['options'][1]['explanation']='Correct. Avoid cancelling a live deployment midway. cancel-in-progress:false preserves the active run but the default single pending slot still replaces older pending runs; configure queueing deliberately.'
 q[11]['options'][2]['text']='The concurrency group serializes matching workflow runs within this repository'
 q[11]['options'][2]['explanation']='Correct for runs using that group in this repository. It is not a distributed deployment lock: another repository or a remote task left running after cancellation may still deploy.'
 q[11]['workedExample']=q[11]['workedExample'].replace('at most one deploy runs at a time. Good.', 'matching workflow runs are serialized within the repository; external deployment activity needs its own coordination.').replace('prefer queueing.', 'avoid cancelling active deployments and select the pending-run policy. As checked2026-10-04, queue:max supports a bounded pending queue and cannot be combined with cancel-in-progress:true.')
questions(b+'git-ci-pipelines.questions.json',ci,'Remove unsafe privileged-artifact advice, fix download-cache installation and clarify concurrency and illustrative throughput.',src)
for name in ['git-workflows','git-code-review','git-ci-pipelines']:
 for ext in ['.md','.questions.json']:
  if b+name+ext not in report['reviewed_files']:report['reviewed_files'].append(b+name+ext)
report.setdefault('omissions',[]).append({'lesson':'git-workflows','claim':'Universal faster-than-linear integration cost as time apart increases','reason':'No reproducible model or evidence establishes this universal law; retained qualitative risks without a numeric growth claim.'})
Path('docs/audit-root.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
