from pathlib import Path
import json
p=Path('content/networks/02-ip-routing/ip-nat-ipv6.md');s=p.read_text()
def r(a,b):
 global s
 assert a in s,a[:80]
 s=s.replace(a,b)
r('There are about 4.3 billion IPv4 addresses and far more devices than that. The Internet survived the shortfall with two answers: a hack that worked immediately (**NAT**) and a replacement that has taken decades to roll out (**IPv6**). Both shape how you build networked software today.','IPv4 has 2³² possible address values, about 4.3 billion, with some reserved for special purposes. **NAT** shares or translates address space; **IPv6** provides a much larger address space. They address different aspects of connectivity and coexist in deployed networks.')
r('This is what almost every home router does.','NAPT is commonly used on home gateways; product configurations differ.')
r('1. Picks a free public port, say 40000.','1. Selects a public address/port mapping, for example port 40000. Allocation and possible reuse depend on protocol and mapping policy.')
r('A toy version:','A toy version for one transport protocol, one public address and endpoint-independent mapping. It omits timeouts, packet/checksum processing, remote-peer filtering, port reuse and high availability:')
r('import itertools','import ipaddress')
r('        self.ip = public_ip\n        self.ports = itertools.count(40000)','        self.ip = str(\n            ipaddress.IPv4Address(public_ip))\n        self.next_port = 40000')
r('        key = (src, sport)','        src = str(ipaddress.IPv4Address(src))\n        if not 1 <= sport <= 65535:\n            raise ValueError("invalid port")\n        key = (src, sport)')
r('            p = next(self.ports)','            if self.next_port > 65535:\n                raise ValueError("ports exhausted")\n            p = self.next_port\n            self.next_port += 1')
a=s.index('The last line is the important one.');b=s.index('\n### Mapping',a)
s=s[:a]+'''The toy drops inbound packets without a mapping. Real routers may also have static mappings, an explicitly configured fallback host or locally listening services. Translation lookup and firewall policy are distinct.

Real NATs expire state. RFC 4787 requires UDP mappings to last at least two idle minutes, with a specific exception for certain well-known destination ports; it recommends a default of at least five minutes. RFC 5382 specifies at least 2 hours 4 minutes for established TCP idle state when the NAT cannot determine whether endpoints remain active. These are protocol requirements, not measurements of every router. Keepalive choices must account for the application, state-refresh rules and actual network.
'''+s[b:]
r('| Mapping | Same public port for every destination | New public port per destination |','| Mapping | Reuses a mapping for the same internal endpoint across destinations | Mapping depends on the remote IP and port |')
r('A symmetric NAT is one with destination-dependent *mapping*: talk to two servers and you appear on two different public ports. That is the hardest kind to traverse.','Those historical categories combine properties; describing mapping and filtering separately is clearer. Destination-dependent mapping can make a STUN-observed mapping unusable with another peer. It does not by itself prove that all direct connectivity checks will fail.')
r('**No inbound connections.** A host behind NAT can\'t be reached unless someone configures **port forwarding** or the app punches a hole.','**Inbound reachability needs a usable mapping and permitted traffic.** Static forwarding, mapping-control protocols, traversal or relays can provide it; a previously unused private endpoint is not automatically reachable through dynamic NAPT.')
r('NATs ship **ALGs** (application-level gateways) to rewrite these, and ALGs are a notorious source of bugs.','Some devices provide **ALGs** (application-level gateways) that rewrite protocol fields. Application-aware traversal and relays are alternatives; encryption or protocol differences can prevent an ALG from doing the required rewrite.')
r('**State in the middle.** The NAT is a single point of failure, and when it reboots or times out, every connection through it dies.','**State in the middle.** Losing an active dynamic mapping can interrupt a connection. Replicated or recoverable state and static mappings change failure behaviour; not every NAT deployment is a single unrecoverable point of failure.')
r('**Carrier-grade NAT** (CGNAT) stacks a second NAT at the ISP, in 100.64.0.0/10. Thousands of customers share one address, so IP-based rate limits and bans hit innocent neighbours, and logging must record ports as well as addresses to identify a user.','**Carrier-grade NAT** shares public IPv4 addresses among subscribers. It can add another translation layer beyond a home NAT, and RFC 6598 provides 100.64.0.0/10 for shared internal addressing. Sharing ratios vary. IP-based bans can affect unrelated subscribers; attribution needs sufficiently detailed mapping records, including protocol, ports and time. A subscriber mapping is not proof of an individual person\'s identity.')
r('NAT drops unsolicited inbound traffic as a side effect, which feels like security. But that protection comes from the *stateful filtering*, which a firewall does deliberately and IPv6 networks still do without NAT.','Translation does not define a complete security policy. Missing mappings can prevent delivery, while filtering determines which traffic may use existing mappings. IPv6 can apply stateful firewall rules without address translation.')
r('With endpoint-independent mapping, that same public address works for other peers too.','Endpoint-independent mapping can make that address reusable with other peers, but filtering, mapping lifetime and path reachability still determine whether traffic works.')
r('then send packets to each other at the same time. Each outbound packet creates a mapping in its own NAT that lets the other side\'s packets in.','then send connectivity probes towards one another. This can create mappings and filtering state that permit replies. Exact simultaneity is unnecessary, and NAT/filter behaviour can still prevent success.')
r('both peers send traffic through a **relay** server.','a peer can allocate a reachable **relay** address; one or both peers may use relayed candidates.')
r('**Nominate** the best pair that works: direct if possible, relay if not.','**Nominate** a valid pair under ICE priorities and application policy. A direct pair is commonly preferred, but relays can be deliberately preferred and nomination does not benchmark every path for optimal performance.')
r('The header is a fixed 40 bytes','The base header is a fixed 40 bytes')
r('| 2000::/3 | Global unicast |','| 2000::/3 | Main global-unicast allocation block, including special-use subranges |')
r('Every interface has a **link-local** address, and usually several global ones too. Multiple addresses per interface are normal in IPv6.','IPv6 addressing specifies a **link-local** address on each interface, apart from exceptions such as the loopback interface. An interface need not have a global address; multiple addresses are supported. `2001:db8::/32` in these examples is documentation space, not a publicly routed allocation. ULA local generation uses `fd00::/8`; the `fc00::/8` half is not defined for that method.')
r('Subnets are almost always **/64**. An ISP typically delegates a /48 or /56 to a site: a /56 holds 256 /64 subnets and a /48 holds 65,536.','Ethernet SLAAC uses **/64** prefixes. Other uses include /127 router-to-router links and /128 host routes, so IPv6 routing is not limited to /64. Delegation sizes vary; a /56 contains 256 /64s and a /48 contains 65,536.')
r("send a Neighbor Solicitation for that address; if nobody answers, it's yours.","probe the tentative address with Neighbor Solicitation. A conflicting Advertisement or another host's DAD Solicitation can reveal a duplicate; absence of a reply is not an absolute uniqueness guarantee.")
r('Routers answer with a **Router Advertisement** containing the /64 prefix, the default router (the RA\'s source) and flags.','A **Router Advertisement** may carry prefix information and flags. A usable autonomous prefix must have its A flag set and suitable length/lifetimes. The RA source becomes a default-router candidate only with a nonzero router lifetime; an RA need not advertise a prefix or a default route.')
r('The host combines prefix + interface identifier into a global address, runs DAD again, and is online.','The host can form an address from an eligible prefix and interface identifier, then perform DAD. Working routing, neighbour resolution and other configuration are still needed for external connectivity.')
r('flip the 7th bit.','XOR the first byte with `0x02` (the U/L bit).')
r('so modern systems use random **stable privacy** identifiers (RFC 7217) and short-lived **temporary** addresses for outbound connections (RFC 8981).','so alternatives include opaque, prefix-dependent **stable** identifiers (RFC 7217) and changing **temporary** addresses (RFC 8981). Which method is enabled depends on the system and configuration; stable identifiers are not freshly randomised for every connection.')
r('Android doesn\'t implement stateful DHCPv6 address assignment, so networks that want to serve every device must offer SLAAC.','Support for DHCPv6 modes varies across client versions. M/O flags do not force a client to implement a mode, and SLAAC prefix processing is controlled separately by the prefix A flag.')
r('**Dual stack**: hosts and networks run both. The common approach today.','**Dual stack**: hosts and networks run both protocol families.')
a=s.index('- **Happy Eyeballs**');b=s.index('\n- **Tunnels**',a)
s=s[:a]+'''- **Happy Eyeballs** (RFC 8305): clients resolve and order addresses, then stagger connection attempts across candidates instead of waiting for a failed family's full timeout. The recommended default connection-attempt delay is 250 ms, but implementations can adapt it; DNS timing, address ordering and path RTT affect the result. It is not a universal 250 ms page-load guarantee.
- **NAT64 + DNS64** (RFC 6146/6147): a translator can connect IPv6-only clients to IPv4 servers. DNS64 can synthesise AAAA records using a configured translation prefix; `64:ff9b::/96` is the well-known prefix, not the only option. 464XLAT adds client-side translation for IPv4-dependent applications. Reachability and application compatibility still depend on the deployment.
'''+s[b:]
r("Adoption is uneven but substantial: Google's measurements put IPv6 at roughly half of its users' traffic, much higher on mobile networks in some countries and much lower in others.","> [!note] Content omitted after review\n> Current IPv6 adoption percentages, client-platform DHCPv6 support, app-store requirements and consumer NAT timeout surveys are omitted because they need versioned or dated evidence not established here. The linked standards define behaviour, not deployment prevalence.")
r('Firewall rules written only for IPv4 leave IPv6 wide open (or block it, breaking Happy Eyeballs\' preferred path).','Review IPv6 firewall policy separately: IPv4-only rules do not establish what the IPv6 policy permits or blocks.')
r('Blocking ICMPv6 breaks IPv6 completely: Neighbor Discovery, SLAAC and Packet Too Big all use it.','Blanket ICMPv6 filtering can break neighbour discovery, router advertisements and MTU feedback. Cached/static configuration or probing may mask some failures; ICMPv6 message types need deliberate treatment.')
r('hole punching opens a direct path','hole punching can establish a direct path')
r('IPv6 uses 128-bit addresses, /64 subnets, link-local addresses on every interface and no broadcast.','IPv6 uses 128-bit addresses and no broadcast. /64 is standard for Ethernet SLAAC, while other prefix lengths serve other purposes.')
r('privacy extensions replace MAC-derived identifiers.','opaque and temporary identifiers can avoid exposing MAC-derived identifiers.')
p.write_text(s)
