import json
from pathlib import Path
p=Path('content/networks/03-tcp/tcp-sockets.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['prompt']='On a blocking TCP socket with no local receive shutdown, recv(4096) returns b"" after all preceding data has been consumed. What does this indicate?'
q(1)['workedExample']='For this positive-length read, an empty result indicates end of the peer’s sending stream. Stop waiting for further input. A half-closed connection may still be usable for sending a response; then close or shut down according to the protocol. Forgetting EOF handling can create a busy loop, but the exact TCP state also depends on local shutdown history.'
q(2)['prompt']='An ordinary Linux TCP listener has room in its pending queues, the path is working, and no Fast Open is in use. Its process pauses in a debugger after listen(128), before accept(). Can a client’s blocking connect() succeed?'
q(2)['options'][1]['explanation']='The kernel can perform the ordinary TCP handshake without the application accepting. The peer may even half-close before the server eventually accepts.'
q(2)['options'][3]['explanation']='The supplied conditions do not require waiting for acceptance or a timeout. Timeout durations are configuration-dependent.'
q(2)['workedExample']='The kernel listener can process SYN and ACK traffic while the application is paused. The client can complete its local handshake and queue data before the server calls accept(). The requested backlog is subject to platform limits and does not establish an exact universal 128-connection failure threshold.'
q(3)['prompt']='Why does a TCP application that needs to distinguish messages need a framing rule, such as a length prefix, delimiter or a defined EOF boundary?'
q(3)['options'][1]['explanation']='send() is not restricted to one MSS; it can accept more, or only part of the supplied buffer. Segmentation is separate from application framing.'
q(3)['workedExample']='TCP preserves byte order but not write boundaries. A receiver may obtain part of a message or several messages in one read. A protocol must define how to recognise its boundaries, which may include EOF. Ordinary UDP preserves the boundary of each delivered datagram, but datagrams can be lost, duplicated or truncated by an undersized receive buffer.'
q(4)['prompt']='On a fresh TCP stream with no other reader, a client successfully sends b"hello" then b"world". No local receive shutdown or connection failure occurs. Which results could the server’s first recv(1024) return? Select all that apply.'
q(4)['workedExample']=q(4)['workedExample'].replace('TCP guarantees **order and completeness**, not **boundaries**.','TCP delivers received stream bytes in order; it does not preserve write boundaries or promise that a connection can never fail.')
q(5)['options'][3]['explanation']='A positive receive size smaller than 4,096 is valid. The bug is assuming the result always fills the requested length.'
q(5)['workedExample']=q(5)['workedExample'].replace('On localhost, data arrives in one piece, so tests pass.','A local test may happen to return the complete header, but short reads are possible even on localhost.').replace('body = recv_exact(sock, n)','if n > MAX_MSG:\n    raise ValueError("message too large")\nbody = recv_exact(sock, n)').replace('Fix: loop until you have exactly n bytes.','Fix: use the lesson’s recv_exact and MAX_MSG, handling EOF/errors and bounding the decoded size before reading the body.')
q(6)['prompt']='On a POSIX system, diagnostics show that retained TIME_WAIT connections prevent an immediate listener rebind, with no competing listener. Which option should a restartable server configure before bind(), subject to that platform’s old/new socket reuse rules?'
q(6)['options'][1]['explanation']='This is an address-reuse problem, not a permission error. Privileged-port thresholds are platform/configuration-dependent.'
q(6)['options'][2]={'text':'SO_REUSEADDR; Python socket.create_server enables it on POSIX','explanation':'Correct. Configure appropriate reuse before binding. On Linux the relevant reuse case generally requires it on both the old and new sockets; exact rules differ across systems.'}
q(6)['workedExample']='TIME_WAIT retains TCP state after orderly closure and can affect rebinding. SO_REUSEADDR relaxes relevant address-reuse checks, subject to platform rules; it does not permit arbitrary sharing with an active listener. Set it before bind(), and configure the original listener appropriately too.\n\n```python\ns = socket.socket()\ns.setsockopt(socket.SOL_SOCKET,\n             socket.SO_REUSEADDR, 1)\ns.bind(("127.0.0.1", 8080))\n```\n\nThe caller must close s when finished. Port reuse does not mean new connections necessarily have different tuples; TCP’s retained state and sequence rules still matter.'
q(7)['workedExample']=q(7)['workedExample'].replace('a sign the peer is speaking a different protocol, which is why real servers cap message lengths.','an incomplete next header. It could be malformed input or part of a later message; the three bytes alone do not prove the peer uses another protocol. The lesson’s size limit rejects an oversized decoded next length.')
q(8)['options'][1]['explanation']='A listener can serve more than 65,535 connections when peer endpoint tuples differ sufficiently. Resource and tuple limits still apply.'
q(8)['options'][3]={'text':'Native threads have stack and scheduling costs; a multiplexed runtime can serve many idle sockets with fewer threads','explanation':'Correct. Backend and runtime details vary; a benchmark and resource limits determine actual capacity.'}
q(8)['workedExample']='One native thread per connection adds stack reservations, task limits and scheduling overhead. A readiness or completion-based runtime can multiplex many waiting operations onto fewer threads. Connections still consume kernel buffers, application state, descriptors and runtime tasks. No fixed 50,000-connection capacity follows from choosing an event loop.'
q(9)['prompt']='A Linux service shows rising TcpExtListenOverflows and occasional delayed connection setup or first requests. With tcp_abort_on_overflow = 0, which explanation is consistent with these observations and should be investigated using captures and queue measurements?'
q(9)['options'][0]={'text':'The accept queue is overloaded; some handshakes may be deferred or dropped while the listener catches up','explanation':'Correct. One overflow path ignores the final ACK and can recover after SYN+ACK retransmission. Other paths and causes exist; this counter alone does not prove that exact trace.'}
q(9)['options'][1]['explanation']='A SYN-queue problem alone is not established by this accept-overflow counter. Attack traffic can still contribute to several types of overload, so do not exclude it solely from one counter.'
q(9)['options'][2]['explanation']='Nagle is not the mechanism counted by a listen-queue overflow counter. Its delay is not universally bounded to a fixed millisecond range.'
q(9)['workedExample']='Inspect backlog limits, arrival bursts, acceptance rate, blocked workers and resource limits. Linux can ignore a final ACK on an overflow path when abort-on-overflow is disabled, while the client already believes setup succeeded. Retries can then add delay, but exact timing and behaviour require capture/configuration evidence. A larger backlog absorbs some bursts; it does not fix sustained service-capacity shortfalls.'
q(10)['options'][2]={'text':'The non-blocking send call itself waits for the slow client to read','explanation':'False. It returns a count or an error rather than waiting for writability. However, an unhandled exception can terminate this toy loop and interrupt service for every client.'}
q(10)['options'][3]={'text':'Correct handling needs retained unsent output and write readiness, plus queue bounds, read backpressure and error handling','explanation':'Correct. Account for partial writes and handle would-block, disconnection and cleanup; an unbounded output buffer merely moves the resource problem.'}
q(10)['workedExample']='The deliberately faulty loop ignores send()’s partial count and does not handle would-block. It can lose bytes or terminate. A non-blocking call does not wait for the slow peer, but loop termination affects all clients. Retain pending output, register write interest only while needed, bound queues and stop reading when output pressure is high. Handle stale readiness for accept/read/write and flush pending output on input half-close. sendall() alone does not solve non-blocking buffering.'
q(11)['prompt']='In the asyncio echo example, suppose the peer keeps uploading but never reads responses. With no output-size policy or total deadline added, what risk is introduced by deleting await writer.drain()?'
q(11)['options'][0]['explanation']='write() may send immediately or buffer unsent data. It does not wait for the receiving application to consume it.'
q(11)['options'][2]['explanation']='Retransmission does not replace application backpressure. Data can accumulate in the asyncio transport’s output buffer.'
q(11)['options'][3]={'text':'Unsent output can grow excessively because the coroutine no longer waits for the transport’s backpressure','explanation':'Correct. drain() waits when writing is paused at the high watermark until the buffer drains to the low watermark. Other failures or limits may stop growth; unlimited growth is a risk, not an inevitable trace.'}
q(11)['workedExample']='If incoming data continues while output cannot drain, write() can accumulate unsent output in user space. drain() makes the coroutine cooperate with transport flow control, indirectly slowing further reads. Its watermarks concern the transport buffer, not a direct test for a zero TCP receive window. Removing it risks memory exhaustion; exact growth and termination depend on the runtime, peer and other limits.'
q(12)['options'][0]={'text':'The kernel selects among separate eligible listening sockets, each with its own accept queue, which can reduce shared-listener contention','explanation':'Correct. Linux’s default selection uses flow-related hashing, but optional BPF policies and implementation details vary. Neither perfect balancing nor removal of all locking is guaranteed.'}
q(12)['workedExample']='With one shared listener, workers take connections from one accept queue. An eligible SO_REUSEPORT group has separate listeners and queues; set the option before bind() and satisfy Linux’s effective-UID and binding requirements. Selection can distribute new connections without every worker sharing one accept queue. A stalled worker can still accumulate work, and measured workload balance is not guaranteed.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
