from pathlib import Path
import json
p=Path('content/networks/01-foundations/nf-arp-switching.questions.json');q=json.loads(p.read_text())
q[0]['prompt']+=' Assume ordinary unicast Ethernet, only connected and default routes, and no proxy ARP.'
q[0]['options'][0]['explanation']='The selected next hop is the default gateway. The laptop resolves that address, not the remote destination.'
q[0]['options'][3]['explanation']='Ordinary DNS name resolution does not resolve the Ethernet next-hop mapping; ARP does.'
q[1]['prompt']='For an initial Ethernet/IPv4 ARP lookup with no cache entry, proxy ARP or address conflict, how are the request and normal reply addressed?'
q[1]['options'][0]['explanation']='The initial lookup request is broadcast. The normal reply is unicast; other ARP uses can include broadcast replies or unicast validation requests.'
q[1]['workedExample']='The initial request uses the broadcast destination and contains the sender IP and MAC. The addressed host can reply directly to that MAC. Each ARP message is 28 bytes. On basic untagged Ethernet, header, padding and FCS make a minimum 64-byte frame; capture formats may omit padding or FCS.'
q[2]['options'][0]['text']='Basic Ethernet has no forwarding TTL to expire a frame after a bounded number of hops'
q[2]['options'][0]['explanation']='Correct. Copies can keep circulating until dropped or the loop is removed. Congestion or faults can discard frames, but there is no hop-count expiry.'
q[2]['workedExample']='A broadcast is flooded out eligible ports other than its ingress port. Copies returning through the cable can be flooded again. New traffic adds load, and source addresses can be learned on alternating ports. This can overwhelm the network, but severity is topology- and traffic-dependent. STP prevents forwarding loops; BPDU guard disables a guarded port when it receives a BPDU, not for every conceivable loop.'
q[3]['prompt']+=' Assume the same spanning-tree instance and equal extended system IDs.'
q[4]['prompt']='A laptop sees both `192.168.1.1` (its gateway) and `192.168.1.66` mapped to `7e:31:9a:04:c2:10` in its ARP cache. No other evidence is available. What can you conclude?'
q[4]['options']=[{'text':'The mapping is definitely normal','explanation':'Multiple IPs can legitimately share a MAC, but this observation does not establish legitimacy.'},{'text':'The cache is definitely corrupt','explanation':'One MAC can serve multiple IP addresses; the representation itself is valid.'},{'text':'ARP spoofing is possible, but the mapping alone is insufficient to establish it','explanation':'Correct. A legitimate multi-address interface or proxy ARP can produce the same pattern. Compare trusted network configuration and packet evidence.'},{'text':'The manufacturer must have assigned duplicate MAC addresses','explanation':'The cache does not prove that two physical interfaces exist or have identical factory addresses.'}]
q[4]['workedExample']='ARP records claimed IP-to-MAC mappings, not device identities or intent. Multiple addresses can belong to one interface, and a proxy can answer for other addresses. Forged ARP is another possibility. A diagnosis needs additional evidence. Properly authenticated encryption protects contents if interception occurs, while metadata and availability can remain exposed.'
q[5]['options'][0]['text']='Correctly configured Dynamic ARP Inspection with trusted DHCP bindings or static ARP ACLs'
q[5]['options'][0]['explanation']='Correct. Inspection rejects inconsistent ARP on protected untrusted ports. Coverage depends on trust boundaries, bindings and static-host configuration.'
q[5]['options'][1]['text']='Using properly authenticated TLS, SSH or a VPN over the relevant traffic path'
q[5]['options'][1]['explanation']='Correct. This protects application contents and integrity across that path; it does not stop poisoning, traffic analysis or denial of service.'
q[5]['workedExample']='DAI can reject forged ARP on protected ports. Authenticated encryption limits exposure of contents and undetected modification. Smaller VLANs reduce the set of reachable layer 2 peers. Extending a timeout does not authenticate updates, and password rotation alone does not constrain a member who remains authorised. None of these alone makes every interception consequence harmless.'
q[6]['prompt']='Two load balancers share a VIP using their distinct physical MACs, without a shared virtual MAC. After failover, local clients can establish new connections, but external clients cannot. A capture shows the upstream router still sending VIP traffic to the failed node\'s MAC. Which explanation fits?'
q[6]['options'][1]['explanation']='Correct. The capture establishes a stale IP-to-MAC mapping. An announcement may have been lost, filtered or rejected. How long it persists depends on neighbour handling and configuration.'
q[6]['options'][3]['explanation']='Existing connection survival depends on replicated state. Failure of new connections plus frames addressed to the old MAC identifies a link-layer delivery problem.'
q[6]['workedExample']='The VIP is unchanged, but its active physical MAC has changed. Local clients learned the new mapping; the capture shows the router has not. Check announcement delivery, neighbour-update policy and any static mapping. A shared virtual MAC avoids changing this ARP mapping, but then switches must learn the virtual MAC\'s new port. Neither design guarantees an immediate recovery time.'
q[7]['prompt']+=' Assume the default 15-second forward delay and an ordinary host-facing port.'
q[7]['options'][0]['explanation']='Correct. With these defaults, listening and learning each last 15 seconds. An appropriately configured host edge port can forward immediately.'
q[7]['options'][2]['explanation']='A link light alone does not diagnose negotiation details, but the specified classic STP timing explains this delay. Forcing one side can create a duplex mismatch.'
q[7]['workedExample']='With the stated timers, listening takes 15 seconds and learning another 15. DHCP requests cannot pass until forwarding begins; client retries determine the visible outcome. Configure genuine host ports as edge/PortFast ports. BPDU guard disables a guarded port when a BPDU arrives, helping enforce the host-only assumption. It does not detect every silent switch or loop.'
q[8]['prompt']+=' Assume three point-to-point links, one spanning-tree instance and a stable topology.'
q[8]['options'][2]['explanation']='On this triangle\'s point-to-point links, S1\'s ends are designated. S2 blocks its direct root link because its path through S3 costs less.'
q[8]['workedExample']=q[8]['workedExample'].replace('  X /  \\\n   /    \\','   /    \\\n X/      \\')
q[9]['prompt']='All switches have equal STP priority/system-ID fields. A newly connected switch advertises a lower bridge ID, and status commands confirm that it became root. Which configuration would prevent that port from accepting an unexpected superior root?'
q[9]['options']=[{'text':'Increase the MAC table size','explanation':'The forwarding table size does not control root election.'},{'text':'Configure intended root priorities and enable root guard on that boundary port','explanation':'Correct. Priorities make the intended election explicit; root guard blocks a boundary port from accepting a superior root.'},{'text':'Lower the new switch\'s numeric priority','explanation':'That makes its bridge ID more favourable, increasing its chance of becoming root.'},{'text':'Enable all redundant ports for forwarding without STP','explanation':'That can introduce forwarding loops and does not enforce the intended root.'}]
q[9]['workedExample']='The observed root ID confirms the election change; switch age alone does not predict it. Set lower numeric priorities on intended root and backup bridges and use root guard where a superior root must not appear. Becoming root does not imply all data traverses that switch: forwarding follows the resulting tree, and a singly connected root cannot be an intermediate path between other switches.'
q[10]['options'][1]['text']='RSTP can use proposal/agreement on suitable point-to-point links to avoid classic forward-delay waits'
q[10]['options'][1]['explanation']='Correct. Rapid transitions depend on port roles and synchronisation. Failure detection, shared media and legacy neighbours can still require timers.'
q[10]['options'][2]['explanation']='RSTP still selects a tree per instance. Aggregation, multiple instances or routed ECMP can provide more usable paths, but do not guarantee every physical link carries data.'
q[10]['workedExample']='With classic default timers, a transition can require two 15-second forward delays, with up to 20 seconds of ageing in relevant failure cases. RSTP retains bridge-ID election but adds roles and handshakes for faster transitions. Sub-second recovery is possible, not universal. Redundant non-forwarding ports still exist within an instance.'
q[11]['prompt']+=' Assume no more-specific routes, no ARP spoofing, and a correct default gateway otherwise.'
q[11]['workedExample']=q[11]['workedExample'].replace('With proxy ARP enabled, the router would answer with its own MAC and things would "work" by accident, hiding the misconfiguration.','A suitably configured proxy ARP router could answer for the remote host and mask the error, provided forwarding and return routing also work.')
q[11]['options'][0]['explanation']='On this ordinary Ethernet next hop the host must address its data frames to the router. The mistaken connected route instead triggers direct ARP for the remote host.'
q[11]['options'][3]['explanation']='Normal VLAN bridging does not carry this broadcast into the other VLAN; no proxy is configured to answer here.'
p.write_text(json.dumps(q,indent=2,ensure_ascii=False)+'\n')
