exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-system-design-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/system-design/08-architecture/'
src=['https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html','https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-sharding.html','https://www.postgresql.org/docs/current/runtime-config-wal.html','https://kafka.apache.org/42/configuration/producer-configs/']
patch(b+'arch-scaling-writes.md',[
('Reads scale by making copies. **Writes don\'t**: every copy must receive every write, so copies multiply the work. To scale writes you have to either **split the data** so each machine handles a fraction of the writes, or **make each write cheaper**.', 'In a single-writer system, read replicas offload reads but do not divide ownership of the write stream. That offload can free primary capacity. To address a write bottleneck, reduce work per write, increase resources, or partition write ownership.'),
('A single relational primary can often handle a few thousand to a few tens of thousands of simple writes per second on good hardware. The limits are:', '> [!note] Evidence gap\n> Generic primary throughput, disk flush latency and Kafka broker throughput figures are omitted: no representative benchmark environment was supplied. Measure the actual workload.\n\nPotential limits include:'),
('- **Disk durability**: each commit must be flushed to the write-ahead log (an `fsync`), which costs anything from tens of microseconds on NVMe to several milliseconds on networked storage.', '- **Disk durability**: synchronous commits wait for the required durable log position. Group commit can share a flush across transactions; asynchronous commit and replication settings change the acknowledgment policy.'),
('- **Index maintenance**: every secondary index is another write per insert.', '- **Index maintenance**: applicable secondary indexes add work; partial indexes may exclude a row, and buffering changes physical I/O.'),
('         hash(user_id) % 4','         user_id % 4'),
('Four shards give you roughly four times the write capacity, *if* writes spread evenly.', 'Four equivalent shards can approach four times one shard\'s capacity if writes spread evenly and routing, coordination and other shared resources do not become bottlenecks.'),
('remaps almost every key when N changes:', 'can remap a large fraction of keys when N changes:'),
('1 insert per txn:   1,000 txns, 1,000 fsyncs', '# Serial synchronous commits; no grouping\n1 insert per txn:   1,000 txns, 1,000 fsyncs'),
('trading a few milliseconds of latency for much higher throughput.', 'amortising request costs; added waiting, throughput and end-to-end latency depend on load and batching settings.'),
('Updating in place is expensive: find the row, lock it, rewrite it, update indexes. **Appending** to the end of a log is the cheapest write there is, because it\'s sequential I/O with no read beforehand.', 'Updates may require lookup, concurrency control and index maintenance. Append-oriented storage can make I/O more sequential, but durability, indexing, validation and compaction still cost work. Buffered B-tree inserts do not necessarily perform a physical random read and write for every row.'),
('They sustain far higher write rates than in-place B-trees, at the cost of read amplification and compaction work.', 'They trade buffering and sequential flushes against read amplification and compaction work. Compare measured sustained throughput: compaction can stall writes and an LSM engine is not universally faster than a B-tree.'),
('and can sustain hundreds of MB/s per broker.', 'with throughput depending on replication, acknowledgments, message size, batching, storage and network.'),
('You get a full audit trail and cheap writes; reads need projections.', 'Retained events can support audit history and projections; completeness, access control and write cost depend on the implementation.'),
('limits each partition to about 1,000 write units/s and 3,000 read units/s.', 'supports at most 1,000 write units/s and 3,000 read units/s per partition. Units are not generally requests: an ordinary write consumes one unit per 1 KiB, while strongly consistent reads consume one per 4 KiB; transactional operations cost more.'),
('`date` as a partition key puts all of today\'s writes on one partition; `device_id` (or `device_id + date`) spreads them.', '`date` concentrates today\'s writes on one logical key. Physical splitting depends on the store, sort keys and indexes; do not equate a partition-key value with one permanent physical partition. A well-distributed device_id (or device_id + date) reduces this concentration.'),
('A typical write-heavy pipeline (say, ingesting 500,000 events/s from mobile apps) looks like this:', 'An illustrative write-heavy pipeline might look like this. The 64-partition choice is not a validated capacity recommendation:'),
('- Writes can\'t be scaled by copying data; you must partition it or make each write cheaper.', '- Read replicas do not partition writes, though offloading reads can free primary headroom.'),
('- Append-only structures (LSM trees, logs, event sourcing) turn random writes into cheap sequential ones.', '- Append-oriented structures can improve I/O locality but still incur durability, indexing, validation and compaction costs.')], 'Correct group commit and storage-engine guarantees, shard diagram mapping, partition units and unsupported performance figures.',src)
def writes(q):
 q[0]['prompt']='In a single-writer architecture with full read replicas, why does replication not partition the write stream?'
 q[0]['options'][0]['explanation']='Each full replica replays the write stream. Read offload can free primary headroom, but replication does not assign independent subsets of writes to additional primaries.'
 q[0]['options'][1]['explanation']='A correctly routed application sends writes to the primary. Rejected misrouted writes are not the architectural reason.'
 q[0]['options'][2]['explanation']='Replication need not change the engine. Replaying writes can cost differently from executing transactions on the primary.'
 q[0]['options'][3]['explanation']='Neither replication nor sharding guarantees linear scaling; sharding can divide write ownership when load and other resources permit.'
 q[0]['workedExample']=q[0]['workedExample'].replace("so there's room for 4× more.", 'so they could support more writes if each has spare capacity and no shared bottleneck dominates.')
 q[2]['workedExample']=q[2]['workedExample'].replace('but a gain of 50–100× is typical.', 'and no typical gain is asserted without a representative benchmark.')
 q[2]['options'][0]['explanation']='Correct under the stated simplified assumptions: 500 commits/s multiplied by 500 rows/commit gives 250,000 rows/s. This is a model, not a measured throughput prediction.'
 q[4]['prompt']+=' Assume ordinary updates of items at most 1 KiB. Consider these as mitigation designs requiring validation.'
 q[4]['options'][0]['explanation']='This reduces per-key demand to about 750 writes/s if balanced. Multiple keys do not guarantee separate physical partitions; verify distribution and throttling.'
 q[4]['options'][1]['explanation']='Aggregation reduces requests but adds delay. Durable input, deduplication and coordinated checkpoints are needed to prevent loss or double counting on recovery.'
 q[4]['workedExample']=q[4]['workedExample'].replace('Reads do 20 gets (or a query) and sum.', 'Read the 20 keys using individual or batch gets and sum; a single Query cannot span distinct partition-key values. Verify their physical distribution.').replace('buffer counts for 1 s, then `ADD views :n` once.', 'buffer counts for 1 s, then apply an idempotently identified batch; a retry of bare ADD can double count.')
 q[5]['options'][0]['explanation']='B-tree pages may be cached and buffered; neither B-trees nor LSM trees universally win on write throughput.'
 q[5]['options'][1]['text']='LSM trees buffer writes and flush sorted files, which can suit heavy ingestion; reads and compaction add costs, so benchmark the workload and sustained compaction behavior.'
 q[5]['options'][1]['explanation']='This states the trade-off without promising a universal winner. Time partitioning can help locality and retention, depending on layout and compaction policy.'
 q[5]['workedExample']='1. B-tree inserts traverse and modify pages, potentially from cache, and may split pages; durable engines also log changes.\n2. A typical LSM engine logs writes, updates a memtable, flushes sorted files and later compacts them.\n3. Measure sustained ingestion, read latency, write amplification and stalls with the chosen durability settings.\n4. Time windows can help range locality and expiry, but late data and compaction policy affect repeated work.'
 q[6]['prompt']+=' The product must continue accepting the tenant\'s contracted traffic.'
 q[6]['workedExample']=q[6]['workedExample'].replace("That's about 5% of total load each.", 'If evenly distributed, that is about 5% of total load each.').replace('also helps noisy-neighbour and compliance', 'can reduce noisy-neighbour interference')
 q[7]['prompt']+=' Assume hash values are approximately uniform.'
 q[8]['options'][1]['text']='It permits up to 10 ms of batching delay for an unfilled batch, potentially reducing request overhead; measure the resulting throughput and latency.'
 q[8]['options'][1]['explanation']='The batch may send earlier when full. Backpressure can delay it longer, and reduced overhead can improve total latency under load; linger is not an end-to-end bound.'
 q[8]['workedExample']='1. Even linger.ms=0 can batch records when records accumulate before sending.\n2. linger.ms=10 permits waiting for an unfilled per-partition batch, normally until its delay expires or it fills.\n3. At a uniform 50,000 records/s, 10 ms brings 500 records total, distributed across partitions.\n4. Measure request counts, compression and end-to-end latency; broker backpressure and queues can delay sends beyond linger.'
 q[9]['options'][0]['text']='Appending independent entries can reduce contention on the balance row, though indexes, constraints and balance validation can still contend.'
 q[9]['options'][0]['explanation']='The original update lock can be avoided on this path; this does not make the entire write operation conflict-free.'
 q[9]['options'][2]['explanation']='Retained entries support history, but these three fields alone do not establish a complete, tamper-resistant or balanced double-entry accounting system.'
 q[9]['options'][3]['explanation']='A fresh read alone cannot prevent two simultaneous debits from overspending; validation and spending must be atomic or use safely reserved rights.'
 q[9]['workedExample']=q[9]['workedExample'].replace('so no shared row lock.', 'potentially avoiding that shared row lock while other contention remains.').replace('still need a consistent read of the balance:', 'need atomic balance validation and spending:')
 q[10]['prompt']=q[10]['prompt'].replace('from 10 s to 40 minutes over three days', 'throughout the observation period')
 q[10]['options'][1]['explanation']='The measured average arrival rate exceeds the drain rate. Rising age alone could have other causes, but these rates imply backlog growth while they persist.'
 q[11]['options'][0]['explanation']='This concentrates demand on one logical key. Depending on sort keys, indexes and adaptive splitting, it need not remain one physical partition.'
 q[11]['options'][3]['explanation']='With roughly even device traffic, high cardinality helps. A day bounds the time window, not bytes unless each device\'s rate and item size are bounded.'
 q[11]['options'][4]['explanation']='Five logical key values concentrate demand. They do not imply a permanent maximum of five physical partitions in a store that can split item collections.'
questions(b+'arch-scaling-writes.questions.json',writes,'Correct write-capacity assumptions, Kafka delay guarantees, DynamoDB physical distribution, queue arithmetic and ledger concurrency.',src)
report['reviewed_files']=list(dict.fromkeys(report.get('reviewed_files',[])+[b+'arch-scaling-writes.md',b+'arch-scaling-writes.questions.json']))
p_report.write_text(json.dumps(report,indent=2)+'\n')
