exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-system-design-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/system-design/08-architecture/'
src=['https://www.elastic.co/docs/reference/elasticsearch/rest-apis/paginate-search-results','https://www.elastic.co/docs/reference/elasticsearch/index-settings/index-modules','https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-index','https://lucene.apache.org/core/10_3_1/core/org/apache/lucene/search/similarities/BM25Similarity.html','https://raw.githubusercontent.com/apache/lucene/main/lucene/core/src/java/org/apache/lucene/search/similarities/BM25Similarity.java']
patch(b+'arch-search-systems.md',[
('so keyword stuffing doesn\'t win.', 'reducing the marginal reward for repetition; it does not guarantee immunity to keyword stuffing.'),
('a match in a 10-word title is more significant than one in a 5,000-word article.', 'within the same field and with other factors equal, shorter fields receive less length penalty. Scores across different fields also depend on their own statistics and boosts.'),
('Per query term, the score is roughly:', 'The classic BM25 teaching formula per query term is below. Its constant (k1 + 1) factor is omitted by current Lucene scoring, so the following numerical values explain this formula rather than predict exact Elasticsearch scores:'),
('taken modulo the number of primary shards.', 'mapped through the index\'s configured routing-shard scheme to a primary shard (a simple modulo description omits split-routing and partitioned-routing details).'),
('3. Once those copies have it, the write is acknowledged.', '3. The primary waits for in-sync copies or removal of a failed copy from the in-sync set before acknowledging. Inspect the response shard results and durability settings; an acknowledgment does not guarantee the configured replica count was available.'),
('The latency of a search is therefore set by the **slowest shard**,', 'The query phase waits for participating shards, and end-to-end latency also includes coordinating, fetch and network work,'),
('sends each shard request to the copy that has been responding fastest.', 'uses response-time, service-time and queue information to choose shard copies.'),
('page 1,000 at 10 per page makes *every* shard return its top 10,010', 'page 1,000 at 10 per page (from = 9,990) can require each participating shard to return up to its top 10,000'),
('The default `refresh_interval` is 1 second, though an index that hasn\'t been searched for 30 seconds stops refreshing in the background until it\'s searched again.', 'The default refresh_interval is 1 second in Elastic Stack and 5 seconds in Serverless. With the interval left implicit, search-idle shards can skip background refreshes until searched; explicitly setting the interval changes this idle behavior.'),
('a document is typically searchable about 1 second after indexing, not immediately.', 'search visibility follows refresh rather than acknowledgment; the configured interval is not a hard visibility deadline.'),
('Kafka buffers, so the indexer can be down or slow without losing changes.', 'Kafka buffers changes within configured durability and retention limits; monitor lag before records expire.'),
('use the row\'s version or log position with Elasticsearch\'s `version_type=external` so an older change can never overwrite a newer one.', 'map each complete row snapshot to a strictly increasing supported integer version and use version_type=external. Equal as well as older versions are rejected; handle a known duplicate conflict deliberately. Deletes need durable tombstones or another replay strategy because delete-version retention expires. A raw PostgreSQL LSN string is not directly a supported integer version.'),
('giving zero-downtime reindexing and schema changes.', 'supporting a cutover without intentionally stopping reads. Coordinate snapshot/live-change ordering, catch up before switching, and keep the old index current if rollback is required.'),
('Writes go to the primary and then to every replica; queries scatter to one copy of every shard and gather the top results, so the slowest shard sets latency.', 'Writes go through the primary and in-sync replication protocol; ordinary queries scatter to eligible shard copies, then coordinate and fetch results. Routing and shard pruning can reduce participation.'),
('documents become searchable on the next refresh, about 1 second by default.', 'documents become searchable on refresh; defaults and idle behavior depend on deployment and settings.')], 'Correct classic vs Lucene BM25 normalization, pagination off-by-one, refresh defaults, routing and versioned CDC guarantees.',src)
def search(q):
 q[1]['workedExample']=q[1]['workedExample'].replace('[great, for, run]', '[great, run] (the standard English stop list removes for)')
 q[3]['options'][1]['explanation']='With positive b, equal TF and other factors equal within the same field, a shorter field gets less length penalty. Cross-field scores also use different statistics and boosts.'
 q[3]['workedExample']+='\nThese numbers use the classic formula displayed here. Current Lucene omits its constant (k1+1) multiplier, so raw scores differ while this relative saturation behavior remains.'
 q[4]['prompt']+=' Assume unrestricted searches with no shard pruning and equal placement, giving the slow node two copies of different shards.'
 q[4]['options'][0]['explanation']='The query phase can be delayed by any participating slow shard. End-to-end latency also includes coordination, fetch and networking.'
 q[4]['workedExample']=q[4]['workedExample'].replace('Response time = max(shard response times) + merge.', 'A simplified query-phase model is max(shard response times) + merge; fetch and network work add further cost.')
 q[5]['options'][2]['text']='Use a correctly configured CDC/outbox path with durable retention and per-product ordering, then index complete snapshots using a suitable strictly increasing external version and a safe delete-replay policy.'
 q[5]['options'][2]['explanation']='This avoids independent request-level dual writes. Snapshot handoff, retained logs, ordering, duplicate conflicts and delete tombstones must be handled explicitly.'
 q[5]['workedExample']='1. Commit order and independent Elasticsearch request order can differ, and a second write may fail.\n2. Capture committed changes with a correct snapshot/log handoff and sufficient retained logs.\n3. Preserve per-product ordering through the whole pipeline or version complete snapshots. Matching keys alone do not order independent producers.\n4. Map the source sequence to a supported positive integer. version_type=external rejects equal and lower versions; treat a verified identical duplicate as complete.\n5. Keep durable deletion markers or another replay barrier so an old update cannot resurrect a deleted document after Elasticsearch forgets its delete version.\n6. Measure lag, monitor retention and support a coordinated full rebuild; no fixed sub-second lag is promised.'
 q[6]['options'][2]['explanation']='An atomic alias change avoids an intentional search outage, provided live updates were caught up correctly. Rollback also requires that the old index remains current.'
 q[6]['workedExample']=q[6]['workedExample'].replace('Meanwhile, send live changes to both (or replay the CDC stream from the backfill\'s start position).', 'Coordinate snapshot and CDC positions; use versions so older backfill records cannot overwrite newer changes, and apply deletes.').replace('Keep v1 for a while for rollback, then delete.', 'Keep v1 updated during the rollback window; an old index that stopped receiving writes is not a safe instant rollback.')
 q[7]['prompt']+=' Assume an ordinary Elastic Stack index with the default interval and a query that includes the listing regardless of score.'
 q[7]['workedExample']=q[7]['workedExample'].replace('(slower write, no extra refresh)', '(waits for visibility; excessive wait_for listeners can force a refresh)')
 q[9]['options'][0]['text']='Each shard may return up to 10,000 candidate hits: up to 200,000 across 20 shards. Offer search_after with stable sort values and a point-in-time view for consistent traversal.'
 q[9]['workedExample']=q[9]['workedExample'].replace('20 shards × 10,000 (id, score) pairs = 200,000 entries to merge.', 'up to 20 × 10,000 candidates = 200,000 entries, if enough matches exist.').replace('sort by (score, id), return the last hit\'s sort values, and pass them as `search_after` for the next page. Each page then costs about the same as page 1.', 'use supported sort fields with a stable tie-breaker and a point-in-time view, then pass the last hit\'s sort values as search_after. This avoids the growing offset window but does not guarantee identical page latency.').replace('real users rarely go past page 10; cap the UI.', 'choose a navigation or export limit from actual product needs, rather than an unsupported universal user-behavior claim.')
 q[10]['workedExample']+='\nThe arithmetic uses the displayed classic BM25 formula, not current Lucene\'s raw score scale; Lucene omits the constant (k1+1) factor.'
 q[10]['options'][2]['explanation']='Term frequency saturates rather than scaling linearly. The classic formula has a (k1+1) multiplier that current Lucene omits.'
 q[11]['options'][3]['explanation']='An indexed prefix query can scale well for some workloads, but this claim does not establish support for analyzed mid-title tokens and relevance. It need not hit a primary if replicas or caches serve it.'
 q[11]['workedExample']=q[11]['workedExample'].replace('Goal: prefix → candidates in a few milliseconds.', 'Goal: prefix → candidates within a measured latency budget.').replace('Elasticsearch\'s `search_as_you_type` field type packages this pattern.', 'Elasticsearch\'s search_as_you_type combines shingle subfields and an edge-ngram prefix subfield; it is not just every possible prefix of every token.')
questions(b+'arch-search-systems.questions.json',search,'Correct analyzer stop words, score comparisons, CDC deletes, alias rollback and search pagination claims.',src)
report['reviewed_files']=list(dict.fromkeys(report.get('reviewed_files',[])+[b+'arch-search-systems.md',b+'arch-search-systems.questions.json']))
p_report.write_text(json.dumps(report,indent=2)+'\n')
