exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-system-design-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/system-design/08-architecture/'
src=['https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-writes.html','https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html','https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html','https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html','https://docs.aws.amazon.com/AmazonS3/latest/userguide/directory-buckets-objects-append.html','https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html']
patch(b+'arch-object-storage-media.md',[
('Putting them in a relational database bloats backups and wastes buffer cache; putting them on app servers\' disks breaks statelessness. Almost every large system puts them in **object storage**:', 'Large media collections can increase database backup, replication and serving costs; database BLOBs can still suit smaller or transactionally coupled workloads. Depending on app-local files makes instance replacement harder. A common media architecture uses **object storage**:'),
('Object storage is a huge, flat key–value store for files:', 'This lesson uses S3 general purpose buckets as its main example: a flat key–value model for objects. Other products and bucket types differ; S3 Express One Zone directory buckets, for example, support appending to objects.'),
('**Effectively unlimited scale**: S3 holds hundreds of trillions of objects. A single `PUT` can upload up to 5 GB; larger objects need multipart upload, and an object can now be up to about 50 TB (48.8 TiB). The old limit was 5 TB until AWS raised it in late 2025.', '**Large objects**: a single PUT supports up to 5 GB; larger objects require multipart upload. The current multipart limits page lists a maximum of 48.8 TiB, with up to 10,000 parts. Check current service limits when implementing a client.'),
('What you give up: per-request latency is tens of milliseconds, not microseconds; there\'s no in-place update, no locking, no transactions across keys and no rich querying.', 'General purpose buckets do not provide arbitrary in-place byte updates, application editing mutexes, or multi-key transactional updates. S3 Object Lock provides retention protection, not a read-modify-write mutex. Use a separate query layer for rich metadata queries.\n\n> [!note] Evidence gap\n> Fixed object-store/CDN latency and transcoding speedup figures are omitted because no representative deployment benchmark supports them. Calculations below are hypothetical.'),
('the next `GET` or `LIST` sees it.', 'a subsequent authorized direct read of the same bucket sees that write or a later modification. This does not make CDN caches or cross-Region replication synchronous.'),
('S3 has no locks, but it does support conditional writes', 'S3 has no application editing mutex, but it does support conditional writes'),
('It can\'t be revoked individually, short of revoking the credentials that signed it.', 'There is no individual URL-token revocation API. Revoking credentials or changing applicable access policies can deny later requests; short expiry and narrow scope reduce exposure.'),
('Mark the object as available only when S3 confirms it, via an `ObjectCreated` event notification or by checking with a `HEAD` request. Then validate it (file type, size, malware scan) before showing it to anyone else.', 'Confirm the upload with S3, then validate the exact object version (file type, size and required scans). Notifications can be duplicated or out of order. A reusable presigned PUT can overwrite a key after a scan, so publish the validated version or protected processed output under an immutable key, not whichever bytes later occupy the upload key.'),
('Object storage isn\'t designed to serve millions of users directly at low latency. Put a **CDN**', 'Object storage can serve clients directly. To improve geographic delivery and reduce repeated origin work, put a **CDN**'),
('Edge caches near users typically cut latency from 100 ms or more to a few tens of milliseconds for cached content.', 'Nearby edge caches can reduce network distance for cache hits; measure the actual latency and hit rate.'),
('The origin (S3) sees only cache misses.', 'The origin sees misses, revalidations and requests that bypass caching.'),
('so you can cache for a year and never need to invalidate.', 'to avoid routine invalidation when publishing a new version. Removal or access-policy changes may still require invalidation or other controls.'),
('split a 60-minute video into 1-minute chunks and encode them across many workers simultaneously, then stitch. Large platforms such as Netflix use this kind of chunked, parallel encoding to cut processing time from hours to minutes.', 'split work at suitable codec boundaries, encode chunks concurrently, then assemble and package them. Handle keyframes/GOPs, timestamps, audio alignment and rendition boundaries; speedup depends on available workers and split/encode/assembly costs.'),
('Name outputs deterministically (`video/123/720p/seg_0042.ts`) so a retry overwrites rather than duplicates.', 'Include source version and encoding settings in output identity. Deterministic names alone do not guarantee idempotency: write temporary outputs, validate them, and conditionally publish a manifest so a stale retry cannot replace newer work.'),
('- Object storage is a flat, massively scalable, highly durable key–value store for blobs with whole-object operations; keep searchable metadata in a database.', '- S3 general purpose buckets use a flat object-key model; distinguish their guarantees from other products and bucket types. A database can maintain searchable metadata.')], 'Scope object-store semantics; correct size units, revocation, upload validation races, CDN invalidation and retry publication.',src)
def media(q):
 q[0]['prompt']+=' Assume large media volume, independently scalable delivery and indexed metadata filtering are required.'
 q[0]['options'][0]['explanation']='BLOB columns can be valid for some workloads, but coupling large media delivery to this database increases its scaling and operational burden under these requirements.'
 q[0]['options'][3]['explanation']='General purpose S3 listings are lexicographic and paginated. Carefully designed keys can support some ordering, but arbitrary metadata filters need additional indexing.'
 q[0]['workedExample']=q[0]['workedExample'].replace('object storage gives eleven nines of durability, unlimited capacity, cheap tiers, and works well with a CDN.', 'S3 Standard has an eleven-nines annual durability design target; this is not every storage class\'s guarantee. Object storage works well with a CDN.').replace('answers the query in milliseconds.', 'supports the requested access pattern; measure query latency.')
 q[1]['options'][1]['explanation']='The signature authenticates the operation and signed parameters; applicable permissions and policy must still allow it. The same URL can be reused while valid.'
 q[2]['prompt']='Users upload a 5 GB file using 100 MB parts (decimal units). Parts 1–32 are confirmed complete before a connection failure; no other parts completed. What happens when the client reconnects?'
 q[2]['options'][0]['explanation']='Completed parts remain under the upload ID until completion or abort. The 18 missing parts need uploading; retain and reconcile part numbers and ETags.'
 q[2]['workedExample']=q[2]['workedExample'].replace('3.2 GB uploaded ≈ 32 parts complete (a part that was mid-upload is lost).', 'The premise confirms 32 complete parts, totaling 3.2 GB. Transferred byte count alone would not prove this with parallel uploads.')
 q[3]['options'][2]['explanation']='Validate the exact source version and publish protected processed output. A still-valid upload URL can otherwise overwrite the key after validation.'
 q[3]['options'][4]['explanation']='Versioned keys avoid routine invalidation for new encodings; removal or access changes may still require cache controls.'
 q[3]['workedExample']='1. Authenticate, choose a server-owned upload key and issue a short-lived PUT URL. A presigned POST policy is an alternative upload mechanism for content-length-range constraints, not a policy attached to this PUT.\n2. Confirm and identify the uploaded source version; deduplicate notifications and reject stale work.\n3. Decode and validate that version, then generate variants.\n4. Publish validated outputs under protected immutable keys and conditionally update the database pointer.\n5. Do not expose a mutable upload key after scanning: a reusable presigned URL could replace its bytes.'
 q[4]['options'][0]['text']='To enable adaptive bitrate streaming: the player selects renditions as bandwidth and buffer conditions change, reducing startup delay and stalls when conditions permit.'
 q[4]['options'][1]['explanation']='S3 supports large objects; the current multipart maximum is listed as 48.8 TiB. Transcoding addresses playback needs, not a 100 MB storage limit.'
 q[4]['options'][2]['explanation']='CDNs can cache video files and segments; segment size trades switching flexibility against request overhead and caching behavior.'
 q[4]['options'][3]['explanation']='Encoding can increase bitrate or change resolution without recovering original detail that was never captured. A rendition is not necessarily lower bitrate.'
 q[5]['options'][0]['explanation']='A larger instance or accelerator could reduce encode time, but it does not by itself provide fine-grained recovery from interrupted work.'
 q[5]['options'][2]['explanation']='Bounded tasks allow parallelism and smaller retries. Correct boundaries and publication control are required; deterministic keys alone do not guarantee safe retries or a particular speedup.'
 q[5]['workedExample']='1. The original measured job takes 90 minutes. Splitting a 2-hour input into 120 one-minute chunks creates 120 tasks per rendition.\n2. In an ideal model with equal-cost chunks and 60 available workers, 2 rounds × (90/120 minutes) = 1.5 minutes. This ignores splitting, encoding boundary effects, scheduling, transfer and assembly.\n3. A failed worker repeats unfinished chunks, not necessarily the whole video.\n4. Use valid GOP/keyframe boundaries and preserve timestamps and audio alignment.\n5. Identify output by source version and encoding settings; validate temporary artifacts and conditionally publish the manifest to block stale retries.\n6. The workflow tracks completion, assembly and publication. Measure actual end-to-end latency.'
 q[6]['prompt']='An S3 log writer sees 503 Slow Down during sharp request-rate increases. Monitoring points to S3 request scaling rather than KMS throttling. Which response is appropriate?'
 q[6]['options'][1]['text']='Retry with backoff and jitter, control the ramp-up, and measure whether parallel request distribution across prefixes or batching small logs improves sustained performance.'
 q[6]['options'][1]['explanation']='S3 scales automatically and gradually. Prefix distribution can help; 3,500 writes/s is documented as at least, not a fixed ceiling, and random prefixing is not universally required.'
 q[6]['workedExample']='1. Check actual peak requests/s and the failing dependency; objects/hour does not establish the instantaneous limit.\n2. S3 documents at least 3,500 write requests/s per partitioned prefix, with gradual automatic scaling.\n3. Use bounded retries with backoff and jitter, and ramp load while observing errors.\n4. If warranted, distribute requests or combine small log records into larger objects. Neither prefix count nor hashing guarantees proportional throughput.'
 q[7]['prompt']+=' Assume an authorized direct request to the same bucket, with no intervening overwrite/delete, CDN cache or cross-Region replica.'
 q[7]['options'][0]['explanation']='Modern S3 object reads are strongly consistent. The older consistency model had operation-specific exceptions, so it should not be summarized as every new object being eventually consistent.'
 q[7]['options'][1]['explanation']='For this same-bucket direct read, the completed write is visible. This guarantee does not make a different bucket\'s cross-Region replication synchronous.'
 q[7]['workedExample']=q[7]['workedExample'].replace('any read initiated after a successful PUT response returns that write.', 'a direct same-bucket read after this successful PUT returns that write, absent a later modification and given valid authorization.')
 q[8]['workedExample']=q[8]['workedExample'].replace("ECS role credentials typically rotate every 1 to 6 hours, so a '24-hour' link fails early.", 'Inspect the signing credentials\' actual expiration. Refreshing a task\'s current credentials is not itself revocation of an older still-valid session; that session\'s expiration caps the link.')
 q[9]['prompt']+=' Use decimal TB and MB in this calculation.'
 q[10]['options'][2]['explanation']='Versioned immutable keys avoid invalidation for routine new encodings; removal and access-policy changes can still need separate controls.'
 q[10]['workedExample']+='\n6. Signed URLs/cookies are bearer capabilities; scope and expire them appropriately. They cannot revoke a copy already downloaded.'
 q[11]['prompt']+=' Assume the first completed write changes the object ETag.'
 q[11]['options'][0]['explanation']='Unconditional read-modify-write can lose a change from the current version. S3 Object Lock concerns retention, not mutual exclusion between these edits.'
 q[11]['options'][2]['explanation']='An ETag mismatch produces 412. This checks ETag equality, not every possible version/metadata change; concurrent conflicts or deletion can also produce 409 or 404.'
 q[11]['workedExample']=q[11]['workedExample'].replace('v2a is gone.', 'the current version lacks A\'s change; enabled versioning may retain older versions.').replace('If someone else wrote in between, S3 returns 412 Precondition Failed;', 'If the ETag changed, S3 returns 412 Precondition Failed; also handle documented conflict/deletion outcomes;')
questions(b+'arch-object-storage-media.questions.json',media,'Fix multipart assumptions, exact-version validation, request-scaling limits, cross-region consistency and conditional-write scope.',src)
report['reviewed_files']=list(dict.fromkeys(report.get('reviewed_files',[])+[b+'arch-object-storage-media.md',b+'arch-object-storage-media.questions.json']))
p_report.write_text(json.dumps(report,indent=2)+'\n')
