from pathlib import Path
p=Path('content/networks/03-tcp/tcp-congestion.md');s=p.read_text()
def r(a,b):
 global s
 assert a in s,a[:100]
 s=s.replace(a,b)
r("CUBIC's cubic growth curve (Linux's default)","CUBIC's cubic growth curve")
r('The links were fine. The problem was TCP itself:','Jacobson and Karels attributed much of the problem to transport implementations’ response to congestion:')
r('No router tells it; it has to work it out from ACKs, losses and delays.','Signals include ACK progress, losses, delays and, when deployed, explicit congestion marks from routers.')
r('its own estimate of how much data the path can hold.','a sender-side limit on outstanding data derived from its congestion-control policy, not a direct measurement of network storage.')
r('It sends at most `min(cwnd, rwnd)` unacknowledged bytes.','In a simplified steady-state model, new-data sending respects `min(cwnd, rwnd)`; recovery, probes, pacing and earlier in-flight data require more detailed accounting.')
r('Because about one window is sent per round trip:','For a continuously backlogged, window-limited flow under stable conditions:')
r('It starts with a small **initial window**, now **10 segments** (about 14.6 KB, [RFC 6928](https://www.rfc-editor.org/rfc/rfc6928)), and adds one MSS to cwnd for every MSS acknowledged.','Its **initial window** is implementation/configuration dependent. RFC 6928 experimentally permits an upper bound `min(10*MSS, max(2*MSS, 14600))` bytes, giving IW10 for MSS 1,460; it does not require every TCP to start at ten segments. Classic slow start increases cwnd on ACKs of new data, with rules affected by ACK frequency and byte-counting variants.')
r('Every segment in a window brings back an ACK that adds one more segment, so cwnd **doubles every RTT**.','In the idealised model with an ACK per full segment and enough data/window capacity, cwnd **doubles per round**. Delayed ACKs, pacing, limits and different growth rules alter that approximation.')
r('A 100 KB response is about 69 segments of 1,460 bytes. With IW10 it takes three round trips of data: 10, then 20, then the remaining 39 (the window would allow 40). At 100 ms RTT, that is about 300 ms of transfer on top of the handshakes, whatever the bandwidth.','A 100,000-byte response needs 69 payload segments at MSS 1,460. Under ideal round-based IW10 doubling, it uses three flights: 10, 20, then 39 (capacity 40). Ignoring serialization, those flights can start near t=0, RTT and 2×RTT. Last-byte arrival additionally needs forward-path delay; final acknowledgement needs return delay. Three flights do not automatically mean 300 ms of extra transfer time at RTT 100 ms.')
r('two flows sharing a link converge to an equal share.','in a simplified synchronous feedback model with comparable flows, rates can converge toward equal shares. Real TCP fairness depends on RTTs, loss/mark patterns, starting times, bottlenecks and algorithm variants.')
a=s.index('- **Three duplicate ACKs** (fast retransmit):');z=s.index('\nIts predecessor',a)
s=s[:a]+'''- **Three qualifying duplicate ACKs**: classic fast retransmit enters fast recovery. The RFC 5681 threshold uses `max(FlightSize/2, 2*SMSS)` as an upper bound, not universally cwnd/2. Reno temporarily inflates cwnd to ssthresh + 3×SMSS, with further duplicate-ACK handling, then deflates on a recovery-completing ACK. The simplified trace below shows only the post-recovery reduction.
- **Retransmission timeout**: on the first RTO retransmission of that data, apply the threshold rule; set the loss window to at most one full-sized segment and resume slow start. A repeated RTO for the same data does not repeatedly halve ssthresh under the RFC rule. Loss/timeout observations do not prove “mild congestion” or “nothing is getting through”.
''' +s[z:]
r('with SACK, the sender knows every hole anyway.','SACK supplies additional received-range information, but limited reports, reordering and receiver reneging still require a loss-recovery algorithm.')
r('This simulation counts cwnd in segments, per RTT, starting from cwnd = 1 and ssthresh = 32 for clarity:','This illustrative per-round model counts segments, assumes a full flight and ideal ACK clock, starts at cwnd=1/ssthresh=32, and treats each event as a separate recovery episode. It omits temporary recovery inflation, repeated-RTO rules, partial ACKs, retransmission scheduling and receiver limits. Its integer halving and hard threshold cap are teaching choices, not a full Reno implementation:')
r('def reno(n, events, cwnd=1, ssth=32):\n    for r in range(n):','def reno(n, events, cwnd=1, ssth=32):\n    if (type(n) is not int or n < 0\n            or type(cwnd) is not int\n            or type(ssth) is not int\n            or cwnd < 1 or ssth < 2):\n        raise ValueError("bad model inputs")\n    for when, event in events.items():\n        if (type(when) is not int\n                or not 0 <= when < n\n                or event not in\n                ("dupack", "timeout")):\n            raise ValueError("bad event")\n    for r in range(n):')
r('A long-running Reno flow oscillates between W/2 and W, averaging about **0.75 W**.','A simplified stable sawtooth with linear growth from W/2 to W has time-average window **0.75 W**. Timeouts, unequal cycles, variable RTTs and application limits change that model.')
r('Consider 10 Gbit/s at 100 ms RTT with 1,500-byte packets:','Consider a model counting 1,500 payload bytes per segment, ignoring headers, at 10 Gbit/s and 100 ms RTT:')
r('Reno simply can\'t use fast long-distance links.','This illustrates Reno’s scaling limitation under the stated assumptions, not an absolute impossibility for every fast path or workload.')
r('has been Linux\'s default since 2006, and is the default on Windows and macOS too.','is widely implemented; the actual default is chosen by the operating system, version and configuration.')
r('on loss it multiplies cwnd by **β = 0.7** rather than 0.5.','its congestion-event reduction normally uses **β = 0.7**; recovery and RTO handling require additional rules. It does not reduce independently for every lost packet.')
r('not per ACK:','to define a target, with actual window updates still driven by ACK processing:')
r('`K` is the time it takes to return to Wmax.','In this simplified epoch, `K` is where the pure cubic target reaches Wmax. Actual behaviour also includes the Reno-friendly estimate, fast convergence, ACK updates and exclusion of application-limited periods.')
r('flows with different RTTs grow at the same rate; Reno favours short-RTT flows, which get more ACKs per second.','the cubic window target reduces dependence on ACK-round counting outside the Reno-friendly region. Similar windows do not imply equal throughput for different RTTs; CUBIC still has RTT bias.')
r('so it is never less aggressive than Reno.','to improve coexistence. That model comparison is not a guarantee that every actual CUBIC flow always outperforms an actual Reno flow.')
r('it keeps growing until a buffer overflows.','it responds to congestion events, which can include ECN marks before buffer overflow. Without suitable queue management its probing can build queues.')
r('instead of reacting to loss, it **measures** the two numbers that define the path, and sends at the rate they imply.','it estimates path properties from delivery feedback and controls pacing/in-flight data from a model. The numerical details below describe **BBRv1 as implemented in Linux v6.12**, not all BBR versions.')
r('estimated as the **maximum delivery rate** seen over the last several round trips.','estimated using a windowed maximum of delivery-rate samples over ten packet-timed rounds in this version, with safeguards for limited sending and other conditions.')
r('estimated as the **minimum RTT** seen over the last 10 seconds.','estimated using a ten-second windowed minimum in this version. The estimate includes endpoint/serialization effects and may include persistent queueing; it is not pure physical propagation delay.')
r('about 2× in BBRv1','a base gain near 2× in BBRv1, with minimum-window, ACK-aggregation and other adjustments')
r('The catch is that you can\'t measure both at once: to see the bandwidth you must fill the pipe (which builds a queue and raises RTT), and to see the true RTT you must drain it.','To observe available delivery capacity the sender must offer enough data; probing beyond it can build a queue and obscure the baseline RTT. Reducing in-flight data can help refresh the RTT estimate. These are estimation challenges, not a theorem that full utilisation always requires a queue.')
r('| ProbeBW | Cycles gain 1.25, 0.75, then 1.0 for six RTTs |','| ProbeBW | Gains 1.25, 0.75, then six 1.0 phases; transitions use timing/in-flight checks |')
r('| ProbeRTT | Every ~10 s, drop to 4 packets for at least 200 ms to refresh RTprop |','| ProbeRTT | On qualifying minimum-RTT expiry, reduce toward 4 packets; duration includes at least 200 ms and a completed round |')
a=s.index('Strengths: BBR keeps queues short,');z=s.index('\n## ECN:',a)
s=s[:a]+'''BBRv1 aims to keep utilisation high without persistently filling queues and can avoid repeated Reno/CUBIC-style reductions for non-congestion loss. It still performs loss recovery and includes loss-related recovery/policer handling; “ignores all loss” is false. Results depend on the path and competing traffic, so there is no guaranteed speedup or fairness outcome.

Later BBR versions change the model and loss response. The **July 2026 BBRv3 IETF draft** retrieved here remains experimental and explicitly does **not** specify a particular ECN response; claims that every BBRv2/v3 implementation has one common ECN algorithm are omitted. Linux BBR uses packet pacing, via `fq` or internal pacing support in the examined implementation.
''' +s[z:]
r('Loss-based algorithms only learn about congestion by losing packets.','Loss-oriented controllers can also react to explicit congestion indications.')
r('Both sides agree to use ECN in the handshake.','In classic TCP ECN (RFC 3168), both sides negotiate ECN capability in the handshake. Later ECN schemes have different feedback details.')
r('A router with a building queue sets **CE** (Congestion Experienced) rather than dropping.','A capable queue-management algorithm may set **CE** (Congestion Experienced) on eligible packets instead of dropping; overload and policy can still cause drops.')
r('No data is lost and no retransmission is needed.','A delivered CE-marked packet does not need retransmission merely because it was marked. ECN does not prevent unrelated loss or guarantee a one-RTT improvement.')
r('On Linux:\n','Example Linux inspection commands (shown output is illustrative, not a guaranteed default):\n')
r('so a server switching to BBR helps downloads to every client without any client changes.','so a server can change its TCP sender algorithm without requiring the client to use the same controller. Whether performance improves must be measured; receiver feedback and available implementation support still matter.')
r('Slow start doubles cwnd each RTT from an initial 10 segments; congestion avoidance adds one segment per RTT; AIMD converges to fairness.','Idealised slow start grows exponentially; Reno avoidance grows roughly one segment per RTT. Initial windows and fairness depend on the model and implementation.')
r('Reno halves cwnd on three duplicate ACKs (fast recovery) and resets to one segment on a timeout.','Reno uses flight-size-based threshold and fast-recovery rules; an RTO invokes a much smaller loss window.')
r('BBR measures bottleneck bandwidth and minimum RTT and paces at that rate, keeping queues low and ignoring random loss, at some cost in fairness with loss-based flows.','BBR versions estimate delivery capacity and baseline RTT to control pacing, with version-specific loss handling and coexistence trade-offs.')
s+='\n> [!note] Content omitted after review\n> Universal operating-system defaults, guaranteed equal-share fairness and fixed BBR speedups are omitted because this review did not establish suitable versioned measurements. Congestion-control traces here are explicit models, not packet-level benchmarks.\n\n- [Linux v6.12 BBRv1 implementation](https://github.com/torvalds/linux/blob/v6.12/net/ipv4/tcp_bbr.c)\n- [BBRv3 IETF draft, July 2026](https://datatracker.ietf.org/doc/html/draft-ietf-ccwg-bbr-06)\n'
p.write_text(s)
