from pathlib import Path
p=Path('content/networks/03-tcp/tcp-performance.md');s=p.read_text()
def r(a,b):
 global s
 assert a in s,a[:70]
 s=s.replace(a,b)
r('Then there is a fourth, structural problem: TCP is very hard to change. That is why the newest transport, QUIC, isn\'t TCP at all.','Deployment is another constraint: transport changes must work with deployed endpoints and middleboxes. QUIC provides an alternative design over UDP.')
r('Most web objects are small. For them, bandwidth hardly matters; the number of round trips does.','For small responses on a sufficiently fast link, handshake and request round trips can dominate. Serialization, server work, DNS, certificate size and loss can also matter.')
r('Fetching a 100 KB object over a brand-new HTTPS connection at 100 ms RTT:','Illustrative model: fetch 100,000 payload bytes over a new TCP + TLS 1.3 connection at 100 ms RTT, with MSS 1,460 bytes, initial window 10 segments, ideal doubling per completed flight, negligible serialization/server processing, no DNS delay, no loss, no TLS retry and no other limits. Ignore handshake bytes when modelling the response window:')
r('With TLS 1.2 the handshake takes two round trips, so six in total. Doubling bandwidth changes none of this; halving the RTT halves it. This is why CDNs terminate connections close to users, why connection reuse (keep-alive, HTTP/2) matters so much, and why removing round trips is the main goal of TLS 1.3, TCP Fast Open and QUIC.','The response needs 69 segments, sent in flights of 10, 20 and 39. The request/first response costs one RTT; each further flight adds one RTT in this ideal model. A conventional full TLS 1.2 handshake adds a round trip relative to TLS 1.3; resumptions differ. The table is an estimate under these assumptions, not a measured or universal HTTPS latency. Connection reuse and closer servers can reduce round-trip costs.')
r('TFO ([RFC 7413](https://www.rfc-editor.org/rfc/rfc7413)) lets a returning client put data in its SYN, using a cookie from an earlier connection, saving one RTT. It works, but middleboxes that drop SYNs with unexpected data or options limited its deployment, and browsers largely gave up on it. That is a recurring theme.','TFO ([RFC 7413](https://www.rfc-editor.org/rfc/rfc7413)) can let a client with a previously obtained cookie send data in its SYN. When supported and accepted, this can save a round trip. Applications must handle replay-related restrictions and implementations need fallback for incompatible paths. This lesson makes no current browser-adoption claim.')
r('For a long-running Reno-style flow, Mathis, Semke, Mahdavi and Ott (1997) derived a simple ceiling:','The Mathis model approximates a sustained Reno-style congestion-avoidance flow with light/moderate loss, sufficient sender data and receive window, and no retransmission timeouts. The ideal one-ACK-per-segment sawtooth yields:')
r('rate  <=  ----- x -----','rate  ~=  ----- x -----')
r('    """bits/s ceiling for one Reno flow."""\n    return mss * 8 / rtt * 1.22 / sqrt(p)','    """Ideal Reno-model estimate in bits/s."""\n    if mss <= 0 or rtt <= 0 or not 0 < p < 1:\n        raise ValueError("invalid parameters")\n    return mss * 8 / rtt * 1.22 / sqrt(p)')
r('At 100 ms RTT, 0.01% loss caps one flow at about **14 Mbit/s**, and 1% loss at about **1.4 Mbit/s**, regardless of link speed. Three lessons follow:','At 100 ms RTT, the formula returns about **14 Mbit/s** for p = 0.0001 and **1.4 Mbit/s** for p = 0.01. These are model outputs, not universal caps or predictions for arbitrary packet-loss patterns. ACK behaviour changes the constant; timeouts and other limits can invalidate the approximation. Within the model:')
r('A server twice as far away gives half the throughput at the same loss rate. Distance hurts twice: more latency and less bandwidth.','Doubling RTT halves the estimate when all other parameters stay fixed. Geographic distance does not by itself determine RTT.')
r('CUBIC beats the formula on long-RTT paths; BBR largely sidesteps it because it doesn\'t react to each loss.','This Reno model should not be applied as a general throughput law for CUBIC or BBR.')
r('The formula is also a diagnostic tool. If a transfer runs at the Mathis rate for its measured RTT and loss (`ss -ti` shows both), the bottleneck is loss, not the link or the receiver.','Use the formula as a teaching comparison, not a unique diagnosis. Matching it does not rule out other bottlenecks. `ss -ti` exposes TCP state and counters on Linux; its retransmission counters are not automatically the model’s loss probability. Compare captures, application demand, receive windows, congestion-control state and link utilisation.')
r('Loss-based congestion control (Reno, CUBIC) keeps increasing cwnd until a buffer overflows. So on a path with an oversized buffer at the bottleneck, a single upload fills it and keeps it full:','A saturated loss-based flow with a large tail-drop queue can sustain substantial queue occupancy. ECN, AQM, competing traffic and sender limits change this behaviour. For a packet joining a FIFO behind the following backlog:')
r('256 KB at a 2 Mbit/s uplink:','256 KiB at a 2 Mbit/s uplink:')
r('Every packet on that link, including your video call, DNS lookups and game traffic, now waits a second in the queue. The throughput is fine; the **latency under load** is terrible. Jim Gettys named this **bufferbloat** in 2010.','A packet behind that backlog waits about 1.05 seconds before its own transmission, ignoring overhead and changes in link rate. Other queues or priority classes can see different delays. Sustained excessive queueing is **bufferbloat**: high throughput can coexist with poor latency under load. The following RTTs are illustrative:')
r('The fix is to manage queues by **delay**, not size:','Active queue management signals congestion before excessive persistent queues develop. Delay is the signal used by CoDel; other AQM designs use other measurements:')
r('If the minimum delay over an interval (100 ms) stays above a **target** (5 ms), it starts dropping (or ECN-marking) packets, more often the longer the excess persists. Bursts pass; standing queues don\'t.','Its usual target and interval are 5 ms and 100 ms. Persistent excess sojourn time can trigger drops or ECN marks; a remaining-backlog check avoids needlessly starving the link. The target is not a hard upper bound on every packet’s delay, and finite buffers can still drop bursts.')
r('each flow gets its own queue, served round-robin, so a bulk upload can\'t delay a sparse flow like a VoIP call. It is the default queueing discipline in many Linux distributions and in OpenWrt.','packets are hashed into queues, with modified deficit round-robin scheduling and CoDel. This reduces interference between bulk and sparse traffic; hash collisions and shared bottlenecks mean isolation is not absolute.')
r('goes further: scalable congestion controllers plus shallow ECN marking aim for queueing delays of around a millisecond.','describes an architecture using scalable congestion control and compatible ECN/AQM behaviour to target low queueing delay. It is not merely a replacement name for CoDel or a guarantee of one-millisecond end-to-end latency.')
r('On the sender side, **BBR** and **pacing** avoid building queues in the first place. Note that the bloated buffer is usually at the bottleneck, often your own uplink, so the fix there is in the home router.','**Pacing** spreads transmissions and can reduce bursts; **BBR** uses a path model but can still build queues. Locate the actual bottleneck. When it is an inaccessible modem/ISP queue, suitable shaping on a controlled router can move the bottleneck to a queue where AQM is effective; measure the throughput trade-off.')
r('every byte after it waits in the receiver\'s buffer until the retransmission arrives','later stream bytes cannot be delivered in order until the gap is filled (or the connection fails)')
r('js, img1, img2: all wait ~1 RTT','later bytes wait for gap recovery')
r('HTTP/1.1 browsers opened six connections per host, so one loss stalled one of six. HTTP/2\'s single connection is more efficient but, on lossy networks (mobile, Wi-Fi), one loss stalls **everything**. At a few per cent loss, HTTP/2 can be slower than HTTP/1.1. The transport, not HTTP, is the problem.','Multiple HTTP/1.1 connections have separate TCP delivery ordering; HTTP/2 multiplexes streams on a connection. A TCP gap blocks later bytes on that connection, not resources already delivered or other connections. Recovery has no fixed one-RTT duration. Which HTTP version is faster depends on the workload, implementation and path.')
r('TCP is implemented in OS kernels, and many devices along the path inspect and rewrite it:','TCP commonly runs in OS kernels, although user-space implementations exist. Devices along a path may inspect or rewrite it:')
r('Measurements found a meaningful fraction of paths interfere with new options. Multipath TCP had to be designed to fall back gracefully when its options were removed.','Compatibility therefore needs testing and fallback. Multipath TCP includes fallback to ordinary TCP when its negotiation does not succeed.')
r('**Kernel upgrade cycles** are measured in years on phones and servers.','**Deployment dependencies** can include OS updates and peer support, depending on the extension. Sender-only congestion-control changes need not update both endpoints.')
r('So new TCP features take a decade or more to deploy, if they deploy at all (as TFO shows). The protocol has **ossified**: the network\'s assumptions froze its wire format.','These constraints contribute to **ossification**: deployed equipment’s assumptions can restrict protocol evolution. This does not mean every TCP change takes a decade or that extensions have stopped.')
r('and is implemented in **libraries**, not the kernel.','and can be implemented in application **libraries** without changing the kernel; the protocol does not mandate an implementation location.')
r('Transport and TLS 1.3 combined: 1 RTT, or 0-RTT on resumption','Combined transport/TLS setup; eligible 0-RTT sends early data, with replay restrictions')
r('Independent streams; a loss stalls only its own stream','Per-stream ordering avoids TCP’s connection-wide delivery gap; shared limits remain')
r('Almost everything, including ACKs, is encrypted','Protected control frames reduce ossification; some fields remain observable')
r('Ships with the app or browser','Can ship in application libraries')
r('Connection IDs, not the 4-tuple','Connection IDs support eligible, validated client migration')
a=s.index('- **Encrypted headers.**');b=s.index('\n### The costs of QUIC',a)
s=s[:a]+'''- **Protection.** QUIC protects payloads, including ACK/control frames, and masks selected header bits and packet numbers. Connection IDs and other fields remain observable. Initial packet keys are publicly derivable, so Initial protection does not provide confidentiality against an observer. The optional spin bit can assist RTT estimation.
- **Loss recovery.** A newly transmitted packet uses a new packet number within its packet-number space; stream data may be resent at the same stream offset. This removes TCP's original-versus-retransmission ACK ambiguity. It does not make loss detection infallible: reordering can still cause spurious loss declarations.
- **Migration.** After handshake confirmation, connection IDs can support client migration, subject to negotiated restrictions, address validation and a working new path. A zero-length connection ID constrains migration. Success and seamless latency are not guaranteed.
- **Shared effects.** Loss can reduce a connection's congestion window, and flow control or application dependencies can delay several streams. QUIC removes the requirement to wait for an unrelated stream's missing bytes; it does not promise complete independence.
- **Congestion control.** RFC 9002 gives a NewReno-like example; compatible alternatives can be implemented. A library deployment can update the algorithm without an OS upgrade.
''' +s[b:]
r('Kernel TCP benefits from decades of optimisation and NIC offloads (segmentation, checksums). QUIC\'s per-packet encryption and user-space processing historically cost noticeably more CPU per byte; UDP segmentation offload (GSO/GRO) and batched system calls narrow the gap.','Encryption, packet processing, batching and offload support affect cost. Compare QUIC with the actual alternative, often TCP **plus TLS**, using measurements for the implementations and workload. User-space location alone does not determine performance.')
r('Browsers race or fall back to TCP, so HTTP/3 is always an optimisation, never a requirement.','Applications that support HTTP/2 or HTTP/1.1 can provide a TCP fallback. QUIC-only applications do not automatically acquire such a fallback.')
r('Keep-alive and pools remove handshakes and keep cwnd warm.','Reuse can avoid setup while a connection remains valid. Idle periods can change congestion-control state.')
r('Linux\'s `tcp_slow_start_after_idle = 1` (the default) shrinks cwnd after an idle period; long-lived connections that send in bursts often set it to 0.','Linux documents `tcp_slow_start_after_idle = 1` as enabling window timeout after sufficient idle time. Assess the algorithm, version and burst risk before changing it; there is no universal recommendation to disable it.')
r('**Size buffers for the BDP** on high-speed long-distance transfers, by raising `tcp_rmem`/`tcp_wmem` maxima.','**Check buffer limits against measured BDP** if flow control is limiting throughput. Linux socket-memory accounting and advertised windows differ; blindly raising maxima may waste memory without helping.')
r('**Consider BBR with the fq qdisc** for servers sending to lossy or distant clients.','**Compare congestion control and pacing configurations** under representative load, including competing traffic and latency. Do not infer a universal BBR improvement from one test.')
a=s.index('## Key takeaways');b=s.index('## Further reading',a)
s=s[:a]+'''## Key takeaways
- Round trips can dominate short transfers; longer transfers can be limited by capacity, congestion control, receive windows, endpoints or application demand.
- The Mathis approximation teaches Reno scaling under explicit assumptions; it is not a universal TCP ceiling or a standalone diagnosis.
- Queueing delay depends on queued work and service rate. AQM, scheduling and pacing address different parts of the problem.
- TCP's ordered byte stream can block later HTTP/2 bytes behind a gap.
- QUIC supports per-stream ordering, integrated TLS and eligible migration, while retaining shared resource constraints and deployment trade-offs.

> [!note] Evidence limits
> Universal browser connection counts, current TFO adoption, fixed protocol speedups and CPU costs are omitted because they require versioned deployment data or measurements not established here. The numerical timing and throughput examples are explicitly simplified models. This review did not run a WAN, QUIC migration or AQM performance experiment.

''' +s[b:]
s+='\n- [RFC 9001: Using TLS to Secure QUIC](https://www.rfc-editor.org/rfc/rfc9001)\n- [RFC 9002: QUIC Loss Detection and Congestion Control](https://www.rfc-editor.org/rfc/rfc9002)\n- [Mathis and Mahdavi: Deprecating the TCP Macroscopic Model (2019 editorial)](https://ccronline.sigcomm.org/wp-content/uploads/2019/10/acmdl19-323.pdf)\n'
p.write_text(s)
