import json
from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-internet-structure.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['workedExample']='The paid service provides broad onward Internet reachability: full transit in this scenario. The neighbour exchange is limited to agreed customer-network reachability and has no settlement payment: settlement-free peering. Transit can supply a default route rather than a full table, peering need not give equal benefits, and both arrangements still have infrastructure costs.'
q(2)['options'][0]['explanation']='Correct as the shared-fabric model. Routes depend on participants’ peering policies and route-server filters; connecting does not automatically give every peer’s routes.'
q(2)['options'][1]['explanation']='IXP peering itself is not full Internet transit. An exchange operator may sell additional services, but a peering port does not imply free transit.'
q(2)['workedExample']='A shared fabric can reach many willing peers without a separate physical link for each. Route servers exchange eligible routes and normally stay out of the data forwarding path; membership and policies limit what is received. Redundant ports/sessions may be needed, and private interconnects remain an option where capacity or policy justifies them.'
q(3)['prompt']='Assume both the forward and return paths each contain exactly 3,000 km of fibre at 204,000 km/s, with other delays ignored. What is the propagation RTT?'
q(3)['workedExample']=q(3)['workedExample'].replace('This is a floor. Real paths are longer than the straight line, and every router and queue adds delay.','This is the propagation component for the supplied actual route lengths. Other delays add to it; if 3,000 km instead described straight-line distance, actual route length would require separate evidence.')
q(4)['prompt']='Use an ideal lower-bound GEO bent-pipe model: request and reply each traverse ground → satellite → ground, with every leg set to the 35,786 km orbital altitude. At about 299,792 km/s, what propagation RTT does the four-leg model give?'
q(4)['options'][3]['explanation']='20 ms does not follow from the supplied GEO distance. Lower orbits can have much smaller propagation delays, but actual service RTT requires additional path information.'
q(4)['workedExample']=q(4)['workedExample'].replace('so real RTTs are typically 600 ms or more. Every TCP and TLS handshake round trip costs this much.','so actual latency exceeds the idealised vertical-leg component. This does not establish a universal 600 ms service RTT.')
q(5)['options'][2]['explanation']='Under the stated model, eligible peer routes are made available to customers. A customer using a default route need not receive each specific prefix individually.'
q(5)['workedExample'] += '\n\nThese are the question’s commercial export assumptions. Actual contracts, selective exports, paid peering and other policies can differ.'
q(6)['prompt']='Verified path information shows London-to-London traffic taking a detour via Amsterdam. Which mechanisms could explain that route? Select all that apply.'
q(6)['options'][0]['explanation']='Correct. Configured policy can prefer a physically longer route. Customer/peer/provider ordering is an operator choice, not a universal BGP requirement.'
q(6)['options'][2]={'text':'The selected interconnection between those networks is in Amsterdam','explanation':'Correct. The chosen path can detour to that interconnection; other transit routes may also exist.'}
q(6)['options'][3]={'text':'With higher-priority attributes equal, a shorter AS_PATH can be preferred even if its physical route is longer','explanation':'Correct. AS-path length does not measure kilometres; one AS can span a large area.'}
q(6)['options'][4]['explanation']='There is no requirement for every Internet path to cross a Tier 1. Direct peering and local caches provide counterexamples without needing a global traffic-share claim.'
q(6)['workedExample']='Policy preference, selected interconnection location and AS_PATH comparison can each produce geographic detours. BGP does not inherently measure RTT, though external controllers can feed measured information into policy. Reverse paths may differ. Hostnames in traceroute alone would not have established the geography; this question supplies verified path information.'
q(7)['prompt']='Use an ideal PON capacity model with exactly 10,000 Mbit/s downstream, 32 active homes, equal sharing, no overhead or other bottleneck, and each demanding its 900 Mbit/s plan rate. What share does each home receive?'
q(7)['options'][0]['explanation']='Correct under the explicitly assumed equal sharing: 10,000 / 32 = 312.5 Mbit/s. Actual scheduling and goodput need not divide equally.'
q(7)['workedExample']='The supplied model divides 10,000 Mbit/s equally among 32 homes, giving 312.5 Mbit/s each. Aggregate offered demand is 32 × 900 = 28,800 Mbit/s, or 2.88 times that capacity. Real PON line rates, overhead, service scheduling and other bottlenecks alter the result; the model does not guarantee a real household’s rate.'
q(8)['prompt']='Assume Sydney users’ RTT to a Virginia-only service is dominated by geographic propagation, with negligible queueing and serialization. Which change directly reduces the response path’s propagation distance for locally serviceable requests?'
q(8)['options'][0]['explanation']='A capacity increase can reduce serialization or congestion in other circumstances, but it does not shorten the geographic path specified here.'
q(8)['options'][2]['explanation']='Congestion control can change queueing delay, but under these assumptions it does not shorten the propagation path.'
q(8)['options'][3]['explanation']='Correct for content or requests that the nearer location can serve locally. Requests that still wait on Virginia retain that remote dependency.'
q(8)['workedExample']='Placing serviceable data/work near Sydney shortens the relevant path. A CDN hit can help, while a miss or synchronous origin dependency may still wait for Virginia. Protocol changes can reduce the number of exchanges, and routing or queue improvements can reduce RTT in other scenarios. No fixed local RTT is guaranteed.'
q(9)['workedExample']=q(9)['workedExample'].replace('P2 learned the route from peer P1 and exports peer routes only to customers, so P3 never hears it.','For traffic toward P3, P2 learns P3’s route from a peer and would not export it to peer P1 under the model. The forward path therefore cannot be built by those exports.')
q(10)['prompt']='A hypothetical network advertises 192.0.0.0/22. A different origin advertises its contained 192.0.2.0/24. A router accepts and installs both routes, with a shorter AS path for the /22. Why does an ordinary destination lookup for 192.0.2.10 use the /24?'
q(10)['options'][2]['explanation']='Correct under the explicit installation assumptions. Best-route selection is performed per prefix, while the forwarding lookup uses the longest matching installed prefix.'
q(10)['options'][3]['explanation']='RPKI validation is not the longest-prefix mechanism. If covering validated records authorise no matching origin/length, an announcement is Invalid; local policy determines rejection. Another applicable valid record can authorise it.'
q(10)['workedExample']='The installed /22 and /24 are different destinations in the routing table. Address 192.0.2.10 matches both, and /24 is the more specific forwarding match. AS-path lengths for these two distinct prefixes are not compared to override that lookup. This is a hypothetical example, not the exact 2008 YouTube timeline. Origin validation and prefix filters can prevent installation of some unauthorised routes, but origin validation does not authenticate an entire path or automatically impose a drop policy.'
q(11)['options'][0]={'text':'Fishing and anchoring are major documented causes of cable faults, especially where human activity overlaps cable routes','explanation':'Correct. ICPC’s June 2025 summary attributes 70–80% of recorded faults to accidental damage, primarily fishing and vessel anchoring; other causes also exist.'}
q(11)['options'][1]={'text':'Marine repair can be prolonged by ship availability, weather, permits and the work of recovering and splicing cable','explanation':'Correct. Exact duration and method depend on the fault and system; there is no universal repair deadline.'}
q(11)['options'][2]['explanation']='Submarine cables are central to intercontinental connectivity. Satellite backup may help, but its available capacity and terminals must be planned rather than assumed sufficient.'
q(11)['options'][3]={'text':'In long-haul repeatered systems, optical amplifiers can receive power from shore-fed high-voltage DC','explanation':'Correct. Repeater spacing, voltage and design vary, and unrepeatered cable systems also exist.'}
q(11)['workedExample']='The supported claims concern documented damage mechanisms, repair logistics and shore-fed power in repeatered systems. Two cables sharing a landing area can share physical hazards or terrestrial backhaul. Resilience improves through route/landing diversity and adequate surviving capacity; backup satellites are not an automatic full-capacity substitute.'
q(12)['prompt']='Compare two hypothetical equal-direction paths, ignoring curvature and processing: (a) 17,000 km of fibre at c/1.47; (b) 550 km up + 17,000 km across space + 550 km down, at c ≈ 299,792 km/s. What are their propagation RTTs?'
q(12)['workedExample']='Fibre RTT = 2 × 17,000 / (299,792/1.47) × 1,000 ≈ 166.7 ms. Space-route RTT = 2 × 18,100 / 299,792 × 1,000 ≈ 120.8 ms. These follow from the supplied fictional path lengths; they are not measured London–Sydney routes. An orbital arc, slant range, inter-satellite hop geometry, ground routing and processing can change the comparison. No actual service advantage is guaranteed.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
