from pathlib import Path
import json
p=Path('content/networks/01-foundations/nf-error-control.questions.json');q=json.loads(p.read_text())
q[0]['prompt']+=' Assume no other integrity check detects the damage.'
q[0]['workedExample']=q[0]['workedExample'].replace('This is why networks, where noise often hits several consecutive bits, use CRCs rather than parity.','A CRC can provide stronger burst-error guarantees than a single parity bit.')
q[1]['prompt']+=' Treat detection and correction as alternative decoder modes.'
for i in [2,5]:
 q[i]['prompt']+=' Here RTT means propagation round trip; ignore processing, losses, ACK transmission and framing gaps.'
q[4]['prompt']='A driver swaps two different, checksum-aligned 16-bit words in a UDP payload. The checksum was computed before the swap and is verified after it. Which check is mathematically unchanged by every such swap?'
q[4]['options'][0]['explanation']='A CRC is position-sensitive, so it is not invariant under every swap. Particular corruptions can still collide; a fixed CRC does not detect all changes.'
q[4]['options'][2]['explanation']='SHA-256 is not invariant under word permutations. Collisions exist in principle, but there is no general checksum-like equality for every swap.'
q[4]['workedExample']=q[4]['workedExample'].replace('A CRC multiplies each bit by its position\'s power of x, so moving bits around changes the result.','A CRC is position-sensitive, so the commutativity argument does not apply to it; this does not promise detection of every possible rearrangement.')
q[5]['options'][0]['explanation']='Ten frame times cover only 100 microseconds, far below the stated 10 ms propagation round trip.'
q[6]['prompt']='For fixed framing in a standard 1518-byte Ethernet frame, which statements about CRC-32 are true? Consider bit flips in the FCS-protected region including the FCS, not preamble/SFD. Select all that apply.'
q[6]['options'][1]['explanation']='Correct. Koopman gives distance at least 4 through 91,607 data bits excluding check bits, beyond the protected data length of this frame.'
q[6]['options'][2]['explanation']='Some errors transform one valid codeword into another. An approximate 2⁻³² miss probability requires an appropriate random-error model.'
q[6]['options'][4]['text']='Shift/XOR logic can implement it at line rate in suitable hardware'
q[6]['options'][4]['explanation']='Correct. Hardware can pipeline or parallelise CRC computation; it still consumes area and power.'
q[6]['workedExample']='Degree 32 with a nonzero constant term guarantees detection of bursts spanning at most 32 bits. Distance at least 4 at this length guarantees detection of all 1–3-bit flips in the protected codeword. Some larger changes remain undetectable. The check is keyless, so an attacker able to replace data and FCS can forge it. Suitable shift/XOR hardware can sustain the link rate.'
q[7]['prompt']+=' Assume ACKs for 0 and 1 reach the sender, no additional new data is sent, ACK n means through n, and recovery is timeout-based.'
q[7]['options'][2]['explanation']='This textbook Go-Back-N model delivers frames in order without gaps. ARQ in general need not promise in-order delivery, but this model does.'
q[8]['prompt']='In the textbook Selective Repeat model with equal sender/receiver windows, ordered channels, and no old duplicates surviving sequence-number reuse, 3-bit sequence numbers provide values 0–7. What is the maximum window?'
q[8]['options'][3]['explanation']='Two works, but four already avoids ambiguity between outstanding old retransmissions and the next receive window under the stated assumptions.'
q[9]['prompt']='A Go-Back-N sender transmits frames 0–999, then pauses for recovery. Only frame 0 is lost; the receiver discards later out-of-order frames. Compare Selective Repeat, where 1–999 are buffered and individually acknowledged. All ACKs arrive and retransmissions succeed. How many frames does each sender retransmit?'
q[9]['options']=[{'text':'Both retransmit 1 frame','explanation':'Go-Back-N must resend the discarded later frames as well.'},{'text':'Go-Back-N retransmits 999; Selective Repeat retransmits 1','explanation':'Go-Back-N resends the missing frame 0 as well as frames 1–999: 1,000 total.'},{'text':'Both retransmit 1,000 frames','explanation':'Selective Repeat knows 1–999 arrived, so it only needs frame 0.'},{'text':'Go-Back-N retransmits 1,000; Selective Repeat retransmits 1','explanation':'Correct. These counts follow from the specified trace, without assuming a throughput formula.'}]
q[9]['workedExample']='Go-Back-N has no accepted frame after the gap and must resend 0–999, a total of 1,000. Selective Repeat has buffered and acknowledged 1–999, so only frame 0 is resent. Actual long-run throughput also depends on timers, acknowledgements, window size and the loss process; these counts alone are not a measured throughput ratio.'
q[10]['prompt']='A file-transfer service occasionally finds corrupted destination blocks despite Ethernet CRCs and TCP checksums. Which explanation is possible, and which additional integrity check addresses a wider path?'
q[10]['options'][0]['explanation']='Jumbo frames do not establish stronger integrity. Link errors, host software and storage faults all need investigation; the observation alone does not locate the cause.'
q[10]['options'][1]['text']='Corruption may occur between or beyond link/transport checks; compute a source file hash and verify it after destination storage'
q[10]['options'][1]['explanation']='Correct. This extends checking across the chosen application/storage boundary. It does not prove where corruption happened or detect damage already present before the source hash was computed.'
q[10]['options'][2]['explanation']='TCP detects checksum failures and can recover through retransmission. UDP alone adds no retransmission mechanism and does not solve this integrity problem.'
q[10]['options'][3]['explanation']='The evidence does not isolate disks or rule out network, memory and software faults. Instrument and compare data at relevant boundaries.'
q[10]['workedExample']='A device can compute a valid outgoing link CRC over data corrupted after its incoming check. TCP adds a different check but can miss structured changes, and neither check covers all source/destination storage operations. Compare a source hash with one computed after destination storage to extend the checked boundary. Protect the expected hash with authentication when malicious modification is in scope. A hash cannot diagnose the cause or cover corruption before its computation or after its verification.'
q[11]['prompt']='Consider a hypothetical 50 Mbit/s satellite link with 600 ms propagation RTT, 1500-byte frames and independent raw bit errors at 10⁻⁵ before FEC. Residual losses remain after coding. Which choices merit consideration for reliable bulk transfer? Select all that apply.'
q[11]['options'][0]['text']='Use a suitable FEC code to reduce residual errors without a retransmission round trip'
q[11]['options'][0]['explanation']='Correct. Coding trades redundancy and decoding delay for error correction. Its effectiveness requires a specific code and channel model; it cannot be assumed to fix most errors without analysis.'
q[11]['options'][2]['text']='Consider Selective Repeat to avoid retransmitting later correctly received frames after a gap'
q[11]['options'][2]['explanation']='Correct. Large windows can make Go-Back-N retransmission waste substantial. Benefit depends on residual loss, memory, processing and timing.'
q[11]['options'][3]['explanation']='Under the independent-bit assumption, a 12,000-bit uncoded frame has at least one error with probability about 11.3%. Larger frames increase that probability; the best size depends on overhead, coding and recovery.'
q[11]['workedExample']='The propagation BDP is 30 million bits, or 3.75 MB: 2,500 frames. Including one data-frame transmission time requires a loss-free window of 2,501 frames in the lesson model, still requiring at least 13 sequence bits for equal-window Selective Repeat. Stop-and-wait utilisation is 0.24/(600+0.24) ms, about 0.04%. Independent uncoded bit errors give 1−(1−10⁻⁵)^12000 ≈ 11.3% probability of some damage. Suitable FEC can reduce residual errors, and selective retransmission avoids resending later acknowledged frames. These are design calculations, not a validated implementation or measured satellite performance.'
p.write_text(json.dumps(q,indent=2,ensure_ascii=False)+'\n')
