import json
from pathlib import Path
p=Path('content/networks/03-tcp/tcp-performance.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['prompt']='In an ideal timing model, a browser makes a new TCP + full TLS 1.3 connection at RTT 50 ms, without Fast Open, early data, handshake retries, loss or DNS delay. A 10,000-byte response fits the available initial window. Ignore serialization and processing. When does the complete response arrive?'
q(1)['options'][2]['explanation']='The stated model requires three round trips: TCP setup, TLS setup, and request/response.'
q(1)['options'][3]['explanation']='Serialization is explicitly ignored in this model. On a slow link it would matter: 10,000 bytes alone take 8 ms at 10 Mbit/s.'
q(1)['workedExample']=q(1)['workedExample'].replace('Bandwidth barely appears. Reusing the connection would cut it to 50 ms.','Under the stated assumptions this is 150 ms. An already usable connection with sufficient send window reduces the model to one request/response RTT, or 50 ms.')
q(2)['options'][0]['explanation']='UDP itself has no congestion-control algorithm, but protocols running over it can provide one. The observed delay does not identify the transport protocol.'
q(2)['options'][1]['explanation']='A rate limit can contribute to queueing, depending on its implementation. The leading explanation for this load-correlated delay is an excessive standing queue; confirm it by measurement.'
q(2)['options'][2]={'text':'Bufferbloat: a persistent queue at a shared uplink delays other traffic using that queue','explanation':'Correct as the leading hypothesis. For a FIFO packet, delay is approximately the queued work ahead divided by service rate; not every packet or priority class necessarily sees the same backlog.'}
q(2)['workedExample']='A large increase in RTT during upload is consistent with a shared standing queue. Identify the bottleneck and queue discipline before concluding. If traffic shares a FIFO, a packet behind B queued bytes at rate R bit/s waits approximately 8B/R seconds. AQM and appropriate shaping at a controlled router can reduce queueing, with configuration and throughput trade-offs.'
q(3)['options'][2]['explanation']='Out-of-order data can be retained and reported with SACK when negotiated. Receivers can also discard buffered data, so retention is not an unconditional guarantee.'
q(3)['workedExample']='HTTP/2 frames share TCP byte ordering. Later bytes cannot be delivered past the missing range until it is recovered; data already delivered is unaffected. Recovery duration is not fixed at one RTT. QUIC removes this cross-stream byte-order dependency, but shared congestion control, flow control and application dependencies can still delay multiple streams.'
q(4)['prompt']='Using the lesson’s ideal Reno Mathis approximation with C = 1.22, MSS 1,460 bytes, RTT 20 ms and p = 0.0001, what rate does the formula return? Assume its model conditions hold.'
q(4)['options'][1]['explanation']='The square root is 0.01; dividing 584,000 × 1.22 by that value gives 71,248,000 bit/s.'
q(4)['workedExample']=q(4)['workedExample'].replace('So even a 1 Gbit/s link gives one such flow only ~71 Mbit/s at this loss rate.','This is approximately 71.2 Mbit/s in the specified model, not a universal ceiling for every TCP algorithm or loss pattern.')
q(6)['prompt']='A FIFO has 500,000 queued bytes ahead of a newly admitted packet, served at a constant 10 Mbit/s. Ignore overhead, priorities and the new packet’s own transmission. What is its waiting time?'
q(6)['options'][3]['explanation']='The question supplies a backlog. Neither CUBIC nor BBR guarantees that queues remain empty.'
q(6)['workedExample']='500,000 bytes × 8 / 10,000,000 bit/s = 0.4 seconds. This is the waiting time behind the specified backlog. CoDel’s 5 ms default target is not a hard guarantee for every packet.'
q(7)['options'][0]={'text':'It combines transport and TLS setup and can support eligible 0-RTT early data','explanation':'Correct. Prior state/configuration is required for early data; rejection, replay concerns, Retry or loss can alter timing.'}
q(7)['options'][1]={'text':'Its per-stream ordering avoids making one stream wait solely for missing bytes on another stream','explanation':'Correct. Shared congestion control, flow control and application dependencies can still affect several streams.'}
q(7)['options'][2]={'text':'Connection IDs can support client address changes when migration conditions are satisfied','explanation':'Correct. Negotiated restrictions, handshake state, usable connection IDs, path validation and reachability matter; seamless success is not guaranteed.'}
q(7)['options'][4]['explanation']='QUIC can run in user-space libraries or other implementation locations. Its specification does not require a kernel implementation.'
q(7)['workedExample']='The first three describe protocol capabilities with their conditions. QUIC does not impose a single global stream delivery order, and its specification does not dictate kernel placement.'
q(8)['prompt']='A previously idle CoDel queue uses target 5 ms and interval 100 ms. No hard buffer limit is reached. Case A spikes to 40 ms but empties within 20 ms. Case B remains at 30–40 ms for seconds with sufficient backlog to satisfy CoDel’s remaining-byte check. Which behaviour is expected?'
q(8)['options'][0]['explanation']='Exceeding the target briefly does not alone trigger CoDel’s persistent-delay response. A burst could still encounter a finite-buffer limit, which this question excludes.'
q(8)['options'][2]['explanation']='CoDel can signal persistent queueing before the buffer fills. It also retains checks intended to avoid starving the link.'
q(8)['workedExample']='Case A clears before a full interval of excessive delay, so it does not trigger the persistent-delay response under these assumptions. Case B satisfies both the persistent-delay and backlog conditions and enters dropping/marking behaviour. The control law schedules increasingly frequent signals using interval divided by the square root of the count. Actual delay still depends on traffic response; 5 ms is a target, not a per-packet guarantee.'
q(9)['prompt']='Within a QUIC packet-number space, each newly sent packet gets a new increasing packet number, even when it resends stream data. Which TCP retransmission ambiguity does this remove?'
q(9)['options'][1]={'text':'An ACK identifies which numbered packet transmission arrived, removing original-versus-retransmission ambiguity for that packet','explanation':'Correct. Other estimation errors and spurious loss declarations remain possible; packet numbers do not make all loss detection infallible.'}
q(9)['options'][3]['explanation']='Packet numbers have header protection. An observer can derive Initial protection keys, so “middleboxes can never read any packet numbers” would also be too strong.'
q(9)['workedExample']='TCP reuses byte sequence numbers when resending data, so an ACK may not reveal which copy caused it; Karn’s rule or timestamps address RTT-sampling ambiguity. QUIC identifies packet transmissions separately from stream offsets, within each packet-number space. This removes that particular ambiguity. ACK delay, sampling choices and reordering still require careful recovery logic.'
q(10)['prompt']='Which mechanisms can make transport extensions harder to deploy or help QUIC evolve? Select all that apply.'
q(10)['options'][0]={'text':'Some middleboxes interfere with unfamiliar TCP options or SYN data','explanation':'Correct. Compatibility and fallback matter; this is not a claim that every middlebox behaves this way.'}
q(10)['options'][1]={'text':'A TCP change in a kernel stack can depend on OS deployment cycles; a QUIC library can be updated with an application','explanation':'Correct. Some TCP changes are sender-only, and neither TCP nor QUIC is required to live exclusively in one implementation layer.'}
q(10)['options'][2]={'text':'Protecting QUIC control frames and selected header fields reduces the information middleboxes can depend on','explanation':'Correct. Some wire fields remain visible and Initial keys are publicly derivable, so encryption does not eliminate all ossification or interference.'}
q(10)['workedExample']='The first three describe compatibility, implementation deployment and protection mechanisms. The base TCP header permits up to 40 option bytes, and TCP standards work continues. None of these mechanisms guarantees a fixed adoption speed.'
q(11)['prompt']='A phone loses its old Wi-Fi path and gains a new address on 5G. Compare ordinary TCP (without MPTCP or an address-preserving tunnel) with a confirmed QUIC connection using usable connection IDs. Assume active migration is allowed and the new path passes validation and remains reachable. Which connection can continue at the transport level?'
q(11)['options'][1]['explanation']='Under the supplied conditions, QUIC can migrate the existing connection to the new path.'
q(11)['options'][2]={'text':'Ordinary TCP cannot move the existing connection to the new address; QUIC can continue through migration','explanation':'Correct under the stated assumptions. QUIC still needs appropriate path validation and congestion-control handling; this does not promise no interruption.'}
q(11)['workedExample']='Ordinary TCP identifies the connection by its endpoint addresses and ports, so the stated address change cannot simply retarget it. An application can reconnect and resume if its protocol supports that. QUIC connection IDs allow the established connection to be found from a new address; validation and path-state changes still apply. The question explicitly supplies successful migration conditions rather than assuming every network change succeeds.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
