import json
from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-cellular.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['prompt']='An RRC-connected LTE UE has uplink data, no usable existing or configured grant, and an available scheduling-request resource. In the ordinary dynamic scheduling path, what does it do before sending that data?'
q(1)['options'][0]['explanation']='The question describes cellular dynamic scheduling, not Wi-Fi contention. Cellular random access can itself involve contention, so “LTE has no contention anywhere” would be incorrect.'
q(1)['workedExample']='Under the supplied conditions the UE requests uplink scheduling and uses the granted resources. An existing grant, configured scheduling or random-access procedure can change the path, so a fresh request is not mandatory for every packet. Scheduling coordinates resources; it does not guarantee no interference or fixed request/grant latency.'
q(2)['options'][1]={'text':'A preserved session anchor—P-GW in LTE or session-anchor UPF in 5G—with updated user-plane paths','explanation':'Correct. Retaining the session’s addressing while updating radio-side paths can preserve connectivity; not every handover preserves every session.'}
q(2)['options'][2]['explanation']='A long lease alone does not redirect the user-plane path during handover. Address-allocation methods can vary, including external mechanisms; anchoring and mobility procedures are the relevant distinction.'
q(2)['workedExample']='A session can retain its anchor and address while the network updates tunnels toward the serving radio node. LTE control functions or the 5G AMF/SMF coordinate the relevant procedures. A 5G UPF forwards user traffic while the SMF manages session/address-allocation procedures. Continuity is possible under the stated observation, not guaranteed for all handovers.'
q(3)['prompt']='A trace confirms that a phone starts an API request from RRC_IDLE and performs RRC setup before transmitting data. Subsequent requests use the connected state. Which cellular mechanism contributes to the first request’s extra delay?'
q(3)['options'][1]['explanation']='Application fetching is not the radio-state transition established by the trace. Edge caching may exist in some deployments, but it does not explain the specified setup sequence.'
q(3)['options'][2]['explanation']='RRC_IDLE does not by itself require loss of registration or session addressing. A full re-attach and new address are not implied by this transition.'
q(3)['workedExample']='The trace establishes a radio-state transition: random access and RRC setup occur before the request’s data transmission. Later traffic can avoid that setup while the required context remains usable. Actual delay depends on configuration and conditions; a slow first request without such a trace could also involve DNS, transport/TLS setup or server work.'
q(4)['options'][2]['explanation']='The three interval unions have lengths 13, 15 and 10 seconds, totalling 38; 33 undercounts their combined duration.'
q(5)['prompt']='Use the lesson’s isolated 10-second-tail model. A background app sends a 200-byte heartbeat every 20 seconds, but its requirements permit minutes of delay and platform push for incoming notifications. Which redesign best reduces the model’s repeated activity intervals?'
q(5)['options'][0]['explanation']='The supplied fixed-tail model assigns the same interval to each request regardless of payload. Real energy consumption also depends on transfer size and radio behaviour.'
q(5)['options'][1]['explanation']='Changing the transport alone does not remove the model’s one interval per heartbeat. Real transport behaviour can affect traffic and energy.'
q(5)['options'][2]['explanation']='Correct for the stated delay-tolerant requirements. Less frequent batching reduces isolated fixed-tail intervals; platform push can avoid a separate polling scheme but is not energy-free.'
q(5)['options'][3]['explanation']='More frequent activity merges intervals into more continuous coverage in this model. Real devices have DRX and power states not represented here.'
q(5)['workedExample']='A 20-second period with isolated 10-second tails covers 50% of time in the toy model; a 300-second period covers about 3.3%. This is not a measured battery reduction. Platform-managed push may share infrastructure across apps, but still has delivery, activity and energy costs.'
q(6)['prompt']='A download uses ordinary TCP without MPTCP or an address-preserving tunnel. It survives cell handovers with the same anchored address. The old cellular path is then lost and traffic must use a new Wi-Fi endpoint address; the connection fails. Which explanation fits?'
q(6)['options'][0]['explanation']='PMTU problems can cause failures, but the stated endpoint-address change directly prevents ordinary TCP from simply continuing with the original tuple.'
q(6)['options'][1]['explanation']='Correct under the supplied conditions. Joining Wi-Fi alone does not necessarily destroy every cellular connection if its original path remains usable.'
q(6)['options'][2]['explanation']='A new router may have stateful policies, but no general rule identifies where an application download began. The given tuple change is the relevant mechanism.'
q(6)['options'][3]['explanation']='A reset is not required for this failure; losing the usable old path can leave the connection unable to progress.'
q(6)['workedExample']='Supported cell handovers preserved the session address. The later forced change to an independently addressed path cannot retarget an ordinary TCP connection. The application can reconnect and resume if its protocol supports that. QUIC migration or MPTCP may preserve transport continuity when their prerequisites are satisfied.'
q(7)['options'][0]['explanation']='Correct. Shared addressing can combine unrelated users under one limit. Account/token controls can help, alongside appropriate unauthenticated-abuse controls.'
q(7)['options'][1]['explanation']='Correct as a general tendency, subject to mappings and filtering policy. ICE can use STUN for discovery/checks and TURN for relaying; STUN is not itself a relay.'
q(7)['options'][3]['explanation']='Translation can provide connectivity. Hostnames and suitable APIs are useful, while 464XLAT or address-synthesis APIs can also support some IPv4-literal applications.'
q(7)['workedExample']='CGNAT can make unrelated users share a public address and therefore a per-IP limit. Mappings/filtering can restrict inbound traffic and idle mappings can expire. An IPv6-only access network can still reach IPv4 services through translation. These are possibilities to investigate, not proof that every observed 429 has this cause.'
q(8)['prompt']='For an NR normal-cyclic-prefix full slot, use spacing 15 × 2^μ kHz and duration 1 ms / 2^μ. What duration corresponds to 60 kHz, and what can wider spacing enable?'
q(8)['options'][1]={'text':'0.25 ms; shorter symbol/slot durations can support faster scheduling and mitigate some high-frequency impairments','explanation':'Correct. μ = 2, so the full slot is 0.25 ms. Actual latency, supported numerologies and trade-offs depend on configuration and band.'}
q(8)['options'][3]['explanation']='The supplied NR formula gives different slot durations. Conventional LTE uses 1 ms subframes, but later shortened-TTI features also make a universal LTE timing claim too broad.'
q(8)['workedExample']='60 / 15 = 4 = 2², so μ = 2 and the normal-CP full slot lasts 1/4 ms. The table gives 1, 0.5, 0.25 and 0.125 ms for μ = 0–3. Wider spacing can support shorter transmission scheduling and different impairment trade-offs; it does not guarantee a particular application RTT. Later NR releases include additional spacings and mini-slot operation.'
q(9)['prompt']='In a laboratory, an IPv6-only host has NAT64/DNS64 but no CLAT. Raw AF_INET socket code tries to connect to a lab IPv4-only server; it does not call an address-synthesis API. A hostname-based AF_UNSPEC client reaches that same server through a DNS64-synthesised AAAA record. Why does the raw IPv4 attempt fail?'
q(9)['options'][0]['explanation']='The successful translated connection demonstrates that this IPv4-only server is reachable through NAT64. The raw IPv4 socket path lacks the required translation/synthesis.'
q(9)['options'][1]={'text':'The raw IPv4 socket has no usable IPv4 path, while the other client obtains an IPv6 destination that the NAT64 gateway can translate','explanation':'Correct for the explicitly specified API path. Some Apple/system APIs can synthesise addresses even for literals, so a literal alone would not prove failure.'}
q(9)['workedExample']='DNS64 can synthesise an AAAA answer for an IPv4-only name, giving the IPv6 client a destination routed to NAT64. The specified raw IPv4 code neither obtains that address nor has client-side translation. Prefer suitable system APIs and hostnames; do not infer failure merely from the presence of an IPv4 literal in a high-level URL. HTTP security policy is separate from this IP-layer experiment.'
q(10)['options'][0]['explanation']='Correct as a capability: eligible QUIC client migration requires permitted migration, suitable connection IDs, a working path and validation. It is not a zero-interruption guarantee.'
q(10)['options'][1]['explanation']='Correct when endpoints, operating systems and application policies support MPTCP subflows on those paths.'
q(10)['options'][2]['explanation']='Ordinary independent Wi-Fi is not automatically anchored by the cellular core. Integrated non-3GPP access or mobility services can exist, so this must not be assumed without deployment support.'
q(10)['options'][4]['explanation']='Correct as an approach to detect change and trigger recovery. Callback timing and reconnection are not guaranteed to complete in a fraction of a second.'
q(10)['workedExample']='Migration-capable transports and application-level reconnection/resumption can improve mobility. Each depends on supported paths and endpoint behaviour. Keepalives can help detect some failures but cannot change ordinary TCP endpoint addresses. An independent Wi-Fi path does not automatically inherit a cellular session anchor.'
q(11)['prompt']='An upload coincides with RTT increasing from 45 to 700 ms on a cellular path, with little observed packet loss. Which is a plausible hypothesis and measurement-led response, rather than a conclusion proved by ping alone?'
q(11)['options'][1]={'text':'A standing queue may be delaying packets; locate it and test pacing, queue management or traffic limits under representative load','explanation':'Correct. Radio retries, scheduling and processing may also contribute. BBR is model-based, and switching algorithms is not a guaranteed cure.'}
q(11)['options'][2]['explanation']='ICMP handling could affect the observation and should be checked. A steady load-correlated increase alone does not exclude it.'
q(11)['workedExample']='If the extra 0.65 seconds were entirely a FIFO backlog at a constant 8 Mbit/s, it would correspond to 8e6 × 0.65 / 8 = 650,000 bytes. That is a conditional estimate, not a measured queue size. CUBIC can respond to ECN as well as loss; BBR can also build queues. TCP_NOTSENT_LOWAT limits unsent local buffering notifications/acceptance behaviour, not all in-flight traffic or a remote queue.'
q(12)['prompt']='An operator uses NSA option 3 with an LTE master and EPC. A customer requests the 5GC-defined slice-selection and session framework. What architectural component is missing from that deployment?'
q(12)['options'][0]['explanation']='Option 3 can use supported NR bands such as mid band; it is not inherently restricted to one frequency range.'
q(12)['options'][1]={'text':'The 5G core and its slice-aware functions; option 3 still uses EPC','explanation':'Correct. Moving to a suitable 5GC deployment enables the relevant framework, but does not itself guarantee end-to-end latency or isolation.'}
q(12)['workedExample']='NSA option 3 combines an LTE master/EPC with NR secondary radio access. SA option 2 connects NR to 5GC, which provides the requested framework. Other deployment options and EPC service differentiation exist. A factory latency guarantee additionally requires provisioned radio/transport/core resources, supported devices, application design and an appropriate service agreement.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
