import json
from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-sdn.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['options'][0]['explanation']='Exchanging routing information belongs to the control plane. An SDN architecture may retain distributed BGP rather than moving every decision to one controller.'
q(1)['options'][2]['explanation']='Correct. Per-packet forwarding is a data-plane operation, whether implemented in hardware or software.'
q(1)['workedExample']='Control logic determines forwarding policy/state; the data plane applies it to packets. Device management configures behaviour. Implementation location and throughput are not definitions of these roles, and SDN does not require eliminating every local control function.'
q(3)['prompt']='An EC2 interface’s only security group allows inbound TCP 443 and has no outbound rules. For a tracked client connection, assume valid tracking state, a listening service and all routing/NACL/host controls permit traffic. Does the missing outbound rule alone block its replies?'
q(3)['options'][1]['explanation']='Correct under the stated tracking and other-control assumptions. Allowed response traffic does not need a separate outbound security-group rule.'
q(3)['workedExample']='The inbound SYN is allowed and tracked. Responses associated with that tracked connection are permitted by security-group state despite the lack of an outbound allow rule. Unrelated initiated outbound traffic is a separate case, and response allowance does not bypass NACLs, routing or other filters.'
q(4)['prompt']='An ordinary AWS private IPv4 /26 subnet uses the standard first-four-and-last reservation rule, with no BYOIP exception or additional reservations. How many addresses remain assignable?'
q(4)['options'][2]['explanation']='Correct. There are 64 total addresses and five reserved, leaving 59. Reserved base-plus-two is not necessarily the actual DNS resolver address of this subnet.'
q(4)['options'][3]['explanation']='Under the supplied ordinary-subnet rule, five rather than ten addresses are reserved.'
q(4)['workedExample']='A /26 contains 2^(32−26) = 64 addresses. For 10.20.48.0/26, the reserved addresses are .0, .1, .2, .3 and .63, leaving .4 through .62: 59 addresses. The base-plus-two address is reserved; the VPC resolver uses the primary VPC CIDR base plus two (and supported link-local addresses), not automatically 10.20.48.2. AWS subnet broadcast is unsupported.'
q(5)['prompt']='For an HTTPS server on TCP 443, a custom subnet NACL allows inbound destination port 443 and outbound destination port 443, denying everything else. A client uses source port 51234. Routing and other filters are correct. Why does this connection fail?'
q(5)['options'][1]['explanation']='Correct. Allow the required client return-port range in the outbound NACL, scoped appropriately. Ephemeral-port ranges depend on the clients and NAT path.'
q(5)['options'][3]['explanation']='This question specifies HTTPS over TCP. HTTP/3 uses QUIC over UDP, but applications do not all guarantee a TCP fallback.'
q(5)['workedExample']=q(5)['workedExample'].replace('outbound allow TCP 1024–65535 (the ephemeral range) to the clients.','an outbound allow covering the required client return ports and destinations; 1024–65535 is a broad commonly used range, not every system’s exact ephemeral range.')
q(6)['prompt']='VXLAN carries untagged inner Ethernet with no inner FCS over IPv4 without options. UDP and VXLAN headers are 8 bytes each. The underlay IP MTU is fixed at 1,500 bytes, with no other encapsulation. What is the largest inner IP packet that fits without fragmentation?'
q(6)['options'][0]['explanation']='The inner IP packet plus 50 bytes of headers must fit the underlay IP MTU. A 1,500-byte inner IP packet needs 1,550 outer IP bytes; the outer Ethernet framing is additional.'
q(6)['workedExample']=q(6)['workedExample'].replace('Set the VMs\' MTU to 1,450, or raise the fabric to jumbo frames (e.g. 9,000) so tenants keep 1,500. AWS lets instances use a 9,001-byte MTU inside a VPC for this kind of reason.','For this fixed underlay use an inner MTU no larger than 1,450. In a different deployment an underlay IP MTU of at least 1,550 would accommodate 1,500 inner bytes under these assumptions; 9,000 is not required. Do not infer a cloud provider’s internal encapsulation from its advertised instance MTU.')
q(7)['options'][1]['explanation']='Correct as a connectivity design, with the necessary routes, attachments and filters. Creating a peering or Transit Gateway attachment alone does not guarantee connectivity.'
q(7)['workedExample']=q(7)['workedExample'].replace('or a Transit Gateway hub (better for many).','or an appropriately routed Transit Gateway hub. Costs, limits and topology determine the choice.')
q(8)['prompt']='A reactive OpenFlow deployment sends new-flow misses to its controller. During a traffic surge, measured packet-in queues fill and flow-installation delay rises, while packets covered by existing rules continue. What explains the new-flow delay?'
q(8)['options'][1]['explanation']='Correct. The measured controller path is overloaded. Preinstalled aggregate rules can remove this dependency for covered traffic, subject to policy and table capacity.'
q(8)['options'][2]['explanation']='OpenFlow supports TCP-related match fields, with exact field availability depending on version and extensions; TCP flags are not universally available in every base version.'
q(8)['workedExample']='A miss notification, controller decision, flow modification and forwarding of the first packet create a control-path dependency. Here telemetry establishes saturation. Dropped setup packets may require retransmission, whose timers are implementation/configuration-dependent. Preinstalling suitable rules can reduce misses, while overload protection and capacity planning remain necessary.'
q(9)['prompt']=q(9)['prompt'].replace('An attacker at 203.0.113.9 connects to SSH. What happens, and why?','For an inbound TCP SYN from 203.0.113.9 to destination port 22, what verdict does this NACL alone produce?')
q(9)['workedExample'] += '\n\nAn ALLOW verdict from this one NACL does not establish that the end-to-end connection succeeds; routes, security groups, the host and return traffic still matter.'
q(10)['options'][1]['explanation']='Correct. A flow-stable source-port hash gives an outer-header ECMP selector useful variation. Hash collisions and mapping changes still occur; perfect balance or ordering is not guaranteed.'
q(10)['workedExample']='For an ECMP implementation hashing only the outer five-tuple, fixed tunnel IPs and UDP ports give the same key for all enclosed flows. A source port derived consistently from inner headers adds variation while retaining flow affinity under a stable mapping. Some hardware can inspect inner headers directly. VXLAN itself supplies no encryption, and the VNI is a separate 24-bit field.'
q(11)['prompt']='An OpenFlow-only fabric loses all controller connectivity for two minutes. Assume fail-secure mode, retained non-expiring proactive entries, no autonomous routing fallback, and any local backups explicitly preinstalled. Which statements follow? Select all that apply.'
q(11)['options'][0]['explanation']='Correct for covered traffic whose forwarding path remains usable under these assumptions.'
q(11)['options'][2]['explanation']='Correct under the stated absence of autonomous fallback. Preinstalled local failover still depends on what failures it can detect.'
q(11)['options'][3]['explanation']='The stated fail-secure mode retains usable entries. Other configured failure modes can behave differently; there is no universal fail-static guarantee.'
q(11)['workedExample']='In the specified fail-secure configuration, existing non-expiring entries can continue to forward. Controller-dependent decisions cannot complete through the disconnected controller. Preinstalled local failover can handle failures it detects; no unspecified OSPF fallback appears automatically. Actual implementations can have timeouts, fail-standalone behaviour or hybrid control, which this question excludes.'
q(12)['prompt']='Traffic uses A → B → D and will move to A → C → D. C lacks a rule; unmatched packets drop. Links remain healthy and updates arrive separately. Which sequence also protects packets already in flight on the old path?'
q(12)['options'][1]={'text':'Install and confirm C’s rule, switch A to C, wait for old-path packets to drain, then remove B’s rule','explanation':'Correct. Downstream preparation avoids a new-path gap, and the drain step protects packets A sent to B before the change.'}
q(12)['options'][3]['explanation']='OpenFlow does not make updates across different switches atomic. Supported local atomic modifications or bundles do not imply network-wide atomicity.'
q(12)['workedExample']='1. Install C → D and confirm processing using the appropriate barrier/acknowledgment mechanism.\n2. Change A’s next hop to C.\n3. Retain B → D until old-path packets have drained, using a justified delay bound or version/epoch mechanism.\n4. Remove the obsolete rule.\n\nA control-message barrier confirms processing; it does not by itself prove that every previously forwarded data packet has left the old path. Versioned updates must also delay old-version cleanup until those packets are gone.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
