import json
from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-wifi.questions.json');qs=json.loads(p.read_text())
def q(n):return qs[n-1]
q(1)['prompt']='Why does ordinary Wi-Fi contention use collision avoidance rather than Ethernet-style detection of collisions during a transmission?'
q(1)['workedExample']='The transmitting radio’s own signal makes sensing weak concurrent incoming signals difficult. More fundamentally, interference depends on what arrives at the receiver: hidden senders may not hear one another. Ordinary Wi-Fi uses carrier sensing, contention and missing expected ACKs instead of Ethernet-style collision detection. No fixed power ratio or claim about every possible radio design is needed.'
q(2)['prompt']='For three nearby 2.4 GHz APs restricted to channels 1–11 at 20 MHz width, which listed conventional channel plan avoids adjacent-channel overlap?'
q(2)['options'][1]['explanation']='The 1-to-4 centre spacing is only 15 MHz. The conventional 1/6/11 plan provides 25 MHz between centres; exact interference also depends on spectral masks and equipment.'
q(2)['options'][2]['explanation']='Correct among these choices. Centres at 2412, 2437 and 2462 MHz are 25 MHz apart. This is not a claim that no other valid plan exists worldwide.'
q(2)['options'][3]['explanation']='Carrier sensing cannot guarantee freedom from interference. Energy detection can defer even without decoding a frame, but overlapping channels still complicate coexistence.'
q(2)['workedExample']='Channels 1, 6 and 11 have centres 2412, 2437 and 2462 MHz, respectively: 25 MHz separation. That makes them the conventional non-overlapping selection among the offered plans for the stated domain. Other countries, PHYs and power arrangements require their own channel planning.'
q(3)['options'][3]['explanation']='Increasing channel width alone does not solve hidden-terminal contention. Coordinated multi-user mechanisms are separate from simply selecting a wider channel.'
q(3)['workedExample']='A and C can interfere at the AP without sensing one another. If C successfully receives and obeys the AP’s CTS, it defers for the protected interval while A sends. RTS/CTS can reduce wasted long-frame transmissions; missing protection frames, other interference and overlapping exchanges can still cause loss.'
q(4)['prompt']='Use the specified DCF model: CW starts at 15, grows as min(2(CW+1)−1, 1023) after each failed acknowledged transmission, and the retry limit permits another attempt. After three failures, what range supplies attempt four’s backoff?'
q(4)['workedExample']=q(4)['workedExample'].replace('a backoff of up to about 1.1 ms before it even starts sending. This is why a congested or interference-heavy channel feels so much slower than its PHY rate suggests: each failure makes everyone wait longer.','up to 1.143 ms of countdown time. Busy-channel freezes and interframe waits can make elapsed time longer. The window grows for this contending station; not every other station necessarily changes its window.')
q(5)['options'][0]['explanation']='The question explicitly supplies alternating equal-sized frames, not equal airtime. The slow frame occupies ten times as much transmission time.'
q(5)['workedExample']=q(5)['workedExample'].replace('This is the **performance anomaly**; airtime fairness on the AP (scheduling by time, not frames) is the mitigation.','This illustrates the **performance anomaly** under the supplied model; suitable airtime scheduling can mitigate it, depending on implementation and traffic direction.')
q(6)['prompt']='In a controlled 2.4 GHz test, two APs on channel 1 decode one another and share airtime. Moving the neighbour to overlapping channel 2 or 3 instead causes substantial retries without useful coordination. Given these observed conditions and choices, which channel should the neighbour use?'
q(6)['options'][0]['explanation']='The question supplies measured retry interference for channel 3; it is worse in this test. That is not a universal result for all powers and equipment.'
q(6)['options'][1]['explanation']='Correct under the supplied observations: channel 1 permits useful coordination. Co-channel use still consumes airtime and does not eliminate collisions.'
q(6)['options'][2]['explanation']='Channel 2 performed worse in the stated test. Energy detection and decoding behaviour vary by conditions.'
q(6)['options'][3]['explanation']='The scenario explicitly gives different measured outcomes. Equal received power alone does not determine interference or throughput.'
q(6)['workedExample']='Choose channel 1 from the supplied observations. Same-channel sensing can support coordinated deferral, while overlapping signals can cause interference. A proper survey should also test permissible non-overlapping options; neither co-channel safety nor adjacent-channel harm is absolute.'
q(7)['prompt']='An example AX3000 product label sums approximately 2,402 and 574 Mbit/s from two radios. A single-link, two-stream Wi-Fi 6 client achieves much less application throughput. Which factors can contribute? Select all that apply.'
q(7)['options'][0]={'text':'The label adds different radios’ maximum PHY rates, while this connection uses one link','explanation':'Correct. The product aggregate is not the single-link application rate; multi-radio arrangements should not be ruled out merely by generation.'}
q(7)['options'][1]['explanation']='Correct. For example, MCS 7 with two streams, 80 MHz and 0.8 µs GI gives roughly 720.6 Mbit/s PHY rate; obstacles alone do not determine this value.'
q(7)['options'][2]['explanation']='Correct. Protocol overhead, radio-resource sharing and retransmissions affect goodput. There is no universal 50–70% ratio.'
q(7)['workedExample']='A conditional example is: aggregate label near 3,000; one radio near 2,402; 80 MHz instead of 160 MHz near 1,201; MCS 7 at two streams/0.8 µs GI near 720.6 Mbit/s. Protocol overhead and other limits can reduce goodput further, but a fixed 0.6 multiplier is not a measured rule. Ethernet jam signals and a universal 64 KB TCP limit do not explain the gap.'
q(8)['workedExample']=q(8)['workedExample'].replace('The fixed cost per channel access is why aggregation, not raw PHY rate, made 802.11n and later fast in practice.','This supplied model illustrates aggregation’s benefit. Real overhead also includes per-MPDU fields, padding, acknowledgments and scheduling details; both PHY rate and aggregation matter.')
q(9)['prompt']='In a simplified same-channel topology, B sends to A while C wants to send to D. Assume concurrent data transmissions would not interfere at either receiver. C nevertheless senses B and defers. What is this effect, and does basic RTS/CTS automatically authorise C to ignore the busy medium?'
q(9)['options'][1]={'text':'Exposed-terminal deferral; basic RTS/CTS does not automatically authorise concurrent transmission','explanation':'Correct. Deferral can suppress a potentially useful transmission, but basic protection is not a general spatial-reuse permission system.'}
q(9)['workedExample']='The question supplies non-interference at both data receivers; merely saying D cannot hear B would not establish that C cannot harm A. C still defers because it senses the medium. This is exposed-terminal deferral. ACK interference and protocol timing also matter, so basic RTS/CTS does not automatically prove a concurrent complete exchange is safe.'
q(10)['prompt']='A busy venue has many compatible clients sending small packets plus older 2.4-GHz-only devices. Which measures can reduce contention or slow-client airtime effects when supported and properly configured? Select all that apply.'
q(10)['options'][0]['explanation']='Correct. Suitable OFDMA scheduling can multiplex compatible clients into one access; workload and scheduler behaviour determine the benefit.'
q(10)['options'][1]['explanation']='Correct as a potential mitigation. Airtime policies and traffic direction determine how much control the AP has; this does not guarantee elimination of every slow-client effect.'
q(10)['options'][2]['explanation']='Correct where permitted and supported. This separates them from older 2.4/5-GHz-only clients, but 6 GHz is not interference-free or guaranteed to use high rates.'
q(10)['options'][3]['explanation']='Higher QAM can shorten data airtime when signal quality permits, but does not directly combine clients’ separate channel accesses. Proximity alone is not the criterion.'
q(10)['workedExample']='OFDMA can amortise contention, airtime policies can improve scheduling, and another permitted band can separate clients into different contention resources. These are candidates for measurement, not a guaranteed ranking. Higher QAM addresses payload rate, while wider 2.4 GHz channels reduce the separate-channel choices available in a dense deployment.'
q(11)['prompt']='With numeric ping output to a home router, measured RTT rises from 4 ms idle to 180–250 ms during a download, without observed loss. Which leading hypothesis should be tested against local queue, retry and CPU measurements?'
q(11)['options'][1]['explanation']='A token-bucket drop policy often causes loss, but ICMP scheduling or prioritisation can also affect latency. Do not exclude all router processing effects from the ping trace alone.'
q(11)['options'][2]={'text':'Load-induced queueing, potentially compounded by wireless retries or contention','explanation':'Correct as a leading hypothesis, not a unique diagnosis. Locate the actual queue before choosing AQM, scheduling or shaping changes.'}
q(11)['options'][3]['explanation']='With numeric output the measured RTT increase is not explained by reverse-name display lookups. Some ping modes do perform name lookups, so “ping never uses DNS” is too broad.'
q(11)['workedExample']='The load correlation suggests queueing or contention. As a hypothetical FIFO calculation, 2,000,000 queued bytes at 80 Mbit/s need 0.2 seconds to drain. The ping alone does not measure that backlog or prove all delay is bufferbloat. Compare wired tests, AP queue/retry counters and CPU load; choose mitigation for the actual bottleneck.'
q(12)['prompt']='In the lesson’s 5 GHz OFDM DCF example, why is SIFS 16 µs shorter than DIFS 34 µs for an acknowledged unicast exchange?'
q(12)['options'][1]={'text':'It gives the immediate ACK priority over compliant DCF contenders that sense the exchange','explanation':'Correct. The ACK can begin before their DIFS expires. Hidden terminals or interference can still disrupt it; this is priority, not an absolute collision-free guarantee.'}
q(12)['options'][2]['explanation']='SIFS includes turnaround/processing constraints, but the comparison with DIFS establishes access priority. It is not a guarantee that all security processing completes before ACK transmission.'
q(12)['workedExample']='For the specified timings, DIFS = SIFS + 2 × slot = 16 + 2 × 9 = 34 µs. A receiver starting its ACK after 16 µs gains priority over compliant contenders that sense it and require 34 µs of idle time. This protects the exchange under those conditions; it is not an atomic guarantee against all other transmissions. Other PHYs and EDCA categories use different parameters.'
p.write_text(json.dumps(qs,indent=2,ensure_ascii=False)+'\n')
