from pathlib import Path
import json
p=Path('content/networks/02-ip-routing/ip-ipv4.questions.json');q=json.loads(p.read_text())
q[0]['options'][2]['explanation']=q[0]['options'][2]['explanation'].replace('4 bytes of options.','4 bytes of options/padding.')
q[0]['workedExample']=q[0]['workedExample'].replace('4 bytes of options.','4 bytes of options/padding.')
q[1]['prompt']='A sender sets initial TTL 64. A packet crosses five ordinary forwarding routers, each decrementing by exactly one, with no rewriting or tunnel effects. What TTL reaches the destination?'
q[1]['workedExample']='The five decrements produce 63, 62, 61, 60 and 59. The destination receives TTL 59. This calculation relies on the known initial value and forwarding assumptions; an arrival TTL alone cannot identify the sender\'s OS.'
q[2]['prompt']='Why must an ordinary IPv4 forwarding router update the header checksum when it decrements TTL?'
q[2]['options'][2]['explanation']='The IPv4 checksum covers the header, not payload. Ordinary forwarding does not re-encrypt the payload.'
q[2]['options'][3]['explanation']='Correct. TTL is part of the checked header. The checksum must remain consistent after modification; an incremental update is sufficient.'
q[2]['workedExample']='TTL is in the IPv4 header, which is covered by the checksum. Forwarding changes TTL, requiring a checksum update, either incrementally or by recomputing. Other simultaneous header changes can also affect the checksum. IPv6 has no corresponding base-header checksum.'
q[3]['workedExample']=q[3]['workedExample'].replace('48 bytes on the wire','48 bytes at the IP layer, before link framing')
q[4]['prompt']+=' Assume replies are permitted and delivered, and the destination really has no listener on the probe port.'
q[4]['workedExample']=q[4]['workedExample'].replace('port 33434+n','the probe\'s destination port')
q[4]['options'][1]['explanation']='For these probes, forwarding TTL expiry produces Time Exceeded. At the destination the unused UDP port instead produces Port Unreachable; Time Exceeded also has a separate reassembly-timeout code.'
q[5]['prompt']='After a VPN change, small TCP exchanges work but larger transfers stall. The firewall blocks inbound ICMP. Which is a plausible cause to investigate, rather than a diagnosis established by these symptoms alone?'
q[5]['options'][0]['explanation']='A small positive congestion window generally limits throughput. The packet-size pattern makes MTU handling worth investigating, but a capture is needed.'
q[5]['options'][1]['explanation']='A DNS problem does not directly explain a stall in an already established transfer to the same address.'
q[5]['options'][2]['explanation']='Encryption load can affect performance, but encryption alone does not establish why the size-dependent stall occurs.'
q[5]['options'][3]['explanation']='Correct as a hypothesis. If encapsulation makes packets too large, DF prevents fragmentation, ICMP feedback is blocked and probing does not recover, classic PMTUD can fail.'
q[5]['workedExample']='Check captures and interface/path MTUs to confirm whether oversized DF packets are dropped and whether corresponding ICMP errors reach the sender. Tunnel overhead matters relative to the actual outer MTU; not every tunnel has the same inner limit. Permit necessary MTU feedback, set a suitable interface MTU, or use appropriate TCP MSS/PLPMTUD support. TCP MSS adjustment must cover relevant directions and does not fix UDP. Retries can ultimately time out rather than continue forever.'
q[6]['prompt']='For a normally fragmented IPv4 datagram with a complete transport header in its first fragment, and ordinary IP forwarding without middlebox reassembly, which statements are true? Select all that apply.'
q[6]['options'][0]['explanation']='Correct under the stated forwarding model. Firewalls, NATs and tunnel endpoints can have separate reassembly functions.'
q[6]['options'][1]['explanation']='IP has no fragment retransmission mechanism. Higher layers may recover the missing data, possibly repacketising it; IP does not itself resend the datagram.'
q[6]['options'][2]['explanation']='Correct under the stated first-fragment assumption. IPv4 otherwise permits tiny first fragments that do not hold the whole TCP header; later fragments lack a directly available port tuple.'
q[6]['workedExample']='Ordinary forwarding preserves fragments until destination reassembly. IP does not retransmit a lost fragment. Under the specified layout the transport header is in the first fragment. Reassembly associates source, destination, protocol and Identification, then uses offsets/MF to reconstruct the payload. IPv6 routers do not perform IP fragmentation; only the source does.'
q[7]['options'][0]['explanation']='Later probes reached further nodes, so the observations do not show that all traffic was blocked. Different probes can use different paths.'
q[7]['options'][1]['text']='No reply was received for those probes; suppression, filtering or loss are possible, and later probes did reach further'
q[7]['options'][1]['explanation']='Correct. Stars do not identify whether the probe or response was lost or suppressed, and do not prove a transit outage.'
q[7]['options'][3]['explanation']='These observations do not establish a loop. Loops, routing changes and load balancing require additional evidence; repeated addresses are not a universal signature.'
q[7]['workedExample']='Each star is a probe timeout. A router may suppress or rate-limit Time Exceeded; either direction may filter or lose packets. Later replies show successful further reachability for other probes, which can follow different paths. They do not establish that forwarding at one device is entirely faultless or identify the cause of the missing reply.'
q[8]['prompt']+=' Assume inner IPv4, this MTU in both directions, and clamping advertisements in both SYN directions.'
q[8]['workedExample']=q[8]['workedExample'].replace('Clamping MSS in the SYN makes both endpoints send segments that fit, even if ICMP is blocked.','Clamping the relevant MSS advertisements in both directions limits both peers under these header/path assumptions. A single SYN advertises only what its sender can receive; other packet types and later path changes need separate handling.')
q[9]['prompt']='A packet arrives with TTL 116. Independently, you know the sender used 128, every forwarding router decremented by exactly one, and no TTL rewriting or tunnelling occurred. What follows?'
q[9]['options']=[{'text':'The packet crossed 116 routers','explanation':'116 is the remaining TTL, not the decrement count.'},{'text':'The sender must run Linux','explanation':'The chosen TTL does not uniquely identify an operating system.'},{'text':'The packet crossed 12 forwarding routers','explanation':'Correct. With the stated conditions, 128−116 = 12.'},{'text':'The sender must run Windows','explanation':'A TTL can be configured or selected by software; this arithmetic is not proof of an OS.'}]
q[9]['workedExample']='Known initial TTL 128 minus observed TTL 116 gives 12 one-unit forwarding decrements. Without those assumptions, an arrival TTL alone does not reveal the initial TTL, exact path length or operating system.'
q[10]['prompt']='A hypothetical sender emits 8,192-byte IPv4 datagrams at 1 Gbit/s measured before link and fragmentation overhead, all with the same source/destination/protocol. It increments one 16-bit Identification counter per datagram and fragments every datagram. Reassembly state can persist for 30 seconds. Roughly when does the ID wrap, and what risk follows?'
q[10]['options'][0]['explanation']='Correct. 125,000,000/8,192 ≈ 15,258.79 datagrams/s; 65,536/15,258.79 ≈ 4.295 seconds. ID reuse with matching source, destination and protocol can conflict with old reassembly state. Actual acceptance depends on fragment layout and checks.'
q[10]['options'][3]['explanation']='The question fixes one sequential 16-bit counter for this traffic tuple. A separate counter for a different destination does not enlarge its sequence space.'
q[10]['workedExample']='1 Gbit/s is 125,000,000 bytes/s at the specified accounting boundary. Dividing by 8,192 gives about 15,258.79 datagrams/s. A 65,536-value counter wraps after 4.295 seconds, shorter than the assumed 30-second reassembly-state lifetime. Reused IDs with the same source, destination and protocol can create ambiguity if old fragments remain. This is a hypothetical sequential-ID model; real ID selection, packet overhead and receiver checks affect the risk (RFC 4963 and RFC 6864).'
q[11]['prompt']='Which statements about ordinary ICMPv4 error handling are true? Select all that apply.'
q[11]['options'][0]['text']='The error types discussed here quote the offending IP header and at least its first 8 payload bytes when available'
q[11]['options'][0]['explanation']='Correct. The traditional format supports identifying the original packet. The quote can be longer and cannot contain bytes absent from the triggering packet.'
q[11]['options'][2]['explanation']='Correct. Rate limiting protects resources and limits error traffic. Missing traceroute replies can also arise from filtering or loss; implementation is not universally a slow CPU path.'
q[11]['options'][4]['explanation']='Blanket blocking can impair ICMP-based PMTUD and diagnostics. Some endpoints recover through packetisation-layer probing, so a black hole is not inevitable.'
q[11]['workedExample']='The covered errors quote the original header and initial payload, permitting matching when enough identifying data is available. ICMPv4 suppresses errors about errors and other prohibited cases such as non-initial fragments and broadcast/multicast traffic. Rate limiting can suppress responses. ICMPv4 is IP protocol 1, not UDP port 7. Necessary errors include IPv4 type 3/code 4 for classical PMTUD; ICMPv6 type 2 serves the corresponding IPv6 role.'
p.write_text(json.dumps(q,indent=2,ensure_ascii=False)+'\n')
