from pathlib import Path
import json
p=Path('content/networks/03-tcp/tcp-udp-ports.questions.json');q=json.loads(p.read_text())
q[0]['options'][3]['explanation']='The base UDP header remains eight bytes. RFC 9868 defines UDP options in a surplus area after user data, rather than making that base header variable length.'
q[1]['workedExample']='1. IPv4 total length is at most 65,535 bytes.\n2. Subtract the specified 20-byte IPv4 header and eight-byte UDP header: 65,507 payload bytes.\n3. With fragmentation permitted, equal 20-byte fragment headers and MTU 1,500, the 65,515-byte IP payload needs 45 fragments (44 × 1,480 + 395). All fragments are needed for reassembly.\n4. Otherwise sending may fail locally or on the path. With those same headers and MTU, 1,472 UDP payload bytes fit without fragmentation; other paths and encapsulation have different limits.'
q[2]['prompt']='Which facilities does base UDP provide, without higher-level reliability protocols? Select all that apply.'
q[2]['options'][0]['explanation']='Correct. UDP uses port fields to support application demultiplexing; not every possible transport protocol must use UDP-style ports.'
q[2]['options'][1]['explanation']='Correct. When enabled and verified, the checksum detects some corruption, including in the pseudo-header. It does not detect all errors or authenticate the sender, and IPv4 permits omission.'
q[2]['options'][3]['explanation']='Correct for ordinary UDP socket use. Received datagrams remain separate; too-small buffers can truncate a datagram, and successful sending does not guarantee delivery.'
q[2]['workedExample']='Base UDP defines source/destination ports, a datagram length and a checksum. These support demultiplexing, message boundaries and limited error detection. It does not define ordered delivery or automatic loss recovery. Protocol guarantees follow from the specification and state machine, not merely from whether a similarly named header field exists.'
q[3]['prompt']=q[3]['prompt'].replace('Assuming nothing is lost','Assuming ordinary datagram socket calls, no loss, duplication or reordering')
q[3]['options'][3]['explanation']='Ordinary UDP sockets preserve datagram boundaries. Here the buffer is large enough; smaller receive buffers can truncate a message rather than return it whole.'
q[4]['prompt']='A proxy uses one source IP and automatic source ports restricted to 32768–60999, all available initially. It repeatedly connects to one backend, 10.0.0.5:5432. Assume negligible active connection duration, exactly 60 seconds of tuple unavailability after closure, no early reuse and no other bottleneck. What approximate sustained rate does this model allow?'
q[4]['workedExample']=q[4]['workedExample'].replace('Steady-state rate = ports ÷ hold time','Under the stated model, steady-state rate = ports ÷ hold time').replace('each adds another 28k tuples','can add tuple capacity, subject to allocation and bind behaviour')
q[5]['prompt']='An HTTPS service accepts 100,000 simultaneous TCP connections on one server IP and local port 443. How many distinct local TCP port numbers do those accepted sockets use?'
q[5]['options'][2]['explanation']='These accepted sockets retain the listener’s local port. The initiating endpoint may choose an ephemeral source port or explicitly bind one.'
q[5]['workedExample']=q[5]['workedExample'].replace('Its real limits are memory per connection and file descriptors (`ulimit -n`).','Practical limits include memory, file descriptors, CPU and connection-tuple availability; this question specifies a service using just one local port.')
q[6]['prompt']='Which requirements can motivate an application to use ordinary UDP datagrams with application-specific control instead of one TCP byte stream? This compares base transports, not reliable protocols such as QUIC built above UDP. Select all that apply.'
q[6]['options'][0]['text']='Independent full-state game snapshots where superseded updates should not block newer ones'
q[6]['options'][0]['explanation']='Correct. The application can discard stale snapshots and avoid TCP byte-stream head-of-line blocking. Important events or delta-dependent state may require separate reliability.'
q[6]['options'][1]['text']='A software download whose only stated requirement is reliable delivery of every file byte'
q[6]['options'][1]['explanation']='That requirement alone does not motivate replacing TCP with base UDP. A higher-level reliable protocol such as QUIC can also carry downloads; this is not a claim that files cannot use UDP-based transports.'
q[6]['options'][2]['text']='A small DNS request/reply where avoiding a fresh transport handshake is useful'
q[6]['options'][2]['explanation']='Correct. UDP can carry the small exchange without a transport handshake; DNS still needs retries, validation and TCP support where required. Existing TCP connections can be reused.'
q[6]['options'][3]['text']='Deadline-sensitive voice packets for which later packets should not wait for expired ones'
q[6]['options'][3]['explanation']='Correct. Media-specific loss recovery can respect playback deadlines. Concealment, FEC or timely retransmission can all be useful; retransmission is not universally pointless.'
q[6]['options'][4]['text']='A payment API whose only stated requirement is that the transaction must not be lost'
q[6]['options'][4]['explanation']='Base UDP adds no delivery guarantee. TCP or QUIC can carry reliable data, but neither alone guarantees durable payment processing: acknowledgements, retries and idempotency belong at the application layer.'
q[6]['workedExample']='Select the requirements that benefit from independent datagrams or no fresh transport handshake: snapshots, a small DNS exchange and deadline-sensitive voice. A file’s completeness requirement or a payment’s durability requirement alone does not motivate bare UDP. Reliable transports built over UDP remain valid options, and application correctness is separate from byte delivery.'
q[7]['options'][0]['explanation']='Correct for this standard truncation/retry path. DNS-over-TCP supports larger messages, but still uses a two-byte message-length field; it is not unlimited.'
q[7]['workedExample']='1. Original UDP DNS used a 512-byte limit; EDNS lets a requester advertise a larger UDP payload size.\n2. DNS Flag Day 2020 recommended 1,232 bytes to reduce fragmentation risk under IPv6 minimum-MTU/header assumptions.\n3. A truncated response sets TC; the resolver can retry using TCP as specified by DNS handling rules.\n4. A new TCP connection adds handshake cost; a reusable connection changes that timing. DNS-over-TCP messages still have a 65,535-byte length-field limit.'
q[8]['prompt']+=' Assume the factor includes the same overhead basis as the 100 Mbit/s figure, and all queries/replies are delivered without rate limiting or capacity constraints.'
q[8]['options'][3]['explanation']='Correct under the assumptions. UDP itself performs no return-routability handshake, and these servers respond without additional validation: 100 Mbit/s × 50 = 5 Gbit/s.'
q[8]['workedExample']='1. The scenario explicitly allows spoofed requests through source-address filters.\n2. These servers send responses to the claimed source without further validation.\n3. With consistent size accounting and no limiting bottleneck, 100 Mbit/s × 50 = 5 Gbit/s at the victim.\n4. Source validation, response limits and protocol-level address validation can reduce this risk. TCP’s handshake changes the attack surface but does not make all TCP reflection or denial-of-service attacks impossible.'
q[9]['options'][2]['text']='Later bytes on that TCP stream wait for the missing bytes; after recovery, several buffered updates may become readable'
q[9]['options'][2]['explanation']='Correct. TCP exposes an ordered byte stream. The question’s RTT does not specify an exact stall duration or imply the application’s whole game loop freezes.'
q[9]['options'][0]['explanation']='TCP does not skip missing stream bytes to expose later ones. UDP-based independent snapshots can avoid that stream-ordering constraint, subject to loss and scheduling.'
q[9]['workedExample']='1. Later stream bytes can arrive out of order and be buffered.\n2. TCP cannot expose them as contiguous application data until the earlier gap is filled.\n3. Detection and recovery time depend on ACKs, timers, the loss position and implementation. RTT alone provides no exact pause duration.\n4. At 60 Hz, six update intervals span 100 ms, but that arithmetic is only an illustration, not a guaranteed six-update stall.\n5. An application can continue local prediction or other work while waiting.'
q[10]['options'][0]['text']='Using existing UDP support can ease traversal of middleboxes compared with introducing a new IP protocol number'
q[10]['options'][0]['explanation']='Correct. Some devices filter unknown protocols or lack suitable translation support. Devices can support other transports too, and UDP can itself be blocked.'
q[10]['options'][1]['explanation']='Correct. Existing UDP socket interfaces allow QUIC implementations in application libraries; operating-system policy and network access still apply.'
q[10]['options'][3]['explanation']='The checksum is not cryptographic authentication. QUIC uses TLS 1.3 for its handshake and derives keys for packet protection; a checksum does not replace that.'
q[10]['workedExample']='1. Reusing UDP allows implementations to use existing endpoint socket APIs and network support.\n2. This can reduce the deployment changes required by a new IP protocol.\n3. It does not make UDP universally reachable or restrict QUIC to user-space implementations.\n4. QUIC supplies its own loss recovery, stream ordering, congestion control and packet protection above UDP.'
for i in (0,1,2,3):q[i]['link']={'title':'RFC 768: UDP','url':'https://www.rfc-editor.org/rfc/rfc768'}
q[7]['link']={'title':'RFC 7766: DNS-over-TCP requirements','url':'https://www.rfc-editor.org/rfc/rfc7766'}
p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
