from pathlib import Path
import json
B=Path('content/theory/05-computability');p=B/'compu-church-turing.md';s=p.read_text()
def r(a,b):
 global s
 assert a in s,a
 s=s.replace(a,b)
r('Why every reasonable model of computation turns out to be equivalent to the Turing machine', 'Why standard models of effective computation agree with the Turing machine')
r('**Every model ever proposed is equivalent or weaker.**', '**Standard models of effective computation agree.**')
r('all compute exactly the TM-computable functions.', 'have universal variants or encodings. Rule 110 universality uses suitable repeating backgrounds; these results concern idealised unbounded resources. Oracle machines and proposed hypercomputers are different models, not counterexamples established as effective procedures.')
r('**Every programming language** that has unbounded memory and unrestricted loops or recursion can simulate a TM and be simulated by one.', '**General-purpose languages with suitable operations** can simulate a TM under unbounded-resource idealisation. Loops plus memory alone are not a proof: a PDA can loop and has an unbounded stack, but its restricted memory access limits its power.')
r('"no algorithm, in any language, on any hardware, decides the halting problem".', '"no effective procedure decides the halting problem for all programs and inputs in the unbounded model". Fixed finite hardware needs the separate qualification below.')
r('Recursion comes from the **Y combinator**, a term that makes any function call itself without having a name. With that, the λ-calculus is Turing complete.', 'In the untyped λ-calculus, a **fixed-point combinator**, such as Y, supplies recursion without a function name. Evaluation strategy matters: a direct Y translation diverges under Python\'s eager evaluation; an eager-language version needs delayed evaluation, for example a Z combinator. The arithmetic examples above need neither.')
r('U is a single fixed machine that can run any program. That is the stored-program computer, described a decade before one was built. The Python TM simulator in the last lesson is a universal machine: the `delta` dictionary is ⟨M⟩. So is CPython, the JVM, and a CPU\'s instruction decoder.', 'U is a single fixed machine that can simulate any encoded TM. It demonstrates the programs-as-data idea behind interpreters. The previous lesson\'s Python simulator illustrates this, with `delta` as the encoded rules, but its step cap makes each call a bounded simulation. CPython and the JVM are practical interpreters with resource limits; a CPU decoder alone is not a universal machine. Universality concerns the whole effective computing system with unbounded storage and execution.')
r('Surprisingly little is needed:\n\n1. **Unbounded memory** (or unbounded integers).\n2. **Conditional branching** that can depend on that memory.\n3. **Unbounded iteration**: a loop or recursion with no fixed cap on how many times it runs.', 'A sufficient imperative construction is a writable tape that can grow without bound, a movable head, finite control that reads/writes symbols and chooses transitions, and unrestricted repetition. Other models encode these abilities differently: λ-calculus and cellular automata need no explicit `if` instruction. A checklist of memory, branches and loops is not by itself a universality proof.')
r('Brainfuck has eight one-character instructions and is Turing complete, because `[` and `]` give a while-loop over an unbounded tape:', 'Brainfuck has eight one-character instructions. With a suitable unbounded tape it can simulate a TM; `[` and `]` supply iteration and the other operations manipulate cells. This intentionally bounded demonstration implements seven instructions and rejects input `,`:')
r('        elif c == "]":\n            j = stack.pop()', '        elif c == "]":\n            if not stack:\n                raise ValueError("unmatched ]")\n            j = stack.pop()')
r('    while pc < len(code):', '    if stack:\n        raise ValueError("unmatched [")\n    if "," in code:\n        raise ValueError("input omitted")\n    while pc < len(code):')
r('        if c == ">": p += 1\n        elif c == "<": p -= 1', '        if c in "><":\n            p += 1 if c == ">" else -1\n            if not 0 <= p < len(tape):\n                raise IndexError("tape bound")')
r('(This sketch omits the input instruction `,` and uses a fixed 30,000-cell tape, as the original did. True Turing completeness needs the tape to grow as required.)', '(The finite 30,000-cell tape means this interpreter is not Turing complete. A negative pointer is rejected rather than accidentally indexing the end of a Python list. It still permits non-terminating programs such as `+[]`.)')
r('**C++ templates** can perform arbitrary computation at compile time.', '**C++ templates** can express universal computation when compiler resource and instantiation-depth limits are idealised away.')
r('**x86 `mov`** alone is Turing complete (Stephen Dolan, 2013), which led to a compiler that emits only `mov` instructions.', '**x86-style `mov` operations**, plus a final unconditional jump back to the start, simulate a TM in Stephen Dolan\'s 2013 construction. It assumes unbounded addressable memory; a finite straight-line sequence of `mov` instructions alone is not universal.')
r('**SQL** becomes Turing complete with recursive common table expressions (`WITH RECURSIVE` in PostgreSQL).', '**SQL with recursive CTEs and suitable data operations** can encode TM simulation when storage and value sizes are unbounded. PostgreSQL `WITH RECURSIVE` supplies iteration, but the keyword alone is not a proof and a real database has finite resource/type limits.')
r('**Conway\'s Game of Life** and **Rule 110** are Turing complete with suitable starting patterns.', '**Conway\'s Game of Life** and **Rule 110** have universal constructions with suitable initial configurations and unbounded space. Cook\'s Rule 110 simulation includes repeating backgrounds extending away from the encoded input.')
r('almost every interesting question about a Turing-complete program is undecidable.', 'every non-trivial property of the recognised language is undecidable for arbitrary TMs. This does not make every useful question undecidable.')
r('| Regular expressions (true) | finite memory | linear-time matching |', '| Formal regular expressions | finite automata | linear input scan for a fixed DFA |')
r('| eBPF in Linux | verifier must prove the program terminates | safe to run in the kernel |', '| eBPF in Linux | verifier restricts accepted programs, including loop bounds | termination and safety checks under its model; not a guarantee against implementation bugs |')
r('| Starlark (Bazel) | no recursion, loops over finite collections only | builds always finish |', '| Starlark core | no recursion, finite iteration | core evaluation terminates; extensions and external build commands need separate analysis |')
r('| Agda, Coq/Rocq, Dhall | total functions only | programs double as proofs |', '| Total fragments of Agda and Rocq; Dhall | termination restrictions | stronger evaluation guarantees; Agda/Rocq also have guarded coinduction and features requiring separate treatment |')
r('Ethereum\'s EVM is Turing complete in principle but bounds every execution with **gas**: each instruction costs gas and a transaction runs out after a fixed budget. That turns "will it halt?" into "it definitely halts within N steps", at the cost of failing some long computations.', 'Ethereum bounds transaction execution with **gas**. Continuing computation consumes the finite budget; some terminating instructions, including `STOP`, have zero base cost, so it is false that every instruction costs at least one gas. A transaction eventually stops normally, exceptionally or out of gas. This guarantees termination under EVM semantics, not successful completion or a wall-clock deadline. Calling the EVM Turing complete also idealises away its actual resource and fixed-width addressing limits.')
r('A laptop with 16 GB of RAM has a finite number of states, so strictly speaking it is a (huge) finite automaton.', 'A closed deterministic computer with fixed finite RAM, registers, storage and other state has finitely many configurations. External inputs must also be fixed or modelled before state repetition implies a loop.')
r('claims any reasonable model can be simulated by a TM with only **polynomial** slowdown.', 'is commonly stated using efficient simulation by a probabilistic classical TM, with only **polynomial** overhead.')
r('A classical computer can simulate a quantum circuit by tracking all its amplitudes, just exponentially slowly.', 'For the standard effective quantum circuit model, a classical computer can approximate amplitudes and outcome probabilities to a specified accuracy, generally using exponential resources. This assumes effectively specified gates; arbitrary exact real-number oracles are not part of that model.')
r('A language with fixed-size integers and no dynamic allocation is a finite automaton, however large.', 'All storage must be bounded, including the call stack and external storage. Fixed-width integers and no heap allocation alone do not establish this.')
r('- λ-calculus, recursive functions, RAM machines, Rule 110 and every general-purpose language are equivalent in power.', '- Standard effective universal models agree on computability, under their appropriate unbounded-resource assumptions.')
r('- Turing completeness needs only unbounded memory, conditional branching and unbounded iteration, so it appears by accident.', '- Prove Turing completeness by simulation; loops and memory alone are not sufficient, and explicit branching syntax is not necessary.')
s+='\n- [Dolan: mov is Turing-complete (construction and assumptions)](https://harrisonwl.github.io/assets/courses/malware/spring2017/papers/mov-is-turing-complete.pdf)\n- [Cook: A Concrete View of Rule 110 Computation](https://arxiv.org/abs/0906.3248)\n- [Ethereum opcode reference](https://ethereum.org/developers/docs/evm/opcodes/)\n'
p.write_text(s)
p=B/'compu-church-turing.questions.json';qs=json.loads(p.read_text());q={str(i+1):v for i,v in enumerate(qs)}
q['1']['workedExample']=q['1']['workedExample'].replace('every formal model anyone has proposed', 'standard formal models of effective computation').replace('has been *proved* equivalent to TMs or weaker', 'have been proved equivalent to TMs under their appropriate unbounded-resource assumptions')
q['2']['options'][0]['text']='Formal regular expressions using union, concatenation and Kleene star'
q['2']['workedExample']='Python can encode a TM tape, control state and transition function, with unbounded resources idealised. A PDA also has unbounded storage and may loop, but can access only the top of one stack; it is not universal. Formal regular expressions describe regular languages. Bitcoin Script deliberately bounds execution.'
q['3']['options'][3]['explanation']='Universality guarantees simulation, not optimal running time for every problem.'
q['5']['prompt']=q['5']['prompt'].replace('interpreter print','function return')
q['5']['workedExample']=q['5']['workedExample'].replace('print chr(66)', 'append chr(66) to the output').replace('the ingredient that makes Brainfuck Turing complete.', 'one component of unbounded Brainfuck simulation; this fixed-tape interpreter is not Turing complete.')
q['6']['prompt']='Which capabilities are used in the lesson\'s sufficient imperative construction of a universal TM simulator? Select all that apply.'
q['6']['options'][0]['text']='A read-write tape that can grow without bound, with a movable head'
q['6']['options'][0]['explanation']='Correct. The simulator needs storage for arbitrarily large finite tape contents.'
q['6']['options'][1]['explanation']='Correct for this construction: control selects the next transition using the current state and symbol. Other universal models need no explicit branch instruction.'
q['6']['options'][2]['explanation']='Correct. Simulation must be able to continue for an unbounded number of steps, including forever when the simulated machine loops.'
q['6']['workedExample']='The construction maintains a tape and head, chooses transitions from state and symbol, and repeats. These specific operations suffice to simulate a TM. Merely listing loops, branches and unbounded storage does not prove universality: a PDA has all three in restricted forms but is weaker. Other universal models encode these operations without explicit imperative syntax.'
q['7']['options'][2]['text']='With suitable memory operations, unrestricted recursion or loops permit universal computation and non-termination; no total analyser can exactly decide termination for every configuration'
q['7']['options'][2]['explanation']='Correct. Starlark restricts core evaluation, but external commands and host extensions need separate guarantees. Useful partial or conservative analysis remains possible.'
q['7']['workedExample']='1. A sufficiently expressive configuration language can encode arbitrary TM simulations.\n2. Exact termination analysis for all such programs is undecidable.\n3. This does not prevent parsing, caching or useful conservative analysis. Rice concerns non-trivial extensional properties, not every tool guarantee.\n4. Restricting core evaluation, as in Starlark, helps predictability without guaranteeing that an entire external build finishes.'
q['8']['prompt']='An EVM transaction has a finite gas budget. Continuing execution consumes gas, although terminating opcodes such as STOP can cost zero. What follows under the EVM execution rules?'
q['8']['options'][3]['text']='Execution eventually stops, whether normally, exceptionally or out of gas; successful completion is not guaranteed'
q['8']['options'][3]['explanation']='Correct. A continuing computation cannot repeat indefinitely without exhausting gas. Zero-cost terminating instructions do not create an infinite free loop.'
q['8']['workedExample']='1. The transaction has a finite gas budget.\n2. Continuing computation consumes it; zero-cost terminating instructions such as STOP do not sustain a loop.\n3. The execution therefore ends, possibly exceptionally or out of gas.\n4. A bound of exactly G instructions does not follow from a budget of G: not every instruction costs at least one gas. Gas also does not promise successful completion or a wall-clock deadline.'
q['8']['link']={'title':'Ethereum opcode reference','url':'https://ethereum.org/developers/docs/evm/opcodes/'}
q['9']['options'][0]['explanation']='Standard quantum algorithms use effectively specified gates and can be classically simulated to specified accuracy; they do not provide a halting oracle.'
q['9']['workedExample']='1. For standard effective quantum circuits, classical simulation can approximate outcome probabilities to specified accuracy, generally with exponential resources.\n2. The extended thesis concerns efficient classical, commonly probabilistic, simulation.\n3. Shor gives polynomial-time quantum factoring; no polynomial-time classical algorithm is known.\n4. A provable super-polynomial separation would refute that simulation claim. Factoring currently supplies evidence, not a proven classical lower bound.'
q['10']['options'][0]['text']='Finite-state analysis is decidable in principle for a closed fixed machine, but the state space can be impractical; unbounded-memory program models still have undecidable problems'
q['10']['options'][0]['explanation']='Correct. Exhaustive state exploration is one decision procedure, not the only possible method. Structure can make particular cases easy.'
q['10']['options'][2]['explanation']='Finite hardware does not make exhaustive analysis practical. For unbounded program semantics no total exact termination analyser exists; particular bounded systems can be analysed exactly.'
q['10']['workedExample']='1. 16 GiB = 16 × 2³⁰ × 8 = 137,438,953,472 bits (GiB, not decimal GB).\n2. RAM alone has 2^137438953472 possible bit patterns. Complete configurations also include registers, control and other storage.\n3. In a closed deterministic finite-state model, a repeated complete non-halting state proves a loop. External inputs must be fixed or modelled.\n4. Exhaustive exploration can be impractical, though structural analysis solves some cases cheaply.\n5. Unbounded-memory semantics abstracts away a particular device limit; undecidability applies to that model.'
q['11']['options'][0]['explanation']='Correct. Cook\'s universal construction uses a finite encoded input with suitable repeating backgrounds extending to either side.'
q['11']['options'][1]['text']='SQL recursive CTEs with suitable operations on unbounded encoded tape data'
q['11']['options'][1]['explanation']='Correct under these idealisations: a CTE can iterate an encoded TM transition. Merely having the keyword, or a finite database instance, is not sufficient.'
q['11']['options'][3]['text']='A total language fragment in which every permitted computation must terminate'
q['11']['options'][4]['text']='Formal regular expressions using union, concatenation and Kleene star'
q['11']['workedExample']='Rule 110 and Life have universal constructions under suitable unbounded-space initial conditions. Recursive SQL with sufficient operations and unbounded values/storage can iterate a TM simulation. A genuinely total fragment cannot reproduce arbitrary divergence. Formal regular expressions define only regular languages; practical regex extensions such as recursion require separate analysis.'
p.write_text(json.dumps(qs,ensure_ascii=False,indent=2)+'\n')
print('church corrections applied')
