from pathlib import Path
import json
base=Path('content/theory/03-probability');p=base/'prob-statistics.md';s=p.read_text()
def r(a,b):
 global s
 assert a in s,a
 s=s.replace(a,b)
r('The **median** is the middle value when sorted. For symmetric data they agree;', 'The **median** is the middle sorted value, conventionally the average of the two middle values for an even-sized numeric sample. For a finite symmetric sample the mean and this median agree;')
r('CPU cost, throughput and capacity planning all scale with the mean. One very slow request really does consume resources.', 'total resource use is the request count times mean resource use per request. Wall-clock latency includes waiting and is not automatically CPU service time; capacity also depends on concurrency, utilisation and variability.')
r('The **p-th percentile** is the value below which p% of observations fall. p50 is the median; p99 means 99% of requests were faster.', 'A **p-th percentile** is a distribution threshold defined by a chosen quantile convention. Under the empirical nearest-rank convention, at least p% of observations are at or below the threshold; ties mean fewer than 100 − p% may be strictly above it. The population p50 is a median; sample conventions can differ from the usual averaged-middle median.')
r('    # nearest-rank method\n    s = sorted(xs)', '    # Nearest rank; extend p=0 to the sample minimum.\n    s = sorted(xs)\n    if not s or not 0 <= p <= 100:\n        raise ValueError("need nonempty data and 0 <= p <= 100")')
r('Latency SLOs are almost always stated as percentiles:', 'Latency SLOs can be expressed using percentile thresholds or the fraction of requests below a threshold, for example')
r('which is noise.', 'which is a very uncertain estimate of a population tail.')
r('Store **histograms** (Prometheus histograms, HdrHistogram, t-digest) and merge those, then compute percentiles from the merged histogram.', 'Store compatible **histograms** or mergeable quantile sketches, merge them over the same time window, then estimate the combined percentile. Prometheus histograms and HdrHistogram retain bucket counts; t-digest is a quantile sketch. Their estimates have representation error; raw observations permit an exact sample quantile under a specified convention.')
r('send a backup request if the first has not returned by roughly the p95, and use whichever answer arrives first.', 'send a backup request after a chosen delay and use the first acceptable answer. A delay near a measured p95 is one possible policy, not a universal threshold; extra load and request semantics matter.')
r('If observations are independent with standard deviation σ,', 'For independent, identically distributed observations with finite standard deviation σ,')
r('Quadrupling the sample halves the error.', 'Quadrupling the sample halves the standard error; the realised estimation error is still random.')
r('By the central limit theorem, x̄ is approximately normal for large n. So a **95% confidence interval** is:', 'Under suitable CLT conditions and a large enough sample for the approximation, x̄ is approximately normal. An approximate **95% confidence interval** is:')
r('For a **proportion** (conversion rate, error rate) with p̂ observed in n trials:', 'For an iid Bernoulli **proportion** with p̂ observed in n trials, the plug-in standard error is:')
r('A 5% conversion rate measured on 10,000 visitors', 'The resulting Wald interval can be inaccurate near 0 or 1 or with small success/failure counts; Wilson or exact binomial intervals are alternatives. For a mean with estimated σ, a Student-t interval is exact under normal iid sampling and approaches the displayed normal interval for large samples.\n\nA 5% conversion rate measured on 10,000 independent visitors')
r('are correlated, and the true uncertainty is larger.', 'can be positively correlated, making an independence-based standard error too small. Correlation does not invariably increase uncertainty; its sign and structure matter.')
r('The **p-value** is the probability of a difference at least that large *if H₀ were true*.', 'The **p-value** is the probability, under H₀ and the assumed sampling model, of a test statistic at least as extreme as observed in the pre-specified direction or directions.')
r('Teams usually aim for 80%.', 'An 80% target is a common design choice, not a universal requirement.')
r('def ab_test(c1, n1, c2, n2):\n    p1', 'def ab_test(c1, n1, c2, n2):\n    # Independent Bernoulli samples; large-count normal approximation.\n    if not (n1 > 0 and n2 > 0 and 0 <= c1 <= n1 and 0 <= c2 <= n2):\n        raise ValueError("invalid counts")\n    p1')
r('    z = (p2 - p1) / se\n    p = 2 * (1 - NormalDist().cdf(abs(z)))', '    if se == 0:\n        raise ValueError("degenerate pooled variance; choose another method")\n    z = (p2 - p1) / se\n    # erfc avoids subtracting nearly equal numbers in extreme tails.\n    from math import erfc\n    p = erfc(abs(z) / sqrt(2))')
r('from statistics import NormalDist\n', '')
r('z₀.₀₂₅ + z₀.₂', 'z₀.₉₇₅ + z₀.₈')
r('          ≈ 14,750', '          ≈ 14,732 (roughly 14,750)')
r("A handy rule of thumb (Lehr's) is", 'Using approximately equal arm variances gives the handy planning rule')
r('Small sites cannot reliably detect small effects, however long they wait for a "trend".', 'Low traffic may make the required sample impractical within a stable experiment window; looking for a trend does not replace adequate sample size. This is an approximate planning formula, not an exact power guarantee.')
r('In a simulation with no real effect, checking 10 times during a test and stopping at the first p < 0.05 produced false positives about **19%** of the time, not 5%.', 'The amount of inflation depends on the test, sample sizes, look schedule and stopping rule.\n\n> [!note] Evidence gap\n> The previous 19% false-positive figure and claimed simulation run are omitted because no reproducible simulation or adequately specified design supported them. Ten looks do not determine one universal error rate.')
r('which platforms like Optimizely and Statsig offer.', 'with error control appropriate to the sampling and stopping rules.')
r('Test 20 metrics (or 20 variants, or 20 user segments) with no real effect and at α = 0.05:', 'For 20 independent tests, each with exact null rejection probability 0.05, the chance of at least one false rejection is:')
r('Something will look like a win.', 'A false rejection is likely in this independent example, but not certain. Correlated metrics need not have this 64% probability.')
r('or control the false discovery rate with Benjamini–Hochberg).', 'or control a different quantity, the false discovery rate, with Benjamini–Hochberg under its independence or appropriate positive-dependence assumptions). Bonferroni controls family-wise error without requiring independence.')
r('so something (a redirect, a bot filter, a crash in one arm) is broken, and the result cannot be trusted.', 'so investigate assignment and logging (for example redirects, bot filters or crashes) before interpreting the treatment comparison; this is strong evidence of a mismatch, not logical proof of a particular defect.')
r('Run tests for full weeks to cover weekly cycles.', 'Use a pre-planned duration that covers relevant cycles; full weeks can address weekly seasonality but do not guarantee novelty or learning effects have settled.')
r('Randomisation prevents this in a proper A/B test,', 'Randomisation balances pre-treatment groups in expectation, but finite-sample imbalance, attrition or post-treatment conditioning can still produce this pattern,')
r('With 10 million users, a 0.01% lift can be significant and still not worth the code complexity.', 'With enough data, a small effect can be statistically significant and still not justify the implementation cost. Whether a particular lift is detectable depends on its units, baseline variance and design.')
r('- A p-value is P(data | no effect), not P(no effect | data).', '- A p-value is a tail probability of a test statistic under the null sampling model, not the probability that the null is true.')
s+='\n- [Statement on p-values — American Statistical Association](https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf)\n- [Confidence intervals for proportions — NIST](https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm)\n- [Histograms and summaries — Prometheus](https://prometheus.io/docs/practices/histograms/)\n'
p.write_text(s)
p=base/'prob-statistics.questions.json';qs=json.loads(p.read_text());q={x['id'].split('-q')[-1]:x for x in qs}
q['1']['options'][2]['explanation']='Replacing one 10 ms request with a 5,000 ms request raises the mean by (5000 − 10)/100 = 49.9 ms.'
q['1']['workedExample']=q['1']['workedExample'].replace('For capacity (total server time) the mean is what matters;', 'Mean resource service time helps estimate total resource work; elapsed latency also includes waiting. For this latency sample,')
q['2']['prompt']='A dashboard using the empirical nearest-rank convention says p99 latency = 420 ms. Which interpretation is correct, allowing ties?'
q['2']['options'][2]={'text':'At least 99% of recorded requests took 420 ms or less; no more than 1% were slower','explanation':'Correct for nearest rank. Ties and finite sample ranks can make the fraction at or below the threshold greater than 99%.'}
q['2']['options'][1]['explanation']='That would be a tail conditional mean, not a percentile threshold; a trimmed mean conventionally discards tail observations.'
q['2']['workedExample']='With n observations, nearest-rank p99 is the sorted value at rank ceil(0.99n). At least that many observations are at or below it; ties can put still more there. The percentile says nothing about how slow the remaining observations are.'
q['3']['prompt']+=' Assume iid runs with unchanged finite population variance.'
q['4']['prompt']+=' Assume iid sampling and a sufficiently accurate large-sample normal approximation.'
q['4']['workedExample']=q['4']['workedExample'].replace("If they came from one warm process during one minute, the real uncertainty about 'this build's latency' is larger.", 'Positive autocorrelation or a changing environment can make this interval too narrow; a sample from one condition also need not represent all deployment conditions.')
q['7']['prompt']='A pre-planned one-sided test of increased sign-ups reports p = 0.03. Under its assumed sampling model, which interpretation is correct?'
q['8']['prompt']=q['8']['prompt'].replace('a **correct** fleet-wide p99','a fleet-wide p99 calculation or an explicitly approximate estimate from combined data over the same time window')
q['8']['options'][4]['explanation']='Correct as an estimate when configurations and time windows are compatible. Merging preserves more distribution information than per-server quantiles, but sketches and histograms have approximation error.'
q['8']['workedExample']=q['8']['workedExample'].replace('so the fleet p99 is about 10 ms', 'so the nearest-rank fleet p99 is 10 ms')
q['11']['prompt']='A team repeatedly checks an ordinary fixed-sample A/B p-value and stops at the first p < 0.05. Under the null, what can be concluded without a fully specified look schedule, test and sample sizes?'
q['11']['options']=[{'text':'The false-positive probability remains exactly 5%','explanation':'The single fixed-look threshold does not generally control the overall probability under repeated optional stopping.'},{'text':'It is exactly 1 − 0.95¹⁰ for ten looks','explanation':'That calculation requires independent looks each with exact size 0.05; cumulative analyses reuse data.'},{'text':'The false-positive probability can exceed 5%; its amount requires the design or an appropriate sequential analysis','explanation':'Correct. The number of looks alone does not determine a universal false-positive probability.'},{'text':'It is zero because the null is true','explanation':'Sampling variation can produce false positives under a true null.'}]
q['11']['workedExample']='A fixed-sample p-value controls its rejection probability at a planned look under the test assumptions. Repeatedly stopping at the first crossing changes the rejection event to a union over looks. Cumulative looks are dependent, so neither 5% nor an independent-look formula supplies a universal answer. Pre-specify the stopping rule or use a sequential method with suitable error control.\n\nEvidence gap: the previous claimed 3,000-run simulation and 19% result are omitted because their setup and output were not available for verification.'
q['12']['prompt']+=' For the multiple-testing probability, assume the 20 null rejection events are independent and each has probability 0.05.'
q['12']['options'][0]['explanation']=q['12']['options'][0]['explanation'].replace('Something (bucketing, redirects, crashes, bot filtering) is broken.', 'This is strong evidence to investigate bucketing, redirects, crashes or filtering; a rare random event is not logically impossible.')
q['12']['workedExample']=q['12']['workedExample'].replace('A 6σ deviation means the assignment or logging is biased', 'A 6σ deviation is strong evidence to investigate assignment or logging bias').replace('20 metrics at α = 0.05:', '20 independent null rejection events at α = 0.05:')
p.write_text(json.dumps(qs,ensure_ascii=False,indent=2)+'\n')
