exec(open('docs/audit-checkpoint-2026-10-05/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-theory-logic.json');r=json.loads(p_report.read_text());findings=r['findings'];b='content/theory/01-logic-proofs/'
src=['https://raw.githubusercontent.com/niklasso/minisat/master/minisat/core/Solver.cc','https://www.cs.utexas.edu/~marijn/drat-trim/','https://github.com/openSUSE/libsolv','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_textbook.pdf']
patch(b+'logp-sat.md',[
('Yet modern SAT solvers routinely handle industrial formulas with millions of variables.', 'Modern SAT solvers can solve large structured industrial formulas, but instance size alone does not predict runtime.'),
('Doing this for every gate gives a CNF whose size is **linear** in the original formula.', 'Add these constraints for every bounded-fan-in gate and a unit clause asserting the root/output variable true. The resulting CNF is linear in formula size. Gate definitions alone do not assert the original formula.'),
('It is not *equivalent* (it has extra variables), but it is **equisatisfiable**:', 'It is generally not logically equivalent over the enlarged set of variables, but it is equisatisfiable:'),
('Sudoku (729 variables,', 'standard 9×9 Sudoku (729 variables,'),
('Problems whose solutions can be checked in polynomial time form the class **NP**.', 'NP is the class of decision problems whose yes instances have polynomial-length certificates verifiable in polynomial time.'),
('The formula is unsatisfiable exactly when some x and ¬x lie in the same strongly connected component', 'First reject any empty clause and encode a unit clause a as (a ∨ a). For the remaining 2-SAT instance, unsatisfiability holds exactly when some x and ¬x lie in the same strongly connected component'),
('Start with everything false and apply unit propagation; this is essentially how Datalog and Prolog-style rule engines reason.', 'Begin with no variables derived true, propagate positive facts through rules, and report a conflict if an all-negative clause has all its variables forced true. With counters and occurrence lists this is linear in input size. Finite Datalog uses related fixed-point reasoning; general Prolog execution is not the same algorithm or termination guarantee.'),
('Clauses are `frozenset`s of integers, with −3 meaning ¬x3.', 'Clauses are frozensets of nonzero integers, with −3 meaning ¬x3. Call dpll with its default empty model; a returned partial model satisfies all clauses and any omitted variables may be chosen freely. This recursive teaching solver is limited by runtime recursion and resource bounds.'),
('The solver never makes that mistake again anywhere in the search.', 'While retained, the learned clause prevents propagation from accepting that same conflicting combination. Practical solvers can later delete learned clauses.'),
('jump back to the earliest decision involved in the conflict, skipping irrelevant parts of the tree.', 'standard first-UIP analysis backjumps to the second-highest decision level among literals in its learned clause, or level zero for a unit clause, making that clause assert a literal. This need not be the earliest involved decision.'),
('Periodically throw away the current assignments (but keep learned clauses),', 'Periodically discard decisions while retaining root consequences and useful learned clauses (subject to clause deletion),'),
('Propagation is most of the runtime. Each clause watches only two of its literals and is examined only when one of them becomes false, so most clauses are never touched on a given assignment.', 'During ordinary propagation, nonunit clauses can watch two literals and avoid scans unless a watched literal becomes false. Unit clauses and other solver phases need separate handling.'),
('Industrial instances with millions of clauses are often solved in seconds.', 'Runtime depends on encoding, solver, hardware and instance structure.\n\n> [!note] Evidence gap\n> Universal claims about million-clause solve times or millisecond verification are omitted: no reproducible benchmark set and machine configuration were supplied.'),
('When a CDCL solver says UNSAT, it has in effect built a resolution proof. Many solvers can output it in a checkable format (DRAT), so you need not trust the solver\'s code. For the pigeonhole formulas ("n + 1 pigeons in n holes"), Haken proved in 1985 that every resolution proof is exponentially long, so these tiny-looking formulas defeat CDCL.', 'Basic CDCL learns resolution consequences. Production solvers may also use preprocessing or stronger transformations, and can emit checkable proof logs such as DRAT. DRAT permits steps beyond ordinary resolution; an independently checked log reduces reliance on the solver, while still depending on the checker and input encoding. Exponential resolution lower bounds for standard pigeonhole encodings do not automatically establish the same limit for every extended solver or encoding.'),
('For random 3-SAT with n variables and m clauses, the ratio m/n predicts difficulty. Below about 4.27 almost all instances are satisfiable and easy; well above it almost all are unsatisfiable and fairly easy to refute. Near the threshold, instances are hardest. Industrial formulas behave very differently from random ones, which is why solver competitions use both.', 'Random-instance experiments must specify the clause distribution, number of variables and solver. Clause density can correlate with satisfiability and observed difficulty in such experiments; it does not determine whether an individual formula is easy. Industrial formulas have different structure.\n\n> [!note] Evidence gap\n> The previous universal density cutoff and easy/hard classifications are omitted because they conflated a model-dependent approximate threshold with a theorem and a runtime guarantee.'),
('Small encoding changes, like adding symmetry-breaking clauses ("vertex 1 is red"), can cut solve times by orders of magnitude.', 'Sound symmetry-breaking constraints may reduce search. For unconstrained graph colouring with interchangeable colours, fixing one vertex to red preserves satisfiability; precolouring or other colour-specific constraints can invalidate that symmetry. Measure the effect on the actual workload.')], 'Correct Tseitin root, NP and Horn premises, CDCL backjump/deletion, proof formats and unsupported runtime/threshold claims.',src)
def sat(q):
 q[1]['options'][0]['explanation']='NP-completeness concerns the satisfiability decision problem. Given an assignment, checking its clauses requires no search.'
 q[1]['workedExample']=q[1]['workedExample'].replace('here a few million lookups: milliseconds.', 'plus clause bookkeeping; the prompt does not specify clause lengths or a measured runtime.')
 q[2]['options'][0]['explanation']='A clause is an OR of its literals; clauses are combined by AND. The zero token terminates a clause, regardless of line breaks.'
 q[2]['workedExample']=q[2]['workedExample'].replace('Literals on a line are ORed.', 'Literals up to the next zero terminator are ORed; a clause may span lines.')
 q[6]['workedExample']=q[6]['workedExample'].replace('A useful rule: adding options to a problem (longer clauses) can only make it harder, so k-SAT for k ≥ 3 is NP-complete.', 'For fixed k ≥ 3, allowing clauses of at most k literals includes every 3-SAT instance unchanged, proving NP-hardness; polynomial certificate checking gives membership in NP. This inclusion argument is not a general rule about adding options to arbitrary problems.')
 q[9]['workedExample']=q[9]['workedExample'].replace('it stops the solver ever exploring x1 = T, x4 = F again anywhere in the search.', 'while retained, it prevents propagation from accepting that conflicting combination. Learned-clause deletion can remove this protection.')
 q[12]['options'][1]['explanation']='The standard guarantee is equisatisfiability and projection of models, not logical equivalence over all assignments to original and fresh variables.'
 q[11]['workedExample']+='\nHere the clauses already force all four variable values, so minimizing installed packages changes nothing in this example.'
questions(b+'logp-sat.questions.json',sat,'Remove unsupported speed, correct DIMACS termination and scope reductions/proof equivalence.',src)
p=Path(b+'logp-invariants.questions.json');q=json.loads(p.read_text());q[1]['prompt']=q[1]['prompt'].replace('``` Assume','```\n\nAssume');p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
r['status']='All6lessons73questions corrected; execution and independent verification pending.'
r['omissions'] += [{'lesson':'logp-sat','claim':'Universal SAT timings and density-based easy/hard cutoff','reason':'No reproducible benchmarks; threshold/complexity guarantees overgeneralized. Explicit lesson notes explain omissions.'}]
p_report.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
