import json
from pathlib import Path
p=Path('content/networks/02-ip-routing/ip-bgp.questions.json'); q=json.loads(p.read_text())
q[0]['prompt']+=' Assume normal AS-loop checking with no configured exception.'
q[0]['options'][0]['explanation']='Correct. Normal AS-loop checking excludes this route because 65010 appears in its advertised path. The path is not proof of actual traffic traversal.'
q[0]['workedExample']='1. The advertised sequence contains 3356, 65010 and 1299.\n2. The receiver uses local ASN 65010.\n3. With normal loop checking, the route is excluded because the local ASN occurs in that sequence.\n4. This is an AS-loop check, not cryptographic verification of the path or a guarantee against every forwarding loop.'
q[1]['options'][0]['explanation']='Base BGP has no OSPF-style multicast Hello discovery. Peer relationships are configured, although implementations can automate provisioning or accept dynamic peers under rules.'
q[1]['options'][1]['explanation']='UDP port 520 and periodic routing updates describe RIPv2, not BGP.'
q[1]['options'][2]['explanation']='Correct. BGP uses TCP and normally incremental UPDATEs. KEEPALIVE and UPDATE messages maintain hold-timer liveness; extensions can request route refreshes.'
q[1]['workedExample']='1. Peer configuration establishes addresses, ASNs and policy.\n2. A TCP session is opened to port 179.\n3. OPEN exchanges session parameters and negotiated capabilities.\n4. Initial advertisements contain the routes permitted by selection and export policy; subsequent updates normally describe changes.\n5. For a nonzero negotiated hold time, KEEPALIVE or UPDATE receipt resets the timer. Expiry closes the session. Graceful-restart mechanisms can retain stale routes under specified conditions; hold time zero disables the hold timer.'
q[2]['prompt']+=' Assume both routes are eligible, visible to the relevant routers, and earlier vendor-specific preferences are equal.'
q[2]['options'][0]['explanation']='MED usually influences entry into the advertising neighbour and is normally compared only for the same neighbouring AS. Under the stated ordering it follows AS_PATH.'
q[2]['options'][1]['explanation']='Correct. LOCAL_PREF is carried over iBGP and, with the earlier checks tied here, takes priority over AS_PATH length.'
q[2]['workedExample']='1. The decision concerns outbound routing within the AS.\n2. Both eligible routes pass earlier checks equally.\n3. Assign LOCAL_PREF 200 to the peer route and 100 to transit.\n4. LOCAL_PREF decides before path length.\n5. Consistent policy and visibility of the preferred route are needed across the AS; iBGP does not guarantee identical information at every router.'
q[3]['prompt']+=' Assume both are eligible and equally weighted, with no local origination or configuration overriding the lesson’s selection order.'
q[3]['options'][2]['explanation']='Route age can be a late eBGP tie-breaker on some implementations; it cannot overcome the AS_PATH difference under the stated order.'
q[3]['workedExample']=q[3]['workedExample'].replace('would be skipped anyway','would normally be skipped anyway')
q[5]['workedExample']=q[5]['workedExample'].replace('Two reflectors rather than one avoids a single point of failure.','Two suitably designed reflectors can tolerate one reflector failing; shared infrastructure and configuration faults can still affect both.')
q[6]['options'][1]['text']='Where both routes were installed, forwarding preferred the hijacked /24 to the covering /22, regardless of the /22’s AS_PATH or LOCAL_PREF'
q[6]['options'][1]['explanation']='Correct. Best-path selection compares alternatives for the same prefix. Once the /24 and /22 are installed, forwarding selects the longer matching prefix.'
q[6]['options'][2]['explanation']='Correct. RIPE RIS observed PCCW propagating the unauthorised announcement; it was not blocked on that path.'
q[6]['options'][3]['explanation']='A /21 would not defeat an installed /24 through longest-prefix match. YouTube counter-announced the /24 and then two /25s; PCCW later withdrew the hijack.'
q[6]['workedExample']='1. YouTube advertised 208.65.152.0/22, covering third octets 152 through 155.\n2. At 18:47 UTC on 24 February 2008, RIS observed Pakistan Telecom’s 208.65.153.0/24 propagated by PCCW.\n3. Where both were installed, the /24 won forwarding by longest-prefix match.\n4. YouTube counter-announced the /24 at 20:07 and two /25s at 20:18. Equal-prefix choices depended on policy; the /25s helped where accepted.\n5. RIS observed PCCW withdrawing Pakistan Telecom-originated prefixes at 21:01.'
q[6]['link']={'title':'RIPE NCC: YouTube hijacking case study','url':'https://www.ripe.net/about-us/news/youtube-hijacking-a-ripe-ncc-ris-case-study/'}
q[7]['prompt']+=' P1 confirms that the updates arrived unchanged and that its customer routes have higher LOCAL_PREF; earlier selection checks tie.'
q[7]['options'][0]['explanation']='The prompt confirms receipt of the updates. Selection policy, rather than propagation delay, explains this case; BGP has no universal convergence-time guarantee.'
q[7]['options'][2]['explanation']='The prompt says the prepended paths arrived unchanged. Some configurations can rewrite paths, but that is not the cause here.'
q[7]['workedExample']='1. P1 sees the direct customer route with higher LOCAL_PREF than the alternative.\n2. With earlier checks tied, LOCAL_PREF decides before AS_PATH length.\n3. Extra prepending therefore does not displace this route inside P1.\n4. Other networks may choose differently under their own policies; the observed traffic shift alone does not reveal all of those policies.\n5. A provider’s documented communities may offer a way to change preference; check its actual policy before relying on them.'
q[8]['prompt']=q[8]['prompt'].replace('The only ROA covering this space says: prefix `192.0.2.0/22`','In this hypothetical validation exercise, the only covering validated ROA record says: prefix `192.0.0.0/22`')
q[8]['workedExample']=q[8]['workedExample'].replace('ROV-enforcing networks drop the two Invalids.','Networks configured to reject Invalid routes drop those two. A different covering record that authorises a route could instead make it Valid; this exercise specifies only one.')
q[9]['prompt']='In a hypothetical validation exercise, AS 65010 is authorised by a validated ROA for a /24. An attacker advertises that /24 with AS_PATH `64666 65010`. What does origin validation establish?'
q[9]['options'][2]={'text':'Valid: the origin matches, but ROV does not authenticate the intervening path','explanation':'Correct. The final ASN and prefix length match the authorisation. ROV alone cannot tell whether the preceding AS relationship is genuine.'}
q[9]['options'][3]['explanation']='ROV’s limitation does not mean no defence exists. Appropriately configured prefix/path filters and deployed path-validation mechanisms can help, with their own assumptions and coverage limits.'
q[9]['workedExample']='1. For this AS_SEQUENCE, the claimed origin is 65010.\n2. The validated record authorises that origin and /24: Valid.\n3. Origin validation does not authenticate the preceding 64666 entry.\n4. Whether this route wins depends on competing routes and policy; its relative length is not specified.\n5. Additional filtering or path validation requires appropriate trusted data and deployment. Merely naming ASPA or BGPsec does not guarantee detection in this scenario.'
q[9]['link']={'title':'RFC 6811: origin-validation security limitations','url':'https://www.rfc-editor.org/rfc/rfc6811'}
q[10]['prompt']='According to Meta’s report on the October 2021 outage, how did the backbone disconnection also make its operational authoritative DNS servers unreachable?'
q[10]['options'][1]['explanation']='Correct. Loss of connectivity to the data centres triggered the DNS sites to withdraw advertisements. Fresh lookups needing these authoritative servers failed; cached answers could still exist, while the backbone outage separately disrupted services.'
q[10]['workedExample']='1. A maintenance command disconnected the backbone between data centres.\n2. DNS sites could no longer reach those data centres.\n3. Their health mechanism withdrew BGP advertisements, leaving the still-operational DNS servers unreachable externally.\n4. DNS failures compounded the underlying connectivity outage; they were not its sole cause.\n5. Network-dependent internal access and recovery tools were also affected.'
q[10]['link']={'title':'Meta: October 2021 outage details','url':'https://engineering.fb.com/2021/10/05/networking-traffic/outage-details/'}
for k in ('prompt','workedExample'):q[11][k]=q[11][k].replace('203.0.113.0/22','203.0.112.0/22')
q[11]['prompt']='In a hypothetical routing exercise, '+q[11]['prompt'][0].lower()+q[11]['prompt'][1:]
q[11]['options'][3]['text']='A forged-origin /24 can pass ROV and win LPM where installed; restrict max length to 22 if only the /22 is authorised'
q[11]['options'][3]['explanation']='Correct. The broader max length permits the forged-origin /24. Where it is accepted and installed beside the /22, LPM selects it. Restricting length makes that /24 Invalid; local rejection policy is still required.'
q[11]['workedExample']='1. Hypothetical ROA: 203.0.112.0/22, max length 24, origin 65010.\n2. The attacker claims 203.0.113.0/24 with path `64666 65010`.\n3. Prefix coverage, origin and permitted length match: Valid.\n4. Where installed with the /22, the /24 wins forwarding for its addresses.\n5. Restricting max length to 22 makes that /24 Invalid, assuming no other authorising record, so networks configured to reject Invalid routes discard it.\n6. A forged-origin /22 can still pass origin validation and compete under normal policy; removing excess maxLength is not complete path authentication.'
q[11]['link']['title']='RFC 9319: The Use of maxLength in the RPKI'
for i in (2,3,7):q[i]['link']={'title':'Cisco: BGP best-path algorithm','url':'https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/13753-25.html'}
p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
