from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-datacentre.md');s=p.read_text()
def r(a,b):
 global s
 assert a in s,a[:70]
 s=s.replace(a,b)
r('A modern web request touches dozens of services: the front end calls auth, a cache, a search cluster, a database and a recommendation model, all in different racks. Most traffic in a data centre is therefore **east–west** (server to server), not **north–south** (to and from the Internet).','A service request may fan out to authentication, caches, databases and other services. This can create substantial **east–west** traffic between servers, alongside **north–south** traffic entering or leaving the facility. The actual traffic mix is workload-dependent.')
r('Data centres instead use a **leaf-spine** fabric, a form of **Clos network**, that gives every pair of servers many equally good paths and spreads load across them.','A common alternative is a **leaf-spine** fabric, a folded **Clos** topology. Under the simple fully connected model below, each leaf pair has multiple paths of equal configured routing cost, not necessarily identical delay or available bandwidth.')
r('so links near the top need enormous capacity, and they are expensive, big-chassis switches.','so aggregate demand can exceed upstream capacity. The required equipment depends on the scale and traffic design.')
r('You pay for two uplinks and use one.','A redundant pair may have only one forwarding path for a particular spanning-tree instance; not every design strands exactly half of all capacity.')
r('- Each server rack has a **leaf** (top-of-rack) switch.','- In this example each rack has one **leaf** switch; real designs may use dual attachment or other placements.')
r('- Any server reaches any server in another rack in exactly three switch hops: leaf → spine → leaf.','- A path between these different leaves traverses three switches: source leaf → spine → destination leaf. Service chains, other fabric tiers and same-leaf traffic differ.')
r('The fabric is built from identical, relatively cheap fixed-port switches. To add capacity between racks, add spines; to add racks, add leaves (up to the spine port count).','Such fabrics can use fixed-port switches, which need not be identical. Adding spines also needs ports and links on every participating leaf. Adding leaves consumes spine ports; cost and topology limits remain.')
r('with each leaf (or each tier) in its own private AS number. Routing has no blocked links, converges per prefix, and contains failures.','with an ASN allocation scheme suited to the topology and loop-prevention policy. L3 ECMP can use redundant links without STP blocking, but convergence, route limits and failure containment require appropriate design.')
r('**Equal-cost multi-path** (ECMP) routing installs all of them and chooses one per packet.','**Equal-cost multi-path** (ECMP) can install multiple eligible next hops, subject to configuration and implementation limits. The forwarding lookup selects a next hop for each packet, commonly using a flow-stable hash.')
r('So switches choose per **flow**:','A common policy therefore selects per **flow**:')
r('def pick_uplink(flow, n_paths):\n    key', 'def pick_uplink(flow, n_paths):\n    if type(n_paths) is not int or n_paths < 1:\n        raise ValueError("invalid path count")\n    key')
r('Every packet of a flow hashes the same way and takes the same path, so order is preserved. Different flows, even between the same two hosts, differ in source port and spread out.','With unchanged inputs and next-hop mapping, a flow selects the same next hop. This avoids reordering caused by this path selector but does not guarantee no reordering elsewhere or during changes. Distinct flows can have different keys and still collide.')
r('Put 8 equal elephant flows on 8 paths.','Assume 8 equal flows choose independently and uniformly among 8 paths.')
r('so roughly a third of capacity sits idle while some links carry two or three flows.','so about a third of paths are empty on average in this model. Actual unused bandwidth also depends on flow demand and other traffic.')
r('flowlet switching** (re-hashing a flow after an idle gap long enough that reordering cannot occur)','flowlet switching** (changing path after a gap intended to exceed the path-delay difference; the guarantee depends on that delay bound)')
r('Only about a quarter of flows keep their old path:','For uniform hashes and a stable ordering of the three surviving next hops, about a quarter of all flows keep their old physical path:')
r('causing reordering, and breaking anything that holds per-flow state,','potentially causing reordering or disrupting unsynchronised per-flow state,')
r('**Resilient hashing** (consistent-hash-style bucket tables) moves only the flows that were on the failed link.','**Resilient hashing** aims to minimise remapping and can preserve healthy assignments on a simple removal. Bucket policies, rebalancing and implementation details determine whether additional flows move.')
r('fabric  = 64 leaves x 600  = 38.4 Tbit/s','uplinks = 64 leaves x 600 = 38.4 Tbit/s')
r('**What 2:1 means:** if every server in a rack sends to other racks at full line rate at once, each gets 12.5 Gbit/s. Traffic within a rack does not touch the uplinks at all.','The last line sums one-direction leaf uplink capacities; it is not a statement of bisection bandwidth or guaranteed delivered traffic. **2:1** means offered off-rack line-rate demand can be twice the aggregate uplink capacity. With equal sharing and no other bottleneck, 600/48 = 12.5 Gbit/s per server; ECMP does not guarantee that allocation. Direct same-leaf traffic avoids these uplinks, but service chaining or dual-attachment policy can differ.')
r('Typical choices: 1:1 (non-blocking) for storage or ML training clusters that genuinely saturate the network; 2:1 to 4:1 for general compute, where most servers are idle most of the time. Lower oversubscription costs more spines, more optics and more cabling, so it is a business decision.','A 1:1 leaf port ratio provides more uplink headroom than 2:1 or 4:1, but is not by itself proof that every traffic matrix runs without blocking. Routing, hash collisions, destination limits and other stages matter. Choose ratios using measured demand, failure headroom and cost; no universal workload-to-ratio rule is assumed here.')
r('The fabric degrades gracefully: no rack is cut off, and routing withdraws the dead paths within moments.','With only this one spine failure and all remaining links/leaves working, racks retain topological connectivity after routing converges. Convergence time and transient packet loss are not guaranteed by the topology alone.')
r('losing one failure halves capacity','losing one failure halves capacity') if 'losing one failure halves capacity' in s else None
r('The classic academic version is the **k-ary fat-tree**','For even k, the classic academic version is the **k-ary fat-tree**')
r('- **Incast.** A query fans out to 100 servers, which all reply at once to one aggregator. The aggregator\'s leaf port overflows its buffer, packets drop, and TCP waits for a retransmission timeout. Linux\'s minimum RTO is 200 ms, while the fabric RTT is tens of microseconds, so one loss can multiply latency a thousandfold.','- **Incast.** Concurrent replies can create a short burst exceeding a destination port’s service rate and available buffer. Loss may then trigger fast recovery, RACK/TLP or an RTO, depending on the trace and stack. Linux’s documented global default minimum RTO is 200 ms, but route/socket settings and newer configurable controls can alter it; not every tail loss waits for that timeout.')
r('- **Shallow buffers.** Merchant-silicon switches have only tens of MB of buffer shared across all ports. Bursts matter more than averages.','- **Finite buffers.** Switch buffer capacity and allocation vary by model. Burst demand and shared-buffer contention matter even when average utilisation is low.')
r('RDMA fabrics use priority flow control and congestion notification.','some RoCE deployments combine priority flow control with congestion notification; RDMA does not universally require PFC, and PFC introduces head-of-line/deadlock risks that require engineering.')
r('| Per-flow hash | no reordering | elephant collisions |','| Per-flow hash | avoids selector-induced reordering while mapping is stable | elephant collisions |')
a=s.index('## Key takeaways');b=s.index('## Further reading',a)
s=s[:a]+'''## Key takeaways
- A fully connected two-tier leaf-spine model offers one path through each spine between different leaves.
- Routed ECMP can use parallel paths, but hashing does not guarantee equal utilisation or congestion-free service.
- Flowlets and resilient hashing reduce particular remapping/reordering problems under their assumptions.
- Oversubscription compares aggregate port capacities. Actual delivered rates, bisection capacity and failure recovery require separate analysis.
- Larger Clos fabrics add tiers. Incast and bursts need queue measurements, transport analysis and appropriate traffic controls.

> [!note] Evidence limits
> Universal data-centre traffic percentages, switch-buffer sizes, workload oversubscription ratios and fixed recovery times are omitted because no applicable deployment measurements were established. The capacity, hash and probability examples are models, not hardware benchmarks. This review did not measure fabric convergence, switch queues or an RDMA deployment.

''' +s[b:]
s+='\n- [RFC 8257: Data Center TCP](https://www.rfc-editor.org/rfc/rfc8257)\n- [Google: Maglev load-balancer design](https://research.google/pubs/maglev-a-fast-and-reliable-software-network-load-balancer/)\n'
p.write_text(s)
