exec(open('/tmp/cs-study-audit-2026-10-04/fix-root.py').read().split("go=['https:")[0])
p_report=Path('docs/audit-se-architecture.json');report=json.loads(p_report.read_text());findings=report['findings'];b='content/software-engineering/05-code-architecture/'
src=['https://martinfowler.com/bliki/DDD_Aggregate.html','https://www.cosmicpython.com/book/chapter_07_aggregate.html','https://docs.python.org/3/library/dataclasses.html','https://docs.python.org/3/library/decimal.html','https://import-linter.readthedocs.io/en/stable/contract_types/layers/','https://github.com/Shopify/packwerk','https://peps.python.org/pep-0649/']
patch(b+'sea-ddd.md',[
('Evans and most practitioners think that\'s backwards: the strategic ideas matter more.', 'Strategic boundaries deserve explicit attention; using entity and repository classes alone does not establish a useful domain model.'),
('    def __hash__(self):\n        return hash(self.id)', '    # Mutable entities are unhashable here.\n    __hash__ = None'),
('Entities are usually mutable and have a lifecycle:', 'Keep entity identifiers stable throughout their lifecycle. The example leaves entities unhashable so mutable attributes cannot corrupt set/dict membership. Entities can have a lifecycle:'),
('Two `Money(10, "GBP")` objects are interchangeable, like two £10 notes.', 'Two equal Money values represent the same amount and currency. Physical notes can have distinct serial-number identities in a different model.'),
('        if self.amount < 0:\n            raise ValueError("negative")', '        if not isinstance(self.amount, Decimal):\n            raise TypeError("Decimal required")\n        if not self.amount.is_finite():\n            raise ValueError("finite amount")\n        if self.amount < 0:\n            raise ValueError("negative")\n        if self.currency not in {"GBP", "USD"}:\n            raise ValueError("currency")'),
('    def __add__(self, other):\n        if other.currency', '    def __add__(self, other):\n        if not isinstance(other, Money):\n            return NotImplemented\n        if other.currency'),
('`frozen=True` makes the dataclass generate `__eq__` and `__hash__` from its fields and blocks attribute assignment.', 'With default eq=True, dataclass generates field equality; combining it with frozen=True normally generates a hash. Frozen blocks ordinary attribute assignment but does not deeply freeze contained objects, and hashing requires hashable fields. This example deliberately supports only nonnegative GBP/USD amounts; other domains may need negative money values and different currency/rounding rules.'),
('a `Money` can\'t be negative or mix currencies, so no other code has to check.', 'this example checks construction and same-currency addition. Currency conversion, rounding, context precision and business-specific limits still need explicit policies.'),
('"an order\'s total must not exceed the customer\'s credit limit", "an order can have at most 50 lines".', '"an order can have at most 50 lines". Customer-wide credit is a separate cross-order invariant unless the model explicitly includes credit reservations.'),
('A transaction modifies a single aggregate.', 'A common DDD guideline is to modify one aggregate per transaction; consciously chosen exceptions exist, and required invariants still need a correct atomic protocol.'),
('```python\nclass Order:\n    MAX = 50', '```python\nclass OrderLocked(Exception): pass\nclass TooManyLines(Exception): pass\nclass EmptyOrder(Exception): pass\n\n@dataclass(frozen=True)\nclass OrderLine:\n    sku: str\n    qty: int\n    price: Money\n\n@dataclass(frozen=True)\nclass OrderPlaced:\n    order_id: int\n\nclass Order:\n    MAX = 50'),
('        self._lines.append(\n            OrderLine(sku, qty, price))', '        if type(qty) is not int or qty <= 0:\n            raise ValueError("positive qty")\n        if not isinstance(price, Money):\n            raise TypeError("Money required")\n        self._lines.append(\n            OrderLine(sku, qty, price))'),
('    def place(self):\n        if not self._lines:', '    def place(self):\n        if self.status != "draft":\n            raise OrderLocked(self.id)\n        if not self._lines:'),
('because you always load and save the whole cluster.', 'so domain changes go through its consistency boundary; optimized queries or persistence need not literally hydrate and rewrite every row.'),
('-- 0 rows updated: someone else won.', '-- 0 rows: stale version or missing row.'),
('one version column on the root protects every line inside it.', 'one root version can protect child changes only if every writer checks/advances it and commits all related changes atomically in the same transaction.'),
('After the order is committed, a handler reserves stock in its own transaction.', 'Commit the state and a durable pending event atomically (for example an outbox); a reliable relay invokes an idempotent reservation handler in a separate transaction.'),
('Conway\'s law means the contexts and team boundaries tend to converge whether you plan it or not.', 'communication structure can influence boundaries; Conway\'s observation is not a deterministic rule that contexts must match teams.'),
('is the one you\'ll write most often.', 'is useful when an external model should not shape your own.'),
('name=rec["NM_FULL"].title(),', 'name=rec["NM_FULL"],'),
('**Generic**: solved problems (authentication, email, payments). Buy or use a library.', '**Generic**: capabilities that do not differentiate this business and can be bought or reused. Authentication or payments may be generic here but core to another business.'),
('- Rules spanning aggregates use domain events and eventual consistency.', '- Rules spanning aggregates need an explicit consistency design; reliable events and compensation suit some requirements, while strict invariants need atomic ownership, reservations or transactions.')], 'Fix mutable entity hashing, shallow frozen/value validation, repeated order placement and aggregate transaction/outbox guarantees.',src)
def ddd(q):
 q[1]['options'][3]['explanation']='This frozen dataclass has hashable int/string fields, so hashing succeeds. Frozen dataclasses containing an unhashable field such as a list can still raise TypeError when hashed.'
 q[4]['prompt']+=' Assume A committed the root version and child rows together, and B runs this statement against current committed data (for example PostgreSQL Read Committed).'
 q[4]['options'][1]['explanation']='Optimistic UPDATE statements also take database locks, but A has already committed in this scenario. With a concurrently running A, B could wait before detecting a conflict; stronger isolation can raise a serialization error.'
 q[4]['workedExample']+='\nThis protects child rows only if every writer advances the root version and persists the child changes in the same transaction; check and roll back failed attempts.'
 q[5]['options'][0]['text']='With whole-graph loading and one shared version, loading is large and unrelated order updates contend on that version.'
 q[5]['workedExample']=q[5]['workedExample'].replace('Anything spanning both (like a credit check) can use a domain event or a check at placement time.', 'A strict shared credit limit needs an atomic reservation protocol; an uncoordinated read/check or delayed event alone cannot prevent concurrent overspending.')
 q[7]['prompt']+=' In this example the documented CRM status mapping says 1 and 2 are active.'
 q[7]['workedExample']=q[7]['workedExample'].replace('name=rec["NM_FULL"].title(),', 'name=rec["NM_FULL"],').replace('If the CRM is ever replaced, only the ACL changes.', 'Preserve personal names rather than applying lossy title casing. This snippet assumes a local Customer type with an active field. Replacing the CRM may remain adapter-local only if the new source provides compatible semantics.')
 q[8]['options'][1]['explanation']='This is a common design when temporary pending status and compensation are acceptable. Use reliable event publication and idempotent handlers; separating transactions does not eliminate hot-stock contention.'
 q[8]['workedExample']=q[8]['workedExample'].replace('Message bus delivers the event.', 'Commit the order plus durable outbox event atomically; a relay delivers it with retries and consumers deduplicate.').replace('short inconsistency window', 'an inconsistency window whose duration needs monitoring and recovery').replace('T2 per SKU: `stock.reserve(qty)`; commit.', 'T2 per SKU: atomically reserve idempotently; on partial failure release earlier reservations or apply the chosen compensation policy.')
 q[10]['options'][0]['text']='The example crosses aggregate boundaries. Model an atomic credit-reservation owner or deliberately choose a suitable multi-aggregate transaction if immediate consistency requires it.'
 q[10]['options'][0]['explanation']='A CreditAccount can atomically reserve rights for orders; alternatively a correct database transaction can enforce the invariant. One aggregate per transaction is a design guideline, not a prohibition on valid atomic transactions.'
 q[10]['workedExample']=q[10]['workedExample'].replace('breaks **one aggregate per transaction**.', 'departs from the one-aggregate-per-transaction guideline.').replace('the order references the reservation by id.', 'the order references the reservation by id, with an explicit protocol for pending orders, retries and release.')
questions(b+'sea-ddd.questions.json',ddd,'Correct frozen hashing, optimistic-lock assumptions, customer-credit invariants and durable domain-event delivery.',src)
patch(b+'sea-modularity.md',[
('None of this is enforced by the interpreter.', 'The interpreter enforces __all__ for star imports, but not privacy for explicit underscore imports.'),
('you can\'t test, release, reason about or extract any of them alone,', 'isolated testing, reasoning and extraction become harder,'),
(' I = 1  maximally unstable', ' I = 1  maximally unstable\n Undefined if Ca + Ce = 0'),
('(interfaces, protocols, pure rules)', '(interfaces or abstract types; a pure calculation is not automatically abstract)'),
('Moving imports inside functions or switching to `import orders` makes the error go away,', 'Deferring an import or deferring access after import orders can avoid some initialization failures. Merely changing the import style does not help if Order is still accessed before it is defined,'),
('For type hints only, `if typing.TYPE_CHECKING:` imports avoid runtime cycles, but treat that as a sign to look at the design, not a fix.', 'For type-only dependencies, TYPE_CHECKING can avoid executing imports. Annotation evaluation must also be handled: older Python versions may need quoted/postponed annotations, and runtime get_type_hints still needs the referenced names. Python 3.14 defers annotations by default. This can be an appropriate type-only solution; it does not remove genuine runtime coupling.'),
('[importlinter:contract:independent]', '[importlinter]\nroot_package = shop\ninclude_external_packages = True\n\n[importlinter:contract:independent]'),
('Shopify is the best-known example.', 'Shopify is one published example.'),
('A module with a clean boundary is also the cheapest thing to extract into a service later, if you ever need to.', 'A clean code boundary can help later extraction, though data ownership, transactions, failure modes and operations still need redesign.'),
('so builds are reproducible.', 'to constrain resolved artifacts. Reproducibility also depends on the interpreter, platform, build tools, system libraries and installation options.'),
('Small, frequent upgrades (Dependabot, Renovate) are cheaper than a two-year jump across five major versions.', 'Tools such as Dependabot or Renovate can propose small, frequent upgrades, which may be easier to review and validate than accumulated changes.'),
('upgrading it is a 200-file change.', 'an incompatible change can affect many call sites.'),
('confines the blast radius.', 'can limit the number of call sites, provided the changed semantics still fit the port.')], 'Correct __all__ enforcement, import-cycle fixes, undefined instability, dependency-lock limits and module-extraction guarantees.',src)
def modular(q):
 q[1]['options'][2]['explanation']='Reachability is not public-API status. Documentation may designate public submodules as well as names re-exported from __init__.py.'
 q[2]['options'][2]['text']='The cycle increases coupling and makes independent reasoning, testing, reuse or extraction harder, even though some isolated tests remain possible.'
 q[3]['options'][1]['explanation']='Four is the denominator alone. The defined ratio lies in [0,1] when Ca+Ce is positive; the isolated-package 0/0 case needs a chosen convention.'
 q[8]['workedExample']=q[8]['workedExample'].replace('`strict` mode stops new ones being added', 'strict enforcement rejects violations even when recorded; ordinary checking can permit recorded debt while failing unrecorded violations')
 q[9]['options'][0]['explanation']='Locks plus hash-checking constrain selected artifacts, but do not prove safety or reproduce an entire environment. Toolchain, OS dependencies and build behavior also matter.'
 q[9]['options'][3]['explanation']='An adapter can limit affected call sites, but a provider\'s changed semantics may still require changes to its port or callers.'
questions(b+'sea-modularity.questions.json',modular,'Correct dependency metric edge case, Packwerk strict-mode meaning and lockfile safety/reproducibility claims.',src)
# Correct an earlier lesson quiz: strict boundaries must permit indirect legal chains.
p=Path(b+'sea-layered.questions.json');q=json.loads(p.read_text());q[7]['workedExample']=q[7]['workedExample'].replace('such as presentation must not import data.', 'such as forbidding direct presentation-to-data imports with allow_indirect_imports=True so a legal chain through intervening layers remains allowed.');p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
report['reviewed_files']+= [b+n+s for n in ['sea-ddd','sea-modularity'] for s in ['.md','.questions.json']]
report['status']='In progress; first four lesson/question pairs fully read; execution and independent verification pending.'
p_report.write_text(json.dumps(report,indent=2)+'\n')
