from pathlib import Path
p=Path('content/networks/06-wireless-modern/wm-sdn.md');s=p.read_text()
def r(a,b):
 global s
 assert a in s,a[:60]
 s=s.replace(a,b)
r('do it billions of times a second in hardware.','perform the configured forwarding operation in hardware or software, at implementation-dependent rates.')
r('learn MAC addresses, compute routes.','compute routes and program forwarding state. MAC learning can also be implemented locally in the data plane.')
r('each configured by hand through its own command line.','with management that may itself be automated.')
r('which programs simple forwarding devices through an open interface.','which exposes programmable control interfaces to forwarding devices. Some architectures retain distributed routing and local decision-making.')
r('When you create a VPC in AWS, Azure or Google Cloud and add a subnet, a route and a firewall rule through an API, you are using the most successful SDN system ever built.','Cloud virtual networks are a practical application of programmable networking. AWS and Google Cloud use the term VPC; Azure calls its corresponding construct a virtual network (VNet). Their scopes and firewall models differ.')
r('Switches only forward; they do not decide.','Forwarding behaviour and its policy/control logic can be programmed separately. Local failover, learning and hybrid routing may remain.')
r('The controller has a global view of the topology and computes forwarding state for everyone. "Logically" because it is a replicated cluster, not one server.','A controller can coordinate a broader view than one device, though observations can be incomplete or stale. Logical centralisation does not require one server or guarantee that a particular implementation is replicated.')
r('and was the first widely used southbound protocol.','as an influential early SDN control protocol.')
r('- **Actions**: output to a port, drop, rewrite a header field, push or pop a VLAN tag, send to the controller, or (from OpenFlow 1.1) continue to another table.','- **Instructions and actions**: instructions can apply/write actions or go to a higher-numbered table. Actions can output or modify packets. Dropping follows from ending processing without an output action; `Goto-Table` is an instruction, not an output action.')
r('earlier versions sent them to the controller by default.','the exact miss behaviour depends on the OpenFlow version and table configuration.')
r('the first packet of a flow misses, goes to the controller, and the controller installs an entry.','with a suitable miss rule, a first packet can generate a controller notification and an entry installation. The controller must also arrange forwarding of the original buffered/unbuffered packet when needed.')
r('No setup latency, but tables must hold everything.','This avoids that reactive setup dependency for covered traffic. Wildcard/aggregate rules can cover many flows without storing one entry per connection.')
r('Hardware tables live in **TCAM**, which supports wildcard matching in one cycle but is power-hungry and small, typically thousands to tens of thousands of entries. Fitting policy into limited TCAM is a recurring constraint.','Wildcard tables may use **TCAM**, while exact-match tables and other stages can use SRAM or different structures. Table size, width, pipeline stages and supported operations are hardware-specific constraints; OpenFlow does not require every table to be TCAM or every lookup to take one cycle.')
r('so a switch can handle new protocols without new silicon.','within the target’s parser, pipeline, memory and action capabilities. P4 cannot make fixed hardware implement arbitrary unsupported operations.')
r('where most SDN actually runs.','on hosts; SDN also has hardware and other software implementations.')
r('Knowing all demands and priorities, it drives many links to near 100% utilisation, where traditional WANs run at 30–40% to leave headroom.','The paper reports high utilisation for its controlled workload and traffic-engineering design. This is a historical deployment result, not a universal target or comparison for every WAN; measurement, failure headroom and traffic priorities matter.')
r('The physical network should know none of this.','An overlay can keep much of this tenant-specific forwarding state out of the transit fabric, though tunnel endpoints and policies still need it.')
r('the hypervisor (or a smart NIC)','a tunnel endpoint, such as a hypervisor, switch or smart NIC,')
r('The encapsulation adds **50 bytes** over IPv4. If the physical MTU is 1,500, tenant packets must be at most 1,450, or the fabric must use jumbo frames.','With outer IPv4 without options, UDP, VXLAN and untagged inner Ethernet without inner FCS, the outer IP packet contains **50 bytes in addition to the inner IP packet**: 20 + 8 + 8 + 14. Thus a 1,500-byte underlay IP MTU permits at most 1,450 inner IP bytes under these assumptions. Outer Ethernet is outside that IP MTU; tags, outer IPv6 or other encapsulation alter the budget. A tenant MTU of 1,500 instead needs at least 1,550 underlay IP bytes here, not necessarily a 9,000-byte jumbo frame.')
r('In AWS, the Nitro hardware on each host encapsulates packets and consults a distributed mapping service, so the VPC is enforced on every host rather than at a central firewall.','A cloud provider may use a proprietary distributed virtual-network datapath. Do not infer that every provider uses standard VXLAN or the same per-host architecture; AWS’s VPC behaviour below is an API-level example.')
r('An AWS VPC (other clouds are similar) is a private address space in one region:','An AWS VPC is a regional logical network supporting IPv4 and/or supported IPv6 configurations. The following describes a conventional private IPv4 example; other clouds have different scoping rules:')
r('AWS reserves **5 addresses** in each: the network address, `.1` (VPC router), `.2` (DNS), `.3` (reserved) and the last (broadcast).','For an ordinary AWS private IPv4 subnet, the first four addresses and the last are reserved. These are offsets from the subnet base, not necessarily addresses ending .0–.3. The VPC DNS resolver is available at the primary VPC CIDR base plus two (and link-local addresses); each subnet’s base-plus-two is reserved, not necessarily its resolver endpoint. AWS does not support subnet broadcast. BYOIP has documented exceptions to the ordinary reservation rule.')
r('**Route tables**: per subnet. A **public** subnet has a route `0.0.0.0/0 → internet gateway`; a **private** subnet routes `0.0.0.0/0` to a NAT gateway (outbound only) or nowhere.','**Route tables**: a subnet is associated with one table, which can be shared by several subnets. A public IPv4 subnet has a direct Internet-gateway route; an instance also needs suitable public addressing, routes and filtering to communicate. Private subnets may use NAT, private connectivity or no Internet route. IPv6 egress uses different mechanisms.')
r('**Stateful** means the security group tracks connections: if inbound TCP 443 is allowed, the replies go out automatically.','For an allowed tracked TCP connection, security-group state permits response traffic without a separate reverse-direction rule, while tracking remains valid. Other controls, including NACLs and routing, still apply.')
r('"allow 5432 from the `app-servers` group" stays correct as instances come and go, with no IP lists.','an eligible rule such as “allow TCP 5432 from app-servers” identifies associated interfaces rather than copying that group’s rules. Referencing depends on supported VPC relationships and path behaviour; middleboxes can change which source identity/address is applicable.')
r('without connecting the networks at all.','without full routed peering between both address spaces. Connectivity is limited to the supported service/resource endpoint model; PrivateLink has additional endpoint types beyond this introductory interface-endpoint example.')
r('Peering and most hub designs require non-overlapping address ranges.','VPC peering requires non-overlapping CIDRs. Other architectures may handle overlap with translation or service endpoints, but ordinary routing cannot unambiguously use duplicate destination ranges without additional context.')
r('If the controller is unreachable, switches keep forwarding with the entries they have, but cannot react to change. Controllers are replicated (often with Raft or Paxos-based stores), and well-designed data planes fail static.','Controller-loss behaviour is configured: in OpenFlow fail-secure mode retained entries can continue, subject to timeout expiry and other changes. Fail-standalone/hybrid behaviour and preinstalled local failover differ. Replication can improve availability but is not mandated by SDN itself.')
r('Sending first packets to the controller does not scale to millions of new flows per second; production systems are mostly proactive.','Reactive control consumes controller/channel/table resources. Test its capacity and use aggregate/proactive rules where suitable; no universal flow-rate cutoff or deployment share is assumed here.')
a=s.index('## Key takeaways');b=s.index('## Further reading',a)
s=s[:a]+'''## Key takeaways
- SDN exposes programmable control over forwarding; architecture, replication and retained local control vary.
- OpenFlow tables select by priority and execute instructions/actions, with version-specific miss and failure behaviour.
- VXLAN carries a 24-bit VNI over UDP; calculate MTU from the actual outer and inner headers.
- AWS VPC subnet, routing, security-group and NACL rules are provider-specific. Stateful response allowance does not bypass other controls.
- Prepare new paths before using them, and retain old rules until in-flight old-path packets have drained.

> [!note] Evidence limits
> Universal SDN adoption shares, TCAM capacities, controller rate limits and unverified provider-internal datapaths are omitted. Cloud rules and product features must be rechecked against current documentation. This lesson’s arithmetic and table traces are models; no live AWS or OpenFlow fabric was deployed during review.

''' +s[b:]
s+='\n- [OpenFlow Switch Specification 1.3.5](https://opennetworking.org/wp-content/uploads/2014/10/openflow-switch-v1.3.5.pdf)\n'
p.write_text(s)
