import json
from pathlib import Path
base=Path('content/networks/06-wireless-modern')
corrections={
'wm-wifi':['Qualified shared-medium transmission for MU/OFDMA/spatial reuse; corrected generation/certification/stream distinctions and region-dependent spectrum.', 'Scoped DCF timing/backoff and NAV/ACK/RTS claims; removed universal channel plans and distance/rate guarantees.', 'Corrected throughput, aggregation and airtime fairness assumptions; qualified diagnosis questions and hidden/exposed terminal geometry.'],
'wm-cellular':['Corrected scheduled-access exceptions, NR numerology scope, core function responsibilities, NSA option3 scope and mobility guarantees.', 'Removed unverified fixed spectrum ranges and universal radio-tail/battery figures; union-of-intervals model explicitly illustrative.', 'Corrected IPv6-only Apple literal-address behaviour, CGNAT/STUN/relay claims, BBR classification and slice/MEC guarantees.'],
'wm-datacentre':['Corrected aggregate leaf-uplink capacity versus bisection bandwidth; oversubscription is not guaranteed per-host throughput.', 'Recomputed equal-path hashing occupancy/remapping, three unused uplinks in two-flow collision example, and fat-tree assumptions.', 'Corrected consistent hashing alone preserving arbitrary load-balancer state; qualified incast, RTO and RDMA/PFC claims.'],
'wm-sdn':['Corrected OpenFlow instruction/action distinction, table-miss/version and hardware/generalisation claims.', 'Clarified VXLAN overhead accounting, AWS subnet reservations/DNS/BYOIP and SG/NACL/route/PrivateLink assumptions.', 'Corrected ordered rule update: control-plane barrier is not proof old data-plane packets drained; removed undocumented Nitro implementation assertions.'],
'wm-debugging':['Replaced uniquely diagnostic interpretations of traceroute, resets, timeouts, curl timing and retransmission counters with conditional evidence.', 'Fixed TLS timing example address family/scope preservation, context-creation timing and socket ownership; explicitly first-address/per-operation timeout.', 'Scoped PMTU IPv4 arithmetic, Mathis Reno assumptions, socket/conntrack capacity and TIME_WAIT model.'],
'wm-internet-structure':['Removed undated global counts/traffic/cable shares and unsupported historical prefix detail; labelled illustrative hijack and satellite examples.', 'Corrected peering/transit/valley-free/RPKI limitations, route-server forwarding misconception, GPON sharing and access oversubscription.', 'Dated retained Dunant/ICPC facts; recomputed propagation lower bounds and corrected valley-free route propagation direction.']}
report={'date':'2026-10-05','status':'Author pass complete: all six lessons and 72 questions fully read/corrected; independent source closure and verification assigned to audit_synth. Root has not stamped.','reviewed_files':[str(p) for p in sorted(base.iterdir()) if p.suffix=='.md' or p.name.endswith('.questions.json')],'coverage':{'lessons':6,'questions':72},'findings':[{'file':str(base/(k+'.md')),'corrections':v} for k,v in corrections.items()], 'validation':['All five lesson Python fences executed; no quiz Python fences. 25,966 assertions pass, including exact printed outputs, randomized radio interval unions, ECMP bounds/remapping, subnet coverage, propagation arithmetic and actual loopback TLS certificate/hostname validation.','Harness: /tmp/cs-study-audit-2026-10-04/check-network06.py; isolated Linux Docker --network none. Initial host loopback binding denied by sandbox; approved Docker used. Test fixture read-after-immediate-client-close produced BrokenPipe and was removed; final run clean.','Scoped build only six expected pending-verification errors.'], 'source_priorities':['Exact Wi-Fi DCF timing and standard/profile scope; Ofcom July2026 spectrum decision is not blanket implemented allocation.','ITU IMT-2020 latency/peak-rate targets; 3GPP core/NR standards; Apple IPv6-only API behaviour.','RFC2992/7938/8257, original fat-tree/Google Maglev/Jupiter publications.','OpenFlow1.3.5 rule update and pipeline semantics, AWS VPC documentation and RFC7348.','curl write-out, man7 ss/ping, Linux ip-sysctl, RFC2923.','ITU GPON/XGS-PON profiles; June2025 ICPC report, Google2021 Dunant and ESA orbit geometry.'], 'gaps':['No live radio/mobile/cloud hardware or WAN measurements; code and arithmetic models do not validate real deployment performance.','Current spectrum allocations, installed fleet counts, global traffic percentages, internal vendor implementation and universal latency/battery figures omitted where reliable context-specific evidence was unavailable.'], 'confidence':'Pending independent review. Core models checked; standards/version/product specifics require independent primary-source closure.'}
Path('docs/audit-networks-modern.json').write_text(json.dumps(report,indent=2)+'\n')
p=Path('docs/RESUME.md');p.write_text('## Latest audit checkpoint — 2026-10-05\n\nReview remains active and incomplete. All DSA, architecture, OS, language, theory, software-engineering, database, system-design and synthesiser module passes are complete. Network01/02/04 complete; network05 final closure active; TCP03 author complete (7 lessons/80 questions, 102,543 assertions), independent audit_system_design next. Wireless06 author complete (6 lessons/72 questions, 25,966 assertions), independent audit_synth active. Security01 complete; security02 closure active, then audit_systems takes03/06; audit_synth takes04 after wireless, audit_system_design takes05 after TCP. Root moves shared glossary/diagram/app-text review. Full build, generated aggregate report, links, mobile/offline and all renderer tests remain. Helpers fix-root1–102 already applied: DO NOT rerun exact replacements. See per-module JSON reports for evidence and limitations.\n\n'+p.read_text())
